### ISSUE TITLE
Documentation of networkx.traversal module

### ISSUE THREAD

**Issue by krichter722** [networkx/networkx#1195]
The functions in <code>networkx.traversal</code> in 1.8 have some counter intuitive behavior, e.g. no return value of <code>dfs_edges</code>, and inconsistent use of terms, e.g. "return" and "produce" (What means "produce"? Is the return value backup up by the graph's node/edge list?) could be used to distungish between functions with return values and those without, at least there shouldn't be a mix.

**Comment by Michael-E-Rose** [comment]
This is about [`algorithms/traversal/depth_first_search.py`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/traversal/depth_first_search.py). I has changed a little since Jun 2014, but not the docs.

I think it's easy to expand on `dfs_edges` by showing how a graph could be rebuild using the edges or by showing how one could get nodes from the result.

However I don't understand the proposal for `dfs_tree`: Why should the function work on a list of nodes (as is the case for `DiGraph.nodes()` or `DiGraph.node_iter()`)?

**Comment by hagberg** [comment]
The docs look ok to me.  And there are examples.  Do they make sense to
you?  If so perhaps we can close this.

**Comment by krichter722** [comment]
The documentation has been approved apparently. I didn't check for completeness of docs.
