### ISSUE TITLE
Visualization with SVG, without using graphviz

### ISSUE THREAD

**Issue by rainwoodman** [networkx/networkx#1312]
Is a direct SVG renderer (not via graphviz) of any interest to the upstream development?

I was to visualize some data flow charts represented with networkx in a IPython notebook. Data flow chart nodes can have very fat text labels. This scenario exposes a few drawbacks with the matplotlib rendering (networkx.draw_xxxx ) functions (
https://github.com/rainwoodman/nxsvg/blob/master/src/mpla.svg ):
- no proper arrows on edges
- marker representation of nodes are too small
- large text labels covers tails and heads of edges
- no multiline support for labels
- parallel edges are overlapping

I tried to fix the matplotlib renderer, but failed. pygraphviz is a solution that I haven't explored since it requires graphviz which cannot be installed via `pip/easy_install` (I imagine that's part of why we have a builtin visualization in networkx)

In the end I wrote a simple direct SVG renderer skipping the matplotlib layer completely. It depends on 'svgwrite', which can be `pip`ed. The new renderer has specifically fixed all of these issues I listed above.

This also opens the possibility of embedding some nice javascripts that allowing the user to pan/zoom or move the nodes around. Unfortunately I don't know how to make this happen.

The SVG renderer is at

https://github.com/rainwoodman/nxsvg/blob/master/src/nxsvg.py

Currently it has support for directed edges, parallel edges and self-looping edges. I am planning to add support for colors, sub/sup-scripts,  and font-sizes in labels, with a mini-language similar to Pango markups.

Here is the same example rendered with the SVG renderer:

https://github.com/rainwoodman/nxsvg/blob/master/src/a.svg

**Comment by dschult** [comment]
There is interest here (judging from the comments over the years). NetworkX
is not primarily a drawing package, but it is nice to have these tools
available and easy to use. Ask here if you need help putting together your
pull requests.

And Thanks,
Dan

**Comment by rainwoodman** [comment]
You mean the patches to the pylab backend or the svg drawing backend?

I am still working on the pylab patch. The main blocker is the size allocation of text boxes. The coordinate conversion can be a bit complicated.

**Comment by chebee7i** [comment]
Nice work. IMO, the placement of arrowheads is less than ideal. And there are a lot of z-order issues with https://github.com/rainwoodman/nxsvg/blob/master/src/a.svg. Generally, it's certainly an improvement. 

Overall though, I think this is still not "nice" enough for my tastes...and I think this is something that all graph drawing in NetworkX suffers from. I had thought we were leaning towards removing drawing functionality (since we can't seem to do it well). Perhaps this pushes people to consider "proper" graph drawing programs instead (e.g. cytoscape), after exporting to a common format. Relatedly, there is a pure graphviz approach that exists outside NetworkX: [nxpd](https://github.com/chebee7i/nxpd)

So I'll go with the majority here, but I think it would be nice to settle on a set of guidelines. Are we keeping drawing functions and adding new ones? Or are we gutting them? Or ....

**Comment by rainwoodman** [comment]
Ah thanks! Now that you've pointed out, I realized `a.svg' does look very untasteful with colors, giant markers, and very thick edges ... I do have a poor (non-)artitistic taste.

I like the easy of pass-through attributes in nxpd. In nxsvg it is a formatter function that evaluates the label and svg-attributes for each node / edge; thus in theory one do not need to modify the graph merely for visualization. 

Those z-order issues have slipped through my eyes; they weren't an issue in the pylab backend. Shapes and proper connector style arrow placement can be done, with a lot of efforts (maybe not worth it). 

The worst issue is that layouting in networkx is far naiver than graphviz; networkx rarely gives any sensible layouts for a flow-chart as far as my experience in last few weeks go. To me, this is the real show stopper for naive python visualizations.

**Comment by hagberg** [comment]
Graph visualization is hard.  Especially in that there are many different objectives when making a drawing  (good labels, specific layout, large number of nodes or edges, etc).   It's would be pretty difficult  to make a single tool that can satisfy even a large subset of those.   

Since NetworkX is primarily for graph data structures and algorithms I have been generally advocating against including special purpose graph drawing or even graph drawing in general.  The current matplotlib drawing was mostly written 10 years ago (!) and is obviously a hack. I've been avoiding improving it since I'd prefer it to be a separate (compatible) package.   I'd prefer separate packages for other drawing tools as well.  

I do think there is a place in NetworkX for algorithms that position nodes (and maybe edges) for use in drawing algorithms.  The current set of those (mostly in layout.py) is pretty slim.  And as @rainwoodman points out they could certainly be improved and would potentially useful to any graph drawing package such as an svg tool.

**Comment by hagberg** [comment]
Any progress on a separate package to do layout and SVG output?

**Comment by rainwoodman** [comment]
No. I haven't been working with graphs for the entire last year.

**Comment by hagberg** [comment]
Closed due to inactivity.
