### ISSUE TITLE
Google Summer of Code 2015 participation?

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx#1326]
(Sorry for having been MIA for quite some time. I just left school and started working. The transition took up the time.)

If my research is correct, NetworkX was in GSoC 2011 with two projects on community detection and maximum flows. What was the experience like? Is there any interest and/or feasibility in doing it again?

**Comment by hagberg** [comment]
Good to see you again.

Yes, we had two projects.  I was the mentor for @bjedwards on the community detection project.   We had a a great summer and made good progress - some code made it into the codebase and there is more we could glean from the project.   Overall the experience for me was great.

I would be interested in supporting this again for NetworkX.  2011 was our first attempt and we learned a lot about how to scope projects, communicate code, etc.  Now that we are using github the discussions and integration of code would be better facilitated.

**Comment by ysitu** [comment]
AFAIK the last time NetworkX was under the umbrella of the Python Software Foundation. I suppose that if we are to participate this year, we probably will want to work under the PSF again. In all cases, some preparation work needs to start now. Organizational application will run from Feb 9 to Feb 20. There is not much time left.

**Comment by hagberg** [comment]
So we have about a month to solicit mentors and ideas for projects.  I think that is doable.
@ysitu are you willing to coordinate this effort?

**Comment by bjedwards** [comment]
I think this is a great idea. @hagberg might be being a little generous about the quantity and quality of work we got done, but I appreciate the sentiment.

I know the organization administrator for the PSF(Terri Oda), I can send and email and see what the status is for this year.

**Comment by ysitu** [comment]
@hagberg @bjedwards Yes, I can coordinate the effort within NetworkX such as collecting ideas for potential projects. But since, I have no external connections nor any knowledge about the GSoC process, it would be helpful if you could help make the arrangments with PSF and alike.

**Comment by hagberg** [comment]
OK - let's go for it.  @bjedwards could you drop a note to Teri Oda and find out how to proceed?

**Comment by bjedwards** [comment]
I'll get in touch. @ysitu can you send me an email address that I can give to Terri? You can it to bjedwards (at) gmail.

**Comment by ysitu** [comment]
@bjedwards I have sent you an email.

**Comment by bjedwards** [comment]
@ysitu, nothing yet, checked spam. Can you try again? (Why is there no PM feature on github?)

**Comment by ysitu** [comment]
@bjedwards I have resent the email.

**Comment by bjedwards** [comment]
Still nothing. Maybe it's my gmail, try bedwards (at) cs (dot) unm (dot) edu

**Comment by ysitu** [comment]
@bjedwards Ben, I wonder if my message reached you. If not, I need to use another email address.

**Comment by bjedwards** [comment]
@ysitu Sorry, still nothing.

**Comment by bjedwards** [comment]
Just sent the email. Hopefully we can get involved this year.

@ysitu let me know if I can help. I'm probably too removed from development at this point to be any use as a mentor, but having been on the student side of the project, I'd be happy to lend any advice.

**Comment by ysitu** [comment]
I have started a draft of the ideas page required by the PSF in the wiki. Currently it is mostly a verbatim copy of PSF's template. I will add contents over this week and hope to send it to the PSF for review by the end of the week.

@hagberg Can you help with the introductory text immediately below "About NetworkX"?
@bjedwards Can you help with the "Writing your application" part?

I will start a separate Issue for project ideas and mentors.

**Comment by MridulS** [comment]
@ysitu @hagberg @bjedwards GSoC 2015 org application starts tomorrow, I guess we should finalise mentors and project wiki, and contact PSF.

**Comment by gcetusic** [comment]
Hello! I see you're applying for GSoC 2015 -> https://wiki.python.org/moin/SummerOfCode/2015
I'm finishing my master's degree in Telecomunications and Informatics and I'm interested in working on this project. Sorry if this isn't the right place, I can send this via the mailing list. It seemed more appropriate instead of just randomly sending an email to the list. I hope this isn't too much but the advice given to students is to start contacting possible mentors as soon as possible. I've also been a CERN summer student so this would be a great way to finish my education and I can send my CV for you to view further. So here it goes.

Let me just explain why this project is interesting to me and let me know if you're interested in taking me on as a student.
I've worked on a lot of Python 2/3 projects and my masters thesis is porting the IMUNES network simulator from FreeBSD to Linux. Basically, you have a sandbox where you create a graph with nodes and edges and then run tiny virtual machines with docker/jails/lxc for nodes and connect them together (http://imunes.tel.fer.hr/)
It's a great network tool but it's in Tcl/Tk and they still use SVN and the project itself is somewhat obscure so I started to rewrite it into Tkinter. I've forked the project to github and started working on separate branches, one for linux and the other for python. I've made a skeleton and you can view it here: https://github.com/gcetusic/IMUNES/tree/python_imunes by running imunes.py inside python_imunes directory. It's really just a skeleton but I hope you get the general idea. 

So my question is: Would you consider adding a GUI interface for networkX? The idea is to make it abstract enough to run both a full fledged network simulator and networkX. The FreeBSD version does basically the same thing: you can add nodes, modify edge weights, draw all kind of graphs automatically...I encourage you to to try it out, it's for FreeBSD until I port it :) I think it's actually a lot more complex than what networkx needs.
Even if you're not interested in this, would you consider me for other ideas like the alternative backend or the 2.0 API? As I said, I have lots of experience in Python and networks and graphs are part of my masters so that won't be a problem.

**Comment by ysitu** [comment]
Update on PSF's response for those who were not in the message loop:

PSF is happy to have NetworkX participate in GSoC 2015 under their umbrella. (NetworkX is now listed in https://wiki.python.org/moin/SummerOfCode/2015#Python_Project_Ideas).

They also have some comments regarding the ideas page. First, we need to list one "purely beginner-friendly" project. This is what Google is proactively looking for according to Terri. Second, some project descriptions needs expansion to clearly define what we want from the student(s). Third, each project needs to have potential mentors assigned.

**Comment by MridulS** [comment]
@ysitu The difficult part of networkx 2.0 API is the design part, as far as implementation is considered I guess it can be considered as a beginner-friendly project, anyone with decent python experience can start working on it. So I think we should start working on it. And get a final word on #1246.

**Comment by ysitu** [comment]
@MridulS I agree with you. There is no need to wait till summer to work on the design.

As for an easier project, I now realize that I may have overrated renaming `nodes_iter` over `nodes`, etc. I marked it intermediate because there are a dozen of such pairs, and each of them has a ton of uses in the current code base. But now I remember that I actually tried working on the `nodes_iter`/`nodes`. It was about one  day of work. So maybe it is not that bad after all.

**Comment by MridulS** [comment]
@ysitu From the #1246 discussion, I guess there are more things to do other than renaming ```func_iter``` over ```func``` . We could start discussing about the ANY() function, having similar implementation of funcitons for Di/Multi/Graph, etc.  

P.S. I am thinking of applying for GSoC as a student and working on 2.0 API.

**Comment by chebee7i** [comment]
I think it would be helpful if we familiarized ourselves with how various graph databases, such as Neo4j, deal with sql-like queries on graphs. We might as well bootstrap our design.

**Comment by RONNCC** [comment]
technically first project proposal and like - second work now and work for
gsoc would be seperate - that is technically a paid project

**Comment by ysitu** [comment]
Close and move project discussions to #1341, other threads and other channels.
