### ISSUE TITLE
PyPy Travis Failures due to unordered dicts

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1351]
Encountered in #1350.
I think travis failures have something to do with the pypy update to 2.5.
After going through http://morepypy.blogspot.in/2015/01/faster-more-memory-efficient-and-more.html and http://bugs.python.org/issue3332 I think this means that dicts that are key-value consistent are not equlivalent due to ordering, and hence the travis fail.

@chebee7i

**Comment by chebee7i** [comment]
I just looked at http://bugs.python.org/issue3332. While I understand why they don't consider it a bug, I agree with the bug advocators that it makes doctests *confusing* for users. We end up having to throw a lot of non-example-demonstrating-code into the doctest.

Is there some way that we could configure how doctests are executed/verified? It would be nice if we could get it to do actual dictionary equality whenever the output looks like a dictionary, etc. Adding line comments such as `#doctest: object_equality` or `# pragma: nocover` are not an option, in my opinion, as it only serves to confuse the user who doesn't care about the fact that developers want to test all their docstrings as part of the build process.

**Comment by chebee7i** [comment]
As linked above, see also some other relevant comments on this issue:  https://github.com/networkx/networkx/pull/1350#issuecomment-73762339.

**Comment by hagberg** [comment]
Can we get by with not using unordered data structures in the doctests or just skip this doctests?
I think there is a middle ground between forcing ordered datastructures and not testing any docs.
(And I agree with Tim Peters that this is a doctest feature not a doctest bug).

**Comment by chebee7i** [comment]
If we want to keep doctests clean and simple but also tested, there is another option to consider. It could be a well-defined, but perhaps large, task for a GSoC project. #1326 

Idea: Convert all doctest style examples to use the [IPython directive](http://matplotlib.org/sampledoc/ipython_directive.html). Here is an example:

```python
.. ipython::

   In [1]: x = 'hello world'

   # this will raise an error if the ipython output is different
   @doctest
   In [2]: x.upper()
   Out[2]: 'HELLO WORLD'

   @doctest float
   In [154]: 0.1 + 0.2
   Out[154]: 0.3
```

When rendered, the user will see:

```python

In [1]: x = 'hello word'

In [2]: x.upper()
Out[2]: 'HELLO WORLD'

In [3]: 0.1 + 0.2
Out[3]: 0.30000000000000004
```
or something similar. This will pass the doctest however, since we have transparently instructed sphinx to compare floats (and it knows not to test for exact equality). We can quietly seed random number generators as well. When hiding seeds, there is still an issue that the user, when pasting, might not see exactly what is in the example, but we can at least guarantee that it will work via this method. There are a few projects that use this format for their documentation---[pandas](http://pandas.pydata.org/pandas-docs/dev/dsintro.html) is included in this group.

Now, this is primarily used for documentation and not for docstrings. One concern with doing this in docstrings is that docstrings are not typically rendered (at least from the IPython terminal), and so users would see the `@doctest float` stuff. This is clearly undesirable. So one "technical" problem that someone could work on is to pass all docstrings through to Sphinx during build time and store the rendered output as the docstring. Overall, this will clean up the docstrings and it will guarantee that we have working, tested doctests.

**Comment by chebee7i** [comment]
Regarding unit tests, we should make sure this issue figures out a nice way to handle the ordering issues mentioned in this comment: https://github.com/networkx/networkx/pull/1356#issuecomment-74567160
