### ISSUE TITLE
Function add_nodes_from does not use adjlist_dict_factory properly

### ISSUE THREAD

**Issue by renehernandez** [networkx/networkx#1394]
While I was reading through the code of the Graph class, I have found what I think must be a bug in the implementation.
Look at the code below:
```
python
for n in nodes:
  # keep all this inside try/except because
  # CPython throws TypeError on n not in self.succ,
  # while pre-2.7.5 ironpython throws on self.succ[n] 
  try:
    if n not in self.node:
      self.adj[n] = self.adjlist_dict_factory()
      self.node[n] = attr.copy()
    else:
      self.node[n].update(attr)
  except TypeError:
    nn,ndict = n
    if nn not in self.node:
      self.adj[nn] = {}
      newdict = attr.copy()
      newdict.update(ndict)
      self.node[nn] = newdict
    else:
      olddict = self.node[nn]
      olddict.update(attr)
      olddict.update(ndict)
  ```
So, the problem is with these two lines:
**self.adj[n] = self.adjlist_dict_factory()** in the try part of the code and
**self.adj[nn] = {}** after the except TypeError if the node is not present in the graph

Both assignments initialize in different ways the adjacency list for a node. I think this could lead to weird behavior when calling this function.

**Comment by dschult** [comment]
Yup--that's a bug.  Thanks!

**Comment by renehernandez** [comment]
@dschult You're welcome! I like to help networkx to become ever awesome

**Comment by chebee7i** [comment]
Nice catch. @dschult, why didn't the unit tests pick this up?

**Comment by dschult** [comment]
I didn't rewrite each unit test of Graph. I set SpecialGraph up to run each
unit test of Graph making sure the output is as expected with OrderedGraph
and ThinGraph. But there is only one unit test that hits this line of the
code and OrderedGraph, ThinGraph, and Graph all return the same results
with the existing unit test.

This will be relevant for matrix data structure backends too.

I suppose unit tests should be created which check the data structure
directly rather than the output from reporting methods.
