### ISSUE TITLE
DiGraph drawing with matplotlib problem.

### ISSUE THREAD

**Issue by pahaz** [networkx/networkx#1434]
Hi, I have problem with drawind DiGraph:
![image](https://cloud.githubusercontent.com/assets/1394025/6854397/e0cd7e9c-d412-11e4-9837-6b25a487377a.png)

As you can see, problem with drawing arrows.

    matplotlib==1.4.3
    networkx==1.9.1

Code:

    g = nx.DiGraph()
    g.add_edge(1, 2)
    ...
    nx.draw_circular(g)  # or nx.draw(g) or ...
    plt.show()

**Comment by hagberg** [comment]
If the problem you have is that the arrows are thicker lines in the links, then we don't have a solution.
Drawing arrows correctly with Matplotlib has been hard to implement.
I'd suggest using Graphviz. You can make suitable dot format file with nx.write_dot().

**Comment by OrkoHunter** [comment]
@pahaz If you are saying about the arrows, yes so far those thick black lines are the only alternatives for DiGraphs.

Concerning your plotted graph, can you put up your exact code instead of `...` ? That would help.

**Comment by pahaz** [comment]
@hagberg, no, the problem in an incorrect drawing some arrows angles and in arrows extending to infinity as you can see on the image.

@OrkoHunter, `...` contain only a some `g.add_edge(...)` calls. For example:

    import networkx as nx
    import matplotlib.pylab as plt
    
    g = nx.DiGraph()
    g.add_edge(1, 2)
    g.add_edge(21, 2)
    nx.draw_circular(g)
    plt.show()

Produce:

![image](https://cloud.githubusercontent.com/assets/1394025/6883496/d925196e-d5d1-11e4-8a0c-e63e43c436f0.png)

**Comment by OrkoHunter** [comment]
@pahaz I'm sure that would be `matplotlib.pyplot` instead of what you've written by mistake.
Further the result produced by your code gave this result.

![screenshot from 2015-03-29 13 16 17](https://cloud.githubusercontent.com/assets/8065913/6884605/44ba8070-d617-11e4-8e7f-56b39b37c530.png)

So, the problem must be with the drawing package. I can't figure out what could be the possible bug.

@hagberg Ping.
