### ISSUE TITLE
Missing arrows parameter in draw_networkx

### ISSUE THREAD

**Issue by AgostinoSturaro** [networkx/networkx#1557]
The parameter `arrows` is present in the doc of [draw_networkx_edges](https://networkx.github.io/documentation/latest/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edges.html), but is not present in the doc of the more general [draw_networkx](https://networkx.github.io/documentation/latest/reference/generated/networkx.drawing.nx_pylab.draw_networkx.html).

However, I tried to use `arrows=False` in `draw_networkx`, and it appears to work. Maybe it's just missing in the doc?

**Comment by SanketDG** [comment]
Currently, the `arrow` parameter of `draw_networkx` is handled by `**kwds` which then gets passed on to `draw_networkx_edges`. I think that there should be a explicit definition of the `arrow` parameter in `draw_networkx` since it should be upon the user to choose the whether arrows should be drawn or not.

I'll send in a PR.

**Comment by chebee7i** [comment]
Fixed in #1594.
