### ISSUE TITLE
Functions that currently produce lists which can (should) produce iterators

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1632]
We should discuss about various functions/algorithms (non core classes methods) that generate lists which can (should) produce iterators.
- `cluster.triangles()`
- `cluster.clustering()`
- `cluster.square_clustering()`
- `boundary.edge_boudary()`
- `boundary.node_boundary()`
- `core.core_number()`
- `dag.topological_sort()`
- `dag.dag_longest_path()` 
- `approximation.kcomponents.k_components()`
- `assortativity.connectivity.connectivity()`
- `bipartite.basic.color()`
- ...........
- ..........
- .........

Looking forward to inputs
@dschult @hagberg @chebee7i @jfinkels @jtorrents @ysitu

**Comment by dschult** [comment]
From my naive perspective it is probably best to make all of these iterators (unless there's a good reason not to for a specific case).  For example, if you really have to construct the list to get the iterator then let's return the list. But usually we would want an iterator.

shortest_path and friends could be quite a project if only because there are so many different versions. :)

**Comment by hagberg** [comment]
I don't mind leaving many of these algorithms as is.  There are surely some though that could benefit from becoming iterators (e.g. traversal algorithms). 

If we want to change the type of return on algorithms I suggest we do it one at a time so we can keep track of errors/changes.   Some algorithms might require significant changes to make them iterators. For others it won't be worth doing at all since as @dshult mentions we already have to build a list or other data structure.

**Comment by MisterSheik** [comment]
Unreversed topological sort cannot produce an iterable.  However, it is called by `is_directed_acyclic_graph` which throws out the return value (just looks for an exception).

**Comment by MisterSheik** [comment]
One of the difficulties with generators as opposed to returning lists is that an caller might accidentally change the graph used in the call while they are processing the iterator.  It might be nice to raise a `GraphChangedError` in that case.

For example, I reimplemented `topological_sort` as an generator.  I could intercept `KeyError` and replace it with `GraphChangedError`.  Also, it's possible for the a user changing the graph while the generator is being processed to fool the algorithm into thinking that there's a cycle, which is unfortunate.

**Comment by chebee7i** [comment]
Good point. Do we have an implicit "contract" that the graph should be static for NetworkX? Are people using it with dynamic graphs?

**Comment by dschult** [comment]
Users do analyze dynamic graphs so we want to avoid surprises due to changing the graph. It is easy to avoid the problem by storing the iterator in a list/tuple before moving to code that changes the graph. But the documentation should make it clear that this is needed.

e.g. for topological_sort(), perhaps the doc_string can include an example where the graph is changed based on the topological sort so we use list(topological_sort(G)) in the example to avoid errors.

As for creating a new exception type for this case, There exists a python error that says the object being iterated was changed during iteration.  What is the error they get with this code? Is it just a KeyError?

**Comment by MisterSheik** [comment]
In [1]: a = {1:2, 3:4}

    In [2]: for x in a:
       ...:     del a[x]
       ...:
    ---------------------------------------------------------------------------
    RuntimeError                              Traceback (most recent call last)
    <ipython-input-2-7b84a6b1aa7f> in <module>()
    ----> 1 for x in a:
          2     del a[x]
          3

    RuntimeError: dictionary changed size during iteration

**Comment by MridulS** [comment]
I was messing around with the functions in `networkx/algorithms/shortest_paths` . `single_source_shortest_path_length` returns a dict of shortest path lengths keyed by target. Does it make sense to return an iterator instead, from the users perspective?

**Comment by MisterSheik** [comment]
In my change, I added `pairwise` and `consume` from `more_itertools` to `utils.misc`.  I noticed that some of the iterable code is using `len(list(x))`.  It would be better, I think, to use `more_itertools.ilen` and not creating the list.

**Comment by dschult** [comment]
@MridulS yes I think it makes sense to have path_length become an iterator of (node, length) 2-tuples.

**Comment by jfinkels** [comment]
In #1837, I changed `edge_boundary` to return an iterator (and `node_boundary` to return a set).

**Comment by hagberg** [comment]
Closed due to inactivity.
