### ISSUE TITLE
Should multigraph keys use uuid.uuid1()?

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#1654]
Currently we are providing sequential integer keys for multigraphs when adding an edge with an unspecified key.  Should we switch to using uuid to get unique keys?  This will solve some issues when working with more than one multigraph like #1619.

**Comment by MisterSheik** [comment]
It looks like that function sometimes returns a random 14 bit integer?  Do you need it to guarantee uniqueness?

**Comment by hagberg** [comment]
The point is to generate unique ids.  uuid is one way to do that.

**Comment by MisterSheik** [comment]
Right, I agree with your reasoning.  I think I just misunderstood the documentation.  I thought it returned 14-bit numbers.  It looks like you get at least 64-bit numbers, which are essentially unique as you wanted.

**Comment by chebee7i** [comment]
I have a PR open that had some code to provide support for user-defined key functions..I think it was the one to make add_edge return a key. I can find it later today when I get access to something other than my phone. But I think ints are fine and if it is configurable, then people can do other stuff if they wanted.

**Comment by hagberg** [comment]
@chebee7i do you think uuid  is overkill?  Why would we want users to be able to define a key generator?

**Comment by chebee7i** [comment]
If you want `G.add_edge()` to assign a key to each edge that is potentially informative in ways more than just uniqueness---say, insert datetime, or insert order (as a monotonically increasing graph-wide integer)---then people might find it useful for this to be configurable. It doesn't matter either way to networkx, since it is just an id, and I don't think we lose much by being flexible.

So far the main justification for why we need uuids is that it solves a problem when working with *multiple* multigraphs. This seems to indicate that this isn't a problem that is intrinsic to the graph classes themselves.  In that sense, it seems unnecessary, but perhaps of use in particular situations---which is no different from people who might want a custom edge key function in their own particular situations. This is part of why I feel the default should stay 'int', but I'm not too torn either way.

[Aside](https://docs.python.org/2/library/uuid.html#uuid.uuid4): 
> Note that uuid1() may compromise privacy since it creates a UUID containing the computer’s network address. uuid4() creates a random UUID.

These uuids are 128-bit and will increase memory footprints by a factor of 2 over 64-bit ints. If you really wanted to save some space, you could provide your custom function to use smaller ints (say `np.int16`) whenever you know a maximum number of edges that you will need to consider.
