### ISSUE TITLE
Need updated web front page.

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#1657]
Now that readthedocs holds our docs and hopefully soon tutorials and examples in notebooks...
A more modern web front door would be great.  Any takers.  See https://github.com/networkx/networkx-website/issues/9

**Comment by hagberg** [comment]
See #2054

**Comment by jarrodmillman** [comment]
I could do this.  I will discuss on networkx/networkx-website#9.

**Comment by jarrodmillman** [comment]
This can be closed when networkx/networkx-website#11 is merged. @hagberg

**Comment by MridulS** [comment]
@jarrodmillman I took a stab at this with a Jekyll based theme, moving from the sphinx based landing page https://nxtestweb.github.io 
No more HTML editing with Jekyll :D

Thoughts? @hagberg @dschult @jarrodmillman

**Comment by dschult** [comment]
The theme on nxtestweb.github.io looks wonky in my browser. The top of the sidebar is cutting off some of the first line of text.  Does it look that way to you?

Also the links in the sidebar are not consistent in that some bring you to a page about that topic while others perform an action directly. For example "Download" initiates a download rather than bringing you to a page about downloading.  I know this kind of comment is about content rather than theme, but its hard for me to separate the two.

I haven't looked at the output of [networkx/networkx-website#11](networkx/networkx-website#11) to make a comparison. But it seems to be closer to our current landing page, only with a new theme.

**Comment by jarrodmillman** [comment]
The website (http://networkx.github.io/) has been updated with the default Sphinx theme.  If this looks reasonable, this issue can be closed.

If there is still an interest in making a more substantial change, I suggest we open a new ticket for discussion.  But I don't think it should be marked as a `networkx-2.0` milestone.  At any rate, it isn't necessary for the landing page to be updated at the same time as a networkx release.

**Comment by MridulS** [comment]
@dschult This is what it is supposed to be ![screen shot 2017-07-19 at 10 44 44 pm](https://user-images.githubusercontent.com/5363860/28380157-e7361120-6cd3-11e7-8676-98a5bb016bc4.png)

It's pretty much inspired by http://www.mdanalysis.org

The alabaster theme looks nice on http://networkx.github.io/ . Anyway as @jarrodmillman pointed out we can change the theme or modify the landing page at any later time 😄

**Comment by hagberg** [comment]
I'm going to close this for now.  All improvements in documentation and web presence are welcome in new PRs.
