### ISSUE TITLE
Build errors on readthedocs

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1667]
See, for example, the log for the most recent build as of the writing of this issue: https://readthedocs.org/builds/networkx/3082116/

If you search for "Build Standard Error" you can see all the errors.

**Comment by SanketDG** [comment]
Judging by the files where the errors are occuring...this is the probable reason for #1642

**Comment by MridulS** [comment]
@SanketDG yes and the documentation is broken at various places

**Comment by hagberg** [comment]
I don't understand what is happening there.  It looks like a lot of errors - is there something global wrong with the config (e.g. numpy docstyle) or is it just that there are many small fixes needed?

**Comment by jfinkels** [comment]
I think it's many small fixes needed, just the result of not being able to easily see the build logs until recently.

**Comment by SanketDG** [comment]
Looks like it fails to load the [gallery](http://networkx.readthedocs.org/en/latest/examples/drawing/ego_graph.html) as well.

**Comment by AgostinoSturaro** [comment]
What about using the same documentation style as 1.9.1, would that prevent some errors?

**Comment by dschult** [comment]
I've almost got this working.
The main trouble is that readthedocs sphinx 1.3 introduced an error so that autosummary won't work correctly. They fixed it in their development version but readthedocs won't change until a new release of sphinx comes out.  They are close to a new release, but I'm not sure what that means.

https://github.com/rtfd/readthedocs.org/issues/1290
https://github.com/sphinx-doc/sphinx/issues/1822

I've managed to get rid of all the other errors, and if I put the (one-line) fix into my local sphinx, the errors go away.  I'll try to put the changes into a PR

**Comment by chebee7i** [comment]
It's a shame that sphinx's one-line solution cannot be monkey-patched in...the fix is in some very long function.
