### ISSUE TITLE
Create and use/raise a `NetworkXNotFound` error

### ISSUE THREAD

**Issue by harlowja** [networkx/networkx#1697]
In a lot of places it seems `NetworkXError` is raised for items not existing in graphs (edges, nodes) but it seems like a much better choice would be to raise some sort of `NetworkXNotFound` error/exception instead as this allows for determining whether something is missing vs the other `serious error in NetworkX` (which is on the docstring of `NetworkXError`).

**Comment by jfinkels** [comment]
This is a good idea. Can I take this opportunity to suggest ditching the `NetworkX` prefix on all of the exceptions? Just create a `NodeNotFound` and `EdgeNotFound` exception, the `NetworkX` part is redundant.

**Comment by SanketDG** [comment]
@jfinkels I think the NetworkX prefix is used on all the exceptions so that the error can be instantly recognized as something related to NetworkX. @hagberg could fill in why was the NetworkX prefix used in all of them.

On the other hand, I find the names `CycleNotFound` and `PathNotFound` much more appropriate and intuitive than `NetworkXNoPath` and `NetworkXNoCycle`. But then again, what if those exceptions are of some other graph package? You could go through the trace back and find out the real reason, but having a prefix like that makes it fast to recognize the issue.

**Comment by jfinkels** [comment]
I assume the prefix is there as another leftover from C-like programming style. In Python, the traceback includes the package in which the exception lives, see the last line:

    $ python -c "import networkx as nx; nx.Graph().remove_edge(0, 0)"
    Traceback (most recent call last):
      File "/home/foo/src/networkx/networkx/classes/graph.py", line 938, in remove_edge
        del self.adj[u][v]
    KeyError: 0

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/foo/src/networkx/networkx/classes/graph.py", line 942, in remove_edge
        raise NetworkXError("The edge %s-%s is not in the graph" % (u, v))
    networkx.exception.NetworkXError: The edge 0-0 is not in the graph

However, I will open a different issue for that. As for the current issue, I think not just `NetworkXNotFound` but more specific errors like `NodeNotFound` and `EdgeNotFound` are appropriate.

**Comment by SanketDG** [comment]
@jfinkels, thanks for clearing that up. The prefix is indeed redundant.

**Comment by hagberg** [comment]
Lets move this to #1705
