### ISSUE TITLE
compose

### ISSUE THREAD

**Issue by stsouko** [networkx/networkx#1713]
compose func merge edges data
e.g. R=compose(G,H)
G.edge = 2: {3: {'p_b': 1}
H.edge = 2: {3: {'s_b': 2}

R.edge = 2: {3: {'p_b': 1, 's_b': 2}

, but not for nodes
G.node = 3: {'p_b': 1}
H.node = 3: {'s_b': 2}

R.node = 3: {'s_b': 2} # 'p_b' missed

**Comment by hagberg** [comment]
This is probably a bug.  It's at least unexpected from the documentation.  For example
```python
In [1]: import networkx as nx

In [2]: G = nx.Graph()

In [3]: H = nx.Graph()

In [4]: G.add_node(1,color='red')

In [5]: G.add_node(2,color='blue')

In [6]: H.add_node(1,color='green')

In [7]: H.add_node(2)

In [8]: R = nx.compose(G,H)

In [9]: R.node
Out[9]: {1: {'color': 'green'}, 2: {}}
```
is surprising since the attribute of node 2 in graph G is replaced by the "no-attribute' state of graph H.

Bug or feature?  Fixes?

**Comment by kshitij10496** [comment]
While reading the codebase of `compose()`, I found the [notes](https://github.com/networkx/networkx/blob/master/networkx/algorithms/operators/binary.py#L315-L318).
As its stated that `Attributes from H take precedence over attributed from G`, I think that the function is working properly.

I think we can add a new feature to choose the precedence which can be useful in such cases.
I would like to work on it.

**Comment by stsouko** [comment]
bug fixed.
at this time attributes with same name from H take precedence over attributed from G.

**Comment by jfinkels** [comment]
This was fixed in pull request #1714.

**Comment by dschult** [comment]
Yes, the bug was fixed... 

but @kshitij10496 was offering to add functionality to allow the user to choose which attribute takes precedence.

With regard to that, couldn't the user pick by specifying the order of the inputs? ```compose(G,H)``` vs ```compose(H,G)```?  Are you suggesting something more than that?

**Comment by kshitij10496** [comment]
Okay, then.
Shouldn't this issue be closed now ?

@dschult I have two points:
- `compose(H, G)` is a nice way to work but I think adding a new argument to the function can make the `compose()` a bit clearer and user-friendly. 
- Moreover, in the function `compose(G,H)` if a node in `G` has a unique attribute, and the same node in `H` does not, the attribute gets dropped. Since, the aim of the `compose()` function is to take a `union` of the two set of nodes(and edges), I think adding such unique attributes of `G` to the final nodes set would be good feature.

**Comment by dschult** [comment]
Yes, I will close this issue now... 

It looks like #1714 fixed the bug that caused attributes in G to be dropped. It works as the python dict update method: Effectively that is a union of the keys with duplicate keys given the value from the H graph.
