### ISSUE TITLE
Remove __author__ from existing files

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1728]
Many files have an `__author__` module-level attribute. This is unnecessary: if it is a copyright notice, the copyright notice should appear in a comment at the head of the file; if it is simply a notice of authorship, this can be inferred from the blame chart for the file (`git blame`) or simply the commit history. Its existence also encourages new contributors to add this attribute to new modules in pull requests which is a bad habit.

**Comment by MridulS** [comment]
I guess this is like PEP8 category changes. Instead of doing `grep`/`sed` and removing `__author__`  at one go we can just add this change if anyone works on a file, just like PEP8 changes.

Anyway I have created a PR https://github.com/networkx/networkx/pull/1731

**Comment by hagberg** [comment]
I agree that using a module level attribute isn't a great idea.  But

**We will absolutely not remove author information.**

Remember this software project is more than 10 years old.  It started long before there was `git` or `github`.  In fact I think the first version control system was `cvs`.   We have tried to retain the authorship history through the years with version control but it is possible some is lost.  Also there are examples I remember where I added authors to the list because they made substantial contributions using channels other than version control such as email.

**Comment by jfinkels** [comment]
If authorship is maintained for copyright purposes, it can simply move to a
comment at the head of the file.

**Comment by jfinkels** [comment]
And if authorship is maintained for historical interest purposes, it
can be moved to the changelog (see the Python "What's New", for
example: https://docs.python.org/dev/whatsnew/3.5.html )

**Comment by hagberg** [comment]
How about we agree to update the author variables to comments when we modify the file for some reason?

**Comment by jfinkels** [comment]
Or just when you modify something near the top of the file...seems fine to me.
