### ISSUE TITLE
Inconsistent signatures for layout methods

### ISSUE THREAD

**Issue by AgostinoSturaro** [networkx/networkx#1749]
I noticed some good additions have been made to layouts for the 1.10 version.

However, I also noticed that `random_layout` is the only method lacking the `scale` parameter.

    random_layout(G, dim=2, center=None)
    circular_layout(G, dim=2, scale=1, center=None)

The `center` parameter has been added in v1.10. Adding `scale` as well would have made it more intuitive to switch between the two layouts.

A similar argument could be made for other methods, the signatures are quite inconsistent.
Notice the order of parameters `dim`, `scale`, `center` and `weight`.

    circular_layout(G[, dim, scale, center])
    random_layout(G[, dim, center])
    shell_layout(G[, nlist, dim, scale, center])
    spring_layout(G, dim, k, pos, fixed, iterations, weight, scale, center)
    spectral_layout(G, dim, weight, scale, center)

They could be re-organized for v2, putting parameters with the same name in the same place

    circular_layout(G[, dim, scale, center])
    random_layout(G[, dim, scale, center])
    shell_layout(G[, dim, scale, center, nlist])
    spring_layout(G[, dim, scale, center, weight, k, pos, fixed, iterations])
    spectral_layout(G[, dim, scale, center, weight])

EDIT: another welcome addition would be a `seed` parameter for `random_layout` and possibly also for `spring_layout` (right now there's no way to make it deterministic).

**Comment by dschult** [comment]
I don't think we should push too hard on making the parameters the same for all the layout functions. In particular the ```random_layout``` was specifically chosen to be different. ```circular_``` and ```shell_``` naturally surround the origin, while ```random_``` and ```spring_``` are more natural on the unit square. I'm not sure ```spectral_``` should even have a "center" argument at all.

The ```random_layout``` is especially important to be clear that the size affects the range of "possible values" and not the range of actual results. If you choose uniformly random values on ```[0,1)``` and then rescale them so the max value is "size", then it's not easy to figure out the random distribution you chose from. Much better to choose uniformly random on ```[0, size)```.

I think this ticket is really about aligning expectations of users with the code.  Users expect the arguments to be the same -- and we should be more clear that the layout range is different for different layouts. 

Perhaps the differences would be more clear if we used different names for the arguments in layouts which return circular results from those with square.  For example, "scale" and "center" for circular domains vs "size" and "shift" for square domains.

    circular_layout(G, scale, center])
    shell_layout(G, nlist, scale, center)
    random_layout(G, size, shift)
    spring_layout(G, weight, k, pos, fixed, iterations, size, shift)

I don't particularly care about the order of the parameters. But if we're going to go there then ```dim``` should not be the first argument. The default is almost always used. Perhaps the last three should be ```scale, center, dim)``` so that the layout specific arguments can be used without keywords: e.g. ```spectral_layout(G, "weight")```.

I would propose (leaving spectral's return values as they are because I don't have a better suggestion):

    circular_layout(G[, scale, center, dim])     --> [-scale, scale] + center
    shell_layout(G[, nlist, scale, center, dim])

    random_layout(G[, size, shift, dim])         ---> [0, size] + shift
    spring_layout(G[, weight, k, pos, fixed, iterations, size, shift, dim])

    spectral_layout(G[, weight, scale, center, dim])    ---> [-scale, scale] + center

@AgostinoSturaro what do you think?

**Comment by AgostinoSturaro** [comment]
Thank you for asking.

I started the topic when 1.10 was released and I noticed that I had to manually rescale some methods and not some others. That collided with my immediate expectations.

Now, if I stop and think about it, there is a reason for `random_layout` to be the only one without a `scale` parameter. But if we talk about expectations, that was definitely unexpected.
I agree on not using the `rescale` function for the `random_layout`, as that would skew the distribution.
Having a reasonable `scale` (or `size`) parameter can be handy, and choosing the distribution in `[0, scale)`, or `[0, size)` should get reasonable results.

I see that some layouts produce a graph in `[-scale, scale]`, while others produce a graph in `[0, size]`, and this may not be very intuitive at first, but it's easy to see the effects by running the functions a couple of times.

I understand why you suggest using a `shift` parameter for `random_layout` instead of `center`.
However, the `center` parameter could have the same meaning for all layouts. It can default at the origin (0, 0) for `circular_layout` and at (0.5, 0.5) for `random_layout`.
It's true that (0.5, 0.5) is not the exact center of [0, 1), but it should fit expectations.
On the other hand, if `center` "shifts" the `random_layout`, then probably it should be called it shift ;)
I see no optimal solution. You decide what to do here.

About `dim`, up to v1.9.1, it was the first parameter for all layouts, except for `shell_layout`.

    circular_layout(G[, dim, scale])
    random_layout(G[, dim])
    shell_layout(G[, nlist, dim, scale])  # here
    spring_layout(G[, dim, k, pos, fixed, ...])
    spectral_layout(G[, dim, weight, scale])

In fact, that tricked me when I used `shell_layout`, because I memorized `dim` to be in the second position, and so I expected it to be there.

To prevent breakages for a minor version (v1.11), I propose these changes only

    circular_layout(G[, dim, scale, center])  # where center defaults to (0, 0)
    random_layout(G[, dim, scale, center])  # where center defaults to (0.5, 0.5)

I agree on your idea of moving the less used parameters at the end.
This could be done for v2, to prevent API breakages, right?
Notice how, `shell_layout`, `spring_layout` and  `spectral_layout` all have `dim` and `scale` parameters, but in different order, and there is no particular reason for the different order.
Here is my proposal for them

    shell_layout(G[, nlist, dim, scale, center])
    spring_layout(G[, k, pos, fixed, iterations, weight, dim, scale, center])
    spectral_layout(G[, weight, dim, scale, center])

With those changes, `dim, scale, center` would always be at the end, and we would gain consistency.
@dschult What do you think?

**Comment by hagberg** [comment]
Does this need fixing for v1.11?

**Comment by dschult** [comment]
#1760 was merged back in Sept to v1.11 to fix this issue for that version. It added scale and center for all but random_layout which did not get the scale parameter (because scaling the points to be in a specific range makes the random process wonky--scaling the potential domain makes sense but differs from the other usage of the keyword ```scale```). I plan to revisit this for v2, but thought we should not do the other changes on a minor release. 

Discussion came back to this issue when #1892 was submitted. but I think of it as being for v2 not for v1.11

The proposal for v1.11 above (two comments up) suggests changes to ```circular_layout()``` that have already been made and then to add ```scale``` to ```random_layout()``` which I had decided not to do because it is potentially confusing.
