### ISSUE TITLE
Graph generators change default random seed

### ISSUE THREAD

**Issue by AgostinoSturaro** [networkx/networkx#1764]
I noticed that, when passing graph generators a `seed` parameter, they change the _default_ seed for `random`. This affects affecting all subsequent calls to `random` in the module.
That is, if a single generator is passed a `seed` parameter, all other generators are affected.
[Most](https://github.com/networkx/networkx/blob/v1.10/networkx/generators/random_graphs.py#L47) [generators](https://github.com/networkx/networkx/blob/v1.10/networkx/generators/random_graphs.py#L602) seem to be doing this. The code in question is

```
if seed is not None:
    random.seed(seed)
```

Here's a discussion [on SO](http://stackoverflow.com/q/12368996/1600770). There is a simple solution. Creating an instance of `random` inside each function would make the seed change self-contained and prevent it from affecting other calls. Something like this would do

```
if seed is not None:
    my_random = random.Random(seed)
else:
    my_random = random
...
# use my_random for calls
```

The same trick can be used if a NumPy random generator is needed

```
my_random = np.random.RandomState(seed)
```

This could be especially useful to add a `seed` parameter to the layout functions, that currently lack one, and do not provide a way to arrange nodes deterministically (the same way in two different calls). see for instance [this function](https://github.com/networkx/networkx/blob/v1.9.1/networkx/drawing/layout.py#L55).

**Comment by NeilGirdhar** [comment]
We shouldn't be taking a seed parameter at all.  We should be accepting an instance of `random.Random` or if None using `random`.  This would allow running simulation for example with a random number generator and getting repeatable results.  You don't want to have to come up with seeds for every time the rng is used.  You want to seed it once and pass it to ever function that needs an rng.

**Comment by chebee7i** [comment]
Related: #1550

**Comment by jeffzemla** [comment]
This bug just cost me three days of my time, so I second using `my_random=random.Random(seed)`. 

Personally I would prefer to pass it a random seed rather the an instance of random.Random, but I can see the merit in that as well.

**Comment by NeilGirdhar** [comment]
@jeffzemla The problem with passing in seeds is that you might have many other pieces of code that use random numbers.  Are you supposed to seed all of those random number generators at the start of your simulation?  When you want to restore the simulation to a particular point, you need to save all, say 5, seeds?  That is really poor design.

That's the reason that all of the scipy and numpy functions that take random numbers accept a random number generator.  It is the de facto Python way of introducing randomness, and in my opinion, it's good design.

Also, a seed limits you as to what kinds of random number generators you can use.  Not all random number generators have a state that can be described using a single number.

**Comment by jeffzemla** [comment]
@NeilGirdhar No, you could still create a single random number generator (e.g., `my_random=random.Random(seed)`) and save that. Whenever you make a call to generate a graph, pass it `seed=my_random.random()`. You can create as many graphs as you like this way, each with a different random seed, same as your method.

If you pass a random number generator, it's not easy to read your code and see what will be returned. If you pass `seed=1232`, you know you'll always get the same result. If you pass `seed=my_random`, you may or may not get the same result depending on the order of the calls.

I realize that not everyone wants to use the stock `random` number generator, and that's a legitimate concern, but seems like a very rare case.

**Comment by NeilGirdhar** [comment]
@jeffzemla  Instead of passing the rng, you're passing a seed from an rng, which you then use to initialize another rng?  That is very roundabout way of just passing the rng.

I don't undersand your second point.  What is hard about reading code that passes an rng?

The order of calls will always matter even in your system of creating seeds — the order in which you create them changes them and changes things.

I personally think this is a poor design.

**Comment by NeilGirdhar** [comment]
By the way, if you want to inspect or serialize a rng, you can always call its `get_state` member.

**Comment by jeffzemla** [comment]
@NeilGirdhar I wouldn't call it roundabout. The difference for the end user is literally a matter of `my_random` vs `my_random.random()` and nothing else.

My second point is that if you see a call that has `seed=1234` you know that code will return exactly the same thing every time. If you see a call that has `seed=my_random` or `seed=my_random.random()` you don't know that it will return the same thing every time unless you know exactly how many times `my_random` has been called previously. My suggestion allows you to use `seed=1234` for clarity, but `seed=my_random.random()` when necessary.

**Comment by NeilGirdhar** [comment]
@jeffzemla It is one extra indirection without value.

If you want a magic number in your code (why you want that I have no idea), you can still do: `rng=RandomState(1234)`.

If I've ever had a fixed seed, it was usually in exactly one place in the code, rather than mixed in everywhere.

**Comment by dschult** [comment]
This should be easier now that #2766 has been merged.

**Comment by NeilGirdhar** [comment]
@dschult Unfortunately, this is really poor design.

Passing an object that exposes the RandomState interface is the de facto standard set by numpy and scipy.  Why would networkx depart from that approach?

Instead, networkx should be passing the rng to functions so that they can be chained together, e.g.

```
form numpy.random import RandomState
from networkx import uniform_random_intersection_graph, gn_graph

rng = RandomState(123)
x = gn_graph(100, rng=rng)
y = gn_graph(200, rng=rng)
i = uniform_random_intersection_graph(n, m, p, rng=rng)
```

Doing that with seeds is very convoluted: you end up needing a seed for each operation, which initializes a new `RandomState` three times (yuck).

**Comment by hagberg** [comment]
I think #1550 makes the same argument for using the RandomState interface.

**Comment by NeilGirdhar** [comment]
@hagberg  Right.  But at the end of that issue, is just a pointer back here.  Am I missing something?  What was wrong with @chebee7i 's suggestion?

**Comment by hagberg** [comment]
I advocated (too weakly) for this in #1550.  It doesn't look like anyone ever created a PR that implements the RandomState approach.

**Comment by dschult** [comment]
I have changed the name of #2766 to better reflect its code -- which DOES implement a random_state approach following the advice from #1550 and #1764.  Sorry for the confusion.  I'm trying to ping this issue because we now have it "solved" for the layout functions, and we have a decorator to help implement it. We need to change the generators and look for other places that use random values.

**Comment by NeilGirdhar** [comment]
@dschult Oh!  I see it now.  I looked at the code too quickly.  Sorry if my message came off badly.  Your code looks great.

**Comment by AgostinoSturaro** [comment]
Thank you, this is good news for me and it will make some of my regression tests easier.

**Comment by dschult** [comment]
I'm thinking that we should implement separate tools to handle ```random``` and ```numpy.random```.  Then individual code can easily choose which environment they want to work with. The other option is to choose one ecosystem for this package. 

The layout code uses ```numpy.random``` -- and it also uses numpy matrices. The graph generator functions use ```random``` and that allows them to work in environments that don't work with numpy (though those are getting few and far between). 

I'm thinking of using ```@np_random_state``` and ```create_np_random_state``` alongside ```random_state ``` and ```create_random_state```.   Thoughts?

**Comment by NeilGirdhar** [comment]
If you don't mind, just to make it clear for me, I'll sum up my understanding:

 `create_np_random_state` would be used internally to turn an argument into a `np.RandomState`.  (It is currently called `create_random_state`.)  A new `create_random_state` would be added to create an object with `random`'s interface.

Users would continue to pass in either `random` objects or `np.RandomState` objects depending on the function.

If this is right, then I think that's pretty good design.

The only question is whether to just make everything use `np.RandomState` or try to keep some functions working with `random` to keep users from having to pull in `numpy`.   Let's call them "single generator type" and "two generator types".

I understand the desire not to depend on numpy.  However, it is often the cases that someone will want to pass the *same* random number generator to all functions, so if you go with the "two generator types" system, then it would be nice to provide an adapter so that an `np.RandomState` can be used as a `random` generator.  It should be possible, but if it's not then I suggest you go with the "single generator type" system.

**Comment by dschult** [comment]
I think you summarized it pretty clearly -- in particular that the remaining question is whether to support two generator types or commit to a single generator type.

I don't think adapting the generators to look the same is a good approach. They have many different methods and it'd be a lot to maintain a unified API that works with either. The different methods make me realize that there are almost certainly advantages to each library. Some of our contributors will want to use ```random``` and others will want ```numpy.RandomState```. 

This makes it tricky to see how to allow someone to use the same random number generator in all functions. Can you explain the need to use the same RNG for, say, generating the graph and initializing its layout?

**Comment by NeilGirdhar** [comment]
One reason to want to use a single generator is when doing any kind of simulation.  You often want repeatable running of that simulation.  You might also want to save the state and reload.  In the two generator version, you would actually need to save and reload two generators in order to accomplish this.  I like client code to be as simple as possible, so just keeping one generator is just simpler.

Also, it's not exactly a unified API that I'm proposing:  You don't need to make `RandomState` work like `random`; you just need those functions from `random` that you actually use be implemented in terms of `RandomState` methods.  How many functions out of `random` are you actually using?

Another argument against using `random` is that using it means that you have to have possibly expensive `random.setstate` and `random.getstate` calls bracketing all use of `random`.  That's going to complicate networkx's code.

**Comment by NeilGirdhar** [comment]
Here's my proposal: Keep using `create_random_state`, but in those methods that only need the simpler `random` interface, pass in a flag like `simpler_interface`.  Then `create_random_state` would create something based off of `random` for them.  I'll code it now and post it here.

**Comment by dschult** [comment]
I'm digging into this again and it looks like the ```simpler_interface``` argument is essentially making two ```create_random_state``` functions. By that I mean that the methods available from ```np.mtrand._rand``` and ```random._inst``` differ. So if you want to use the ```random``` interface for your code you call with the ```simpler_interface``` set.  If you want the ```numpy``` interface you use the default ```simpler_interface```.  It's generally not possible to allow the user to pick the RNG so we're back to using two RNGs.

Perhaps our codebase doesn't use more than ```choice```.  But if we use ```randint(a,b)``` anywhere, the arguments are different (numpy has top value exclusive while random is inclusive) then we'll have to either support users using two RNGs or force contributors to use ```numpy```. 

I'm leaning toward your example's approach of allowing contributors to use wither of two RNGs (```random``` and ```numpy```) and users will need to supply state for both (if they use functions that use both).  I think I prefer to make two functions though rather than the ```simpler_interface``` argument to make it all more obviously explicit.

Thoughts?

**Comment by NeilGirdhar** [comment]
> I'm digging into this again and it looks like the simpler_interface argument is essentially making two create_random_state functions. By that I mean that the methods available from np.mtrand._rand and random._inst differ. So if you want to use the random interface for your code you call with the simpler_interface set. If you want the numpy interface you use the default simpler_interface. It's generally not possible to allow the user to pick the RNG so we're back to using two RNGs.

I think you misunderstood.  The `simpler_interface` argument supports passing a numpy interface.  Please look again.

> I'm leaning toward your example's approach of allowing contributors to use wither of two RNGs (random and numpy) and users will need to supply state for both 

That's terrible.

**Comment by dschult** [comment]
My reading of the example code is that a contributor calls ```create_random_state(rng, True)``` when they want the ```random``` package and ```create_random_state(rng)``` when they want ```numpy```.   The returned value is different and can't be used interchangeably. So they are effectively two separate functions.

Doesn't that mean the user will have to set the state for 2 RNGs?

We won't need lots of ```getstate``` and ```setstate``` with the random package. That code can take a RNG as an argument just like the code that uses numpy. Create a new RNG with random.Random(). Use the global RNG with ```random._inst``` just like ```numpy.random.mtrand,_rand```.  It's all the same, but the API is different. so we can't quite use them interchangably.

**Comment by NeilGirdhar** [comment]
> The returned value is different and can't be used interchangeably. So they are effectively two separate functions.

The returned value can be used interchangeably because they implement the same interface.

> Also, we won't need lots of getstate and setstate with the random package. 

It's the user code that might want to preserve the state so that execution is consistent.  The way things are written now, it is overly complicated to accomplish that.

**Comment by NeilGirdhar** [comment]
I think the misunderstanding might be because you have missed that there is no `else` clause to `if simpler_interface:`.  If you don't pass `None` or an `Integer` for `random_state`, then it _falls through_ and checks to see if you passed in a `RandomState`.  In any of those cases, it returns some object that implements enough of the `RandomState` interface to work with the calling function.

**Comment by dschult** [comment]
> The returned value can be used interchangeably because they implement the same interface.

The RandomState returned does NOT have the same interface. That's the problem we are facing. 

One example is that ```randint(1,3)``` for ```random._inst``` has 3 possible outcomes while for ```np.random.mtrand._rand``` it only has 2.  Maybe I need to look at the APIs more closely, but I believe that the numpy versions returned arrays of values while random do not. We are essentially creating a 3rd random number generator API (some sort of lowest common API between the two.

Am I missing something here?

**Comment by NeilGirdhar** [comment]
> The RandomState returned does NOT have the same interface. That's the problem we are facing.

That's fixed by using a facade like I did in `SimpleRandomState`.

> One example is that randint(1,3) for random._inst has 3 possible outcomes while for np.random.mtrand._rand it only has 2. Maybe I need to look at the APIs more closely, but I believe that the numpy versions returned arrays of values while random do not.

Good catch!  That's fixed in my code now.  The numpy versions return scalars when size is none.

> We are essentially creating a 3rd random number generator API (some sort of lowest common API between the two.

You don't need to do that.  You just need to make one look like the other.

**Comment by dschult** [comment]
> That's fixed by using a facade like I did in SimpleRandomState.

But it's not fixed. The facade either has to implement the entire API or we end up with some 3rd API that is a least-common-api approach.  For this example facade, we lose the ability to use the ```size``` to return an array of values. So now -- to make our code work for either RNG, we must have ```size=None```.  Every contributor that uses numpy.RandomState will not be able to use the size argument.

I like the idea that contributors can use either random package's API without our having to maintain it. I like the idea that users can control the random_state. Merging those two goals seems to mean that a "seed" becomes two integers -- one for each package.

**Comment by dschult** [comment]
>It is fixed. You only ever call create_random_state with simpler_interface=True in those cases where >you rely only on the random interface. You don't need the size parameter in those cases.

Are you saying that any code that "relies only on the random interface" has to use the "simpler_interface"?  Those two interfaces are different.  You are saying that contributors can't use the ```random``` interface.

I'm confused. How is this helping? It seems like any contributor of code has to use the numpy interface which the simpler_interface then translates if needed. We might as well require all contributors to use the numpy interface.  I want contributors to be able to use whatever package they prefer... 

>Contributors that rely on the full RandomState interface will not set simpler_interface to true, and >they can therefore use the full interface.

So you are saying that any user who wants to use a single RNG will need to use a numpy RandomState object.  I guess I was getting hung up on making it work either direction.  Let's clarify the goals.

[By the way -- thanks for sticking with me on this. I'm not agreeing but I feel that it is helping and we're making progress even if it does take a bit for me to catch on.]

Cases:
1) our code written to use RandomState, user wants to use RandomState.
2) our code written to use RandomState, user wants to use random.
3) our code written to use random, user wants to use RandomState.
4) our code written to use random, user wants to use random.

I think your proposal is to have cases 3) & 4) rewrite the code to use the simpler_interface and case 2) isn't supported.

Can we think about this instead: 
1) and 4. Pass through without issue
2) isn't supported
3) create a facade to allow ```random``` syntax to be used with the RandomState RNG (inverse translator of the above example).

I'm hoping this: allows contributors to use what they want while allowing users to use RandomState for everything if they want to.  Users would not be able to use ```random``` for everything.

**Comment by dschult** [comment]
>>I think your proposal is to have cases 3) & 4) rewrite the code to use the simpler_interface and case >>2) isn't supported.
>
>Yes, exactly. Note that case 2 and case 3 are currently unsupported.

Agreed!  :)   and to summarize: 
Cases 2 and 3 are not currently supported. Both our proposals add case 3. 
One difference is that under your proposal, 4 would require rewriting existing code that uses ```random```. Another difference is that under my proposal NX would have some functions that use the numpy ```RandomState interface``` and some that use the "quircky" ```random``` interface. 

Implementation:
- create tools (helper functions and decorators) to allow easy support for a single RNG.
- update all functions that use a global RNG without allowing a "seed" parameter.
- update all  functions that use "seed" parameter so that they allow an RNG.
- (your proposal) update all functions that use the ```random``` interface to use the ```RandomState``` interface.

Note that we might want to do the last bullet even with my proposal.  Newly contributed  code could use the ```random API``` but existing code for v2.2 would all use ```RandomState API```.

I think the next step is to figure out how much work the last bullet would be -- and potential for inserting bugs.  This feels like we're getting somewhere.

**Comment by NeilGirdhar** [comment]
Totally agree.  You're right that if that last bullet point is too much work, we should go with your proposal.

**Comment by dschult** [comment]
How about this for doc_string description of argument:

    random_state : random_state, integer or None (default)                                
        Indicator of what random state to use for random number generation.       
        If a random number generator (either `random.Random` or                   
        `numpy.random.RandomState`) it can then be used again.                    
        If the package `numpy.random` or `random`, use the default                
        generator for that package.  If an integer, set the seed                  
        for a random number generator used solely for this function call.         

Also, what do you think about leaving the argument name as ```seed``` for functions to allow backward compatibility?

**Comment by NeilGirdhar** [comment]
The docstring looks fine.

I think if you want to keep `seed` for backwards compatibility, you should deprecate it, call `warnings.warn` and add `random_state` alongside it.  This is what `tensorflow` did with their `axes` parameters.

**Comment by AgostinoSturaro** [comment]
Do I understand correctly that the original issue of NetworkX changing the seed for the default random number generator has been solved?
It won't change the default np.random instance either, right?
Thanks.
