### ISSUE TITLE
Python 3 graphviz layout gives "IndexError: list index out of range"

### ISSUE THREAD

**Issue by mfitzp** [networkx/networkx#1836]
Trying to use the graphviz layout `pos=nx.graphviz_layout(G, prog='dot')` with Python 3 gives an `IndexError: list index out of range`.

    /usr/local/lib/python3.4/dist-packages/networkx/drawing/nx_pydot.py in pydot_layout(G, prog, root, **kwds)
        294 
        295         if isinstance(node,list):
    --> 296             node=node[0]
        297         pos=node.get_pos()[1:-1] # strip leading and trailing double quotes
        298         if pos != None:

    IndexError: list index out of range

This can be fixed for Python 3 by removing the `.encode('utf-8')` on line `#292`:

        pydot_node = pydot.Node(make_str(n)).get_name() #.encode('utf-8')

Of course this fix probably breaks Python 2 but hopefully gives some indication as to the cause. Tested against latest `master`. See also [this SO post](http://stackoverflow.com/questions/32183964/python-3-networkx-draw-graphviz-does-not-work).

**Comment by SanketDG** [comment]
`pydot` itself does not support py3 but [pydot2](https://github.com/davidvilla/pydot) and [pydotplus](https://github.com/carlos-jenkins/pydotplus) does, as it seems. Maybe we could switch.

**Comment by chebee7i** [comment]
I wasn't aware of pydot2. We can probably add that to the list we already search. See also: #933, #1334, #1389

**Comment by chebee7i** [comment]
@mfitzp If you make one of these other pydot libraries available, then I suspect it will just work. As of now, NetworkX tries the following modules (in order, breaking once it finds one): ['pydot', 'pydotplus', 'pydot_ng'].

The whole situation is *still* a mess...

**Comment by KevinTyrrell** [comment]
I can confirm this exact same problem is still present within `nx_pydot.py`, precisely as the OP (@mfitzp) has described.

Occurs on the call:

    pos = nx.nx_pydot.graphviz_layout(graph, prog="dot")


This occurred on networkx 3.5, pydot 4.0.1, graphviz 0.21


This issue should be reopened. @hagberg 


<img width="1312" height="526" alt="Image" src="https://github.com/user-attachments/assets/0502cb7e-333c-4753-af8e-73c5f7f40f08" />

**Comment by MridulS** [comment]
@KevinTyrrell Can you open a new issue with a minimal reproducible example?

Trying a basic example with networkx 3.5 and pydot 4.0.1 I don't see any errors.
``` python
import networkx as nx
G = nx.complete_graph(4)
pos = nx.nx_pydot.graphviz_layout(G, prog="dot")
```

Also which version of graphviz do you have? I assume the graphviz 0.21 is coming from pypi which just wraps the DOT spec of graphviz. It is not THE graphviz on your system. Running `dot -V` in the command line should give you more information.

Something like:
```
$ dot -V
dot - graphviz version 14.0.4 (0)
```

The binaries for graphviz need to be installed via something like chocolatey  or conda.

**Comment by KevinTyrrell** [comment]
@MridulS Thanks for the reply. I will try to get a minimum reproducible example, but my codebase is complex. I'll open up a new issue when I do.

I installed Graphviz physically on my system using the windows installation wizard. Then I added `pydot` (`4.0.01`), `networkx` (`3.5`) and `graphviz` (`0.21`) with PyCharm's package manager. The libraries seem to be configured correctly. For example, `import pydot` of `def pydot_layout(G, prog="neato", root=None):` passes. 

`dot -V` inside of my `(.venv)` shows as: `dot - graphviz version 14.0.4 (20251115.1723)`

**However**, I've been debugging `networkx` and I believe I spot the issue.

Line 352 in `nx_pydot.py` is the following: `node = Q.get_node(pydot.quote_id_if_necessary(str_n))`
This is disastrous, because my node objects were added to the `networkx` **by reference**, not by string or int.

This means that in `core.py` in `def get_node(self, name: str) -> list[Node]:`
```py
match = []
if name in self.obj_dict["nodes"]:
    ...
return match
```
will **always** return `[]` and thus exception on `node = node[0]` of line 356 of `nx_pydot.py`'s `pydot_layout(...)` call. The string lookup is the culprit here.

Nodes are added to the graph via:
```py
class Node:  # example node
    ...
    @property
    def label(self) -> str: return self.__label
    def __str__(self) -> str: return self.__label

vertices: list[Node] = ...
for vertex in vertices:
    graph.add_node(vertex, label=vertex.label)
```

This works with layouts `spring_layout`, `shell_layout`, `circular_layout` etc but upon swapping to `nx_pydot.graphviz_layout`, the `str` component of the nodes are used via `str_n = str(n)` on line 352 of `nx_pydot.py`.

I believe this is exact same reason why @mfitzp 's error occurred as well, as the only way for the list to be empty is if the mapping of str -> node reference isn't defined.

**Comment by dschult** [comment]
I'm guessing that your comment about `core.py` refers to code from `pydot`. Is that correct?

It seems from your comments that `pydot` does not support the nodes you are using. Is this a `pydot` issue or a NetworkX issue?

If all my guesses are correct, you might do better with `pygraphviz` (our other interface to GraphViz). But I can't be sure.

**Comment by KevinTyrrell** [comment]
Ah I didn't notice `core.py` is from pydot. Perhaps this deserves an issue on their repo. I'll look into `pygraphviz`.

In terms of networkx, I'm not convinced that `nx_pydot.graphviz_layout` will work in any graphs in which nodes are added by reference (vertices that are not strings or numerical).

**Comment by dschult** [comment]
I think any node object that is converted to a string by `str(node)` should work. But maybe I am misunderstanding.
