### ISSUE TITLE
The minimum_edge_cut() function  returns empty set([]) in some case

### ISSUE THREAD

**Issue by litaotju** [networkx/networkx#1859]
I've noticed that sometimes the function minimum_edge_cut( digraphA) return a empty set([]) in my examples.For example:

import networkx as nx  

a = nx.DiGraph()  
a.add_edges_from([(1,2),(1,3),(1,4),(3,2),(4,2)])  
print nx.minimum_edge_cut(a)

###The following would be printed   
 set([])  

So would be glad to know if you guys know is this correct ? For a weakly connected DiGraph more than 2 nodes, an edge cut should always exist. So may be the minimum_edge_cut should never return an empty set().

**Comment by jtorrents** [comment]
Indeed this is a bug. Thanks for the report, I'll look into it.

**Comment by joelmiller** [comment]
The reason this appears to be happening (for this graph) is that there isn't a path from 2 to 3.  So it's interpreting this to mean that it doesn't have to delete any edges to disconnect the graph.

The documentation should be made clearer about how directed graphs are handled.  If the current version is the appropriate interpretation then the current test for whether the graph is weakly connected should be changed to test if it's strongly connected.

**Comment by jtorrents** [comment]
Good point @joelmiller . At a first sight it seemed a bug, but I think you are right that this is a corner case for weakly connected directed graphs. The materials on which we based the implementation were only concerned with undirected graphs (see the docstrings for the references). Generalizing it to directed graphs seemed straightforward but there are always hairy corner cases.

So we have to decide between two options: either consider all weakly connected digraphs as having edge connectivity 0, and thus no edge cut should exist (close to the current not documented behaviour and I'd say the correct one theoretically; we'd only need to change the test for weakly connected to strongly connected as @joelmiller points out). Or, when a weakly connected digraph is passed to `minimum_{edge|node}_cut` return a edge|node cut that when removed disconnects the digraph (ie makes it not weakly connected). This may not be theoretically accurate but might be useful in practice (and it's easy to implement).

I'm all for `practicality beats purity` but we should make sure that it's actually useful in practice. @litaotju can you elaborate a bit on your use case for this feature? In any case we should improve the documentation explaining the behaviour in these corner cases.

**Comment by joelmiller** [comment]
I would say that it's best to have it return `set([])` for an undirected network if it is already disconnected and also for a directed network if it's not strongly-connected.  So I'm actually suggesting a change to what happens if it gets a disconnected undirected graph.

I think it would be a mistake to make it response to a directed graph differently if the graph is weakly connected compared to strongly connected.  Too much opportunity for a misunderstanding (how did I increase the size of the minimum edge cut by deleting an edge?)

There could be a flag for the user to say that they are interested in breaking the weakly-connected property rather than the strongly-connected property (in which case it would just need to use the undirected algorithm).

So what I'm proposing is 

if `G` is undirected and disconnected, return `set([])`

if `G` is weakly connected, return `set([])`

if `G` is weakly connected, but the weakly-connected flag is `True` return whatever edges are needed to disconnect it [with some consideration to the case where (1,2) and (2,1) are both edges in the system - is that 1 to delete or 2?]

**Comment by litaotju** [comment]
@jtorrents  @joelmiller. Thanks a lot for discussing this tiny question.
In my case, I always give a directed acyclic graph(DAG) to the function, which implies that the graph is always a weakly connected  directed graph. And I always need to cut the graph to two small graphs. So a non-empty set is expected every time I called this function.

To clarify this question, I've look for a graph theory text book for the formal definition of edge cut. Here is a little quote from the book[1]:

 Let G be a nontrivial connected graph with vertex set V(G) and let S be a non-empty subset of V(G). For and non-empty set S*=V\S. let [S*, S] denote the set of all edges of G that have one end vertex in S and the other in S*. A set of edges of G of the form [S*, S] is called an edge cut of G. An edge e is a cut edge of G if {e} is an edge cut of G. An edge cut of cardinality k is called a k-edge cut of G.

In this context, I think when we are looking for a minimum edge cut of a directed or un-directed graph, they have the same meaning of "disconnect". I agree @joelmiller 's proposal for undirected graph. But I propose that:

When a connected directed graph is the function's parameter. Whether the directed graph is  weakly connected or strongly connected, the function should have the same behavior, which is: **always return a set of edges with minimum cardinality to disconnect the graph**.  The last question of @joelmiller , maybe the (1,2) and (2,1)  should both be deleted, if these two are in the minimum edge cut set.

[1]R. Balakrishnan. K. Ranganathan.  A Textbook of Graph Theory

**Comment by jtorrents** [comment]
This is fixed in #1925 which is already merged
