### ISSUE TITLE
Feature request: edge coloring, and color-specific paths and iterators

### ISSUE THREAD

**Issue by borisdan** [networkx/networkx#1946]
I realize edge colors can be set using attributes, but I think this particular property is more interesting, and should have more capabilities.
1. Add a color parameter to the *edges*, *edges_iter* functions, which gives all edges of a particular kind.
2. Find a shortest path out of edges of a specific color. Again, this can be done by having a different weight attribute per edge-type, but then each edge needs to have all other possible weight attribute type set to *float('inf')*.

**Comment by harora** [comment]
Hi
I am Himanshu. I wish to take this up.

From what i understand:
1) Add a parameter for colour in edges
2) Add a function for taking coloured edges in graph class 
[Later can be added to other classes]
3) Find shortest path using dijktra with edge colour same in path. 

Can some mentor guide on how should i go about this ?

**Comment by MridulS** [comment]
@borisdan If we have different weight attribute per edge-type then I think it shouldn't be a problem.
``` python
In [23]: G.add_edge(1, 2, r_weight=10, b_weight =4)

In [24]: G.add_edge(2, 3, r_weight=10, b_weight =4)

In [25]: G.add_edge(1, 3, r_weight=8)

In [26]: nx.shortest_path(G, 1, 3, weight='r_weight')
Out[26]: [1, 3]

In [27]: nx.shortest_path(G, 1, 3, weight='b_weight')
Out[27]: [1, 3]
```
`nx.shortest_path(G, 1, 3, weight='b_weight')` returns `[1, 3]` because the implementation gives any absent weight attribute a default value of 1. I guess we can change that and add a `default` argument.
Something like `nx.shortest_path(G, 1, 3, weight='b_weight', default=float("inf")` [This won't change the graph structure]

**Comment by borisdan** [comment]
@MridulS , this solution will be sufficient to find the shortest path with different types of edges.
Still would be nice to have a way to get only the edges, or degree, for a specifc type, but that's actually quite an easy wrapper around the normal implementation.

**Comment by jfinkels** [comment]
This can be implemented more easily if pull request #1740 gets merged. That pull request adds a method for getting an edge-induced subgraph. Then you can do

    H = G.edge_subgraph((u, v) for u, v, d in G.edges(data='color') if d == 'red')
    nx.shortest_path(H, x, y)

**Comment by dschult** [comment]
In the meantime, you can use:

    H = nx.Graph((u, v) for u, v, d in G.edges(data='color') if d == 'red')
    H.add_nodes_from([x, y]) # in case x or y has no red edge
    nx.shortest_path(H, x, y)

**Comment by MridulS** [comment]
@jfinkels @dschult In both cases we create a new graph. What do you think of exposing the `default` parameter to the user?

**Comment by dschult** [comment]
My guess is that creating the new graph will be more efficient/effective than having to look at edges which default to ```inf```.  I'm not opposed to exposing the default value, but I don't think this issue is a compelling case for doing so.

Perhaps it would be good to develop a subgraph view of graphs that restricts nodes and/or edges.

**Comment by jfinkels** [comment]
You mean like `G.subgraph(node=..., edges=...)`?

**Comment by dschult** [comment]
Due to #1690 (now merged), a feature in Dijkstra allows the weight to be a function. So, you can get shortest paths based on edge properties like color.

    def color_blue(u, v, edata):
        return 1 if edata['color'] == "blue" else None
    G=nx.Graph([(1, 2, dict(color="blue")), (2, 3, dict(color="blue")), (1, 3, dict(color="red"))])
    shortest_path(G, 1, 3, weight=color_blue)  # [1, 2, 3]
