### ISSUE TITLE
k-core algorithm produces incorrect output for DiGraph

### ISSUE THREAD

**Issue by mikk-c** [networkx/networkx#1959]
As per title, calling `nx.k_core(G, k = x)` does not return the x-core of a graph, if `G` is a `DiGraph`.

See attached file.

[6954_2011.txt](https://github.com/networkx/networkx/files/105086/6954_2011.txt)

To reproduce, run:

```python
import networkx as nx

G = nx.DiGraph()
with open("6954_2011.txt", 'r') as f:
   for line in f:
      fields = line.strip().split('\t')
      G.add_edge(fields[0], fields[1])

core = nx.k_core(G, k = 12)
core.number_of_nodes() # Outputs "24"; expected output: "12"
```

There are only 12 nodes with (in+out) degree 12 once you remove recursively all those which don't qualify. These are:

IND
AUT
CHE
BEL
USA
ESP
CHN
FRA
NLD
GBR
ITA
DEU

While
```python
core.nodes()
```
says `['BEL', 'SWE', 'DEU', 'GBR', 'KOR', 'USA', 'SGP', 'MYS', 'POL', 'NLD', 'HKG', 'FRA', 'CHE', 'ESP', 'CHN', 'AUT', 'THA', 'JPN', 'TUR', 'ITA', 'IND', 'RUS', 'NOR', 'CZE']`

The method seems to work ok for `nx.Graph`, or at least I've yet to find a counter-example.

**Comment by dschult** [comment]
How can a subgraph of 12 nodes have the node degree in that subgraph be >=12? The largest degree they can have in the subgraph is 11.  Please look at the referred paper for the definition of k-core. 

I'm not saying that there is not a bug -- there might be.  But you haven't demonstrated a bug.

**Comment by mikk-c** [comment]
It is a directed graph, as per issue title. From the Networkx documentation of the method:

```
For directed graphs the node degree is defined to be the in-degree + out-degree.
```

Therefore, in a 12 node subgraph the largest "degree" can be 22 (11 outgoing edges + 11 ingoing edges). So there can be 12 nodes in a 12-core, in fact there can be even as little as 7.

**Comment by dschult** [comment]
Yes, you are correct about the degree... I was mistaken.
Still, the returned 12-core is bigger than your proposed subgraph (24 nodes vs 12 nodes). Is the returned subgraph not a 12-core? 

The definition of core number seems to be, for each node, the largest k for which that node is in a k-core. Then to form the returned subgraph, we take all nodes with e.g. core number >= 12. The paper claims that the k-cores nest inside each other as k increases. So this way of choosing nodes seems to make sense from that perspective. What I don't understand is that in your example the returned 12-core subgraph has nodes with degree 11 (within that subgraph). For example, 'NOR' has core number 12, but has degree 11 in the returned subgraph. I'm not an expert in k-cores and it has been years since I even looked at this part of the code. Do you have any perspective on how core numbers relate to the degree of the nodes in the k-core subgraph?

**Comment by mikk-c** [comment]
As far as I know, the textbook definition of k-core is:

```
A k-core is a maximal subgraph that contains nodes of degree k or more.
```

This means that NOR cannot be part of the 12-core, because in that subgraph it has to have degree of at least 12. If NOR gets assigned a core number of 12, either the function assigning it is wrong, or the core number is not the correct way to determine if the node is in the k-core.

My suspicious is that the former is true. In particular, the error seems to be in the last line of the nested for loop:

```python
core[u]-=1
```

Since it's a directed graph, if we are removing a node with both in- and out- link, this line should remove 2, not 1. This is exactly what happens when we remove DNK from the set: it has a reciprocal link with NOR, but removes only one from NOR's core number.

Here's a printout of the `core_number` function when `u` is NOR, for every pair of nodes I print one line at the beginning of the block and at the end, for each line the current core number of the node:

```
NOR ISL 19 1
NOR ISL 18 1

NOR CMR 18 3
NOR CMR 17 3

NOR AGO 17 4
NOR AGO 16 4

NOR DNK 16 10
NOR DNK 15 10 # Should be 14!

NOR IDN 15 11
NOR IDN 14 11

NOR FIN 14 11
NOR FIN 13 11

NOR CAN 13 11
NOR CAN 12 11
```

So the proposed fix would be an `if` before that instruction, checking if the nodes have a reciprocal connection, or always subtracting G.number_of_edges(u, v), or something like that.

**Comment by dschult** [comment]
Your investigation seems correct to me. It makes sense.

Also, the paper only provides the algorithm for undirected graphs with a paragraph describing how to change it to work for directed graphs. The paragraph does not mention changing the decrement size depending on number of edges between (u,v), and the algorithm details only state: ```dec(deg[u])``` So I see nothing in the paper to contradict what you are saying -- and it is the treatment that makes sense.

Clearly directed graphs are a poor sibling in this implementation of the algorithm (and in the original paper). My initial response was also indicative of neglect of directed situations. :{ Thank you for being persistent and for your detailed investigation!

If you would like to submit a pull request that would be great -- if you prefer that I do the coding I will take it on. I will try to create a test on a small graph as well that shows this issue.

**Comment by hagberg** [comment]
I took a quick look at that paper again. I can't see for sure without some closer reading - but double check the `inc(bin[du])` there too.

**Comment by mikk-c** [comment]
I prefer not doing the pull request myself. I'm not 101% confident that my treatment won't introduce other bugs and I don't know the networkx code too well to predict unexpected behaviors, so I prefer leaving it to you guys.

**Comment by dschult** [comment]
OK... Thank you @mikk-c I'll take a look at it, try to come up with a test too and send a shout out to you when its ready.

@hagberg I agree that both the ```inc(bin[du])``` and ```dec(deg[u])``` are suspect (perhaps all the ```inc``` and ```dec```).  The paper explains that those two terms act to shift the node u to the next lower bin. But if the degree is reduced by 2 maybe it should shift by 2 bins. What if it leapfrogs the current vertex.  I wonder if the author worked through the directed ```deg = in+out``` case carefully.

**Comment by hagberg** [comment]
It could be the right thing to do is to consider the undirected version of the graph unless you want to do something like http://www.graphdegeneracy.org/dcores_ICDM_2011.pdf

**Comment by dschult** [comment]
I'll look some more... we could make k_core ```NotImplemented``` for directed with docs for both making it undirected and pointing to d_core.

**Comment by dschult** [comment]
OK... here's a summary of what I found. The [referenced 2003 paper](http://arxiv.org/pdf/cs/0310049v1.pdf) has a [precursor 2002 paper](http://arxiv.org/pdf/cs/0202039.pdf) both by Vladimir Batagelj and Matjaˇz Zaverˇsnik. There they give a more general theoretical discussion which shows that this algorithm should work with any monotonic measure of centrality--not just degree. This includes in+out degree as we are pursuing for directed graphs (and is explicitly discussed there). So we should not rule out directed graphs for k_core--though we may want to implement D-cores too.

Furthermore, digging through the code and algorithm some more I see that we form a neighbor ```set``` rather than a neighbor ```list```. That removes duplicates -- which is precisely what occurs if you use a DiGraph and have edges in both directions. By handling such a neighbor twice, we decrement ```degree``` and increment ```bin``` correctly.  I have tested this change on the @mikk-c example graph and it corrects that example. If anyone wants to try it, change ```set``` to ```list``` on line 84 of core.py.

I will update the code, docs and tests.  Thank you to @mikk-c !! Longstanding Bug Finder.  :)
