### ISSUE TITLE
New Feature: SPFA algorithm ?

### ISSUE THREAD

**Issue by MichaelBroughton** [networkx/networkx#1964]
Although not so well documented, it might be cool to have as an option for one of the shortest path algorithms available to use. I would love to add it , if there is any interest.

https://en.wikipedia.org/wiki/Shortest_Path_Faster_Algorithm

**Comment by dschult** [comment]
I think the best way to do that is to create a separate function (perhaps starting by copying bellman_ford) rather than providing an option on an existing function. Then we can see how it works, compare them and decide if its better to combine the functions.

I don't work with negative edge weights much so I don't know about interest--but you sounds interested enough. :) Go for it. :)

**Comment by MichaelBroughton** [comment]
After reading into the bellman_ford code more closely, it appears that networkx already uses the queue based version of the algorithm (which is basically SPFA) so I guess in a way this feature is already in networkx. It is probabley also worth noting that I did test out the optimizations to SPFA from the wikipedia article without much performance boost.
