### ISSUE TITLE
Doc_string Standards for arguments

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#1971]
Currently the conf.py file for sphinx makes back-ticks use the ```:math:``` role.  That doesn't follow the numpydoc standard which uses ```:obj:``` to create a link to documentation for the listed python object. If not found, then emphasis is used instead.  With the standard, you might write ```create_using``` and you'd obtain a subscript u on the e of create.  See #1423 

I'm not sure how to find all the places where single-backticks need to use math mode.  Changing conf.py is easy, but then we have to find the places that need math mode and add ```:math:```.  Similarly we should find the places where double-backticks have been used for function arguments and use single-backticks instead.

What do people think?  Should we make a change to match numpydoc and gets easy links? 
Or keep the easy in-line math mode but lose the easy links and emphasis?

**Comment by jfinkels** [comment]
I think at the very least there should be a documented standard for how to format function arguments. I prefer to follow the Python documentation's lead, which uses emphasis for function arguments. Since I think references to function arguments occur much more frequently than math mode, I prefer changing to have explicit math mode roles (i.e. require the use of `:math:` before LaTeX). It's a pain to change though...

**Comment by hagberg** [comment]
I prefer explicit math mode as @jfinkels suggests.  It'll require some work to update.
