### ISSUE TITLE
documentation for ancestors() on DAGs is misleading

### ISSUE THREAD

**Issue by dorkaerdos** [networkx/networkx#1993]
Hi,

I am working with a directed acyclic graph and want to find all nodes that are on any path between the source of the graph and the given node. The DiGraph.ancestors() function only outputs nodes that are on a shortest paths between the source and the node. However, this only becomes clear by looking at the source code, it is not said in the documentation. It would be nice if you could add this to the documentation. Same holds for the predecessors() function.

Thank you!

Best,
Dora

**Comment by dschult** [comment]
Perhaps I'm confused. On a directed acyclic graph, I thought ancestors based on shortest path would be the same as ancestors on any path.  If there is a path then there is a shortest path, right? I don't think the fact that we look at shortest paths matters.

**Comment by dorkaerdos** [comment]
I want to output all node ids that are on ANY directed path between the
root and my node. In a DAG there could be multiple paths from the source to
the node with different length, not just the shortest path. Remember, a DAG
is not necessary a tree.

Anyway, I'm just going to implement the function that I need for myself,
I just wanted to make you aware that maybe adding more information to the
documentation would make it more clear for some people (me).

Thanks for your time!


Here is an example for what I mean:
I will index my graph nodes by numbers. Let 1 be the root. Let us assume
directed edges are (1,2), (2,3), (3,4), (1,5),(5,4). In this case I would
like to have DiGraph.all_ancestors(4) = [1,2,3,5]

**Comment by dschult** [comment]
But that IS what nx.ancestors(G, 4) gives for your example graph.

In [*1*]: import networkx as nx

In [*2*]: G=nx.DiGraph()

In [*3*]: G.add_edges_from([(1,2), (2,3), (3,4), (1,5),(5,4)])

In [*4*]: nx.ancestors(G, 4)

Out[*4*]: {1, 2, 3, 5}

It doesn't matter whether the path is a shortest_path or another path.  If
there is ANY path from a node to 4, then that node will show up as an
ancestor.  We get away with using shortest_paths because if there is any
path, then there must be a shortest_path. So by looking at shortest_paths
we get the same nodes as using any path.  Your original understanding of
the function is correct. You don't need to write a new function.
Dan
