### ISSUE TITLE
subgraph isomorphism error

### ISSUE THREAD

**Issue by stsouko** [networkx/networkx#1995]
then I try matching disconnected (on nodes 2,3) graph **g** and **h** where nodes 2,3 connected, GraphMatcher don't found subgraph.
but for **c**, where nodes 2,3 not connected between themselves its work.

from networkx.algorithms import isomorphism as gis

`g=nx.Graph()`
`h=nx.Graph()`
`c=nx.Graph()`

`g.add_edges_from([(1,2,{1:1}), (3,4,{1:3})])`
`h.add_edges_from([(1,2,{1:1}), (2,3, {1:2}), (3,4,{1:3})])`
`c.add_edges_from([(1,2,{1:1}), (2,5, {1:2}), (5,3,{1:2}), (3,4,{1:3})])`

`gis.GraphMatcher(c,g, edge_match=gis.categorical_edge_match([1], [None])).subgraph_is_isomorphic()`
return True

`gis.GraphMatcher(h,g, edge_match=gis.categorical_edge_match([1], [None])).subgraph_is_isomorphic()`
return False

**Comment by chebee7i** [comment]
I believe that this is giving the correct answer.  The subgraphs that are constructed are node-induced subgraphs. So when you test if a subgraph of c is isomorphic to g, then note that the node-induced subgraph on nodes (1,2,3,4) is isomorphic to g.  On the other hand, there is no node-induced subgraph of h that is isomorphic to g since the edge (2,3) will always be present.

This is the distinction between a monomorphism and an isomorphism. See also #948 and http://stackoverflow.com/questions/459799/whats-the-difference-between-subgraph-isomorphism-and-subgraph-monomorphism

**Comment by chebee7i** [comment]
Going to close this now.
