### ISSUE TITLE
nx_pylab.draw_graphviz is not possible to use

### ISSUE THREAD

**Issue by TaskeHAMANO** [networkx/networkx#2023]
I tried to execute program below on Network X 1.11.

```lang:python
import networkx as nx
import pylab as pl
from itertools import product

dag = nx.DiGraph()
h1 = ["0"]
h2 = ["1", "2", "3"]
h3 = ["1.1", "1.2"]
h4 = ["2.1"]
h5 = ["2.1", "3.1", "3.2", "3.3", "3.2.2"]
h6 = ["3.2.1", "3.2.2"]
dag.add_nodes_from(h1+h2+h3+h4+h5+h6)
dag.add_weighted_edges_from(list(product(h2, h1,[1])) + 
                   list(product(h3,["1"],[1])) + 
                   list(product(h4,["2"],[1])) + 
                   list(product(h5,["3"],[1])) +
                   list(product(h6,["3.2"],[1]))
                  )
nx.drawing.nx_pylab.draw_graphviz(dag)
```

Finally I got error like below .

```text:error.log
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-788560fba59b> in <module>()
     17                    list(product(h6,["3.2"],[1]))
     18                   )
---> 19 nx.drawing.nx_pylab.draw_graphviz(dag)

/usr/local/var/pyenv/versions/anaconda3-2.4.0/lib/python3.5/site-packages/networkx/drawing/nx_pylab.py in draw_graphviz(G, prog, **kwargs)
    982        See networkx.draw_networkx() for a description of optional keywords.
    983     """
--> 984     pos = nx.drawing.graphviz_layout(G, prog)
    985     draw(G, pos, **kwargs)
    986 

AttributeError: module 'networkx.drawing' has no attribute 'graphviz_layout'
```

This error may occured by #1931 .

**Comment by 4c656554** [comment]
I think you want:

`nx.nx_agraph.graphviz_layout(...`)

This is a change (I'm not sure in what version).

**Comment by dschult** [comment]
Issues #1997 correctly points out this bug also.

The short term solution is to not use ```nx.pylab.drawing_graphviz```.  That function created confusion because you could be using pygraphviz or pydotplus to access the graphviz libraries and this function doesn't tell you which and its fairly tricky to find out which because it depended on import order.

All the function did was get the layout positions and then call ```nx.draw```.  So the fix is to replace your last line with two lines.  

If you use pygraphviz:

    pos = nx.drawing.nx_agraph.graphviz_layout(G)
    nx.draw(G, pos=pos)

If you use pydotplus: 

    pos = nx.drawing.nx_pydot.graphviz_layout(G)
    nx.draw(G, pos=pos)

More details can be found on the [layout docs](http://networkx.readthedocs.org/en/stable/reference/drawing.html)

**Comment by TaskeHAMANO** [comment]
Oh! sorry!!
I missed previous issue.
I understand what to do. Thanks.
