### ISSUE TITLE
Load graph from pandas dataframe as adjacency matrix

### ISSUE THREAD

**Issue by hlin117** [networkx/networkx#2029]
As of now, [nx.from_pandas_dataframe](http://networkx.readthedocs.org/en/stable/reference/generated/networkx.convert_matrix.from_pandas_dataframe.html) assumes that the data is oriented in some sort of table kind of form. However, it would also be advantageous to accept pandas dataframes oriented as some sort of adjacency matrix, such as [this stackoverflow post](http://stackoverflow.com/a/21210849/2014591).

At the current moment, [from_numpy_matrix](http://networkx.github.io/documentation/networkx-1.7/reference/generated/networkx.convert.from_numpy_matrix.html) is the way to construct a graph using an adjacency matrix. However, the matrix doesn't have the nodes labeled, and the current way to label the nodes is the method described in the above stackoverflow post.

How does a function like `from_pandas_adjacency_matrix` sound?

**Comment by hagberg** [comment]
Maybe it would be better to generalize `from_numpy_matrix` to `from_adjacency_matrix` and allow either a numpy matrix or a square pandas dataframe?  The reasoning is that it would be almost the same code so this way we won't be repeating ourselves in a new function.

The current from_pandas_dataframe is essentially an edgelist with optional edge attributes so that function, while useful, isn't quite correctly named either.  Note that the [stackoverflow post](http://stackoverflow.com/a/21210849/2014591) you mention fstarts with a "biadjacency matrix" which is yet another graph data structure used for bipartite graphs.  There is a pair of functions for biadjacency data too https://networkx.github.io/documentation/latest/reference/algorithms.bipartite.html#module-networkx.algorithms.bipartite.matrix

**Comment by hlin117** [comment]
> Maybe it would be better to generalize from_numpy_matrix to from_adjacency_matrix and allow either a numpy matrix or a square pandas dataframe? The reasoning is that it would be almost the same code so this way we won't be repeating ourselves in a new function.

I like that idea; that would make the API interface much cleaner.

The current script I have to perform this conversion is as follows. Do you think there's a faster way to implement this, @hagberg?

```
import numpy as np
# Assume that we have a dataframe df which is an adjacency matrix

def find_edges(df):
    """Finds the edges in the square adjacency matrix, using
    vectorized operations. Returns a list of pairs of tuples
    that represent the edges."""
    values = df.values
    n_rows, n_columns = values.shape
    indices = np.arange(n_rows*n_columns)
    values = values.flatten()
    _indices = indices[values == 1]  # A value of 1 means that the edge exists
    
    # Create two arrays `rows` and `columns` such that for an edge i,
    # (rows[i], columns[i]) is its coordinate in the df
    rows = _indices / n_columns  
    columns = _indices % n_columns
    
    # Convert the coordinates to actual names
    row_names = df.index[rows]
    column_names = df.columns[columns]
    return zip(row_names, column_names)    # Possible that itertools.izip is faster
    
G = nx.DiGraph()
G.add_nodes_from(df.index.tolist())

edges = find_edges(df)
G.add_edges_from(edges)  # Speed is questionable, not sure if this is vectorized
```

**Comment by hlin117** [comment]
More testing has to be done to check whether the above script works for sparse data frames.

**Comment by dschult** [comment]
Is this Issue completed already by PR #2558 ?
Or am I missing something in this suggestion that isn't in the current ```from_pandas_adjacency```?
