### ISSUE TITLE
Generate a random planar graph

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2034]
It would be cool to be able to generate a random planar graph. An implementer might start from the StackOverflow question "[Generate a large random planar graph](http://stackoverflow.com/q/3232048)". For example, one of the answers there references a Java implementation at the [homepage of Eric Fusy](http://www.lix.polytechnique.fr/~fusy/) (search for "Uniform random sampling of planar graphs in linear time"). 

This complements issues #1602 and #1603.

**Comment by hagberg** [comment]
For some tests of algorithms see http://i11www.iti.uni-karlsruhe.de/extra/publications/TR-mw-aesgp-11.pdf

**Comment by jfinkels** [comment]
Interesting. So whatever planar graph generator is proposed is likely to have some deficiencies?

**Comment by hagberg** [comment]
It looks like some variant of "Faster, better, cheaper - pick two".   Some of the algorithms might be pretty complicated to implement.

**Comment by lucyking** [comment]
I've wrote a simple python script that can generate 2D random map 
[script](https://github.com/lucyking/Vector-Map)

**Comment by benelot** [comment]
@hagberg Would something like this be a valid contribution towards this issue:
https://github.com/briandconnelly/seeds/blob/master/seeds/plugins/topology/CartesianTopology.py
?
I just tested it and it generates graphs that look very much like the graphs we all know from the centrality wikipedia article:
https://upload.wikimedia.org/wikipedia/commons/1/11/6_centrality_measures.png (original graph by Claudio Rocchini)

**Comment by benelot** [comment]
I could certainly turn the code into a generator, given it is very close to one and also provide some example for it plotting different centralities for the generated graph.

**Comment by dschult** [comment]
That code is very close to the NetworkX function [random_geometric_graph](https://networkx.org/documentation/stable/reference/generated/networkx.generators.geometric.random_geometric_graph.html) though it does choose the radius where edges are formed in a way to make the expected number of edges be a controlled value. Our function allows you to select the radius instead, but they can be mapped from one to the other.

This Issue is not about creating random geometric graphs. It is about creating "planar graphs", which are defined as graphs for which the nodes can be placed in the plane so that no edges cross other edges.

Thanks for the offer of a new function. But I think we already have that functionality. If I'm missing something please open a new issue.

**Comment by benelot** [comment]
You are right. I was planning to propose a functionality that generates planar graphs, but reviewing my own graphs that it generates they are not planar. Sorry for generating noise.
