### ISSUE TITLE
cycle_basis() and copy() inconsistency 

### ISSUE THREAD

**Issue by samholmes0** [networkx/networkx#2144]
I'm running the following code on graphs:

```
def compute_betti(G):
    #Compute cycle basis
    cb = nx.cycle_basis(G)

    #Compute Betti number of graph
    betti = 0
    for cycle in cb:
        if len(cycle)>3:
            betti += 1

    #Return (betti number, graph size, cyclomatic number)
    return betti, len(G.nodes()), len(cb)
```

When I run:

```
G = nx.read_adjlist(some_file) #original graph
 H = G.copy() #deep copy
J = nx.Graph(G) #shallow copy
 compute_betti(G)
 compute_betti(H)
 compute_betti(J)
```
the result of compute_betti differs between G and both copies. Now, literally all that compute_betti is doing, as you can see, is counting the amount of basis cycles that are greater than length 3 -  this certainly shouldn't differ between 'identical graphs'. So this leads me to believe there is some sort of issue with the way copy() affects the result of cycle_basis(). 

EDIT: I'm doubting whether the sentence 'this certainly shouldn't differ between 'identical graphs'.' is true. That being said, I think the answer here is still worth clarifying - also, having identical cycle bases for graphs generated using .copy() would be useful.

**Comment by hagberg** [comment]
When I run this version of your code it produces the same result for G,H,J.  Could you try that?

```python
import networkx as nx

def compute_betti(G):
    #Compute cycle basis
    cb = nx.cycle_basis(G)

    #Compute Betti number of graph
    betti = 0
    for cycle in cb:
        if len(cycle)>3:
            betti += 1

    #Return (betti number, graph size, cyclomatic number)
    return betti, len(list(G.nodes())), len(cb)


#G = nx.read_adjlist(some_file) #original graph
G = nx.gnp_random_graph(100,0.4)
H = G.copy() #deep copy
J = nx.Graph(G) #shallow copy
print(compute_betti(G))
print(compute_betti(H))
print(compute_betti(J))
```

**Comment by samholmes0** [comment]
Yes - that produces the same result in all three cases. 

In that case, I'm at a bit of a loss.
[adj.txt](https://github.com/networkx/networkx/files/283187/adj.txt) is the file I'm trying to run the script on, turning it into a graph by using
 `G = nx.read_adjlist(~/adj.txt)`

I am getting the following as results:
```
G -> (1023, 283, 2125)
H -> (1111, 283, 2125)
J -> (1142, 283, 2125)
```
when running the same script., 

Let me know if you can reproduce these.

**Comment by dschult** [comment]
The cycle basis of a graph is not unique. Just as a basis for a euclidean space is not unique.  One can "add" two cycles and "subtract" them and use the results to replace the two original cycles and you'll still have a cycle basis. So any computation that relies on the number of cycle **basis** entries longer than 3 is suspect.  I suspect your betti number algorithm needs to be looking at something other than a cycle basis.

Presumably the cycle basis returned by nx.cycle_basis depends on the order of nodes and edges as produced by the dict data structure. The order of reporting from dicts is not consistent in Python by design.  If order matters to you you can try OrderedGraph, but special care is needed even there for any algorithms which store intermediate results in dicts. 

In your case though, I think you need to focus on your algorithm for finding the betti number. It can't be correct that looking at lengths in a single choice of cycle basis is enough to compute the betti number.

**Comment by samholmes0** [comment]
I just tried OrderedGraph and it work - thanks! As for the algorithm, I'll need to learn more about the Betti number to verify what you're saying. This code is isomorphic to what my non-mathematician/computer scientist research advisor gave to me - I'm not sure if it's correct. That being said, even if we call whatever it is we're computing something else, an inconsistency with graphs produced by .copy() is still a pain - but OrderedGraph fixes this via OrderedDict. Thanks for all the help.

**Comment by hagberg** [comment]
Be careful here.  You'll likely get different results if you e.g. reorder your input file.   So I don't think OrderedGraph fixes this for you.   The cycle basis output is often misunderstood. @dshult probably has a standard form for answering questions about it.    It is not computing all cycles of a certain length.
