### ISSUE TITLE
nan values in minimum_spanning_tree

### ISSUE THREAD

**Issue by mwshinn** [networkx/networkx#2164]
When calculating the minimum_spanning_tree, the algorithm does not correct for (or at least warn about) edges with nan weight.  This can give very strange results, such as a few nodes with very high degree, 'or introduce more subtle bugs.

Simple MWE:

``` python
import networkx, math, random
import matplotlib.pyplot as plt
G = networkx.complete_graph(100)
for n1, n2 in G.edges_iter():
    G.edge[n1][n2]['weight'] = random.random()

# Pre-nan
f, [ax1, ax2] = plt.subplots(2, 1)
ax1.imshow(networkx.to_numpy_matrix(networkx.minimum_spanning_tree(G))!=0)
# Post-nan
G.add_edge(1, 50, {'weight' : float('nan')})
ax2.imshow(networkx.to_numpy_matrix(networkx.minimum_spanning_tree(G))!=0)
plt.show()
```

**Comment by chebee7i** [comment]
I updated your MWE to show the plots side-by-side.  The presence of nans definitely affects Kruskal's algorithm (which is what is used by `minimum_spanning_tree`) since it tries to sort all the weights. Of course, nan's are not sortable and so the resultant "sorted" list is not sorted in general.

We could remove the nans from consideration, but that also might cause bugs in people's code who didn't expect them in the first place.  If we opt to filter them out, I think we should consider adding an option to raise an exception on the detection of a nan weight.

**Comment by hagberg** [comment]
We could special case the sort function (which will slow things down) or filter or raise an exception as @chebee7i suggests.  In general I don't like a lot of input checking in the algorithms.  What about filtering them out since those edges can't participate in any spanning tree?

**Comment by mwshinn** [comment]
Filtering them out seems like it would be a good solution if we don't want to check for valid input.  I agree that input shouldn't be checked too stringently, since it could make the code messy pretty quickly and it goes against the spirit of duck typing.  But I also see the other side, that many users of NetworkX do scientific work and passing the nan (which isn't in the domain and is thus by definition a bug in their code) through silently will be a very difficult bug to catch.  However I think either of the proposed fixes would be a good solution.
