### ISSUE TITLE
I add edges first, then I get the edges,but the the order of edge's node changed

### ISSUE THREAD

**Issue by zhengdou** [networkx/networkx#2182]
##code is here:
```
g = nx.Graph()
g.add_edge('b', 'c')
print g.edges()
# result is [('c', 'b')]
```
----------------------
what I want is [('b', 'c')].
enter others like ('a','b'),it show as [('a','b')],  **just('b','c') have this problem**
please tell me this is for what.
thanks

**Comment by dschult** [comment]
This might be better sent to the email list discussion group
<https://groups.google.com/forum/#!forum/networkx-discuss>

Briefly, if order of the nodes matters, you might want to use DiGraph
instead of Graph.  Or if you really need a graph (edges are bidirectional),
you can try the OrderedGraph class.
Dan

**Comment by CrazyPython** [comment]
This issue tracker is for bugs and improvements - not help.  As @dschult said, you can message the google group or alternatively go to stackoverflow.com. You can use the tag networkx.
