### ISSUE TITLE
PEP 484 type hints

### ISSUE THREAD

**Issue by CrazyPython** [networkx/networkx#2183]
PEP 484 type hints would be useful. If I sent a PR, would you accept it?

**Comment by jfinkels** [comment]
Can you clarify in what sense you would consider these "useful"? The *[Rationale and Goals][1]* section of PEP484 states

> This PEP aims to provide a standard syntax for type annotations, opening up Python code to easier static analysis and refactoring, potential runtime type checking, and (perhaps, in some contexts) code generation utilizing type information. 
>
> Of these goals, static analysis is the most important. This includes support for off-line type checkers such as mypy, as well as providing a standard notation that can be used by IDEs for code completion and refactoring.

[1]: https://www.python.org/dev/peps/pep-0484/#rationale-and-goals

**Comment by CrazyPython** [comment]
@jfinkels When I'm in my IDE, type hints provide me code insights/inspections/type inference/type checking. To implement:

```python
def foo(spamgument: TheArgumentType, bargument: TheOtherArgumentType) -> SomeReturnType
    pass
```

You can also do it for variables like this:
```
parrot = None  # type: Parrot or None
```

Note that this is official Python syntax.

For example, if in my IDE if I tried to add the result of `n_nodes` to a string, it would highlight the error. Right now I have to manually add the types.

**Comment by CrazyPython** [comment]
@jfinkels  any updates?

**Comment by hagberg** [comment]
I'm not very enthusiastic about adding PEP 484 style type annotations.  Perhaps when we drop Python 2 support and the tools for type checking or code generation are more mature it would be worth a discussion.

**Comment by CrazyPython** [comment]
@hagberg  how about this: we add separate `.pyi` files so we can have the best of both worlds

**Comment by hagberg** [comment]
I'd still vote no until type annotations more mature and they provides some wider value.  But if there are lots of other developers that want this I am willing to support putting some .pyi files in a stubs directory or maybe they should go here https://github.com/python/typeshed/tree/master/third_party

**Comment by CrazyPython** [comment]
@hagberg you don't understand the inconvenience of not having type hints - it leads to hard-to-debug bugs and extra manual work. They aren't a preliminary feature and it isn't going to be changed in a non-backwards compatible fashion. I annotate my functions not for the same reasons I add tests to my files - I annotate because it gives me benefits in the *short-term* (i.e. this commit, this session, this day).

**Comment by hagberg** [comment]
I'm not keeping you from having type hints.  I'm suggesting that they be separate from the networkx code in a special directory or at the typeshed project.  This project isn't ready to drop Python3 support yet so I'd like to postpone the discussion of inline type annotations until we get there.

**Comment by CrazyPython** [comment]
@hagberg do you consent to having type hints so for the record developers can add it to typeshed?

**Comment by hagberg** [comment]
I think that is what I suggested you do.

**Comment by CrazyPython** [comment]
Just making sure - you know people sue each other for everything nowadays!

**Comment by fmagin** [comment]
I am currently working on an (internal) codebase that strongly benefits from static typing which requires that at least the externally used interfaces for networkx(which we use a lot) are annotated. 
This already proved fairly useful for development because it allows PyCharm to infer the types in expressions like `[ n for node in graph]`, immediately warns in cases of `graph.add_edge("foo", "bar")` when `graph` is a graph over integers, etc.

In my opinion the goal should not be that networkx is internally statically typed but that at least the common interfaces are annotated, so that IDEs and mypy can use it for projects that use networkx and type annotations.

I did not find any other public effort to create a -stub package for networkx which is the only option of neither inline annotations nor separate .`pyi` files in the networkx package are started working on my own at https://github.com/fmagin/networkx-stubs . This is still heavily WIP and only covers external interfaces we use (and I have annotated so far). Furthermore I won't even guarantee that some annotations aren't outright wrong for some use cases other than mine, the networkx code style does not easily allow typing. Some of them are annotated, others I might have missed.

I hope this will serve as an example that this is in fact useful and saves others the work I already did.
This _should_ also work for Python2, but I haven't tested this so far.

I would suggest to add this package to the networkx project at some point, mark it as WIP/experimental and encourage PRs from anyone with real world projects. I'd rather not have it published on PyPI or Typeshed until it I have gotten feedback from others using it. This allows anyone requiring this to still easily find it, installing as a Python package is still simple (and is enough to be picked up by mypy and PyCharm), but does not raise expectations that networkx is fully typed.

**Comment by jinwuxia** [comment]
Hi, 
Does the Networkx  group consider adding type annotations to source code?  Prefer to use inline type or separate stub files (*pyi )?

**Comment by stefanv** [comment]
@jinwuxia Most of this discussion is now taking place on https://github.com/networkx/networkx/pull/4014

**Comment by fmagin** [comment]
I'd argue that this issue is the more appropriate place for discussion and should be reopened so any further discussion happens here. Searching for "PEP 484" in the issues is the way that I'd expect most people interested in type annotation will use to find the relevant issue/discussion. Or we could open a new dedicated issue referencing the previous discussion and detailing the next actions that are needed.

The discussion in the PR #4014 concluded, if I understand your last comment correctly @stefanv , that inline annotations are the way to go forward, but the CI setup for basic type checking would probably be required before such PRs will be merged.

So my question is:
Do we want a dedicated issue now that PEP 484 type annotations are a tractable issue that PRs are welcome for or do we want to reuse this issue? If you find a new issue reasonable I'll reread the discussion in the PR and the issue and summarize it so it is easier for new contributors to understand the general approach and goals.

**Comment by stefanv** [comment]
CI configuration using pre-commit:

```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.782'
    hooks:
    -   id: mypy
```

**Comment by stefanv** [comment]
Linking in another issue: https://github.com/networkx/networkx/issues/3988
