### ISSUE TITLE
write_graphml doesn't properly escape characters for XML

### ISSUE THREAD

**Issue by michalsta** [networkx/networkx#2193]
```
>>> import networkx
>>> G = networkx.Graph()
>>> G.add_node("\\1")
>>> import StringIO
>>> s = StringIO.StringIO()
>>> networkx.write_graphml(G, s)
>>> s.getvalue()
'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">\n  <graph edgedefault="undirected">\n    <node id="\x01" />\n  </graph>\n</graphml>\n'
```

The expected output would instead contain  `<node id="\1" />`. The actual output isn't even valid XML:

```
>>> from xml.etree import ElementTree as ET
>>> ET.fromstring(s.getvalue())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 4, column 14

```

Verified on both 1.11 and git master.

**Comment by hagberg** [comment]
Hmm, that's ugly.  I don't know how to fix that properly.  @chebee7i do you have any idea?

**Comment by jfinkels** [comment]
(Note the reported issue is for Python 2.7; might be worth checking on Python 3.)

**Comment by hagberg** [comment]
It's also broken on Python3 or I would have already suggested to just use Python3 😄

**Comment by chebee7i** [comment]
This one is a bit tricky.  In the implementation, we are using etree and it handles all the unicode/bytes stuff for you. The important point to note is that when we call `tostring()`, it returns utf-8 encoded bytes. This means that on Python 3, you cannot use StringIO and must use BytesIO. When you do that, it works:

```
In [1]: import networkx as nx

In [2]: import io

In [3]: G = nx.Graph()

In [4]: G.add_node('\\1')

In [5]: s = io.BytesIO()

In [6]: nx.write_graphml(G, s)

In [7]: print(s.getvalue())
b'<?xml version =\'1.0\' encoding=\'utf-8\'?>\n<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">\n <graph edgedefault="undirected">\n    <node id="\\1" />\n  </graph>\n</graphml>\n'

In [8]: print(s.getvalue().decode(utf-8'))
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <graph edgedefault="undirected">
    <node id="\1" />
  </graph>
</graphml>
```

As for Python 2.x, this is a bit of a wart in dealing with all the unicode/bytes differences and trying to keep a single codebase with 3.x.  The culprit is that we use `networkx.utils.make_str` whose goal is to take a string (bytes in 2.x, unicode in 3.x) and return unicode.  For 2.x, we use `unicode(text, 'unicode-escape')`. This allows people to have escaped unicode in their byte strings. For example:

```
# Python 2.x
>>> s = 'Sk\xf6ld'  # unicode-escaped bytes
>>> print unicode(s, 'unicode-escape')
Sköld
>>> unicode(s, 'utf8') # fails
>>> print repr(unicode(s, 'unicode-escape').encode('utf8')) # utf-8 bytes
'Sk\xc3\xb6ld'
```

So here we made a decision that strings in Python 2.x were actually unicode, rather than utf-8.  In your case, when 'unicode-escape' encounters the `'\\1'`, it has trouble doing the conversion and returns the empty string.  The quick way around this is to pass in the node as unicode: `G.add_node(u'\\1')`. Then you'll get the behavior you want.

Or use Python 3. 
Or we can rethink whether we want to assume bytes in Python 2.x are unicode-escaped bytes.
