### ISSUE TITLE
dfs_labeled_edges returns self-loops for sources

### ISSUE THREAD

**Issue by ProgVal** [networkx/networkx#2212]
As shown here: https://github.com/networkx/networkx/blob/d67f13025fc438149874fee70879a2d5ab22d0ec/networkx/algorithms/traversal/tests/test_dfs.py#L60-L68

Is this actually the expected behavior?

**Comment by dschult** [comment]
That looks like a bug to me. And it is not just for sources. 
With ```self.D``` in the second tests, it creates a spurious self-loop when it starts each connected component.

**Comment by hagberg** [comment]
I'm pretty sure that is intentional.  But I can't remember the reason just now.

**Comment by jfinkels** [comment]
I ran into this and I also believe it is intentional: the `(root, root, 'forward')` signals the start of the traversal and the `(root, root, 'reverse')` signals the end. This function came from the original code in PADS: https://www.ics.uci.edu/~eppstein/PADS/DFS.py, which I assume was done in this manner because it was helpful when implementing some of the other functions in PADS. I recommend leaving it as-is unless there is a good reason to change it. If you want to exclude the first element from the iterator, you can use, for example, `itertools.islice(dfs_labeled_edges(G), 1, None)`.
