### ISSUE TITLE
bug with LPA algorithm

### ISSUE THREAD

**Issue by SkyTodInfi** [networkx/networkx#2219]
https://github.com/networkx/networkx/blob/master/networkx/algorithms/community/asyn_lpa.py#L75
When `weight = None`, the label freq should sum over all possible labels, but `Counter` will set all freq to 1.
`label_freq = Counter([labels[v] for v in G[node]])`  will give right result when `weight = None`, is it a bug?

**Comment by jfinkels** [comment]
Yes, this appears to be a bug. The problem is that if two nodes have the same label (say node 0 and node 1 both have label 5), then the dictionary comprehension will only reflect one entry for the label (the key 5 will have value 1) so the Counter only counts that label once. Can you prepare a pull request that includes the proposed change to the code as well as a unit test in `networkx/algorithms/community/tests/test_asyn_lpa.py` that would fail with the current implementation but passes with the proposed change?
