### ISSUE TITLE
How to identify community from weighted networks?

### ISSUE THREAD

**Issue by xflicsu** [networkx/networkx#2226]
I want to use 'asyn_lpa_communities', 'girvan_newman' and 'k_clique_communities' to identify communities from weighted directianl networks.
I am a new begainer of python, how can I adopt these method?
Thanks

**Comment by leotrs** [comment]
Please post what you have tried and what went wrong so we can help better.

**Comment by xflicsu** [comment]
#####Node file
GeneName        NodeType
0610007P14Rik   4
0610009B22Rik   4
0610009O20Rik   4
0610010B08Rik   4
0610010F05Rik   4

###edge file
Source  Target  SourceNodeType  TargetNodeType  weight
Trrap   Rnf2    2       1       0.29142826628701
Trrap   Esrrb   2       0       0.0302370939235559
Trrap   Ep400   2       2       0.298713000304477
Trrap   Tfcp2l1 2       0       0.0565377375549192
Nfxl1   Nipal1  0       4       4.42971557451346
Zfp513  Mzf1    0       0       0.0215451682062103

###My script

net01 = networkx.Graph()
for i in table01.index:
       net01.add_node(table01["GeneName"][i], nodetype=int(table01["NodeType"][i]))
for i in table02.index:
       net01.add_edge(table02["Source"][i], table02["Target"][i],weight=table02["weight"][i])
community=asyn_lpa_communities(net01[, weight])

#####
####error report
 File "cirNet-test.py", line 53
    asyn_lpa_communities_test(net01[,'weight'])
                                    ^
SyntaxError: invalid syntax
#####

I want to identify community from that weighted networks. 

I also change 
community=asyn_lpa_communities(net01[, weight]) ------>
community=asyn_lpa_communities(net01)

It work without weight values

My question is how to use weight values, when I adopt "asyn_lpa_communities"?

Thanks

**Comment by leotrs** [comment]
> `community=asyn_lpa_communities(net01[, weight])`

This is invalid python syntax. I assume you have copied this code from some documentation. When you see square brackets with a comma in the first place, like in `(net01[, weight])`, it means the function can be called in two different ways. Either by specifying only the first parameter, or both. So, either do `community=asyn_lpa_communities(net01)`, which is what you are doing and it will not consider the weights because you are not passing any, or do `community=asyn_lpa_communities(net01, weight)`, without the square brackets.

Please refer to [this](https://networkx.readthedocs.io/en/latest/reference/generated/networkx.algorithms.community.asyn_lpa.asyn_lpa_communities.html) page which determines how to use the second parameter.

**Comment by jfinkels** [comment]
For help with using NetworkX, you'll probably find the discussion group more helpful: https://groups.google.com/forum/#!forum/networkx-discuss
