### ISSUE TITLE
Hashing inconsistencies(?) when using DiGraph

### ISSUE THREAD

**Issue by axt** [networkx/networkx#2282]
I found some strange behaviour of DiGraph. This is the simplest example I could come up with to demonstrate it.

If I create a class with custom hash function like this:

```
class X(object):
    def __init__(self, x, s):
        self.x = x
        self.s = s;
    def __hash__(self):
        return self.x
    def __eq__(self, x):
        return x.x == self.x
    def __str__(self):
        return "label=%s hash=%d" %(self.s, self.x)
```

and then build this simple graph:

```
    g = nx.DiGraph()
    g.add_node(X(1,"1a"))
    g.add_node(X(2,"2a"))
    g.add_edge(X(1,"1b"), X(2, "2b"))
    g.add_edge(X(1,"1c"), X(2, "2c"))
```

Edge iterations:

```
for s,t in g.edges():
    print '%s -> %s' % (s,t)
    for ss, tt in g.out_edges(s):
        print '\tout\t%s -> %s' % (ss,tt)
    for ss, tt in g.in_edges(t):
        print '\tin\t%s -> %s' % (ss,tt)
```

will produce this results:

```
label=1a hash=1 -> label=2b hash=2
    out label=1a hash=1 -> label=2b hash=2
    in  label=1b hash=1 -> label=2b hash=2
```

So the two `add_edge` produce only 1 edge, which I guess its the expected behavior, since the hashes are the same. What is strange, that the source node is `looked up` and changed to `1a` while the target node is not, and remains `2b`. Another oddity is when we do the `in_edges` iteration, which will return `1b` although in the `edges` and `out_edges` we see only `1a`.

**Comment by hagberg** [comment]
NetworkX is using Python dictionaries to store the node and edge information.   The expectation is that the objects used as nodes are hashable to make this possible.  You got that satisfied by providing a hash function.  But the way you set it up two objects that aren't the same can have the same hash.  It looks like that collision causes ambiguity in which objects get stored/replaced in the dictionaries.  I'm not sure if this is really a NetworkX bug.  

Is there a reason you can't use a better (unique) hash function?

**Comment by ProgVal** [comment]
>  But the way you set it up two objects that aren't the same can have the same hash

That's not the issue here. Because of this:

```
    def __hash__(self):
        return self.x
    def __eq__(self, x):
        return x.x == self.x
```

objects are equal if and only if they have the same hash.
And it is not an issue for two unequal objects to have the same hash (unless you care about performance).

The problem is that the definition of equality for these objects is twisted, because equals objects are displayed differently.
So we tell Python these two objects are equal, but we don't read their string representations as being equivalent

**Comment by hagberg** [comment]
Yes, @ProgVal put it more clearly than what I wrote (indeed there can be hash collisions).

**Comment by axt** [comment]
Actually the graph is totally correct if we check the objects by the equality relation. There is an edge from hash:1 to hash:2, basically I've added that edge twice. 

What was strange for me, that if I do an n' = inedge(outedge(n)) for the node (1a), then n' will be equal to n by the equality relation, but will be a different object than n (it will be 1b). Also when adding an edge ((1b,2b),(1c,2c)), the source nodes are "looked up" to the node that already exist in the graph (1a), while this doesn't hold for the destination nodes. (It will be 2b for the first edge, and 2b again for the second edge, although 2a exist in the graph already).

I don't want to store this kind of tricky objects in the graph, just debugged a pretty complex code for several hours, when I realized this is happening. 

I also don't think its a bug, as I said the graph is correct by the equality relation, but I thought that the in_edge and out_edge interations producing different objects can cause a lot of confusion. (For me it would be "less confusing" if the destination nodes would be also "looked up" to the node what already exist, but I'm not familiar with the internals of the library.)

I can live with this, just wanted to let you know about this behavior. Feel free to close the issue.

**Comment by axt** [comment]
Just another note on this, since the `networkx.write_dot` function uses the `__str__` representation of the nodes in the dotfile, the above behavior can lead to false plots (e.g: edges missing, duplicated nodes).

**Comment by hagberg** [comment]
Thanks for the update on this.  I think I see the situation now.  NetworkX assumes that objects compare equal are the same object.  There is some inconsistency when existing (compare equal) nodes and edges are added again to the graph data structure (i.e. the internal dictionary of dictionaries).  This is probably fixable with some performance loss by either deleting the existing objects and inserting the new ones or ignoring the new objects completely (but somehow we'd want to update the values of some of the existing dictionary keys).

I can't tell if this is a subtle and awful bug lurking in the depths or more of a "don't do that" advisory when designing custom objects to use with Python dictionaries.

The issue is the few lines in add_edge https://github.com/networkx/networkx/blob/master/networkx/classes/digraph.py#L557
(and likely other places where we modify the adj/pred/succ dictionary structure).

**Comment by ProgVal** [comment]
> with some performance loss

This will happen even when dealing with integers greater than 256, because two instanciations of the same (greater than 256) numbers give different objects (which obviously are equal):

```
>>> a = 257
>>> b = 257
>>> a is b
False
```

**Comment by hagberg** [comment]
Indeed - so a vote for not a bug and "don't do that"? - i.e. always put equals semantics on custom objects that match the expectation of the object user...

**Comment by axt** [comment]
Thanks for the answers, feel free to close the issue!
