### ISSUE TITLE
Mixed negative and positive values for Katz centrality

### ISSUE THREAD

**Issue by apitts** [networkx/networkx#2307]
Recently, while using networkx, I computed Katz centrality on a network using the default values and no edge weighting. The results showed a mix of negative and positive values for this metric which I believe should always be positive (or in some circumstances always negative). Please see this link: https://lists.nongnu.org/archive/html/igraph-help/2009-10/msg00059.html

I believe the cause of this may be that for this network the default value for alpha was not less than the inverse of the largest eigenvalue for the Adjacency matrix (please see here: https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.centrality.katz_centrality.html). Does this sound correct?

If that is correct, is it possible to add a check to see whether this condition is satisfied rather than to return erroneous numbers?

**Comment by hagberg** [comment]
It's certainly possibly to check `max(nx.adjacency_spectrum(G))` to estimate appropriate values for alpha.   I think we must not be doing that since it adds extra computation - maybe roughly doubles the computation time.   A middle ground would be to put some information in the docs on how to compute the largest eigenvalue.

**Comment by apitts** [comment]
Thank you @hagberg. I will implement that check in my own code.

**Comment by hagberg** [comment]
Needs a PR to add documentation on how to compute the required eigenvalue.
