### ISSUE TITLE
Calling nx.fiedler_vector() on certain graphs hangs indefinitely

### ISSUE THREAD

**Issue by hinnefe2** [networkx/networkx#2381]
In certain cases making a call to `nx.fiedler_vector` will hang indefinitely. 

Minimum working example (for me this will hang indefinitely)
```
import networkx as nx
G = nx.Graph()
G.add_path([1,2,3,4])
G.add_edges_from([(5,3), (6,2)])
nx.fiedler_vector(G)
```

Some observations:
1. Calling the function with `method='lanczos'` works fine, it's only the default behavior that sometimes hangs.

2. A cursory look through the code / stack trace when interrupting suggests that the `while True:` loop at line 73 in `networkx/linalg/algebraicconnectivity.py` might be the culprit.

**Comment by hagberg** [comment]
Seems like a bug somewhere in the vicinity of where you suggest.   Another report which could be the same issue http://stackoverflow.com/questions/43382204/networkx-cant-calculate-algebraic-connectivity/43383130#43383130

**Comment by tabac** [comment]
I have the same issue. 

In both my case and the example above, the `while` loop hangs because `beta` becomes `inf` [here](https://github.com/networkx/networkx/blob/master/networkx/linalg/algebraicconnectivity.py#L81) and as a consequence _"everything else"_ becomes `nan` which results in the failure of the exit condition [here](https://github.com/networkx/networkx/blob/master/networkx/linalg/algebraicconnectivity.py#L78).

I am afraid I am not very familiar with the Preconditioned Conjugate Gradient Method. However, I have to say that something like:

```python                                  
from math import isinf
...
    t = ddot(r, z)
    if isinf(t):
        return x
    beta = t
...
```

looks reasonable to me.

**Comment by dschult** [comment]
Line 270 in ```_find_fiedler_function``` needs to add postprocessing of the regular expression:

    if method is None:
        method = 'pcg'

When method is None (the default), it causes ```q``` to be treated as if chol/lu methods were being used instead of pcg. But in the tracemin function 'pcg' is used. So the method is a cross between the two. The major impact I see is that 'pcg' is always set to find the "largest" two eigenvectors -- fiedler vector being the second one and the first being a constant vector. This makes 'pcg' look for more than two vectors.  The 'chol' and 'lu' methods find more than two eigenvectors. 

The result for the failing example is that when the default method takes more than one iteration (enters the deflate loop) the second column of ```W``` becomes all zeros and the matrix is thus singular. This creates "NaN" which never allow the finishing condition to be satisfied.

This bug is very old (~3 years).  It is possible that the default method has been giving incorrect results.  All tests I have done show that the default was either correct, or the process hung. This would align with the idea that the problem only arose if the program got into the "deflate" loop of of the tracemin algorithm, and that at that point it always hung.

**Comment by dschult** [comment]
Still getting rare (but not rare enough) hangs due to random initialization of ```X```. 

Fix for now is to use a different method (```tracemin_lu``` or ```tracemin_chol``` or ```lanczos``` or ```lobpcg```) I'll try to track down more.

**Comment by hagberg** [comment]
See #2681
