### ISSUE TITLE
Reading GML files

### ISSUE THREAD

**Issue by eflegara** [networkx/networkx#2383]
Reading the `polblogs.gml` file [downloaded here ](http://www-personal.umich.edu/~mejn/netdata/) using NetworkX's `read_gml` function throws `NetworkXError: edge is duplicated`. 

This was not the case previously. I'm running both `Python 2.7` and `Python 3.6`; the same error is thrown using both kernels. My NetworkX version is 1.11.

**Comment by hagberg** [comment]
It looks like the code has changed significantly since your previous experience.   I didn't look into the details yet. A workaround for this error is to add "multigraph 1" to the header of the file to reflect that it has multiple edges
```
graph [
  directed 1
  multigraph 1
  node [
    id 1
...
```
The previous version of read_gml figured out whether the input file was a graph or multigraph by inspecting all of the edges.

**Comment by hagberg** [comment]
At minimum this needs some documentation.
