### ISSUE TITLE
bipartite.to_vertex_cover() gives incorrect results

### ISSUE THREAD

**Issue by embe** [networkx/networkx#2384]
This program:
```python
import networkx as nx

print('Using version ' + nx.__version__)

G = nx.Graph([(0, 3), (1, 3), (1, 4), (2, 3)])
print('Edges: ' + repr(list(G.edges())))
assert nx.is_bipartite(G)
assert nx.is_connected(G)
matching = nx.bipartite.maximum_matching(G)
print('Matching: ' + repr(matching))
for u, v in matching.items():
    assert matching[v] == u
vertex_cover = nx.bipartite.to_vertex_cover(G, matching)
print('Vertex cover: ' + repr(vertex_cover))
for u, v in G.edges():
    assert u in vertex_cover or v in vertex_cover
```

produces:
```
$ python2.7 vertex_cover.py
Using version 1.11
Edges: [(0, 3), (1, 3), (1, 4), (2, 3)]
Matching: {0: 3, 1: 4, 3: 0, 4: 1}
Vertex cover: set([0, 1])
Traceback (most recent call last):
  File "vertex_cover.py", line 16, in <module>
    assert u in vertex_cover or v in vertex_cover
AssertionError
$ python3.6 vertex_cover.py
Using version 1.11
Edges: [(0, 3), (3, 1), (3, 2), (1, 4)]
Matching: {0: 3, 1: 4, 3: 0, 4: 1}
Vertex cover: {0, 1}
Traceback (most recent call last):
  File "vertex_cover.py", line 16, in <module>
    assert u in vertex_cover or v in vertex_cover
AssertionError
```

The vertex cover is incorrect, as verified by the `assert`s.

Current git version (21114082) fails in the same way.

**Comment by hagberg** [comment]
Thanks for the report.  It looks like a bug to me (I think in _is_connected_by_alternating_path).
@jfinkels may be able to comment if that is the issue.

**Comment by jtorrents** [comment]
Yes I think there is a bug in `_is_connected_by_alternating_path`, concretely in the inner function `_alternating_dfs` that checks if unmatched nodes are linked to other nodes by alternating paths. In this concrete example the unmatched node of the left node set is 2, which is linked by alternating paths to nodes 0 and 3, but the current implementation fails to report them and thus the vertex cover reported (`{0, 1}`) is incorrect.

It's not obvious to me why the inner function `_alternating_dfs` fails in this example. A possible solution could be to reimplement this inner function iteratively instead of recursively, like this:

```python
    def _alternating_dfs(u, along_matched=True):
        if along_matched:
            edges = cycle([matched_edges, unmatched_edges])
        else:
            edges = cycle([unmatched_edges, matched_edges])
        visited = set()
        stack = [(u, iter(G[u]), next(edges))]
        while stack:
            parent, children, valid_edges = stack[-1]
            try:
                child = next(children)
                if child not in visited:
                    if (parent, child) in valid_edges or (child, parent) in valid_edges:
                        if child in targets:
                            return True
                        visited.add(child)
                        stack.append((child, iter(G[child]), next(edges)))
            except StopIteration:
                stack.pop()
        return False
```  
I've checked this example with this approach and it works as it reports a correct vertex cover (`{1, 3}`). I can prepare a pull request if this approach looks good.

I'll also merge #2375 now as it has already been reviewed and would generate conflicts with a PR for fixing this bug.

**Comment by hagberg** [comment]
Looks good.  Please do make a PR.

**Comment by jtorrents** [comment]
Done! See #2386.
