### ISSUE TITLE
Counter-intuitive API design for degree centrality in bipartite module

### ISSUE THREAD

**Issue by ericmjl** [networkx/networkx#2400]
I have noticed something kind of counter-intuitive with the bipartite module.

In the [degree centrality docs](https://networkx.github.io/documentation/development/_modules/networkx/algorithms/bipartite/centrality.html#degree_centrality), the degree centrality computation requires passing in a list of nodes from one partition, but returns the degree centrality distribution over all nodes. Just wondering, why is the API design as such? Perhaps I'm lacking some historical background here.

I think it might be more intuitive if it were one of the following API designs, perhaps? Here are my thoughts:

- Pass in a container of nodes, and return only degree centrality scores for that container of nodes.
- Do not require passing in a container of nodes, and return degree centrality scores for all nodes in both partitions.
- Make container of nodes an optional keyword, and return DC scores for those nodes only if a container of nodes is passed in, otherwise return all DC scores.

What do others think? As I mentioned earlier, I might be lacking some historical perspective here, so please pardon me if I misunderstood the original API design.

**Comment by jtorrents** [comment]
Hi @ericmjl, the API design is a result of the fact that we don't have a proper bipartite graph class in NetworkX, the convention (as explained in the module level docstrings of the bipartite package) is to use a node attribute to keep track of which node set each node belongs to.

As the Notes section of the docstring of `degree_centrality` explains, this measure is the degree of each node divided by the maximum degree possible for each node. In the unipartite case this is `n-1` (where `n` is the number of nodes in the graph) but for the bipartite case the maximum degree of a node in a bipartite node set is the number of nodes in the opposite node set.

Thus we need to know to which node set each node belongs to in order to properly compute centrality metrics (and others) in bipartite graphs. This can be computed using `bipartite.sets`, but the trouble comes in the case of disconnected graphs because more than one valid solution exists. To deal with this ambiguity we require the user to specify the nodes in one of the bipartite node sets as an argument for most bipartite functions to avoid returning wrong results depending on the concrete solution found in `bipartite.sets` (see #2375 for recent work on this). 

Do you think that we should update the docstrings for bipartite centrality functions to make this more clear?

**Comment by ericmjl** [comment]
@jtorrents thanks for the explanation! Yes, that definitely clears up the historical perspective for me.

Having seen the explanation, I'm now just wondering whether it might be better to harness the 'bipartite' keyword argument rather than pass in a list of nodes? Here's what I'm thinking in terms of API/code changes:

```python
def degree_centrality(G, partition, partition_only=False):
    top = set([n for n in G.nodes() if G.node[n]['bipartite'] == 'partition'])  # suggested change
    assert len(top) > 0  # defensive programming check

    bottom = set(G) - top
    s = 1.0/len(bottom)
    centrality = dict((n,d*s) for n,d in G.degree_iter(top))

    if not partition_only:  # suggested change
        s = 1.0/len(top)
        centrality.update(dict((n,d*s) for n,d in G.degree_iter(bottom)))
    return centrality
```

The main suggestion here (please feel free to disagree) is that the user does not have to first gather together in a container the list of nodes that they want to specify as the "top". It's one less for-loop/list comprehension that the user has to write; that list comprehension is built into the function definition.

I also added in a suggested change where we add a `partition_only` (or analogous) keyword argument, which allows the user to specify whether they want the degree centralities from that partition only, or to get all degree centralities for all nodes. By default, it is false, so the default behaviour would match the current API design, and thus the new implementation would be backward compatible in terms of expected behaviour.

These are just suggestions that I hope might make the bipartite interface a bit more declarative and hence more intuitive for an end-user. What are your thoughts on this?

If this isn't acceptable, no worries. I think updating the docs to make the historical perspective a bit clearer might help as well.

**Comment by jtorrents** [comment]
@ericmjl The main problem that I see with the approach you suggest is that we would be adding more constraints on the graphs that bipartite functions can successfully process. And thus I think we would be adding more work on the user side in order to use bipartite functions. Note that the use of a node attribute named `bipartite` with values 0 for one node set and 1 for the other is now only a suggestion. We use this convention for bipartite generators, but that's it. The user if free to follow this convention or to organize their data as they see fit.

With the API you suggest it would be a requirement to use a node attribute with this exact name, and we would also to enforce the use of concrete values for the attribute to distinguish node sets. I think it's easier for users to create a container with all nodes in on bipartite node set (which is a line of code) than to follow a convention that might not suit their data. I work a lot with bipartite graphs, and sometimes I didn't generate them but I have to analyze them, sometimes the node set to which each node belong is part of the node name/id, sometimes is a node attribute other than bipartite, etc ... In all these cases, I only need a line of code to gather all nodes in one node set in a container and use all bipartite functions. If we enforce the use of a node attribute with defined values I'd have to do more work in order to use bipartite functions. 

Regarding making the docs clearer, what would you suggest? Rereading the docstings I feel that they are clear, but of course I'm not in the best position to see how docs could be improved as I wrote those functions and I've been using them for a long time.

**Comment by ericmjl** [comment]
@jtorrents thanks for your response. One thing that previously confused me is that the `bipartite` keyword is consistently used in the docs as the node attribute to identify partitions, but it isn't made consistently clear across the bipartite docs that this is just a suggestion; this is only described in brief as a 'convention' on [this](https://networkx.github.io/documentation/development/reference/algorithms.bipartite.html) page, but that isn't necessarily the page I get directed to when I'm looking for a specific bipartite algorithm. This led me to think that bipartite was baked into the codebase as being "the" keyword. 

On the docs, I think explaining the rationale behind having the user gather one set of nodes together would help an end-user. Something along the lines that "In the source code, no assumptions are made about the partition that the nodes come from, so we require the user to pass it in." (or perhaps something clearer than my muddied brain is thinking of right now.)

I do notice, however, that the `degree_centrality` and `betweenness_centrality` functions assume that nodes from only one partition are passed in, and that there's no node from the other partition. Is that a good idea? Wouldn't it be a good defensive check to ensure that the node container passed in only contains nodes from one partition? Or might I be missing something here?

**Comment by jtorrents** [comment]
@ericmjl In general we try to minimize the sanity checks for inputs. For instance, hardly any of the functions in the bipartite package checks that the input graph is actually bipartite. There is a cost in terms of running time in doing sanity checks, and it's impossible to cover all corner cases. In the end the "garbage in -> garbage out" rule always applies. So we assume that users are careful preparing the inputs for functions.

Regarding the documentation, I'll prepare a PR trying to improve the explanations of the APIs in the bipartite package. Thanks for looking at this carefully and for your comments, it's very useful. This is the best way to improve usability.
