### ISSUE TITLE
Travis with Python3.6 miniconda fails

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#2415]
Fails with a gdal conflict error.
Can a conda expert help us figure out how to fix this?

```
UnsatisfiableError: The following specifications were found to be in conflict:

  - gdal -> libnetcdf 4.3.2 -> curl 7.38.0 -> openssl 1.0.1*
  - gdal -> numpy 1.9* -> python 2.7*
  - python 3.6*

Use "conda info <package>" to see the dependencies for each package.
CondaEnvironmentNotFoundError: Could not find environment: test-environment .
You can list all discoverable environments with `conda info --envs`.
```

**Comment by jtorrents** [comment]
See #2416 for a workaround. It seems that the problem is that conda for python 3.6 installs the latest version of gdal (2.1.3) which is not compatible with the package libgdal-dev provided by Travis version of Ubuntu. By installing gdal after creating the conda environment that build for 3.6 is not killed and gdal is installed successfully for all other python versions.
