### ISSUE TITLE
Random access to node neighbors

### ISSUE THREAD

**Issue by robertour** [networkx/networkx#2438]
At least, in network simulations is common to have  to randomly select a node out of the possible neighbors:

For example, select two nodes that are going two perform an interaction. I have to do this.

    for id1, n1 in self.g.nodes_iter(data=True):
        n2 = self.g.node[random.choice(self.g.neighbors(id1))]

However as far I can read from the code, `neighbors()` is generated from `self.g.adj` so it has an O(n) time. Ideally we would have random access, i.e. O(k) time. 

One posibility would be to keep a separated list of node indexes, or to use a random access dictionary such as this: https://github.com/robtandy/randomdict

Would this improvement makes sense at all? I understand that most of the time nodes have very few neighbors, but at the same time in simulations the g.neighbors(id1) is accessed constantly. 

(Obviously I can keep the list of neighbors as an attribute myself, but I am just posting because I think that it is an important issue that should be at least discussed)

**Comment by dschult** [comment]
Take a look at the ordered dict graph class:
https://github.com/networkx/networkx/blob/v1.11/networkx/classes/ordered.py
NetworkX uses Python dicts by default, but we put code into the base classes that allows other dict-like objects to be inserted in place of the default dict class. The most common request was for ordered dicts. But it sounds like your interest would be exactly served by the same treatment using randomdict instead of OrderedDict.  

Also note, to make this work you'll want to access the neighbor dict directly instead of through self.g.neighbors.  self.g.adj[n1] provides a dict-like object with keys being the neighbors of n1.

**Comment by robertour** [comment]
Nice! Thank you. I don't think the OrderedGraph is in the documentation, instead I found this (https://github.com/networkx/networkx/blob/v1.11/networkx/classes/graph.py#L177) which is what I need. I will close the issue, thanks again!
