### ISSUE TITLE
Incorrect formula for collaboration_weighted_projected_graph

### ISSUE THREAD

**Issue by rafguns** [networkx/networkx#2444]
The formula given in `collaboration_weighted_projected_graph` makes little sense. For reference, the one in the paper by Newman is:

`w_{i, j} = \sum_k \frac{\delta_{i}^{k} \delta_{j}^{k}}{n_k - 1}`

where `i` and `j` are nodes from the "bottom" node set (the set of nodes to project onto), and `k` is a node of the "top" node set. The value `n_k` is the degree of node `k` in the bipartite network and `delta_{i}^{k}` is 1 if node `i` is linked to node `k` in the original bipartite graph or 0 otherwise.

It is probably also worth mentioning explicitly that "top" nodes with degree <= 1 are excluded.

**Comment by Michael-E-Rose** [comment]
For reference: http://networkx.readthedocs.io/en/stable/reference/generated/networkx.algorithms.bipartite.projection.collaboration_weighted_projected_graph.html?highlight=collaboration_weighted_projected_graph with `i = v`, `j = w`.  It seems that the first delta should have superscript `k` and the denominator should be `k` (or `n^k`), but not `k_w`.

To me the code looks correct, however.  Can someone confirm?

When fixing this, someone should apply PEP8 and add the decorator.  I bet we can also gain some speed by computing a degree dictionary once rather than twice in each iteration.
