### ISSUE TITLE
fixing a subset of nodes in spring_layout

### ISSUE THREAD

**Issue by ccoffrin** [networkx/networkx#2448]
The following layout works reasonably well,
```
import networkx as nx

G = nx.Graph()
G.add_edges_from([(0,1),(1,2),(2,0),(2,3)])
pos = nx.spring_layout(G)
print(pos)
```
However, the results from run to run are not easily reproduced because the initialization is random.  

To mitigate this we can fix node 0 to (0,0), as follows,
```
init_pos = {0:(0.0, 0.0)}
fixed_pos = [0]
pos = nx.spring_layout(G, pos=init_pos, fixed=fixed_pos)
print(pos)
```
This results in  the following error,
```
networkx/drawing/layout.py:342: RuntimeWarning: divide by zero encountered
```
A work around seems to be to provide initial points to all positions as follows,
```
import random
init_pos = {n:(random.uniform(-1.0, 1.0), random.uniform(-1.0, 1.0)) for n in G}
init_pos[0] = (0.0, 0.0)
fixed_pos = [0]
pos = nx.spring_layout(G, pos=init_pos, fixed=fixed_pos)
print(pos)
```

**Comment by dschult** [comment]
Interesting...  Thanks for the report. 

Setting the initial position to (1, 1) works.  The strange behavior occurs when setting one node to the origin. That occurs because we find the domain_size by taking the maximum value of all initial positions. Unfortunately, if that maximum value is ```0``` then the domain size is set to zero and all the points are initially put at the same point. That leads to a division by zero exception. 

I think a straightforward fix would be to check if there is only one initial point provided. If so, then set the domain_size to be 1.  

Would someone like to provide a pull request for this?  Thanks!
