### ISSUE TITLE
Restricted turns for a MultiDiGraph

### ISSUE THREAD

**Issue by sephib** [networkx/networkx#2452]
Hi,
I trying to implement a MultiDiGraph street route network based on [HERE ](https://here.com/en/products-services/data/here-map-data) data (taking inspiration from the [OSMNX](https://github.com/gboeing/osmnx) project.  
I was wandering how I should implement the restricted turns for a car network. Is there a way to implement a solution not using the `weight` attribute (as suggested in [this post])(https://gis.stackexchange.com/questions/16453/how-to-restrict-or-block-certain-paths-in-networkx-graphs)?

Any directions would be appreciated.

Sephi

**Comment by dschult** [comment]
I am not very familiar with mapping applications on graphs, but it seems to
me there are two natural implementations for storage in a NetworkX graph.

The first is to make edges represent roadway segments with nodes
representing the intersections. In this storage system it is hard to
restrict turns. But it is good for finding "shortest paths" because edges
hold the lengths of the roadways.

The second is to make nodes represent an end of a roadway segment and edges
represent two types of objects: the roadways themselves or a turn from one
segment to a different segment. This seems like the natural way to restrict
turns. But it does increase the number of nodes and edges quite a bit
though. Each roadway segment is assigned two nodes -- one at each end. Each
intersection is represented by (usually) 4 nodes and edges for each turn
possible (usually 12 for all directions except u-turns).

**Comment by sephib** [comment]
Hi
Thank you for your thoughts.
Your second suggestion is interesting, it is a bit clunky - but I may not have any other choice.
Will try and update.
