### ISSUE TITLE
All pairs dijkstra returning both paths and lengths

### ISSUE THREAD

**Issue by prcastro** [networkx/networkx#2465]
Today Networkx only have `all_pairs_dijkstra_path` and `all_pairs_dijkstra_path_length`, but there is no way to get both paths and lengths at the same time (as we have in `single_source_dijkstra`)

**Comment by dschult** [comment]
This should be pretty straightforward to add. It's very similar to the methods you mention only using ```single_source_dijkstra``` instead of the path and length varieties of these functions. 

Note that if you have the paths it is fast to find the lengths, so maybe you don't need both.

In any case, would anyone put forward a PR for this?

**Comment by markhkim** [comment]
Here it is! https://github.com/networkx/networkx/pull/2510

**Comment by dschult** [comment]
implemented in #2510 and #2612
