### ISSUE TITLE
Notebooks and Tutorial at github/networkx/notebooks

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#2518]
With many discussions regarding having Jupyter notebooks for examples and tutorial the consensus is to create a new repo https://github.com/networkx/notebooks. Currently this contains some files (verbose copy) from docs/examples in .ipynb format. Making sure this works and is manageable requires the notebooks to be tested (preferably with something like Travis) and the other advantage of having notebooks is having an interactive way for users to play around with NetworkX. This can be done with https://beta.mybinder.org (this is still under works so the UI doesn't work yet)[1] a build can be triggered for the notebooks repo by this URL https://beta.mybinder.org/v2/gh/networkx/notebooks/master , the build is failing right now because of pygraphviz. Need to look into that.

I have a built a rudimentary setup with binder and travis for the tutorial notebook at https://github.com/MridulS/test-tut , the binder notebook can be spawned by https://beta.mybinder.org/v2/gh/mriduls/test-tut/master and using https://github.com/computationalmodelling/nbval we can test the notebooks. Travis: https://travis-ci.org/MridulS/test-tut 

Another important point is that we need to maintain at least 2 copies[different branches] of notebooks to make sure that the notebooks work with the latest release available through pip and the current master dev branch on GitHub. This could be done through branches. The default branch should point to the latest release. 

[1] https://github.com/jupyterhub/binderhub

@hagberg @dschult @jarrodmillman

**Comment by dschult** [comment]
This looks good.  I think the branches should mimic the ones for the networkx repository. That is, when a release is made we should make a release of the notebooks too. The master branch in each should be the development branch.  Otherwise I'm going to have trouble keeping track of which release matches with which examples release.  :)

**Comment by dschult** [comment]
If I understand correctly mybinder.org is a website where users can run a "live" version of each notebook through their browser.  It's too bad that the site isn't quite production ready yet. Perhaps we can wait on browser based functionality and concentrate on setting up automated testing where each branch of notebooks tests with a corresponding version of NetworkX.  I think that is what is needed to make the notebooks separate repository viable.  

It looks like sphinx-gallery can put many of the examples on ReadTheDocs with a link to download the notebook in either ```.py``` or ```.ipynb``` form. That interface allows automated testing through Travis with a sync'd version of networkx (because they are in the same repository).  Can we do something like that with a separate notebooks repository?

**Comment by dschult** [comment]
Ok maybe i am getting the gist of this more...  
This system would allow us to automatically test the notebooks by putting a Travis.yml file in the repository. Should the branch of NetworkX be controlled in requirements.txt? Or maybe instead using pip to github directly in the yml file? 

The nbval testing system for notebooks seems pretty good. Each cell is a test against the expected output.  Also, while the mybinder live-notebook-in-a-browser is still in beta, it is pretty good already. I was able to do what I wanted with the UI.

The issue with installing pygraphviz is probably that it needs GraphViz. Any I don't think GraphViz can be installed by pip (though maybe it can -- I'm no expert on pip).  The front page mentions that you can use either a requirements file or a DockerFile to set up the install. Somehow we need GraphViz installed before the pip command tries to install pygraphviz.

**Comment by MridulS** [comment]
> Should the branch of NetworkX be controlled in requirements.txt? Or maybe instead using pip to github directly in the yml file?

We can just add `git+https://github.com/networkx/networkx.git` in requirements.txt to install the GitHub master branch version of networkx. And we need requirements.txt for mybinder.

> Also, while the mybinder live-notebook-in-a-browser is still in beta, it is pretty good already. I was able to do what I wanted with the UI.

mybinder was a regularly maintained project but I am not so sure what happened with that. Now they have shifted to work with the folks at jupyterhub (which is now used in the background). Hopefully it should be soon out of the beta :)

>The issue with installing pygraphviz is probably that it needs GraphViz. Any I don't think GraphViz can be installed by pip (though maybe it can -- I'm no expert on pip). The front page mentions that you can use either a requirements file or a DockerFile to set up the install. Somehow we need GraphViz installed before the pip command tries to install pygraphviz.

Yeah, that seems to be the issue. The build log shows that it fails at `libcgraph` which is a part of graphviz installation. I'll take a look at setting up a DockerFile :)

**Comment by MridulS** [comment]
Dockerfile is all set for GraphViz. PR https://github.com/networkx/notebooks/pull/7

**Comment by MridulS** [comment]
current build at binder https://beta.mybinder.org/v2/gh/mriduls/notebooks/master

**Comment by jarrodmillman** [comment]
I am sorry for jumping into this conversation so late, but I am not sure this is the right thing to do.  Providing notebooks as an **end-product** seems reasonable to me, but they are a bad format for working in (I wouldn't edit them for example).  Now that we are using ``sphinx-gallery`` and ``nb2plots`` we automatically get notebooks as an output format for free, while still being able to work with nice, easy to edit, and easy to version control source files.

I am planning to clean up the examples and tutorial more at some point, but I don't have the patience to pull out fixes from notebooks in a different repository.  I would rather see your time and effort spent on revising the current example scripts directly.

I assume that the original idea for converting things to notebook format was not wanting to maintain the custom gallery scripts.  But now we are using standard sphinx extensions, so I don't think this is an issue anymore.  Is there any other reason for wanting to use notebooks as source files?

**Comment by MridulS** [comment]
@jarrodmillman Yes you are right converting examples to notebook format seem redundant now as we are using standard sphinx extensions to get a pretty gallery and downloadable notebooks, but converting examples to notebooks is just an excuse to get the notebooks repo up and running. The examples and tutorial **shouldn't** be the only things in networkx/notebooks. User generated notebooks and elaborate use of NetworkX in detailed tutorials should be a part of this ultimately  . There is a [PR open](https://github.com/networkx/notebooks/pull/6 ) in the notebooks repo which is example of such a notebook. [link to notebook](https://github.com/cole-maclean/notebooks/blob/a33f2969965474450147560c101119d1fe923e81/generators/geometric.ipynb). We should end up with something like https://github.com/RaRe-Technologies/gensim/tree/develop/docs/notebooks which contains a folder of detailed python tutorials which uses gensim and related python ecosystem.

> I am planning to clean up the examples and tutorial more at some point, but I don't have the patience to pull out fixes from notebooks in a different repository. I would rather see your time and effort spent on revising the current example scripts directly.

If I find something that is broken in the examples and I'll update notebooks and examples both :) . I did see use of `add_path` in a couple of examples which isn't a part of the core Graph class anymore, i.e. `nx.add_path` instead of `G.add_path`. I'll push changes ASAP.

Let me know if this makes sense :)

**Comment by jarrodmillman** [comment]
I agree that having a separate repo for long-form, narrative tutorials is a good idea.
The geometric network tutorial you linked to is a good example (I hadn't noticed it before).

I have two main issues:

1.  I don't think storing these tutorials in the notebook format is a good idea.
My recommendation for the long-form tutorials is to use Sphinx
with the ``nb2plot`` and ``texext`` extensions.

Here are a couple of examples using ``nb2plot``:
- http://networkx.readthedocs.io/en/latest/tutorial.html
- http://matthew-brett.github.io/teaching/pca_introduction.html

If you scroll to the bottom of either page, you will find links
to autogenerated python scripts and notebooks.

There are many advantages to using reStructuredText and Sphinx with
the ``nb2plot`` extension compared to working directly in notebooks.
For example,
- better format for version control
- more standard tool chain for testing and continuous integration
- more advanced features such as support for indices, search, and cross-referencing
- easier to edit using text editors and command-line tools
- pretty and easier to read webpages
- nice PDF output

In addition, ``nb2plot`` provides extra functionality that the notebook
lacks.  For example, you can hide complicated code cells when it
distracts from the exposition.

I would also name the repository something like ``tutorials``.
Naming the repository after the content instead of the particular format we
choose to use will make it clearer what the purpose of the repository is.

I am happy to quickly (i.e., by the end of today) setup a skelton repository using
``notebooks/generators/geometric.ipynb`` (or I could quickly put together a something,
e.g., using the Fiedler vector and the karate club dataset).
That way we could compare the two options.
Alternatively, I could review and provide advice on using the toolstack, if you would
prefer to do it.

2.  I think we should have only one canonical location for the main tutorial and
small examples.
The main tutorial (http://networkx.readthedocs.io/en/latest/tutorial.html)
should have links to the long-form tutorial and gallery examples.
I don't think we need to populate the tutorial repo with placeholder
tutorials.
While you may be able to keep the two versions in sync now, I worry that
they will diverge over time.

Thoughts?

**Comment by hagberg** [comment]
Now that @jarrodmillman has shown us the light in how to generate multi-format output with the Sphinx tooling I think we should do that (basically the status quo).  

I'm not opposed to having other notebooks (separate repository) but I can see the significant advantages of keeping everything in sync using this approach.

**Comment by MridulS** [comment]
I agree with pretty much all the points here. Not moving examples to notebooks is perfectly fine. The reason I am advocating of having notebooks (for long form narrative tutorials) in a separate repo is integrating it with services like mybinder, giving users the capability to test out the notebook without installing all the pre requisites of the notebook on their local machine.

For example this an [executable notebook](https://beta.mybinder.org/v2/gh/mriduls/test-tut/master) of the official tutorial where users can play around with the tutorial and write and execute code.

Regarding testing the notebooks we can use nbval and travis, for version control I know notebooks are pain to work with but tools like nbdime do a good enough job for diff (at least on local machine).

IMO this shouldn't be a repo actively updated by the core developers but instead should be a crowdsourced initiative, from the users of networkx.

Regarding keeping the two repos in sync, I guess keeping just the official tutorial shouldn't be a problem for the long term too.

[Sorry for the late reply, just moved to a new place]

**Comment by hagberg** [comment]
I think we agreed on keeping the examples as is.
