### ISSUE TITLE
Blockmodel with incomplete/partial partitions

### ISSUE THREAD

**Issue by pckroon** [networkx/networkx#2529]
Hi all,

This is part question, part easy improvement suggestion.
Currently, if I want to make a blockmodel of my graph I have to assign every node to a partition:

```
G = nx.path_graph(6)
partition = [[0, 1, 2], [3, 4, 5]]
M = nx.blockmodel(G, partition)
```

Is it desirable to be able to provide incomplete partitions?

```
G = nx.path_graph(6)
partition = [[0, 1], [4, 5]]
M = nx.blockmodel(G, partition)
```

This would generate a disjoint graph, but I don't think this is really an issue (but I'm not well versed in graph theory). 
Currently, in version 1.11, if I try this it gives me a `KeyError` which can be easily fixed/circumvented by either a check or a `try`/`except` in `networkx/algorithms/block.py` around lines 100 and 101.

What's your thoughts on this? I'd be happy to make a PR.

**Comment by mddddd** [comment]
I would be happy to contribute PR for this issue but have some questions. As I see `blockmodel` was replaced by more general `quotient_graph`, taking this into acount is this issue still valid? (some math oriented people may argue that there is no quotient graph without proper partition, so this should be error)

If it is still valid then what is the expected behaviour when partition is incomplete? I see 2 possibilities:
- Return a quotient graph of a subgraph induced by nodes from partition.
- Update partition with singletons made from nodes not present in original partiton.

what do you think?

**Comment by pckroon** [comment]
Hey,
thanks for the reply :)

`quotient_graph` seems to be capable of doing what I want, but it is a little cumbersome to have to define a function and filter out the singleton nodes afterwards. E.g:
```python
G = nx.Graph()

G.add_edges_from([(0, 1), (1, 2), (2, 3), (3, 4)])

partitions = [(0, 1), (3, 4)]

def quot(n1, n2):
    for partition in partitions:
        if n1 in partition and n2 in partition:
            return True
    return False

H = nx.quotient_graph(G, quot)

remove = set()
for node in H:
    if len(node) == 1:
        remove.add(node)
H.remove_nodes_from(remove)
```

I don't now enough about the math to be able to say anything about "proper" partitions and such, and what the ramifications are. 
What I expected as behaviour is option 1, so I need to filter out singleton nodes. 

I don't know how much of an edgecase this use-case is, so it's up to you whether it should be included in networkx. Either way, I'll wrap the code above in a function for my own use :) Let me know if you want me to post it here as well, might save you some work.
If you choose to include this, maybe it (c|sh)ould be an option whether singleton nodes are removed.
