### ISSUE TITLE
NetworkX Failing 57 Tests

### ISSUE THREAD

**Issue by miov** [networkx/networkx#2582]
Running on:
Linux Ubuntu 16.04     and   Windows 10
Pyzo 4.4.1  using conda
Python 3.6.1

When I run import networkx as nx; nx.test()  it results in 57 failed tests on both LInux and windows. I am running pyzo 32bit on the windows parition and the 64bit version on my linux os.

here is the logfile test() produces:
[testlog_57failures.txt](https://github.com/networkx/networkx/files/1200882/testlog_57failures.txt)

I also have a post to this problem on [stack overflow](https://stackoverflow.com/questions/45509149/networkx-test-failure)

**Comment by jarrodmillman** [comment]
The current release of ``networkx`` doesn't support Python 3.6.  We will release ``networkx`` 2.0 soon and this will no longer be an issue.  The 2.0 release changes quite a few things, which is why it has taken longer to finalize than previous releases.  Thanks for you patience.

You can follow 2.0 development here:
https://github.com/networkx/networkx/milestone/3
