### ISSUE TITLE
Readthedocs pain

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#2646]
Readthedocs (RTD) is a pain to work with and keeps having timeout errors.  I started to look into whether we can build the docs on our own and push them to RTD instead of having it built on the site.  It would also make more sense to have the doc build process as part of our CI process, rather than only checked after the fact.

Has there been any discussion about moving away from RTD before (at least the build process)?  If so, was there a reason not to move?  I assume it is too late to move back to hosting the docs on github, but I thought I'd check since it might be easier to do.

**Comment by hagberg** [comment]
When we moved to RTD (from hosting on github) the idea was that it would be simpler engineering than building and pushing docs to github.   If there is a CI approach that is reasonable to maintain that seems like a good path forward.

**Comment by jarrodmillman** [comment]
I will look into our options then.

**Comment by dschult** [comment]
I agree that RTD is not as smooth as travis. And it would be nice to track the sphinx errors rather than have to go clean it up every N months. Building the docs and pushing them to github.io would be great so long as it is automated in a low-maintenance way.  I'm interested to see what options you come up with.
