### ISSUE TITLE
Network analysis time is very slow.. :-(

### ISSUE THREAD

**Issue by pak3345** [networkx/networkx#2685]
I was SNA with networkx from python. But it have many time for analysis..(2days)Data is 2.5 million connection data. data format is

> in out 00996609 00197091 00197091 80000002 80000002 00996599 00996599 00996599 00996599 00996609 00996609 00197091 00197091 00996599 00996599 00197091 00197091 00996599 00996599 00197091 00197091 00996599 00996599 00996599 00996599 00996599 00996599 00996599 00996599 00996599 00996599 00996599 00996599 00996599 00996599 00197091 00197091 00996599 00996599 00197091 00197091 00996599 00996599 00996599 00996599 00197091 00197091 80000002 80000002 00197091

Code   
`# -*- coding: utf-8 -*-
"""
Created on Wed Sep 20 17:52:29 2017

@author: UrbanLab-4
"""
import networkx as nx
import time
start_time = time.time()
G = nx.Graph() # 그래프 생성

f= open('file.txt','r') # 파일 열기
#파일 읽기
f_1 = f.readlines()
for lineF in f_1:
    i = lineF.split('|')
    categories = i[0]
    k = (i[0],i[1].rstrip('\n'))
    G.add_node(i[0]) # 노드 지정
    G.add_edge(*k) # 라인 생성

#pos = nx.shell_layout(G)  #좌표 지정
#nx.draw_networkx_labels(G,pos,font_size=10) # 라벨 씌우기
#nx.draw_shell(G) # 그래프 모양 지정

#네트워크 분석
#네트워크 분석

x = G.number_of_edges() # 총 연결된 라인수
y = len(G) #총 노드의 수

o = nx.degree_centrality(G)
o1 = []
o2 = []
for v in o.values():
    o1.append(float(v))
e = float(sum(o1)/y)  #연결중심성평균
for w in o.values():
    o2.append(float(pow(w-e,2)))
j = float(sum(o2)/y) #연결중심성분산
o = str(o)#연결정도중심성

#매개중심성 PARRT
p = nx.betweenness_centrality(G) 
p1 = []
p2= []
for s in p.values():
    p1.append(s)
l = float(sum(p1)/y) # 매개중심성평균
for t in p.values():
    p2.append(pow(t-l,2))
m = float(sum(p2)/y) # 매개중심성분산
p = str(p) #매개정도중심성

q = nx.degree(G) #연결정도

n1=[]
for r in q.values():
    n1.append(r)
n = sum(n1)#라인 연결정도 합
n = str(n)
e = str(e)
j = str(j)
l = str(l)
m = str(m)
q = str(q)
x = str(x)
y = str(y)

g = open('resultfile.txt','a+')
print('총노드수 '+': ' + y + '\n',file=g)
print('\n'+'총 라인수 '+': ' + x + '\n',file=g)
print('\n'+'라인 연결정도 합 '+': ' + n + '\n',file=g)
print('\n'+'연결정도 '+': ' + q + '\n',file=g)
print('\n'+'연결정도중심성 '+': ' + o + '\n',file=g)
print('\n'+'연결정도중심성 평균 '+':'  +e + '\n',file=g)
print('\n'+'연결정도중심성 분산 '+':'  +j + '\n',file=g)
print('\n'+'매개정도중심성 '+':'  +p + '\n',file=g)
print('\n'+'매개정도중심성 평균 '+':'  +l + '\n',file=g)
print('\n'+'매개정도중심성 분산'+':'  +m + '\n',file=g)
g.close()
f.close()
end_time = time.time()
print(end_time - start_time)`

I compared with Netminer program. Result same but analysis time is very different... I want to know fast analysis time..

**Comment by dschult** [comment]
There are so many things that affect timing. Your other program may be a compiled program -- Python in interpreted. The advantage of Python is flexible and understandable code. If you need speed, you should run your python code with PyPy or with Cython.

A brief look at your code tells me that there are some things you can do to speed it up. Perhaps the first would be to time portions of the code to find the bottlenecks. Your single line: ```p = str(p)``` could be taking a huge amount of time since you have 2.5 million keys and values to make into a string. Each of those keys is many characters and you have values associated with each. So you are probably talking about a 30-50 million character string.  You don't ever use the string version of p, so why create it?

I'm going to guess that most of your time is spent reading the file, creating an graph and calculating betweenness_centrality. Perhaps conversion to and from strings is a fair amount too. If it is reading the file and creating the graph, then you should do just that once and store the graph in a different format. If it is betweenness_centrality then you should consider making your nodes into integers rather than strings, and using Cython or PyPy to run the same code.

**Comment by pak3345** [comment]
Thank you for your answer.

**Comment by pak3345** [comment]
Thank you for your answer
I want to write each figure on a notepad
If not string, don't write them, when this is dic format.
And I want to use Cython or PyPy. How do i get to started???

**Comment by pak3345** [comment]
I will use PyPy.
Is it possible to use that code in PyPy?
