### ISSUE TITLE
improve Search Engine results for documentation

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#2730]
It seems like every time I do a web search for a networkx function (or even networkx itself) the top results are documentation from v1.9 or v1.10.  This was true when we used ReadTheDocs too, but it is more true now.

Perhaps there is some way to redirect some of the pagerank from our older documentation to the newer stuff.  Something like rel=canonical might be helpful, though I'm not sure it is right because it is supposed to be for pages that are identical.

**Comment by hagberg** [comment]
I'm don't know the approaches for this - maybe telling crawlers not to index the old pages? 
https://support.google.com/webmasters/answer/93710

**Comment by dschult** [comment]
If we use ```noindex``` to have crawlers ignore the page, then we lose that pagerank.
The advantage of ```rel=canonical``` is that it forwards the pagerank from all those older stackoverflow questions to the latest version of the same function. The more I read about ```rel=canonical``` the more I'm convinced that search engine optimization is a free-for-all and canonical can be used where it wasn't originally designed to be used.  But submitting a ```Sitemap``` for NetworkX might be easier than ```rel=canonical``` anyway.

What do other Open Source Projects do about this?  I see similar search results where the old version comes up first in numpy and scipy. It seems like someone should have thought about how to migrate pagerank from older versions to later versions.

One basic question: do we want people to go to the ```latest``` docs or the ```stable``` docs?

**Comment by jarrodmillman** [comment]
@dschult @stefanv Search engines have been returning links to old versions of our documentation.  We want them to point to our stable docs first.

PR #3707 should handle things going forward.  I believe we need to add the canonical URL information to documentation from older releases:  https://github.com/networkx/documentation

Here is a short script to do that:
https://gist.github.com/jarrodmillman/678d509d53f0326b1fcfb0f8b30b5c1c
I would like to update the old docs sometime this weekend, so it would be great if you both could take a  quick look at my script and let me know if you have any suggestions or see any potential issues.

## Sphinx / html_baseurl / canonical_url

Sphinx has 
```
html_baseurl

    The URL which points to the root of the HTML documentation.
    It is used to indicate the location of document like canonical_url.

    New in version 1.8.
```
from https://www.sphinx-doc.org/en/master/usage/configuration.html.  But that didn't seem to do anything.  May be that was because we use the sphinx_rtd_theme (I haven't checked whether it works with other themes yet).  Adding this
```
html_theme_options = {
    "canonical_url": "https://networkx.github.io/documentation/stable/"
}
```
to `conf.py` did work as you can see in PR #3707.

## Sitemaps

We may want to create a sitemap, but I haven't looked into that much.

Here some links that may be helpful:
- https://github.com/readthedocs/readthedocs.org/issues/557
- https://github.com/readthedocs/readthedocs.org/pull/5122
- https://github.com/jdillard/sphinx-sitemap

## Next Steps

I think many of the other projects have similar issues, so if this works I will likely try (by creating a PR) to get other projects to do something similar.

**Comment by dschult** [comment]
One potential problem is that from 1.11 to 2.0 we switched the documentation folder structure inside references.  In 1.x we used ```algorithms.centrality.etc``` while in 2.x and later we used ```algorithms/centrality/etc```.  So the canonical may not exist in many cases. 

Finding a way to convert path names to the current stable path name seems tricky -- but perhaps doable... I haven't looked to see how many files this affects.

**Comment by jarrodmillman** [comment]
I could check if the new URL exists and handle it if not.  For example, instead of just
```
insert = f'{base}{path}"/>'
write_file.write(insert)
```
I could do something like
```
# check if it exists
url = url_base + path
if requests.get(url) == 200:
    insert = f'{base}{path}"/>'
    write_file.write(insert)
else:
    # algorithms.centrality.html -> algorithms/centrality.html
    path = path.replace(".", "/", path.count(".") - 1)
    url = url_base + path
    if requests.get(url) == 200:
        insert = f'{base}{path}"/>'
        write_file.write(insert)
```
where
```
url_base = "https://networkx.github.io/documentation/stable/"
```

We may not get all of the pages this way, but it may be enough.  I will see if I can find any other missing links and let you know what I find.

**Comment by jarrodmillman** [comment]
I updated the script to handle some of the mapping:
https://gist.github.com/jarrodmillman/678d509d53f0326b1fcfb0f8b30b5c1c
It doesn't cover everything, but it gets a fair bit.  I may try to improve it over the weekend.

**Comment by dschult** [comment]
I see that you've introduced a mapping of html paths.  That's probably the only way to account for all the strange cases.  Nicely done. 

Also, only bothering with the versions since v1.9 is a good choice. It reduces the special cases needed, and it seems (my experience with google's search engine) that v1.9 and later are the primary hits that come up for NetworkX.

**Comment by stefanv** [comment]
See also https://github.com/scikit-image/scikit-image.github.com/blob/master/robots.txt

**Comment by MridulS** [comment]
It would be nice to also have version warnings on older documentation, something like https://github.com/humitos/sphinx-version-warning

**Comment by dschult** [comment]
Interesting approach @stefanv 

Does that make search engines lose any links pointing to the old docs? It might be better to have the link power forwarded to the more recent links. But I'm guessing in most cases, the most recent code would still come up top on the search.

**Comment by stefanv** [comment]
I don't think they "lose" links, but they prioritize newer results.  If you search for scikit-image, the website and the latest docs show up 1 and 2.  If you search for "skimage", you get all in the first item (not sure why Google chooses "skimage" instead of "scikit-image").

So, Googling scikit-image is a good test case to see if this does what you want!

**Comment by stefanv** [comment]
> It would be nice to also have version warnings on older documentation, something like https://github.com/humitos/sphinx-version-warning

Yes, that's a good idea!  Let's definitely add that.

**Comment by dschult** [comment]
I think the "skimage" is highlighted because it is used as the word in the link that points to that page. Somehow the hypertext link text gives it more power in the algorithm I think.

Googleing scikit-image is good. Also googling img_as_int is a good test case -- it comes up with skimage and then v0.17.2 and then v0.8.0 docs.  The skimage page is labeled as "no information is available for this page" because it is blocked from reading it by the robots.txt.  But I think it comes up first in the list because so many places point to it.

It is certainly a better result than what we often get which is the old docs coming up before the new docs in a search for a function.  An example is searching for: networkx single_source_shortest_path.

**Comment by jarrodmillman** [comment]
I added EOL warnings to old documentation:
https://github.com/networkx/documentation/commit/36eb5d10d6cfc1c8c66cdc2819144461ece073ff

For example,
- https://networkx.github.io/documentation/networkx-1.10/
- https://networkx.github.io/documentation/networkx-1.9/

**Comment by jarrodmillman** [comment]
@dschult @rossbar @MridulS I think the changes mostly worked.  Before hand when I searched ``networkx add_node`` or ``networkx add_edge``, I would often see 1.9 or 1.10 links on google, bing, yahoo, and others.  It took awhile for all three to update, but they mostly seem correct now.

I am still seeing this PDF pop-up at the top occasionally:
https://www.bu.edu/networks/files/2012/08/networkx_tutorial.pdf
For example,
https://search.yahoo.com/search?p=networkx+add_node

Maybe we should ask them to remove it?

**Comment by dschult** [comment]
That's great news Jarrod!

**Comment by rossbar** [comment]
> It took awhile for all three to update, but they mostly seem correct now.

Agreed - I see the v2.4 docs as the top hit for these search terms everywhere now :+1: 

> I am still seeing this PDF pop-up at the top occasionally:

I only see this with the linked yahoo query. I'd suspect it has more to do with yahoo than anything else...

**Comment by jarrodmillman** [comment]
If we notice more problems, we can try again.

**Comment by dschult** [comment]
Yay!!  This is great!
