### ISSUE TITLE
connected_components_subgraphs VERY slow in 2.0 but not in 1.11

### ISSUE THREAD

**Issue by daefresh** [networkx/networkx#2743]
Hi NetworkX Team:
We have been using your library since 1.8 and love it. 
We recently upgraded to 2.0. We have observed a **drastic** speed degradation in connected_component_subgraphs. 
We need to create a list of connected_component_subgraphs copies. On a graph size of 40k ndoes this worked in under a second on 1.11. 
Whereas to do the same on 2.0 it takes 20+ minutes and sometimes never completes. I created a sample below to demonstrate what we're doing:

```
import networkx as nx
graph = nx.MultiGraph()
for counter in range(20000):
    node_keys = [counter, counter*-1]
    graph.add_path(node_keys)
components = [c for c in nx.connected_component_subgraphs(graph, copy=True)]
```

The last line of code takes the longest. Any ideas?

Thanks

**Comment by dschult** [comment]
Thanks @daefresh for this report!  The example helps quite a bit too. 

I've isolated the problem to subgraph's iteration when there are many nodes in the graph and few in the subgraph.  It looks like this requires a replication to FilterAdjacency of what #2687 did for FilterAtlas.  We can check for a "nodes" attribute on the NODE_OK attribute of the filter. If it is there (usually the case) then iterate over those nodes checking that they are in the graph rather than iterating over the graph and checking if the nodes are in the filter.  I hope to have a PR by the weekend that would fix it.

If you need it quickly, look for the ```__iter__``` method in ```FilterAdjacency``` (about line 325 of coreviews.py).  Add the following two lines before the currently one-line body of that method.

            if hasattr(self.NODE_OK, 'nodes'):
                return (n for n in self.NODE_OK.nodes if n in self._atlas)

Thanks again for this report!

**Comment by daefresh** [comment]
Thanks @dschult I'll look for the PR and try out this fix. Thanks!
