### ISSUE TITLE
Nonexistent functions referred to in the tutorial

### ISSUE THREAD

**Issue by jdjohnston** [networkx/networkx#2849]
In point 1 of the "Graph generators and graph operations" section of the [tutorial](https://github.com/networkx/networkx/blob/master/doc/tutorial.rst), the last 2 functions, `convert_to_undirected(G)` and `convert_to_directed(G)`, do not exist in networkx. Of course, `to_undirected(G)` and `to_directed(G)` are available.

While I'm here, could someone explain why the functional versions of `to_*directed()` generate views while the graph methods generate copies by default?

**Comment by dschult** [comment]
Thanks for this!   It's always good to have a tutorial that is actually correct. :)

The various versions of ```to_*directed``` should probably always generate views (views are easy for the user to copy if needed. But the methods have defaulted to copies since before views (or even generator expressions) existed. We have left them that way for backward compatibility and perhaps somewhat due to lack of attention. Your question  helps with that.
