### ISSUE TITLE
DiGraph.copy() does not preserve subclassing

### ISSUE THREAD

**Issue by fritzo** [networkx/networkx#2889]
To reproduce,
```py
class X(DiGraph):
    node_dict_factory = collections.OrderedDict

assert X().node_dict_factory == collections.OrderedDict
assert X().copy().node_dict_factory == dict
```
To fix
```diff
  def fresh_copy(self):
-     return DiGraph()
+     return type(self)()
```
I have not checked, but I assume this broken pattern occurs elsewhere in networkx

**Comment by dschult** [comment]
Unfortunately, ```type(self)()``` does not work for graph views (subgraphs, etc). So this fix will break many parts of NetworkX.  The better approach is to redefine ```fresh_copy``` in the new subclass:

    class X(nx.DiGraph):
        node_dict_factory = collections.OrderedDict
        def fresh_copy(self):
            return X()

If there is a better class inheritance structure that would get around the need for ```fresh_copy``` I would like to hear about it. Currently, the Views are subclasses of the base Graph classes.

**Comment by jbarnoud** [comment]
Are the correct steps for subclassing a graph documented somewhere? The pages for each type of graph has a section on subclassing, but it does not mention `fresh_copy`.

What would be the steps to follow to have a subclass of `Graph` that does not have its method revert back to the parent class? From a quick look at the code I see that I would need to:
* write a new version of `graphviews.SubGraph`, and `graphviews.GraphView` to subgraph the orrect class;
* overwrite `G.fresh_copy`;
* overwrite `G.subgraph` to return the new `SubGraph`;
* overwrite `G.copy` to return the new `GraphView` when the "as_view" argument is `True`;

Am I missing something? Could the classes to use as `SubGraph` and `GraphView` be class attributes in the way `node_dict_factory` is? This would allow avoid to rewrite `G.subgraph` and `G.copy`.

**Comment by dschult** [comment]
Thank you for this direct question on this issue -- I believe many subclasses will only need to overwrite ```fresh_copy``` to return an empty version of itself. The Views will often work. But it depends what you change when building your subclass.  Presumably you aren't changing how edges or nodes are reported, but perhaps you are. In this case, all bets are off and you may have to rewrite the whole class -- or much of it (see e.g. MultiGraph for an example).  Most of the time you are adding features beyond what is offered for Graph and leaving the graph theory aspects of Graph the same. Then overwrite ```fresh_copy``` should be enough.  If the parts of GraphView that overwrite Graph methods are going to be changed, then you would have to subclass the GraphView and SubGraph class as you describe.

Unfortunately I don't think there is a single answer to your question. It depends on what features of the Graph class you are changing. Still, I think most cases that leave the graph theory parts of Graph the same will only need to replace ```fresh_copy```.

**Comment by jbarnoud** [comment]
The problem I see with the views is that they inherit from a specific graph class. Even if the graph logic is untouched in the subclass, the subclassing itself is lost with the view. One demonstration of this is to make a copy of a view, even with the existing subclasses:

```python
graph = nx.OrderedGraph()  # OrderedGraph
graph.add_nodes_from(range(10))
subgraph = graph.subgraph([2, 3, 4])  # SubGraph
graph_copy = subgraph.copy()  # Graph
```

In the example above, we expect `graph_copy` to be an instance of the same class as `graph`, but because `SubGraph` subclasses `Graph` and not `OrderedGraph`, `graph_copy` is an instance of `Graph`.

The same goes for `GraphView` for the same reasons:

```python
graph = nx.OrderedGraph()  # OrderedGraph
graph.add_nodes_from(range(10))
graph_view = graph.copy(as_view=True)  # GraphView
graph_copy = graph_view.copy()  # Graph
```

Finally, for the same reason, views do not make available the additional method a subclass may have:

```python
class MyGraph(nx.Graph):
    def my_method(self):
        print('I am a ustom method.')
    
    def fresh_copy(self):
        return MyGraph()


graph = MyGraph()
graph.add_nodes_from(range(10))
graph.my_method()

graph_view = graph.copy(as_view=True)
# graph_view.my_method()  not available

graph_copy = graph_view.copy()
# graph_copy.my_method()  not available
```

With the way views are implemented, I do not see an other way than have a custom version of `SubGraph` and `GraphView` for every subclass.

One way around the issue would be to have views not be subclasses, but wrapper that use `__get_attr__` magic to emulate the underlying graph object.

**Comment by jbarnoud** [comment]
I had a deeper look at the question. My suggestion of having what `SubGraph` and `GraphView` classes declared as class attribute of the graph class cause some cyclic references, and threfore does not work. It implies to reference a class that is not yet declared in the graph object, or to subclass that does not exist yet in the views.

My wrapping suggestion may work, but requires profound changes that are likely not desirable.

I managed some result with a bit of meta programming. In the example bellow, I create a non-functional template for a view class: `MyGraphViewTemplate`. When an instance of a graph is created, the view template is combined with the `ReadOnly` class and the graph class to create a functional view class that subclasses the 3 classes. It is that class that is used in the subsequent method instead of the hard coded class that are used currently.

```python
class MyGraphViewTemplate():
    UnionAdj = nx.classes.coreviews.UnionAdjacency

    def __init__(self, graph):
        if graph.is_multigraph():
            msg = 'Wrong View class. Use MultiGraphView.'
            raise NetworkXError(msg)
        self._graph = graph
        self.root_graph = graph
        while hasattr(self.root_graph, '_graph'):
            self.root_graph = self.root_graph._graph
        self.graph = graph.graph
        self._node = graph._node
        if graph.is_directed():
            self._adj = self.UnionAdj(graph._succ, graph._pred)
        else:
            self._adj = graph._adj


class MyGraph4(nx.Graph):
    view_factory_template = MyGraphViewTemplate
    
    def __init__(self, incoming_graph_data=None, **attr):
        super().__init__(incoming_graph_data, **attr)
        self._view_factory = type(
            '{}View'.format(self.__class__.__name__),  # name
            (self.view_factory_template,  # base classes
             nx.classes.coreviews.ReadOnlyGraph,
             self.__class__),
            {}  # class attributes
        )

    def my_method(self):
        print('I am a custom method.')
    
    def fresh_copy(self):
        return MyGraph4()
    
    def copy(self, as_view=False):
        if as_view is True:
            return self._view_factory(self)
        G = self.fresh_copy()
        G.graph.update(self.graph)
        G.add_nodes_from((n, d.copy()) for n, d in self._node.items())
        G.add_edges_from((u, v, datadict.copy())
                         for u, nbrs in self._adj.items()
                         for v, datadict in nbrs.items())
        return G


graph = MyGraph4()  # MyGraph4
graph.add_nodes_from(range(10))
graph.my_method()

graph_view = graph.copy(as_view=True)  # MyGraph4View created for that instance of MyGraph4
graph_view.my_method()
print(type(graph_view))

graph_copy = graph_view.copy()  # MyGraph4
graph_copy.my_method()
```

In this example, the creation of the view class from the template is done in the `__init__` of `MyGraph4`. Ideally, it should be in the `__init__` of `nx.Graph` instead, so that all the subclasses can benefit from it.

This approach should be as flexible as what is used currently. A type of graph that needs to change the logic of the view can define a new template and declare it with the `view_factory_template` class attribute.

One thing that is not ideal is that a view class is created for each instance. It may be fixed by using a metaclass that would create the view class only once per subclass.

The main point of the approach is that it streamlines the subclassing. In the example above I had to include quite some code in `MyGraph4` to implement the new logic, but subclassing from it looks like:

```python
class MyGraph5(MyGraph4):
    def my_method_from_5(self):
        print('I am an **other** custom method!')
    
    def fresh_copy(self):
        return MyGraph5()


graph = MyGraph5()
graph.add_nodes_from(range(10))
graph.my_method()
graph.my_method_from_5()

graph_view = graph.copy(as_view=True)
graph_view.my_method()
graph_view.my_method_from_5()
print(type(graph_view))

graph_copy = graph_view.copy()
graph_copy.my_method()
graph_copy.my_method_from_5()
```

If this approach is not deemed to crazy, I can work on a PR to fix the ability to subclass graphs.

**Comment by dschult** [comment]
There are some reasonable ideas above -- but tricky to implement. I'll take a look at it in more detail. If you have code/ideas/tests that would be helpful.

**Comment by dschult** [comment]
Thanks for this.  The new GraphViews should allow subclasses more easily now.  Try it out!
