### ISSUE TITLE
nx.write_gpickle and nx.read_gpickle not implementing os.PathLike

### ISSUE THREAD

**Issue by ryanpeach** [networkx/networkx#2942]
If you use pathlib in python3, networkx.write_gpickle and networkx.read_gpickle will not accept these as paths.

**Comment by ryanpeach** [comment]
This is easily fixable (I think) just by using str(x) whenever you expect a string path.

**Comment by dschult** [comment]
Each of these functions uses the ```@open_file``` decorator to determine if the argument is a string-like name of the file or a file object. Your suggestion would lead to a change in that decorator so that if it is a pathlib object, a reasonable file object is created.

Would you be able to take a look at open_file and see if there is a good way to identify the argument as a pathlib object? Then pathlib would work for all networkx functions.

**Comment by dschult** [comment]
Actually, I think it might be better/faster/cheaper just to have the user put ```str(p)``` when they are calling the function, instead of adding a bunch of code to NetworkX which would eventually need to be changed to keep up with pathlib. The pathlib library helps you manipulate the path, but when you want to use it you turn it into a string by using ```str```.  

So I think I will close this issue in favor of leaving specific code out of networkx and instead requiring the user to turn the argument into a string before calling these functions.

**Comment by ryanpeach** [comment]
I think keeping up with pathlib is pretty important, as it's a base package and is trying to create a standard for how to handle paths in python. Part of python 3 compatibility should be compatibility with all base packages and compatibility with PEP paradigms.

**Comment by dschult** [comment]
I agree with keeping up with all base packages. But isn't the proper use of pathlib to turn it into a string when you want to use it?

**Comment by ryanpeach** [comment]
I'm not sure I can cite the book, but my impression was that anything that implements os.pathlike should be considered a path, so any modules that take paths should handle things that are pathlike.

**Comment by ryanpeach** [comment]
I understand that it's easy on either the user or the developer end just by calling str, but sometimes it's hard to know as a user which methods can take pathlikes and which require strings. So slowly identifying and converting anything that cant take pathlikes will improve user experience in the distant future when 3.6 is the new 2.7

**Comment by ryanpeach** [comment]
It's also been awhile but I think I recall opening this issue bc when I was debugging some code where I passed a pathlike to networkx it gave some horrid traceback that took a bit to realize what was wrong. So at least maybe we should add a typecheck assert. But at that point it's just as easy to cast to string.

**Comment by dschult** [comment]
OK... I put together an unsatisfying workable version.  Unsatisfying because pathlib objects should really be sent to ```open``` directly. But that doesn't work for python 3.4 or 3.5.  So casting to ```str``` is what I'm doing. Also, checking for patlib by looking for attr ```resolve``` because ```__fspath__``` is not present on py34 or py35.

**Comment by ryanpeach** [comment]
Perhaps we could do a python version check inline with the type checking to make it more "satisfying" lol?

Let me know if I can help, and thank you for your consideration.

**Comment by ryanpeach** [comment]
Awsome, very clean.
