### ISSUE TITLE
Transitive reduction is inefficient + improvement proposal

### ISSUE THREAD

**Issue by JasperNL** [networkx/networkx#3032]
I found that the current implementation of transitive reduction is very inefficient, while it can be solved in O(n^omega) assuming the transitive closure is known. In my own code I'm dealing with this as follows.

```python
import numpy as np
import networkx as nx

g  # NetworkX DiGraph, assuming it's transitively closed (or first call nx.dag.transitive_closure(g))
m = nx.adjacency_matrix(g).todense().astype(bool)  # Conversion to dense may be slow.
m &= ~(m @ m == m)  # When you can reach a node from another node in both 1 and 2 steps, remove arc.
# Now create the digraph again, if needed.
```

I'd love to create a pull-request for a proposed different method, but this uses a conversion to a numpy dense adjacency matrix. Any information is discarded like labelling, and that's an unwanted side-effect. Also multi-edges are discarded.

What are your thoughts on this?

**Comment by dschult** [comment]
Your algorithm looks simple and indeed is described in [wikipedia's article on transitive reduction](https://en.wikipedia.org/wiki/Transitive_reduction) and boolean matrix multiplication.  However, simple to describe does not mean efficient.  

Can you explain what you mean by efficient in this case? Also what is omega (and n) in O(n^omega)?

You have to create a dense matrix which uses lots of RAM and then do matrix multiplication, which might theoretically be order O(n^2.37...) but I doubt that numpy gets to that level -- probably similar to O(n^3).

Most networks of practical interest as networks are sparse. The wikipedia section on complexity in the sparse case describes the algorithm we intend to implement in NetworkX. It is O(n*m) where n in number of nodes and m is number of edges. Even for dense networks (m=n^2) so this is O(n^3) too. For sparse networks, it is much closer to O(n^2). Looking at the code, it is not clear to me that we have achieved this complexity, but I didn't look at it very long. Do you have reason to believe our implementation is not optimal, or does not follow the algorithm for sparse networks described in the link?

I wouldn't worry about discarding information -- the user still has the original graph. And multiedges are a special case. The question is whether our algorithm is O(n*m). And whether your boolean matrix multiplication is efficient.

**Comment by JasperNL** [comment]
I've tried applying the algorithm to graphs with between 400 and 1200 nodes. The graph that I'm considering is transitively closed, but it becomes sparse as soon as the transitive reduction is known. Because it's transitively closed, the number of arcs is enormous. Assuming dfs_edges is O(|V|+|E|), your implementation would indeed give O(|V|^2 (|V|+|E|)). As my initial graph resembles |E| = O(|V|^2), making the whole similar to O(|V|^4) instead of the |V|^omega that would be necessary. 

Omega is in this case the theoretical lower bound on matrix multiplication, hence >2, <= 2.37, but regular implementations are just normal matrix multiplications, so we can say omega = 3. Indeed, NumPy will simply do |V|^3.

In terms of running times, the numpy-implementation takes less than a second on my instance, while the NetworkX variant takes more than 2 minutes to complete. I believe this is not only due to the asymptotic improvement to O(|V|^3), but mainly due to the Python overhead. Many operations are performed on sets, which requires a lot of random reads, which is not very efficient when considering swaps from RAM to the CPU cache. Numpy caches chunks of the array when multiplying. 

I did not compare your code to the proposed code on wikipedia for sparse graphs, mainly because my input graphs were far from sparse.

I certainly believe your implementation may work faster on input graphs that are sparse, but I did not test that. If the number of nodes becomes lots larger, the numpy-approach will also not be feasible because of the required RAM. I'm not sure if SciPy may work well in this case. 

All in all, I think it's questionable which approach is more efficient, and both approaches may have pros and cons. What I think is certain is that dense graphs are better off with the proposed numpy-implementation. It may be a good idea to implement both, for instance adding a `transitive_closed_dense(G)`?

**Comment by dschult** [comment]
I thought the implementation described in wikipedia is O(n*m), so in this case O(|V| (|V|+|E|)) and Not O(|V|^2 (|V|+|E|)) as you describe.  Then the whole process for dense networks is O(n^3) because m=n^2. This should be the same complexity as the matrix implementation.

But, I'm concerned that our implementation is not actually doing what it should -- I mean that it seems to be doing more work than needed.  The code says:

        for u in G:
            u_edges = set(G[u])
            for v in G[u]:
                u_edges -= {y for x, y in nx.dfs_edges(G, v)} 
            TR.add_edges_from((u, v) for v in u_edges)

Forget for a moment that ```u_edges``` should be named ```u_nbrs```. This seems to compute the depth-first-search for each node v many times. That is ```G.in_degree(v)``` times. It should be much faster to compute ```{y for x, y in nx.dfs_edges(G, v)}``` once for each ```v``` and store it. I believe this could be done using a more efficient ```dfs_*``` function too -- because we don't need the edges -- only the nodes -- but I haven't checked that out thoroughly.

For a dense network I think this means we have implemented O(n^4) instead of O(n^3) as intended.

I would prefer to get this algorithm correct before implementing a matrix based version that would be the same complexity for dense networks as this intends to be and worse for sparse networks.  If it is true that a dense version of this function would be better then we should include that as an alternative function.  And certainly we should include your 4 line implementation in the doc_string if it doesn't get implemented. It's so simple and intuitive!

Do you have code to time the various versions? Can we easily insert a scaling of the network -- say doubling the number of nodes while keeping density approximately the same. Then we could get the complexity of the actual function rather than the algorithm.   :)

**Comment by dschult** [comment]
If you do try to time these codes, could you try this version of transitive reduction:

    TR = nx.DiGraph()
    TR.add_nodes_from(G.nodes())
    long_connections = {}
    for u in G:
        u_nbrs = set(G[u])
        for v in G[u]:
            if v not in descendants:
                descendants[v] = {y for x, y in nx.dfs_edges(G, v)}
            if v in u_nbrs:
                u_nbrs -= descendants[v]
        TR.add_edges_from((u, v) for v in u_nbrs)
    return TR

Thanks very much!

**Comment by JasperNL** [comment]
Hi dschult,

I do not have a benchmark script, but on my instance graphs I find that the proposed code above is significantly faster -- in the manner of a fraction of a second to a few seconds on beforehand transitively closed graphs with 300~2000 nodes. On my instance the numpy-variant is still faster, but that's probably due to the denseness of my graph.

I can also verify that the resulting adjacency matrices are the same as mine, so presumably the code is correct.

Thanks!
