### ISSUE TITLE
Enhance Networkx Performance with Cython (or equivalent)

### ISSUE THREAD

**Issue by Jacobe2169** [networkx/networkx#3059]
Hi everyone,

I'm a Ph.D. student in Computer Science, and as part of my work, I'm using Networkx a lot. Unfortunately, even if Python is brilliant language, Python can be slow... However, certain "framework" intended to ease the dialog between C/C++ and Python. Which leads to my question: Do Networkx main contributors consider implement part  #of Networkx in C/C++ ?

**Comment by dschult** [comment]
Yes -- we have spent many hours over the years looking at this.

:rant:  Python can be slow for some tasks, but it has some surprisingly fast data structures.
You need to choose of course, but the tradeoff between people-time and computer
time is quite real. When the questions being asked are changing faster than the development
time for the C programs, it makes good sense to value people-time first.
 :end-of-rant:

We haven't found a useful way to make a C/C++ interface for NetworkX work in general. 
Once you make it general enough, it is better to keep it in python.  My suggestion for your
development pipe-line is to write it in python. Do some simple cases. Do some harder cases.
Once you see what you want and how much time it will take, try to speed it up. Do the following steps and stop when your problem can be done in the time you really need it by. Don't get sucked into making something work optimally if you don't need to. Profile your code to find the bottlenecks.  

- Use Cython first with no changes to the python code.
- Find the slow parts and use Cython to speed up those bottlenecks that take time. Inner loops are quite effective.
- rewrite the inner loops/bottlenecks in C/C++.  Actually this can almost always be done at the previous bullet since Cython allows C code to mix with the python.

**Comment by Jacobe2169** [comment]
Thank you for that clarification :) Actually, I'm already using cython + networkx to implement my algorithms :) 

PS. : Nevertheless, I still hope that one day, brave developers will integrate a bit of C/C++ in networkx ;)
