### ISSUE TITLE
`view_pygraphviz` fails for a `path` that is `str`

### ISSUE THREAD

**Issue by aanastasiou** [networkx/networkx#3060]
In the following, `view_pygraphviz` works fine:

    import networkx
    G = networkx.generators.trees.random_tree(100)
    networkx.drawing.nx_agraph.view_pygraphviz(G, prog="dot", args="-Nshape=box");

But when you try to specify the `path` which is supposed to be a `str`...

    import networkx
    G = networkx.generators.trees.random_tree(100)
    networkx.drawing.nx_agraph.view_pygraphviz(G, path="mytest.png", prog="dot", args="-Nshape=box");

...it raises `TypeError: write() argument must be str, not bytes` from within `pygraphviz/agraph::draw()`.

Now, if you:

    import networkx
    G = networkx.generators.trees.random_tree(100)
    A = networkx.drawing.nx_agraph.to_agraph(G)
    A.draw("mytest.png", prog="dot")

This will work fine, minus of course the specific formatting (graph, edge, node appearance) that `networkx` adds in `view_pygraphviz`.

Therefore, the "problem" must be in `view_pygraphviz`.

After a bit of experimentation, it turns out that this works:

    import networkx
    G = networkx.generators.trees.random_tree(100)
    networkx.drawing.nx_agraph.view_pygraphviz(G, path=open("mytest.png", "w+b"), prog="dot", args="-Nshape=box");

The hint to pass a file descriptor rather than a `str` was obtained from [the documentation](https://github.com/networkx/networkx/blob/master/networkx/drawing/nx_agraph.py#L425), specifically *"# Assume the decorator worked and it is a file-object."*.

Is this a bug? If not, which decorator does this function hint at?

**EDIT:**

Netowrkx version 2.1, Python version 3.5.2

**Comment by dschult** [comment]
The decorator is ```open_file``` (it appears in the line before the function signature ```def ...``` with an ```@``` in front.  The decorator is defined in ```networkx/utils/decorators.py``` and opens the file if needed, or passes the file object through otherwise.

You have clearly found a work-around for the error. But it'd be nice to fix this...

In looking at both this code and the code for pygraphviz, it looks like we should have the decorator specify mode ```'w+b'```.  But I'm not close to machines that can easily test whether this works for the different cases and versions of OS/python/etc.  Can you easily verify that changing the 'w' to 'w+b' in the ```@nx.utils.open_file``` decorator fixes this bug?
