### ISSUE TITLE
Reduction of memory footprint possible?

### ISSUE THREAD

**Issue by ju-w** [networkx/networkx#3064]
I am working on a project with a graph that has multiple millions of edges. 
(Around 5 mill nodes, 60 mill. edges.)

I am already using the Thin Graph:

```python
class ThinGraph(nx.Graph):
    all_edge_dict = {'weight': 1}
    def single_edge_dict(self):
        return self.all_edge_dict
    edge_attr_dict_factory = single_edge_dict
```

and my graph is using around 10 GB of memory.

Is there a way to further reduce the memory consumption?

**Comment by dschult** [comment]
That size network should not be a problem... but it depends on what your nodes are and what attributes you store.  Since you are using ThinGraph, you aren't storing edge attributes. So the first question I'll ask is:  What objects are your nodes?

They should be integers to reduce memory usage.  Other objects close in since to integers will work too. Strings and more complex objects can end up using a lot of memory, though I don't completely understand why.   You can try to build the graph with integer nodes (while storing a list of nodes for each integer) or if . you've already got the graph (and the memory), use [nx.convert_node_labels_to_integers](https://networkx.github.io/documentation/latest/reference/generated/networkx.relabel.convert_node_labels_to_integers.html)

**Comment by ju-w** [comment]
Yes, I am using Ints as Ids. Currently I'm just using a random Graph to get a grasp on the performance. Kind of like this:

```python
G = ThinGraph()
for _ in range(60*10**6):
    G.add_edge(random.randrange(5*10**6), random.randrange(5*10**6))
```

The performance is ok, as long as memory does not get swapped. I'm on a machine with 16GB, so I already run into issues.

**Comment by dschult** [comment]
Ahh -- sorry, I read your original as 6 million instead of 60 million.  yes, I suspect you could be running into trouble even with the ThinGraph if you have 16MB.

Think of it this way: if you have to store two numbers per edge. Then you need 120M numbers. which gets you to 1GB just to point to the numbers (8 byte pointers on 64-bit machines). So after including the adjacency dict structures themselves (240 bytes per dict overhead) and the 28 bytes per number for storing the numbers, I'm not surprised you are getting up near 10GB.
