### ISSUE TITLE
draw relative distance of Graph

### ISSUE THREAD

**Issue by GoingMyWay** [networkx/networkx#3078]
In networkx, how can I draw a plot showing the relative distance of edges?  The test code is

```
G = nx.Graph()
G.add_edge(0, 1, length=2)
G.add_edge(1, 2, length=9)
G.add_edge(0, 2, length=15)
pos = nx.spring_layout(G)
length = nx.get_node_attributes(G, 'length')
```

**Comment by ericmjl** [comment]
By "relative distance of edges", do you mean plotting the distribution of lengths? 

If so, then to start with, you are getting node attributes rather than edge attributes, so I would first make sure you have:

```python
length = nx.get_edge_attributes(G, 'length')
```

Then, plot the cumulative distribution as follows:

```python
import numpy as np
import matplotlib.pyplot as plt

def ecdf(data):
    x, y = np.sort(data), np.arange(1, len(data)+1) / len(data)
    return x, y

fig = plt.figure()
ax = fig.add_subplot(111)
x, y = ecdf(length)
ax.scatter(x, y)
```

I recommend the cumulative distribution for the reasons listed in [my blog post](https://ericmjl.github.io/blog/2018/7/14/ecdfs/).

On the other hand, if you are trying to show the edge weights on a drawing of the graph, then that is different:

```python
nx.draw(G, pos=nx.spring_layout(G))
nx.draw_networkx_edge_labels(G, pos=nx.spring_layout(G), edge_labels=length)
plt.show()
```

**Comment by GoingMyWay** [comment]
I really appreciate your answer, but that is not I want.

I want to draw a graph so that there is a label on each edge showing the length of each edge,  the plot should show length between nodes since edge has its corresponding length.

There is a simliar [question](https://stackoverflow.com/questions/51464123/how-to-draw-length-of-graph-in-networkx) on SO.

**Comment by ericmjl** [comment]
@GoingMyWay according to what you've described, the bottom part of my first response is exactly what you'll need then -- try it out! I'll close this issue, feel free to reopen if it still isn't what you need.

**Comment by GoingMyWay** [comment]
@ericmjl Thank you, but I don't want a distribution of length.

```
G = nx.Graph()
G.add_edge(0, 1, length=3)
G.add_edge(0, 2, length=4)
G.add_edge(1, 2, length=5)
nx.draw(G, pos=nx.spring_layout(G))
nx.draw_networkx_edge_labels(G, pos=nx.spring_layout(G), edge_labels=length)
plt.show()
```
And I got

![image](https://user-images.githubusercontent.com/9346460/43052341-7d94b482-8e57-11e8-8fe1-863f8da5f081.png)

But the length in the plot is the same, they have different length, the plot should show the length. If you draw the map of America with networkx, the length between NY and DC is smaller than that between DC and LA in the plot.

**Comment by dschult** [comment]
I believe your question is not well-formed.  If you have node positions (an embedding), NetworkX can draw the graph with the nodes in those positions.  So I assume you don't have node positions. If you don't have node positions, but you want each distance to equal the length attribute of each edge, then for almost all cases, the graph can't be embedded in two dimensions.  You need many dimensions.

When networkx draws the map of the US, it starts with the positions of NY and DC and computes the lengths.  It would be a hard problem to find the positions of the cities if all you are given is the distances.

So, yes, NetworkX does not provide this functionality.  But I think you are probably looking for the wrong solution to your problem. :)

**Comment by ericmjl** [comment]
@GoingMyWay thanks for looping back.

Just a small point to clarify, the following code block doesn't give you a distribution of lengths:

```python
In [8]: G = nx.Graph()
   ...: G.add_edge(0, 1, length=2)
   ...: G.add_edge(1, 2, length=9)
   ...: G.add_edge(0, 2, length=15)
   ...: pos = nx.spring_layout(G)
   ...: length = nx.get_edge_attributes(G, 'length')
   ...:
   ...: nx.draw(G, pos=nx.spring_layout(G))
   ...: nx.draw_networkx_edge_labels(G, pos=nx.spring_layout(G), edge_labels=length)
   ...:
   ...: plt.show()
```

![figure_1](https://user-images.githubusercontent.com/2631566/43083937-a02bb0fa-8e65-11e8-9ba1-caef641bd21a.png)

And to illustrate what happens when we try to respect the weights using a Kamada-Kawaii (force-directed) layout:

```python
In [9]: G = nx.Graph()
   ...: G.add_edge(0, 1, weight=2)
   ...: G.add_edge(1, 2, weight=9)
   ...: G.add_edge(0, 2, weight=15)
   ...: length = nx.get_edge_attributes(G, 'weight')
   ...:
   ...: nx.draw(G, pos=nx.kamada_kawai_layout(G))
   ...: nx.draw_networkx_edge_labels(G, pos=nx.kamada_kawai_layout(G), edge_labels=l
   ...: ength)
   ...: plt.show()
```

![figure_1](https://user-images.githubusercontent.com/2631566/43084006-ce684abe-8e65-11e8-9b19-57262e839254.png)

As you can see, it is impossible in a 3-node system to accurately represent all edge weights simultaneously using the built-in force-directed layout. Even if I change one of the weights, the layout fundamentally remains the same:

![figure_1](https://user-images.githubusercontent.com/2631566/43084115-095437f0-8e66-11e8-8509-ec3db59b71b4.png)

As such, I agree with @dschult. If you want to draw the map of America with networkx, you have to pre-compute the node positions with longitude and latitude. More generally, my personal sense is that to rationally view a graph (beyond a random/hairball layout), it is important to first prioritize the position of nodes, instead of using edge weights as a surrogate for positioning the nodes. As @dschult mentioned, this ends up requiring more than 2 dimensions to have everything computed correctly. 

If you're looking to do basic geographic graph viz, I am developing a declarative interface for geographic graph viz in [nxviz](https://github.com/ericmjl/nxviz/). There is a branch, [geoplot](https://github.com/ericmjl/nxviz/tree/geoplot), which you can install from GitHub (the interface for matplotlib is complete; the altair implemention is not done). Once I have finished the altair implementation, I will cut a new release to PyPi and conda-forge. An example, from the Chicago divvy dataset, is shown below, with code:

```python
g = GeoPlot(G_new,
            node_lat='latitude',
            node_lon='longitude',
            node_color='dpcapacity',
            node_size=0.005)
```

An example of the data stored on each node:

```
(5, 
 {'name': 'State St & Harrison St', 
 'latitude': 41.87395806, 
 'longitude': -87.62773949, 
 'dpcapacity': 19, 
 'landmark': 30, 
 'online date': Timestamp('2013-06-28 00:00:00')
 }
)
```

![figure_1](https://user-images.githubusercontent.com/2631566/43083542-c509a6e4-8e64-11e8-8905-b0998967e01d.png)

I intend for nxviz to be a seaborn-like viz library to "get a first-pass feel" for your graph data. If you need more complicated geospatial analysis tools, that would be out of scope for nxviz.
