### ISSUE TITLE
why didn't implement katz score in link prediction?

### ISSUE THREAD

**Issue by tz28** [networkx/networkx#3093]
hi,
why didn't implement katz score in link prediction? is it because  computational complexity of Katz score is high and it  is not suitable for large-scale network?

**Comment by itsshavar** [comment]
Hi,
I want to add some more link prediction algorithm such as Katz and CCPA (https://www.nature.com/articles/s41598-019-57304-y) recently published in Nature Scientific Reports. 
CCPA is an advance feature based algorithm with less complexity and better accuracy so that will be a good addition.

**Comment by tz28** [comment]
> Hi,
> I want to add some more link prediction algorithm such as Katz and CCPA (https://www.nature.com/articles/s41598-019-57304-y) recently published in Nature Scientific Reports.
> CCPA is an advance feature based algorithm with less complexity and better accuracy so that will be a good addition.

that's great work.

**Comment by tz28** [comment]
> Hi,
> I want to add some more link prediction algorithm such as Katz and CCPA (https://www.nature.com/articles/s41598-019-57304-y) recently published in Nature Scientific Reports.
> CCPA is an advance feature based algorithm with less complexity and better accuracy so that will be a good addition.

great work

**Comment by rossbar** [comment]
AFAICT this issue has been addressed: both Katz centrality and CCPA are now available as `nx.katz_centrality` and `nx.common_neighbor_centrality`, respectively.

There may be other more specific questions, like why `katz_centrality` is implemented in the centrality package while `common_neighbor_centrality` is implemented in the link_prediction package, but this should be a relatively minor concern especially from the user's perspective since both functions are available in the top-level namespace.

If I've missed something or there are further suggestions on how things could be reorganized, please feel free to reopen this or open a new issue with specific suggestions!
