### ISSUE TITLE
top-level "tests" import necessary?

### ISSUE THREAD

**Issue by speleo3** [networkx/networkx#3106]
The [top level module](/networkx/networkx/blob/master/networkx/__init__.py) imports `networkx.tests` on line 126:
```python
from networkx.tests.test import run as test
```
Is this necessary or relevant?

While bundling up a lightweight Python environment I removed all `lib/python*/site-packages/*/tests` directories and noticed that `networkx` was the only package that broke.

**Comment by dschult** [comment]
Well... unfortunately we called our module ```tests``` instead of something more private like ```tester``` or ```_tests```.  We should probably fix this naming issue while ding #3102 .  Thanks for pointing this out.

To directly answer your question -- this import is relevant to be able to run the tests on the package. Something like it appears in each of the packages that you probably use. But they use a different naming scheme.  For example numpy creates the test function using the module ```_pytesttester```.

If you don't plan to use the ```test``` function you can safely remove that import statement. We will work to fix the naming issue of a module named ```tests.py``` in a coming release -- though probably not v2.2 as that is close to completion.

**Comment by speleo3** [comment]
Thanks for the prompt reply. So this could be as simple as moving `tests/test.py` to `testing/test.py`?

Tackling #2900 (lazy loading) would also help.
