### ISSUE TITLE
steiner_tree should accept MultiGraph

### ISSUE THREAD

**Issue by tomalrussell** [networkx/networkx#3155]
I'm using `steiner_tree` on a road network which may have multiple edges between nodes. 

It looks like `steiner_tree` will fail if passed a `MultiGraph`:
- as a next-to-last step, edges are generated as `(u, v)` tuples pairwise [here](https://github.com/networkx/networkx/blob/master/networkx/algorithms/approximation/steinertree.py#L87)
- before being passed to `G.edge_subgraph` which raises a `ValueError` from `nx.filter.show_multiedges`

This should reproduce the issue:

```python
import networkx as nx
import networkx.algorithms.approximation as nxa

def test_simple_steiner_tree():
    G = nx.Graph()
    G.add_weighted_edges_from([
        (1, 2, 1),
        (2, 3, 1),
        (3, 4, 1),
        (3, 5, 1)
    ])
    terminal_nodes = [2, 4, 5]
    expected_edges = [
        (2, 3),
        (3, 4),
        (3, 5)
    ]
    T = nxa.steiner_tree(G, terminal_nodes)
    assert list(T.edges) == expected_edges

def test_multi_steiner_tree():
    G = nx.MultiGraph()
    G.add_weighted_edges_from([
        (1, 2, 1),
        (2, 3, 1),
        (2, 3, 999),
        (3, 4, 1),
        (3, 5, 1)
    ])
    terminal_nodes = [2, 4, 5]
    expected_edges = [
        (2, 3, 0),
        (3, 4, 0),  # first edge has weight one
        (3, 5, 0)
    ]
    T = nxa.steiner_tree(G, terminal_nodes)

test_simple_steiner_tree()  # passes
test_multi_steiner_tree()  # throws ValueError 
```

The quick fix might be to add `@not_implemented_for('multigraph')`. 

For my current purposes, the following does the trick to handle the `MultiGraph` case:

```python
# get unique links pairwise (u, v)
links = set(chain.from_iterable(
    pairwise(d['path'])
    for u, v, d in mst_edges
))

# for each link in the chain
multi_edges = []
for u, v in links:    
    # consider each edge  between the pair of nodes,
    # keeping track of the one with the minimum weight
    # (there may be a better way - convenience functions/accessors?)
    num_edges = G.number_of_edges(u, v)
    min_k = 0
    min_weight = None
    for k in range(num_edges):
        curr_weight = G.edges[u, v, k][weight]
        if min_weight is None:
            min_weight = curr_weight
        elif curr_weight < min_weight:
            min_weight = curr_weight
            min_k = k
    multi_edges.append((u, v, min_k))

# create subgraph from multi edges - list of (u, v, k)
T = G.edge_subgraph(multi_edges)
```

**Comment by dschult** [comment]
I see how that would fail. It looks like the implications of MultiGraph were not looked at closely.
Your coded solution would not work in general because it assumes a pattern for the edge keys (they are assumed sequential integers starting from 0).  Your suggestion of ```NotImplementedFor``` will certainly fix the surprise nature of the thrown ```ValueError```. 

Another small changes I'd like to see in steiner_tree is a paragraph description of what a steiner tree is in the doc_string.

**Comment by tomalrussell** [comment]
Thanks for the response @dschult - I'd be happy to work on this a little. 

Could be three pieces:
- surprise-reduction fix, adding `NotImplementedFor`
- Steiner tree description in docstring
- (perhaps with a bit more discussion) implementation for MultiGraph

**Comment by dschult** [comment]
That's great!  Thanks...  I'll try to merge the quick-fix before the new release coming up.
We can aim for the MultiGraph implementation in the next release.

**Comment by dschult** [comment]
The currently available ```steiner_tree``` actually computes the correct edges. It just doesn't return the 3-tuple with the edge key.  It returns a 2-tuple and makes you go find which key has the minimum weight for those two pairs of nodes.

This is a similar problem to #3159 where the treatment of MultiGraph was not clear because the edge keys were not returned as part of the edge-tuple. 

I'm going to re-allow MultiGraphs for this function. The code works just fine. It just doesn't return as much information as might be useful. To find the 3-tuple edges from the 2-tuple edges you'll need something like:
```python
def argmin(keydict, weight):
    return min(keydict, key=lambda edgekey: keydict[edgekey][weight]) 

multiedges = [(u, v, argmin(G[u][v], weight)) for u, v in steiner_tree.edges()]
```
I'll add to the docstring to make that more clear.

**Comment by dschult** [comment]
In #4160 I updated the steiner_tree function to provide the desired multigraph tree with edge keys. It passes the test set up when multigraph was marked as "Not Implemented"  So this issue is fixed when that PR gets merged.
