### ISSUE TITLE
dag_longest_path not correctly working for MultiDiGraph

### ISSUE THREAD

**Issue by anishpdoshi** [networkx/networkx#3159]
https://networkx.github.io/documentation/stable/_modules/networkx/algorithms/dag.html#dag_longest_path isn't properly fetching weights from multidigraph edges. I suspect the algorithm would have to be modified a little to account for this, but right now the result is deceptive due to the default_weight property.

**Comment by dschult** [comment]
Please describe what you think is wrong with the way it is handling the weights, or provide a simple example showing the trouble. "isn't properly fetching weights" is too vague to investigate.

**Comment by anishpdoshi** [comment]
Sorry. Let me clarify: In line 654 of https://github.com/networkx/networkx/blob/master/networkx/algorithms/dag.py, there is a line that looks like:
```
us = [(dist[u][0] + data.get(weight, default_weight), u)
              for u, data in G.pred[v].items()]
```
However, this line seems to not work when G is a MultiDiGraph, since data will be a keyed collection of edges from `(u, v)` instead of a single edge. So, `data.get(weight, default_weight)` will always fail to find the weight attribute, and instead default to `default_weight` each time.

Instead, I think that line should also consider the MultiDiGraph case, and I believe a way to do this is to simply choose the edge with maximum weight among all edges from (u, v), since we are interested in the longest path property.

Here's a modified version that illustrated what i mean, though I'm not sure its the best solution.
```
   # edgedata is either a single edge's data, or a keyed collection of edges. 
   def max_edge_weight(edgedata):
      if isinstance(G, nx.MultiDiGraph):
        return max(edgedata[key].get(weight, default_weight) for key in edgedata.keys())
      return edgedata.get(weight, default_weight)

    if not G:
        return []
    dist = {}  # stores {v : (length, u)}
    for v in nx.topological_sort(G):
        us = [(dist[u][0] + max_edge_weight(data), u)
              for u, data in G.pred[v].items()]
        # Use the best predecessor if there is one and its distance is
        # non-negative, otherwise terminate.
        maxu = max(us, key=lambda x: x[0]) if us else (0, v)
        dist[v] = maxu if maxu[0] >= 0 else (0, v)
    u = None
    v = max(dist, key=lambda x: dist[x][0])
    path = []
    while u != v:
        path.append(v)
        u = v
        v = dist[v][1]
    path.reverse()
    return path
```

**Comment by dschult** [comment]
Good -- Thanks!  
Now I see the problem. It looks like other functions in the same module have a similar problem.

Do you want the minimum distance or the max? Seems easy to get that switched.

We could try to fix the functions for MultiGraphs by using ```g.in_edges``` instead of ```g.pred```. Instead, we could allow users to input a ```weight``` function which takes an edge dict and returns the weight. That would allow MultiGraphs to work if the weight function treated it as an edgekeydict keyed by edge key to the data dicts. But I have a preference for marking the function as "not implemented for" MultiGraphs and having the user convert multiedges to single edges separately from the algorithm. It is more effective and controllable if the user handles the conversion manually.  Perhaps we could provide functions to help with that.  What do you think

**Comment by anishpdoshi** [comment]
I personally like the `weight` function idea, as otherwise the caller of the function is forced to switch from a multigraph to a regular graph which may not be ideal or performant. It would also allow callers to define custom weight functions on the fly rather than having to define them as attributes first.

But I think it is simple to integrate into this particular algorithm because of the max() quirk; I'm guessing there are algorithms for which it's not always simple to do. I guess my suggestion would be to try including a `weight` function param for this method, and also explicitly mark algorithms as being supported/unsupported for multigraphs.

**Comment by gibernas** [comment]
What is the status on this? 

I have the same problem while trying to use all_pairs_dijkstra_path_length, and I think it is present in all the functions from shortest_path. It basically makes weighted MultiGraphs unusable.. 

Is there a plan? I could help to fix this

**Comment by dschult** [comment]
The shortest_path functions default (for multigraphs) to using the minimum weighted edge between node-pairs.  Furthermore, all those functions allow weight to be a function ```wt(u,v,datadict)``` which can handle multigraph classes in a very general way. Is this general enough? Would this solve the problem in this issues for longest_path?

Some progress in this realm has been made in the 2 years since this issue was raised. But I'm not sure that it is solved. Take a look at the shortest_path handling of "weight" and MultiGraph. I hope that porting that treatment to this function would be sufficient.

**Comment by gibernas** [comment]
I can explain my problem better: I was using a DiGraph on which I performed a shortest_path using a weight function `wt(u,v,datadict)`. As the weight of the edges depended on some data which was shared between some of the edges, i did not save this in the graph object itself, in order to save quite some memory. in the weight function then i process the `(u,v)` tuple to fetch the data I need from the external dict to compute the weight.

I am now switching to a MultiDiGraph, and the previous process is not possible anymore as the `wt(u,v,datadict)` doesn't know which edge is being processed (we don't have access to the key). 

I feel like with MultiGraphs, `(u,v,key)` should be passed to `wt` instead of just `(u,v)`. I feel like these kind of problems are related to the discussion about typing. I think Edge objects should be passed, and what that actually is depends on the case.

Do you see any solution other than saving all the data on the edges (that would require quite some memory)?

**Comment by dschult** [comment]
I see the confusion. It isn't advertised well, but the ```(u,v,datadict)``` includes ALL the keys.  That is, in this setting for Multi(Di)Graph, ```datadict``` is the edge key dict:  a dict keyed by edge_key to the edge attribute dict for each edge.
So, by default, the weight function for a MultiDiGraph is:
```python
lambda u, v, d: min(attr.get(weight, 1) for attr in d.values())
```

To use the keys you could use:
```python
def mymultiweight(u, v, dd):
    return min(my_function(u, v, ekey, edatadict) for ekey, edatadict in dd.items())
```

**Comment by dschult** [comment]
This issue will be complete when #4114 is finished.
I'm going to close this issue. But feel free to post more for continued discussion. I'll reopen if need be.
