### ISSUE TITLE
Problem in write_shp

### ISSUE THREAD

**Issue by danyuliuyan** [networkx/networkx#3287]
when i export a graph to shp file, i met the problem ' 'int' object has no attribute '__getitem__''

>>> import networkx as nx
>>> g = nx.Graph()
>>> g.add_node(1)
>>> g.add_node(2)
>>> g.add_edge(2,3)
>>> g.add_edge(1,3)
>>> nx.write_shp(g,'/home/zyp/test.shp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/nx_shp.py", line 183, in write_shp
    g = netgeometry(n, data)
  File "/usr/local/lib/python2.7/dist-packages/networkx/readwrite/nx_shp.py", line 139, in netgeometry
    elif type(key[0]).__name__ == 'tuple':  # edge keys are packed tuples
TypeError: 'int' object has no attribute '__getitem__'

**Comment by dschult** [comment]
Verified in Python 3.6 also.

**Comment by danyuliuyan** [comment]
Thanks for your attention. Is there any other way i can export the graph to a shp file?

**Comment by mangecoeur** [comment]
The problem is in this line:

https://github.com/networkx/networkx/blob/acae7c5f771d9646835e34912af79430c147a4a6/networkx/readwrite/nx_shp.py#L221

It indeed assumes the *node* key is also a tuple, even though the comment only mentions edges. It should at least fail gracefully in this case (rather than just erroring trying to index into the key). More useful would be to have options as to what node and/or edge attributes are used to create geometry - e.g. if you already have a `pos` attribute containing position data it would make more sense to use that.

**Comment by dschult** [comment]
The [docs for the write_shp function](https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.nx_shp.write_shp.html) state:
```
Nodes and edges are expected to have a Well Known Binary (Wkb) or
Well Known Text (Wkt) key in order to generate geometries. Also
acceptable are nodes with a numeric tuple key (x,y).
```

So I think there is fair warning(?) maybe?

**Comment by mangecoeur** [comment]
Fair point, it's a bit different compared to how node positions are handled elsewhere (e.g. the pos arg) but ok - threw me a bit but it had been a long day. Could still add a check for the key format to return a slightly clearer error I suppose. 

Ended up diving into the code a bit to see about implementing more options and TBH it's probably not worth reworking the whole thing since a better solution is to export the graph data and use either shapely+fiona or GeoPandas to save GIS files (added bonus that its easy to use other formats).

**Comment by iboates** [comment]
It is worth nothing that there is a devil in the details regarding simple (x, y) notation of coordinates in the geographic domain - a common method of storing unprojected coordinate data (like latitude and longitude) is via [lat, lon], which, when mis-intuitively mapped to a cartesian plane, would actually produce (y, x) coordinates. This is unfortunately a problem that rears its ugly head quite frequently in my experience, due to oversights in one library or another. For that reason I would propose restricting any geographic write functions to requiring WKB or WKT, or potentially even just leaving the work to libraries specifically for geographic data manipulation.
