### ISSUE TITLE
bipartite graph with similarity clustering of the two subgraphs

### ISSUE THREAD

**Issue by diallobakary4** [networkx/networkx#3316]
I would like to implement a weighted bipartite graph with similarity clustering of the two subgraphs. A good example is [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3605000/figure/F1/).
Each subgraph will be clustered according to a similarity matrix. Edges between the two subgraphs will be weighted.  So far we can implement a  spring_layout for a graph using Fruchterman Reingold based on a distance matrix. Also, It is possible do a weighted bipartite graph. I am looking for a way to combine the two approaches in the same layout. 

​Thanks​

**Comment by rossbar** [comment]
I'm going to go ahead an close this one as inactive. It seems like an interesting idea though, so if there's desire to do so, please follow up either by opening a new issue with more details or better yet a PR that encapsulates some of the main ideas. Note that you can open a draft PR so that you don't have to implement everything to start but can get feedback on higher-level ideas.
