### ISSUE TITLE
KeyError: <class 'dict'> when saving DiGraph to graphml

### ISSUE THREAD

**Issue by sbushmanov** [networkx/networkx#3326]
I'm running `networkx 2.2` and I'm trying a very simple example and getting error when saving to a `graphml` format:

```
import networkx as nx
nodes = list("abcdefhjkh")
l = [np.random.choice(nodes,2) for _ in range(100)]
G = nx.DiGraph(l)
dups = [("a","b")]
for dup in dups:
    g = nx.contracted_nodes(G, *dup, self_loops=True)
nx.write_graphml(g, "./g.graphml") # must be g, not H
...
...
...
~/anaconda3/lib/python3.6/site-packages/networkx/readwrite/graphml.py in add_graph_element(self, G)
    652                     attributes[k] = v
    653         for k, v in attributes.items():
--> 654             T = self.xml_type[self.attr_type(k, "node", v)]
    655             self.get_key(make_str(k), T, "node", node_default.get(k))
    656         # Edges and data

KeyError: <class 'dict'>
```

1. There is no error if the graph is undirected or I'm writing to other formats.
2. There is no error if I do not do `contracted_nodes`
3. It seems there were no such an error in networkx 1.x version 

Is this a bug or I am missing something?

**Comment by dschult** [comment]
I'm not sure if this should be called a bug or just an undeveloped / disallowed feature of write_graphml . By the way, I do get this error with an undirected graph. And I think you want your example to write the graph ```g``` and not ```H```.

The code ```g=nx.contracted_node(G,'a','b')``` contracts 'a' and 'b' correctly. But it also adds a node attribute to node 'a' so that ```g.nodes['a']['contraction']``` is ```{b: {}}```.  In other words the contraction attribute holds the node and node data for the node that no longer exists in the graph.

This causes a problem when using ```write_graphml``` because graphml does not support dicts as attributes.  To fix it, remove that attribute -- or replace it so it doesn't use a dict as attribute value. For example, add a line:

    del g.nodes[dup[0]]['contraction']

Or to replace {b:{}} with a tuple of contracted nodes:

    attrs = g.nodes[dup[0]]['contraction']
    g.nodes[dup[0]]['contraction'] = tuple(attrs)
