### ISSUE TITLE
Reversed arrow on the calculation for a directed graph edit distance

### ISSUE THREAD

**Issue by davide1995** [networkx/networkx#3327]
I just wondering why in the follows situation the calculated edit distance is two and not one.

```
import networkx as nx

g1 = nx.DiGraph()
g1.add_edge("a","b")
g1.add_edge("b","c")
g1.add_edge("c","a")

g2 = nx.DiGraph()
g2.add_edge("a","b")
g2.add_edge("b","c")
g2.add_edge("a","c")

edit_distance = nx.graph_edit_distance(g1, g2)
print(edit_distance)
```

I understand that we need to remove an arrow and insert a new one, so it makes an edit distance of two. But why besides addition and deletion, it has not been implemented the reverse cost?
Current situation:
addition = 1
deletion = 1
reverse = deletion + addition

Desired situation:
addition = 1
deletion = 1
reverse = 1

**Comment by dschult** [comment]
The operation "reverse" is not one of the operations allowed when computing edit distance. The definitions I have seen usually stick to insertion, deletion and substitution of nodes. (They sometimes talk about substitution of edges, but can always related that back to substitutions of nodes because: "the matching of the edge structure is uniquely defined via operations which are actually carried out on the nodes" (pg 30 of [this book](https://www.springer.com/cda/content/document/cda_downloaddocument/9783319272511-c2.pdf?SGWID=0-0-45-1545097-p177820399)).  

Why people choose to define it that way I can't say. I believe some people have considered other more exotic edit operations. But I don't know what they were. I think there is a reference to them in the above referenced pdf file.
