### ISSUE TITLE
2.3rc1 drops python 2.7 support in a minor version 

### ISSUE THREAD

**Issue by zdw** [networkx/networkx#3374]
People using  `NetworkX~=2.2` as their version specifier to pip, but still on Python 2.7 will get this message now that 2.3rc1 is out:

```
NetworkX requires Python 3.5 or later (2.7 detected).
```

This happens with no changes to their code. 

Would dropping Python 2.7 support be enough of a change to necessitate a new major version of NetworkX?

**Comment by dschult** [comment]
Hmmm..   I suspect this is happening with many other packages. For example, pandas and numpy both planned to stop supporting python2. Neither plans to change the major release number -- numpy-1.17 will no longer support python2 and Pandas will have 0.24 be the last to support python2.

Maybe it will work for them because of people using ~=0.24.2 which is equivalent to >=0.24.2, == 0.24.*
Maybe we can do the same with people expected to use ~=2.2.0.  But we haven't been using 3 numbers for our releases.

Thoughts?

**Comment by zdw** [comment]
Going to `major.minor.patch` usually implies that that [Semantic Versioning](https://semver.org) is being used.  Is that what you're proposing?

Probably the simplest way to deal with this would be to make a note in the readme or docs about the versioning scheme and forwards/backwards compatibility expectations that a user should have.

**Comment by jarrodmillman** [comment]
Would something like this work for you:
```
We don't use semantic versioning.  The first number indicates that we have
made a major API break (e.g., 1.x to 2.x), which has happened once and probably
won't happen again for some time.  The point releases are new versions and may
contain minor API breakage.  Usually, this happens after a one cycle deprecation
period.  API changes are documented here:
https://networkx.github.io/documentation/stable/release/index.html
```

**Comment by zdw** [comment]
That sounds good. Maybe adding a compatibility matrix like this would also help (numbers are mostly made up):

NetworkX Version | Python Version
------------------ | ----------------
1.x                           | 2.7, 3.4, 3.5
2.0, 2.1, 2.2            | 2.7, 3.5, 3.6, 3.7
2.3                          | 3.5, 3.6, 3.7
2.4                          | 3.7, 3.8

**Comment by jarrodmillman** [comment]
I am less convinced on the compatibility matrix.  That information is already in the release notes, the install instructions, and each released package keeps track of its Python version dependency.  That is already three locations that I have to keep updated.  I am not eager to create yet another location with redundant data, which needs to be kept synchronized.

At any rate, I made a PR to keep the discussion going.  I will keep it open for a day or two to see if we can get any more feedback.

**Comment by dschult** [comment]
I think the main problem specified in this Issue is that using pip with ```~=2.2``` won't work for networkx. Users should stick to other version specifiers like ```==``` and ```>=```. 
Is that an accurate description of the problem?

If so, we could add to the paragraph something like:

    The pip shortcut version specifier syntax ```~=``` won't always work with our numbering system.
    It is better to use syntax such as ```==``` or ```>=```.

I agree that we shouldn't create yet another place to update with version numbers for each release! :}

**Comment by jarrodmillman** [comment]
I don't think there is a good reason to use ``~=`` for networkx, since we don't currently make bug-fix only releases and we make major releases only occasionally.  However, users will run into the same problem if they use ``>=`` instead of ``~=``.  The main difference being that ``>=`` will also run into problems when we make a 3.x release at some point in the future, while ``~=`` won't.

I wouldn't want to be too prescriptive regarding what folks should include in their ``requirements.txt`` files.  Different people use them for different things.  For instance, we currently have a mix of ``==`` and ``>=`` in our requirements files.  I tend to want to see errors quickly so I default to using ``>=``.  If we have known problems, then I tend to switch to ``==`` until the issue is fixed.  Other people might always use ``==`` and only test new releases of their dependencies by hand.

Maybe we could just say something like:
```
Since we don't normally make bug-fix only releases, it may not make sense
for you to use ``~=`` as a pip version specifier.
```

**Comment by dschult** [comment]
Sounds good to me.  Thanks!

**Comment by zdw** [comment]
Agreed - the `~=` as a specifier wasn't a good choice, and made some unfounded assumptions about when versioning compatibility.

**Comment by lissyx** [comment]
It looks like 3.4 was also dropped:
```
    NetworkX 2.3+ requires Python 3.5 or later (3.4 detected).
```

**Comment by jarrodmillman** [comment]
Python 3.4 support was dropped for the 2.2 release last September:
https://networkx.github.io/documentation/stable/news.html#networkx-2-2
