### ISSUE TITLE
Error with union operation when a node is on both graphs

### ISSUE THREAD

**Issue by renan-cunha** [networkx/networkx#3422]
```python3
import networkx as nx

graph1 = {1:[2], 2:[1]}
graph1 = nx.Graph(graph1)

graph2 = {1:[3], 3:[1]}
graph2 = nx.Graph(graph2)

nx.union(graph1, graph2)
```

With this code, the following error appears

---------------------------------------------------------------------------
NetworkXError: ('The node sets of G and H are not disjoint.', 'Use appropriate rename=(Gprefix,Hprefix)or use disjoint_union(G,H).')

**Comment by renan-cunha** [comment]
Where i am trying to do is done by the networkx.compose method

**Comment by stevenganz** [comment]
I suggest reopening this.  The fact that there is an operator called "compose" that is described in its documentation as performing a union (rather than a [composition]([url](https://igraph.org/r/doc/compose.html))) does not resolve this issue.  Until this is fixed, people will continue to waste time on it.  The union operator clearly operates in a manner different than described in its own documentation.

**Comment by dschult** [comment]
Perhaps your concern is different from the original issue of the poster? The compose function did what that user needed. Apparently it is also what you wanted.  In fact the newer graph method ```update``` might do even better without the potentially confusing name:
```python
G.update(H)
# or if you still need G around:
GG = G.copy()
GG.update(H)
```

The ```compose``` function and ```update``` method simply take the union of the node set and also the union of the edge set.  That is NOT the union of the two graphs as commonly defined in the literature. It is also NOT the composition (or lexicographic product) of two graphs as defined in the literature.

Perhaps your issue is that we should improve the documentation of ```union``` and ```compose``` by having them point to each other better.  Would that be sufficient to have helped you?  If so, we'd love a PR that improves documentation, but we will get to it if you aren't able to.  
It would help to open a new issue rather than reopen an issue someone already closed themselves.

**Comment by stevenganz** [comment]
Thanks, Dan.  I'm opening a new issue that expresses my concerns more directly.
