### ISSUE TITLE
[FEA] parallelize all_pairs_shortest_path_length

### ISSUE THREAD

**Issue by jazzmuesli** [networkx/networkx#3439]
Suggestion: Use multiprocessing or something better to utilise multiple CPUs

**Comment by ericmjl** [comment]
This would be a neat PR. I can see using Dask as a generalized backend for parallel computations.

**Comment by MridulS** [comment]
@ericmjl regarding backends for computations check out https://github.com/Quansight-Labs/uarray. But to make that work with networkx will require a bit of work, cuz everything builds up on the dict-o-dict-o-dict data structure instead of arrays/lists/dataframe which Dask uses. [I am thinking on the lines of using Dask data structures to store the graph/network].
It would actually be pretty great if this could be done! :)

**Comment by jazzmuesli** [comment]
@MridulS I've implemented parallelisation using multiprocessing in this PR https://github.com/networkx/networkx/pull/3440 and for this particular feature request I feel it can be useful. In general, it might make sense to parallelise more functions in networkx, but it would require a lot more work.

**Comment by jfinkels** [comment]
Hi! See #2265.

**Comment by rossbar** [comment]
My sense is that there would need to be a bit more discussion on a general policy for parallelization before moving forward with tackling any specific function - see #4064.

**Comment by SultanOrazbayev** [comment]
Perhaps this is something to pass to external implementation/libraries that can be dispatched to.

**Comment by rossbar** [comment]
Agreed - I think parallelization is definitely best left to dispatching and/or user code.

**Comment by MridulS** [comment]
To be discussed further in https://github.com/networkx/networkx/issues/4064 and https://github.com/networkx/networkx/pull/6306 . Thanks for opening the issue @jazzmuesli !
