### ISSUE TITLE
Misplaced dominating_set algorithm in networkx/algorithms/dominating.py

### ISSUE THREAD

**Issue by alabarre** [networkx/networkx#3453]
This is probably a broader issue, but if there's an interest in using `networkx` to solve NP-hard/complete problems we should probably distinguish between exact and approximation algorithms. 

The `approximation` subdirectory was likely created to that end, and in my opinion the (misleadingly named) `dominating_set` function that can be found in `networkx/algorithms/dominating.py` should move to `networkx/algorithms/approximation/dominating_set.py` -- preferrably in a way that at least temporarily does not break existing code (issue deprecation warnings?).

This principle might apply to other functions as well (I haven't checked), and perhaps at some point we will need to rename those functions and follow the same patterns as in, say, `mst.py`, to select preferred algorithms, or ask for the best solution out of all heuristics in a transparent way, and so on.

**Comment by dschult** [comment]
Can you say a little more about why dominating_set is misleadingly named and why you think it is an approximation algorithm? It seems like the function that returns a dominating set is reasonably named dominating_set.  The module name dominating.py could be renamed dominating_sets.py (notice the plural so it isn't the same name as the function.

In general, I'm not in favor of renaming functions and modules in order to improve the organization of the package. We could easily spend all our time managing the names when we could be implementing algorithms. :}

If you find something confusing, go ahead and report what is confusing and back it up. If you find something organized differently than what you think it ought to be, hold on to that thought until you find something confusing.

**Comment by alabarre** [comment]
Yes, let me clarify: it is of course reasonable to name it `dominating_set` if that's what it returns, but given that it's outside the approximation module, I was at first expecting it to return an optimal solution, whereas it returns an approximate solution like the others.

But if that's just me, let us forget about it. I fully agree that our time is better spent on writing code, and if I ever come up with implementations of exact algorithms for hard problems that fit networkx, I'll just organise them as I see fit and start discussions then.

**Comment by dschult** [comment]
I see. You were expecting ```minimal_dominating_set``` while this just returns ```dominating_set```.

I agree with you that approximate algorithms should be placed in the ```approximation``` subpackage. I'm going to claim that this function is not approximate because it doesn't claim to look for the smallest dominating set. It is an exact algorithm for finding a dominating set. 

Thanks for clarifying. This is useful.
