### ISSUE TITLE
A* (A star) function astar_path returns a wrong answer

### ISSUE THREAD

**Issue by Leesprin** [networkx/networkx#3464]
Suppose we have a graph below:
![astarexample](https://user-images.githubusercontent.com/51309106/58777405-b8cbd980-8600-11e9-9630-166c665db555.png)
Find shortest path from N5 to N0.
Numbers in bracket alongside each node are heuristic values estimating distance to n0. (This is a bad example of heuristic function I constructed to use in my classroom.)
The best path from n5 to n0 is:  
n5→n4→n3→n2→n1→n0
What networkx.algorithms.shortest_paths.astar.astar_path returns: 
[n5, n1, n0] 
which is apparently not correct.

**Comment by dschult** [comment]
Here's a similar very simple example that shows the same bug:

    Gedges = [(1,0,11), (1,2,1), (2,0,6)]
    G = nx.DiGraph()
    G.add_weighted_edges(Gedges)
    def heur(u,v):
        distance = {0:0, 1:36, 2:16}
        return distance[u]
    nx.astart_path(G,1,0,heur)    # returns  [1, 0]  instead of shorter [1,2,0]

Definitely a bug here. I think when the code finds the target it never checks whether the heuristic estimate of distance is correct... It just stops.  Why don't any tests find this bug? Am I missing something?  We need a PR with a test and some fixed code.

**Comment by uludag** [comment]
I get correct answer for the above simple example, the following test is not failing for me:
```python
    def test_astar_directed3(self):
        Gedges = [(1, 0, 11), (1, 2, 1), (2, 0, 6)]
        G = nx.DiGraph()
        G.add_weighted_edges_from(Gedges)

        def heur(u, v):
            distance = {0: 0, 1: 36, 2: 16}
            return distance[u]

        assert_equal(nx.astar_path(G, 1, 0), [1, 2, 0])
```

**Comment by matejklemen** [comment]
Hey,
in your example @dschult, I think the result is actually correct as you do not have an admissible heuristic (i.e. one that underestimates cost to the goal) and in that case A* is not guaranteed to find an optimal solution.

In the case of the main example, there actually seems to be a bug. As far as I can tell, the problem seems to be the checking of already explored nodes. It stores explored nodes in a dictionary, so when the same node is encountered twice, it does not explore the node again. In the example here, a "bad path" is found first (`n5`->`n1`->`n0`), which correctly gets put at the end of the priority queue (and is not yet fully explored!). The problem is though, that all other paths through `n1` do not get explored because `n1` in stored among the already explored nodes. Therefore, the "bad path" gets returned as solution.  

I'll test it a bit more and see if I can come up with a PR.
