### ISSUE TITLE
GraphML output not using <edge id="XXX">

### ISSUE THREAD

**Issue by peterjc** [networkx/networkx#3470]
The NetworkX GraphML output seems to demote edge ``id`` to a named attribute.

The GraphML primer has an example with node colors encoded as attributes of selected nodes, and weights on edges:

http://graphml.graphdrawing.org/primer/graphml-primer.html#Attributes

Example on macOS with Python 3.7 and NetworkX 2.3

```
$ curl -L -O http://graphml.graphdrawing.org/primer/attributes.graphml
$ python3 --version
Python 3.7.0rc1
$ python3 -c "import networkx as nx; print(nx.__version__)" 
2.3
$ python3 -c "import networkx as nx; nx.readwrite.graphml.write_graphml(nx.readwrite.graphml.read_graphml('attributes.graphml'), 'attributes2.graphml')"
```

Input ``attributes.graphml``:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file was written by the JAVA GraphML Library.-->
<graphml xmlns="http://graphml.graphdrawing.org/xmlns"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key id="d0" for="node" attr.name="color" attr.type="string">
    <default>yellow</default>
  </key>
  <key id="d1" for="edge" attr.name="weight" attr.type="double"/>
  <graph id="G" edgedefault="undirected">
    <node id="n0">
      <data key="d0">green</data>
    </node>
    <node id="n1"/>
    <node id="n2">
      <data key="d0">blue</data>
    </node>
    <node id="n3">
      <data key="d0">red</data>
    </node>
    <node id="n4"/>
    <node id="n5">
      <data key="d0">turquoise</data>
    </node>
    <edge id="e0" source="n0" target="n2">
      <data key="d1">1.0</data>
    </edge>
    <edge id="e1" source="n0" target="n1">
      <data key="d1">1.0</data>
    </edge>
    <edge id="e2" source="n1" target="n3">
      <data key="d1">2.0</data>
    </edge>
    <edge id="e3" source="n3" target="n2"/>
    <edge id="e4" source="n2" target="n4"/>
    <edge id="e5" source="n3" target="n5"/>
    <edge id="e6" source="n5" target="n4">
      <data key="d1">1.1</data>
    </edge>
  </graph>
</graphml>
```

Output from NetworkX:

```xml
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="id" attr.type="string" for="edge" id="d2" />
  <key attr.name="weight" attr.type="double" for="edge" id="d1" />
  <key attr.name="color" attr.type="string" for="node" id="d0">
    <default>yellow</default>
  </key>
  <graph edgedefault="undirected">
    <node id="n0">
      <data key="d0">green</data>
    </node>
    <node id="n1" />
    <node id="n2">
      <data key="d0">blue</data>
    </node>
    <node id="n3">
      <data key="d0">red</data>
    </node>
    <node id="n4" />
    <node id="n5">
      <data key="d0">turquoise</data>
    </node>
    <edge source="n0" target="n2">
      <data key="d1">1.0</data>
      <data key="d2">e0</data>
    </edge>
    <edge source="n0" target="n1">
      <data key="d1">1.0</data>
      <data key="d2">e1</data>
    </edge>
    <edge source="n1" target="n3">
      <data key="d1">2.0</data>
      <data key="d2">e2</data>
    </edge>
    <edge source="n2" target="n3">
      <data key="d2">e3</data>
    </edge>
    <edge source="n2" target="n4">
      <data key="d2">e4</data>
    </edge>
    <edge source="n3" target="n5">
      <data key="d2">e5</data>
    </edge>
    <edge source="n4" target="n5">
      <data key="d1">1.1</data>
      <data key="d2">e6</data>
    </edge>
  </graph>
</graphml>
```

The node and edge identifiers are still present, as are the node color and edge weights. So far so good.

NetworkX has reported the named attributes in reversed order, strange but harmless?

However, NetworkX has demoted the edge id to a named attribute (``d2``)!

Before:

```xml
    <edge id="e0" source="n0" target="n2">
      <data key="d1">1.0</data>
    </edge>
```

After:

```xml
    <edge source="n0" target="n2">
      <data key="d1">1.0</data>
      <data key="d2">e0</data>
    </edge>
```

This seems like a bug to me.

**Comment by peterjc** [comment]
Is the rational that in GraphML the node id is required and it is explicit is must be unique in the file:
http://graphml.graphdrawing.org/primer/graphml-primer.html#GraphNode

Whereas, for nodes the id is optional (and only implicit that this be unique):
http://graphml.graphdrawing.org/primer/graphml-primer.html#GraphEdge

(And this does this single unique string idea not map to how NetworkX handles edge identifiers?)

**Comment by dschult** [comment]
Not quite sure I understand. Is it the node id or the edge id that is causing trouble. Your first post talks about edge ids, but the second about node ids.

It has been long enough since I looked at this code and we've got other very similar type of issues with other formats, so I may not have the right answer... Probably looking at the code and searching for node and edge id handling names would be understandable.

I believe the edge ids are stored on the graph as an attribute when reading a file. The name 'id' is not a special attribute name though so when writing the file it is not clear what attribute to use as the edge id. The currently written graphml file is valid graphml and it preserves all the information. A second read/write cycle would return the same output.  (I think this is correct...)

This kind of stuff is tricky to implement and difficult to maintain. Would love some code that handles it using readable code.

**Comment by peterjc** [comment]
Sorry, I had an unfortunate typo in the second comment (see correction).

So it sounds like it is in part down to different object models?

**Comment by dschult** [comment]
Yes, it seems that graphml allows ```id``` attributes to be stored in multiple ways and we have chosen one of those ways when we write files. We read either way. So, in general reading and writing is not invariant, but once we read and write, further read/write cycles should leave the file invariant.

**Comment by kiryph** [comment]
Are there specific reasons why networkx has choosen the graphml output representation for edge ids to be different to node ids?

This inconsistency is surprising for the user and reduces IMHO the readabililty of the xml code.

**Comment by peterjc** [comment]
My understanding is this is down to the GraphML format defining a node ID, but not defining an edge ID - meaning NetworkX stores any edge identifiers as an attribute instead.

**Comment by kiryph** [comment]
@peterjc 


The GraphML Schema Documentation defines the edge id as non-required xml attribute: http://graphml.graphdrawing.org/specification/xsd.html#element-edge

which lists all required and optional attributes.

The [GraphML primer](http://graphml.graphdrawing.org/primer/graphml-primer.html#GraphEdge) repeats this:

> Optionally an identifier for the edge can be specified with the XML Attribute id. When it is necessary to reference the edge, the id XML-Attribute is used.
> 
> An edge with all XML-Attributes defined
>  
>     ...
>     <edge id="e1" directed="true" source="n0" target="n2"/>
>     ...

From my point of view one could say the GraphML format defines an edge ID as well.

Another motivation to treat them more special are graphs with multi-edges.

**Comment by dschult** [comment]
Perhaps this should be in a new Issue (or maybe a new pull request?)...

It's not clear to mean what you (@kiryph ) are questioning/suggesting. 
What should the edge ID be? Why isn't it enough to have the edge data as attributes?
What is your expected behavior? 
To answer your question bluntly: We can't treat edges the same as nodes because, well, they aren't the same. :)

**Comment by kiryph** [comment]
@dschult Thanks for your response.

> It's not clear to mean what you (@kiryph ) are questioning/suggesting.

As the OP I would have used the xml representation as written in the title of this issue

    <edge id="XXX">

and used on the graphml website.

> What should the edge ID be?

It is an optional attribute and should only be written when the user has created edge ids or the original input has provided ones.

> Why isn't it enough to have the edge data as attributes?

I see several reasons why I would prefer the edge id as an attribute instead of an edge data:

- More readable xml files: 
  less lines and no cryptic and easily confused key id `d1` (in another file without node colors it is `d0`).
- XPATH expressions do not have to be modified (assuming the original file uses the representation from graphml.org). Furthermore, selection is similar to nodes, i.e. more intuitive. Example with xmlstarlet:

```
❯ curl -L -O http://graphml.graphdrawing.org/primer/attributes.graphml
❯ xml sel -t -v '//_:node/@id' attributes.graphml
n0
n1
n2
n3
n4
n5
❯ xml sel -t -v '//_:edge/@id' attributes.graphml
e0
e1
e2
e3
e4
e5
e6
```
Run once through networkx
```
❯ python3 -c "import networkx as nx; nx.readwrite.graphml.write_graphml(nx.readwrite.graphml.read_graphml('attributes.graphml'), 'attributes-networkx.graphml')"
```
Original XPATH expression does not work anymore:
```
❯ xml sel -t -v '//_:edge/@id' attributes-networkx.graphml

# nothing. You have to modify your XPATH expression
❯ xml sel -t -v '//_:edge/_:data[@key="d2"]' attributes-networkx.graphml
e0
e1
e2
e3
e4
e5
e6
```

- Output in agreement with the examples given on the official website of graphml (more newbie friendly)
- Smaller xml files (less important for xml, but still)
- Graphs with multi-edges are written in a more obvious way. In general I would argue data for different edges can be equal but edge ids cannot which makes this value more special than edge weight/direction/...

Actually, I do not know any reason why I would prefer it the other way. Saying that nodes are different to edges is obvious (the xml tags are `<node>`and `<edge>` and makes this clear enough). There is no need for additional syntactic differences.

**Comment by kiryph** [comment]
### `MultiGraph`

I have noticed that generated ids, when using networkx `MultiGraph`, are saved as I was expecting:

```
import networkx as nx
G = nx.MultiGraph()
G.add_edge(1,2,color='red')
nx.readwrite.graphml.write_graphml(G, 'demo-multigraph.graphml')
```
```
❯ cat demo-multigraph.graphml
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd"><key attr.name="color" attr.type="string" for="edge" id="d0"/>
<graph edgedefault="undirected"><node id="1"/>
<node id="2"/>
<edge id="0" source="1" target="2">
  <data key="d0">red</data>
</edge>
</graph></graphml>
```

Would it be sensible to create a networkx MultiGraph when the graphml file contains edge ids?

**Comment by dschult** [comment]
That looks like a good suggestion to me!
Can you also add tests to make sure we check what happens with each case?
This should be a good PR.
