### ISSUE TITLE
Apparent bug in `betweenness_centrality_subset`

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#3481]
See this question:

https://stackoverflow.com/questions/56569070/is-this-betweenness-calculation-correct

I believe the issue is that the `_rescale_e` function requires a factor of 0.5 if `G` is not directed, and that this got copied over into the `_rescale` function and wasn't fixed.

The result is that betweenness centrality appears to be off by a factor of 0.5.

**Comment by dschult** [comment]
I believe the docstrings for betweenness_centrality_subset mentions this. They state that the normalization may appear to be strange, but is designed to make the results of ```nx.betweenness_centrality_subset(G, G.nodes, G.nodes)``` agree with ```nx.betweenness_centrality(G)```.

When all nodes are in both ```sources``` and ```targets``` then we traverse paths in both directions. So normalization should account for this.

What do you think?

**Comment by nandahkrishna** [comment]
Hello, hope you don't mind if I just add something here. In `betweenness_centrality`, the default is `normalized=True`. So, would it be better if we changed `betweenness_centrality_subset` to also have `normalized=True` by default (it's `False` right now)? This would ensure that the values are the same for the case you mentioned, which is also given in the docstring. 

Since normalization would ensure that the results agree, I think it might be fine if we remove the scale factor of 0.5, so the query may be addressed for more general cases, as indicated by the StackOverflow question. 

I'm also doubtful about `betweenness_centrality`, for which the same `scale = 0.5` appears in `_rescale`. Would this issue arise there as well?

I hope I'm making sense here, please do point out if I have any errors in my understanding.

**Comment by nandahkrishna** [comment]
Just some outputs:
```
>>> G = nx.path_graph(5)
>>> nx.betweenness_centrality(G, normalized=False)
{0: 0.0, 1: 3.0, 2: 4.0, 3: 3.0, 4: 0.0}
>>> nx.betweenness_centrality(G) # normalized is True by default
{0: 0.0, 1: 0.5, 2: 0.6666666666666666, 3: 0.5, 4: 0.0}
>>> nx.betweenness_centrality_subset(G, G.nodes, G.nodes, normalized=True)
{0: 0.0, 1: 0.5, 2: 0.6666666666666666, 3: 0.5, 4: 0.0}
>>> nx.betweenness_centrality_subset(G, G.nodes, G.nodes) # normalized False by default
{0: 0.0, 1: 3.0, 2: 4.0, 3: 3.0, 4: 0.0}
```
The proposed betweenness subset function would give `{0: 0.0, 1: 6.0, 2: 8.0, 3: 6.0, 4: 0.0}` when not normalized, and `{0: 0.0, 1: 0.5, 2: 0.6666666666666666, 3: 0.5, 4: 0.0}` when normalized.

The docstring (in betweenness_centrality as well as betweenness_centrality_subset):
```
normalized : bool, optional
      If True the betweenness values are normalized by `2/((n-1)(n-2))`
      for graphs, and `1/((n-1)(n-2))` for directed graphs where `n`
      is the number of nodes in G.
```

**Comment by joelmiller** [comment]
I am traveling with very limited internet at the moment.  But my recollection is that when I used the definition for centrality in the docstring of `betweenness_centrality_subset` to calculate by hand I did not get the same answer as what `betweenness_centrality_subset` produced.  I looked at the normalization and that didn't seem to explain it.

**Comment by dschult** [comment]
The strange value that @joelmiller saw and discussed in the StackOverflow post appears half as big as expected. This is due to the factor 0.5 in ```_rescale```.  The expectation seems that the unnormalized value comes from computing the fraction of all paths from source to target that go through each node.  (There is no problem with the "normalized" version of the code as far as I can see.)

The total number of paths between source and target is counted differently for directed and undirected graphs. Directed paths are easy to count. Undirected paths are tricky: should a path from "u" to "v" count as 1 undirected path or as 2 directed paths? 

For ```betweenness_centrality``` we report the number of undirected paths when G is undirected. 

Now, when we switch to the ```subset``` case, if the source and target subsets are the same, then we again presumably want to count undirected paths. But if the source and target subsets differ -- for example, if sources is {0} and targets is {1}, then we are only counting the paths in one direction. They are undirected paths but we are counting them in a directed way. To count them as undirected paths, each should count as half a path.

I believe that is the reason for the factor 0.5 in ```_rescale```. If you want to know the number of paths, you need to count each directed path you find as half of an undirected path. Otherwise when you add up the counts over all the subsets you will have a higher count than the number of paths in the graph.

**Comment by nandahkrishna** [comment]
Thanks @dschult for explaining. I too think there is no error in the "normalized" code, it ensures that values of `betweenness_centrality` and `betweenness_centrality_subset` are the same no matter the test case. 

Seeing as `normalized=True` is default for `betweenness_centrality`, I think it would be better for subset betweenness to also be normalized by default. Makes things uniform, I guess.

The definition of subset betweenness considers paths **from sources** and **to targets**, so in the **literal sense**, the element of **direction** seems to be present. I'm not sure, but it might be fair to assume that calls to subset betweenness mostly don't have repetition of source nodes in targets - this means we could count paths in 1 direction as one full path and **undirected paths as 2 directed paths**. The value of centrality being higher than the total number of paths in the graph in some cases may not be a huge concern. So it might be alright if we remove the 0.5, and normalizing by default would help in uniformity across functions.

Do let me know what you think would be the best way forward. Thanks.

**Comment by dschult** [comment]
I'd like to make this a documentation fix.

1) add a long description similar to what I wrote above about undirected paths, counting, etc and the "reason" networkx counts half-paths. 
2) add more warnings about normalization in the docstrings. Especially in the ```_subset``` docs we should add an entire paragraph to say that the default for normalization is different for ```_subset``` than for the non-subset function.
