### ISSUE TITLE
[Feature request] Signed and Weighted Clustering Coefficient

### ISSUE THREAD

**Issue by j1c** [networkx/networkx#3490]
[This paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0088669) proposes a new a method for computing the clustering coefficient and average clustering coefficient for weighted and signed graphs. The current implementation (I believe) is only for binary graphs.

Would `networkx` be interested in the algorithm? If so, I am more than happy to work on this.

**Comment by dschult** [comment]
Yes, we would be interested in those algorithms. 
Perhaps put them in ```algorithms/cluster.py```.
Choose your own names for them but something simple like signed_clustering and signed_average_clustering.  The top of that module doesn't match our proclaimed style (described on the github networkx wiki page) so that could be updated as well. That code hasn't been touched in a while.

Thanks!
