### ISSUE TITLE
add_edges_from() method missing some edges

### ISSUE THREAD

**Issue by congx961** [networkx/networkx#3531]
I'm using add_weighted_edges_from() method which is actually calling add_edges_from() to generate a graph from a list contain 303535 edges, but the graph object returned by this method only have 303190 edges. 

I've checked the source code and find it called the Graph.update() so i check my edgelist if there are some duplicate edges but the result is NO. 

Another interesting thing is when I use the nx.read_edgelist() everything is OK, but I just don't know why and it's really confusing.

**Comment by dschult** [comment]
You are telling us what you think you are doing and the resulting missing edges should not happen in that case.  So your theory is just fine. It's the implementation that is causing you trouble (probably).  Can you show us what you are actually doing instead of what you think you are doing?
Don't include the whole edge list. Maybe a short version of the code with only 3 edges in the edge list, but all other case the same.

**Comment by congx961** [comment]
> You are telling us what you think you are doing and the resulting missing edges should not happen in that case. So your theory is just fine. It's the implementation that is causing you trouble (probably). Can you show us what you are actually doing instead of what you think you are doing?
> Don't include the whole edge list. Maybe a short version of the code with only 3 edges in the edge list, but all other case the same.

Thank you for reply! After rechecking my code and I found that it's my fault to use the nx.Graph() to generate the graph object instead of nx.DiGraph() since the edgelist is from a directed graph. 

Anyway thank you again.
