### ISSUE TITLE
Convert crossing edges into new node?

### ISSUE THREAD

**Issue by ofou** [networkx/networkx#3532]
Hi! I'm a musician doing a musical investigation on the [circle of fifth](https://en.wikipedia.org/wiki/Circle_of_fifths) and I'm new to networkx. I want to make new nodes from crossing edges. Is it possible to do that with nx? 
I want to be able to analyze all the intersections of a complete K12 graph as musical notes of the circle and convert them into new nodes.

Any suggestions would be greatly appreciated.

![image](https://user-images.githubusercontent.com/12256669/62189236-77c01f00-b33c-11e9-80b6-162fff790bb8.png)

```
notes = ['C', 'G', 'D', 'A', 'E', 'B', 'F#', 'C#', 'G#', 'D#', 'A#', 'F']
M = nx.complete_graph(notes)
pos = nx.draw_circular(M,  with_labels = True)
```

**Comment by dschult** [comment]
The graph structure only says which nodes connect to which others. The "crossing edges" depends on the position of the nodes, which is a property of the picture, not of the nodes themselves.  If you want to stick to evenly spaced circular layouts with complete graphs, there is likely a formula for crossings you could derive using ideas from geometry. But I don't think it will be part of a network package only because it depends on where you place the nodes.

**Comment by ofou** [comment]
I was looking for something to detect path crossing and I couldn't find anything useful. Personally, I think it would be very helpful to have such tool for developing new graph's drawing algorithms for nx, for example. I sincerily think that the crossing edge's feature might help to push the library forward. 

By the way, thanks you so much for answering! 
Have a nice day

**Comment by dschult** [comment]
Edges crossing is closely related to G being a "planar graph" (can be drawn on paper without any edges crossing). So a planar graph is sort of the opposite of a graph with edges crossing. We do have some basic planar graph algorithms. It would definitely be harder to keep track of the crossings though.  Lots of topology to mess with our heads. :)

It would definitely be good to have a layout routine that places nodes to avoid crossing edges!
Best regards
