### ISSUE TITLE
`get_edge_data` returns dict of dicts when called on multidirectional graph

### ISSUE THREAD

**Issue by awa5114** [networkx/networkx#3582]
I have the following code to demonstrate the issue:
```
import networkx as nx

graph = nx.Graph()
mgraph =  nx.MultiDiGraph()

for G in [graph, mgraph]:
    G.add_edge(1, 2, weight=4.7)

print(graph.get_edge_data(1, 2))
print(mgraph.get_edge_data(1,2))
```

Running the above results in :
```
{'weight': 4.7}
{0: {'weight': 4.7}}
```

The second printed statement shows a dict of dicts which is very confusing to me. Since both graphs have exactly the same attributes, how is it that the results are different? What does the 0 key represent in the MultiDiGraph?

**Comment by dschult** [comment]
Take a look at [the documentation ](https://networkx.github.io/documentation/stable/reference/introduction.html) especially the introduction and the multigraph/multidigraph references. 

For a MultiDiGraph, the edge data includes the key and an attribute dict. This is related to the fact that specifying one (1,2) doesn't tell you for which edge between 1 and 2 you want edge data.  If you know the edge keys you can use ```G.get_edge_data(1, 2, 0)``` and specify the key. Also, rather than get_edge_data you can use G[1][2] and/or G[1][2][0] if you prefer.

**Comment by awa5114** [comment]
Thanks a lot.
