### ISSUE TITLE
I am not able to get the list of selfloop_edges

### ISSUE THREAD

**Issue by jorluis2695** [networkx/networkx#3679]
g.selfloop_edges(), this give me an error in version 2.4.  (worked fine in version 2.3)

**Comment by jarrodmillman** [comment]
The `selfloop` methods were deprecated as graph methods in favor of networkx functions in 2.0.  In 2.4, we removed the deprecated method.  Instead of `g.selfloop_edges()` use `nx.selfloop_edges(g)`. There is more information here:
 https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html

**Comment by jorluis2695** [comment]
Top thanks
