### ISSUE TITLE
Premature deprecation

### ISSUE THREAD

**Issue by salotz** [networkx/networkx#3683]
I noticed that in 2.4 release a number of methods on the core graph classes were deprecated. See: https://github.com/networkx/networkx/commit/6b1ce03f485076d39994e8d624bbf6ca82466eb9#r35619092

In the comments it says these will be deprecated in 3.0. Perhaps this was an accident to remove them for 2.4?

I would request that unless there is a really good reason, to put these methods back along with any other deprecations. It really is not fun to have the rug pulled out from under you and there probably is no reason other than cleaner code to get rid of them. If NetworkX is following semantic versioning then this would go against the rules there as well.

At the least deprecation warnings should be put in place a couple releases in advance.

**Comment by dschult** [comment]
The deprecation warnings have been in place for v2.0, v2.1, v2.2, v2.3.
I'm sorry for any inconvenience. The functions you refer to are easy to update.

    G.add_path(path) --> nx.add_path(G, path)

and similar for add_cycle, add_star, and the selfloop functions as well.
The reasons to remove them involve shifting our tests from nose to pytest and yes, there probably is a way to get around issues there and keep the functions, but I'd rather spend time on getting new things in place than mucking with having tests handle deprecated functions that have been deprecated for 4 versions.  The comment about v3 was from so long ago that we have changed our expected release schedule since then. Python itself has talked about never increasing the first digit again.  

I'm sorry about the confusion and the pain to have to rewrite your code. But I hope in the end this doesn't qualify as pulling the rug out from under you.

**Comment by salotz** [comment]
It won't be so hard to update personally, but I just don't see the need to break things for the sake of testing. If you want to stop writing tests for deprecated features, feel free. If I see deprecated on features I know it's something the developers don't care about anymore and I will update as I see fit. 
Re python not changing the first digit. The first digit in semantic versioning is supposed to give you an indication of backwards compatibility. By commiting to not changing the first digit you are commiting to backwards compatibility. Even if it costs code and docs complexity.
My two cents. Im not a core dev so I can't make the call regarding commitments to compatibility vs growth, but I just wanted to make sure the effects were known.

**Comment by salotz** [comment]
The major API breakage for me is the `node` attribute which is a simple alias. I don't see why this is a problem leaving it in the API. 

Having said that, in the migration guide it says it is removed, which is fine except that it actually wasn't. It would've been unsurprising had this part of the API was just broken at the major number instead of soft deprecating. Then I would've seen errors of using this code when I migrated the first time, without doing a thorough (and still probably insufficient) audit of my codebase.
Whether or not the project uses semantic versioning that is what people expect from the x.y.z version scheme, more or less.
