### ISSUE TITLE
all_shortest_paths inconsistent in undirected graph

### ISSUE THREAD

**Issue by nycnighthawk** [networkx/networkx#3685]
Steps to reproduce below
>>> from networkx import nx
>>> g = nx.Graph()
>>> g.add_path([1, 2, 3, 5, 7, 8])
>>> g.add_path([1, 2, 3, 4, 6, 7, 8])
>>> g.edges[3,4]['weight'] = 0
>>> list(nx.all_shortest_paths(g, 1, 8, weight='weight'))
[[1, 2, 3, 5, 7, 8], [1, 2, 3, 4, 6, 7, 8]]
>>> list(nx.all_shortest_paths(g, 8, 1, weight='weight'))
[[8, 7, 5, 3, 2, 1]]

the result is correct for 1, 8, but incorrect for 8, 1 when associate the edge [3, 4] with weight=0, effectively means both paths are equal from calculation point of view.

**Comment by dschult** [comment]
Thanks for this very simple example!!  Looks like a bug.

**Comment by boothby** [comment]
I traced this issue, and the root cause is that `all_shortest_paths` defaults to using Dijkstra's algorithm, which is only correct for positive weights.  Bellman-Ford does not have this limitation, but the runtime is worse.  I see two options here:

1) default to Bellman-Ford and suffer the runtime hit, or
2) check if all weights are positive to determine which algorithm to dispatch.

**Comment by dschult** [comment]
I believe Dijkstra is correct for non-negative weights.
It should be Ok with zero weights or positive weights if I understand correctly.

**Comment by boothby** [comment]
Okay, I stand corrected.  I have a modification to Dijkstra's algorithm that handles zero-weight edges.  This does kick the problem down the road a little.  Minifying @nycnighthawk's example, I add the test:

```
    def test_all_shortest_paths_zero_weight_edge(self):
        g = nx.Graph()
        nx.add_path(g, [0, 1, 3])
        nx.add_path(g, [0, 1, 2, 3])
        g.edges[1, 2]['weight'] = 0
        paths03 = list(nx.all_shortest_paths(g, 0, 3, weight='weight'))
        paths30 = list(nx.all_shortest_paths(g, 3, 0, weight='weight'))
        assert sorted(paths03) == sorted(p[::-1] for p in paths30)
```

Inside `all_shortest_paths`, we compute predecessors,

    >>> nx.dijkstra_predecessor_and_distance(g, 0, 3, weight='weight')
    {0: [], 1: [0], 3: [1, 2], 2: [1]}
    >>> nx.dijkstra_predecessor_and_distance(g, 3, 0, weight='weight')    
    {3: [], 1: [3], 2: [3, 1], 0: [1]}

If we modify Dijkstra's to handle zero-weight edges correctly, we have

    >>> nx.dijkstra_predecessor_and_distance(g, 0, 3, weight='weight')
    {0: [], 1: [0, 2], 3: [1, 2], 2: [1]}
    >>> nx.dijkstra_predecessor_and_distance(g, 3, 0, weight='weight')    
    {3: [], 1: [3, 2], 2: [3, 1], 0: [1]}

This looks fine, but results in "paths" of indefinite length.  Thus, I'm adding cycle-detection in the `all_shortest_paths` method.  However, I'm a little concerned about other consumers of `nx.algorithms.shortest_path._dijkstra_multisource` falling into this trap.  Thoughts?

**Comment by dschult** [comment]
It seems to me that we have found two things here.

1) ```_dijkstra_multisource``` has a bug in its predecessor finding routine. I believe this goes beyond zero-weight edges. It we have ties for shortest path it may or may not report both predecessor for some nodes.

2) ```all_shortest_paths``` should not allow zero-weight edges. This is a concept that doesn't make sense. With a zero-weight edge, you will get an infinite number of shortest paths if any shortest path includes the zero weight edge. To make the answer determined, it is perhaps better to do a node-contraction for the two nodes on either side of every zero-weight edge.  I feel this is a strange enough case that we should handle it with documentation rather than e.g. checking for zero-weight edges.

Comments?

If I've got the above correct, then we should retain the fix for weighted.py in #3783 and change the documentation for all_shortest_paths to suggest that zero weight edges be handled using node contraction.

**Comment by boothby** [comment]
With regard to (1), I believe that the fix I posted should be correct in all cases of ties -- I'm not actually checking for zero-weight edges; I'm only checking for ties.

With regard to (2), we should first agree on the definition of a path.  The definition that I work with is that paths are not allowed to repeat nodes [1].  Under that definition, there are a finite number of paths from `s` to `t`; regardless of edge weights.  If nodes are allowed to repeat, then we'd be computing shortest _walks_, which admit infinite solutions in the presence of nonpositive edges, and I agree that the only feasible solution is to document the issue.  Under this definition of path, I believe my fix to be correct.

I've been looking a bit deeper into other shortest-path algorithms, and each one seems to have something strange going on.  I haven't done a comprehensive reading of the literature, but in what I'm reading; it seems to be standard to (a) prove that an algorithm works on digraphs in the presence of nonpositive edges, and (b) recommend treating undirected graphs as digraphs.  The issue that keeps cropping up is that 2-cycles do not exist in simple graphs, but they trap algorithms meant for digraphs.  So, that "standard advice" becomes a problem and the appropriate treatment of zero-weight edges is to contract the edges... but I'm yet unsure of how to properly handle negative-weight edges in undirected graphs.  I'll post some examples tonight of what's breaking down and what I've been able to fix.

[1] https://en.wikipedia.org/wiki/Path_(graph_theory)#Walk,_trail,_path

**Comment by boothby** [comment]
As I suspected, there's more than one path-tracing implementation -- the one in `_bellman_ford` has the same flaw for undirected graphs.

```
>>> G = nx.Graph()                                                                                                                   
>>> G.add_weighted_edges_from([(0,1,0), (1,2,0), (2,3,1), (3,0,1)])                                                                  
>>> nx.bellman_ford_path(G, 1, 0) 
[infinite memory consumption loop]
```

**Comment by dschult** [comment]
Very nice!  I'm just catching up here.  

I think we use the term ```simple path``` to be a path that does not repeat nodes. We have a function ```all_simple_paths```.  I guess that for shortest_paths you usually only get simple paths, so it really is a corner case that appears with either zero or negative weights.

I like your fix for ```_dijkstra_multisource```.  We should search for other routines that might use that feature.

I thought Bellman-Ford would catch infinite loops due to cycles because they could occur with negative weight around the cycle too.

**Comment by boothby** [comment]
Yeah, this is a real bug in Bellman-Ford -- it can get tripped up on zero-cycles that don't contain zero-weight edges too:

```
>>> D = nx.DiGraph()
>>> D.add_weighted_edges_from([(0,1,1), (1,2,1), (2,3,1), (3,1,-2)])  
>>> nx.bellman_ford_path(D, 1, 3)
[hangs, gobbling memory]
```

It seems to me that we can't efficiently enumerate "all shortest paths" unless we actually mean all shortest simple paths -- if a node ever gets repeated, that indicates that paths of unbounded length will be generated.  Giving up on efficiency, we could store all prefixes of a given length, and `yield` the ones that find terminate on targets (this seems absurd).

**Comment by dschult** [comment]
The wikipedia entry on Bellman-Ford says that the algorithm can identify and report negative weight cycles. I think our implementation does this. 

We should make our implementation also report zero weight cycles.

And we should construct ```all_shortest_paths``` to report all shortest simple paths with a comment to that effect near the top of the doc_string.

**Comment by boothby** [comment]
Yes, negative-weight cycles are handled correctly in theory and implementation.  I'm not sure why we'd want to report zero-weight cycles though.  Are you suggesting we raise an exception in Bellman-Ford?

IMHO the most permissive solution would be to also tweak Bellman-Ford to construct simple paths.  I've just pushed that to my current branch; factoring out the path-tracing algorithm from `all_shortest_paths` to an internal `_all_shortest_simple_paths(G, sources, target, pred)`.  Let me know what you think.

**Comment by dschult** [comment]
I like what you've got in  #3783 factoring out the path-tracing from ```all_shortest_paths```.
(sorry for long delay in review)

I think this is ready to merge.  I have one more only somewhat related question...
Right now there is a function ```shortest_simple_paths``` in module ```algorithms.simple_paths.py``` that yields simple paths ordered by length.
That is different from only returning the shortest simple paths (which is what ```all_shortest_paths``` does.  

@jarrodmillman would it be reasonable to rename ```shortest_simple_paths``` to ```simple_paths_by_length```? That would require a deprecation period I suppose. But it might reduce confusion with these shortest_path algorithms.

**Comment by dschult** [comment]
Let's push off renaming discussion to a different PR. This is fine as is.
