### ISSUE TITLE
Review G.adj as property instead of attribute

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#3700]
Currently G.adj is a property that creates an AdjacencyView of G._adj.
Is this better than creating an AdjacencyView during Graph.__init__? 
As a property, it speeds up graph creation by one AdjacencyView instantiation.
But it slows very slightly each use of the form G.adj

Are there other reasons besides speed that a property is better? 
(like, switching G._pred and G._succ to reverse directed edges)

Let's look into it...

**Comment by AndrewEckart** [comment]
I think there is a middle ground that could be useful in some cases: keep the property, but if it is going to be used many times, then store it as a local variable as a performance optimization. For an example of this approach, see #5032.

**Comment by rossbar** [comment]
This seems like it's related to #4895 . For instance, would we get the 10-15x speedup in `nx.selfloop_edges` mentioned in #4895 if `adj` were an attribute instead of a property? Said another way, is the AdjacencyView object creation the bottleneck for that (and other) functions/operations?

There are obviously tradeoffs involved here that affect core functionality, so it'd be nice to have some robust benchmarking in place to get a sense for what the impact would be.

**Comment by dschult** [comment]
This issue about checking if `G.adj` should become an attribute instead of a property was fixed by converting to a cached_property in #5614
So I'll close this issue.
