### ISSUE TITLE
Road network junctions using g.degree()

### ISSUE THREAD

**Issue by ktjaco** [networkx/networkx#3730]
Hello,

I am attempting to generate road network junctions using NetworkX (g.degree()) and I am having some issues. The road junctions I am interested in are dead ends (junctions with a degree equal to 1) and intersections (3 or more segments). 

Below is the script I am using to generate these junctions, however I've noticed that some junctions generated that should have a degree of 3 have been assigned a degree of 2. Junctions with a degree of 2 I am not interested in (for example, roads that create an "L" shape).

Is there any indication what may be causing this? I initially thought it might have to do with the graph not being connected exactly but that is not the case.

Any help or further information would be greatly appreciated!

Kent

![image](https://user-images.githubusercontent.com/14288239/69379424-72396c80-0c7e-11ea-9e33-8e58ea538fc6.png)

```py
import os
import sys
import geopandas as gpd
import networkx as nx
from datetime import datetime

# start script timer
startTime = datetime.now()

sys.path.insert(1, os.path.join(sys.path[0], ".."))

# read shapefile
g = nx.read_shp(os.path.abspath("data/interim/ott_roads_test.shp"))

print("Total number of nodes in original graph: " + str(nx.number_of_nodes(g)))
print("Total number of edges in original graph: " + str(nx.number_of_edges(g)))

g_other = nx.Graph()
g_dead_end = nx.Graph()
g_two = nx.Graph()

other = [node for node, degree in g.degree() if degree > 2]
dead_end = [node for node, degree in g.degree() if degree == 0 or degree == 1]
two = [node for node, degree in g.degree() if degree == 0 or degree == 2]

g_other.add_nodes_from(other)
g_dead_end.add_nodes_from(dead_end)
g_two.add_nodes_from(two)

print("Total number of dead ends: " + str(nx.number_of_nodes(g_dead_end)))
print("Total number of 'other' junctions: " + str(nx.number_of_nodes(g_other)))

nx.write_shp(g_other, os.path.abspath("data/interim/other.shp"))
nx.write_shp(g_dead_end, os.path.abspath("data/interim/dead_end.shp"))
nx.write_shp(g_two, os.path.abspath("data/interim/two.shp"))

# output execution time
print("Total execution time: ", datetime.now() - startTime)
```

**Comment by dschult** [comment]
You haven't given us the information that would be helpful yet (your map and your code don't help us see what the output is nor see what the actual connections in the graph are.  Importantly, we can't run your code and we have no way to tell how the map actually relates to the NetworkX graph you read in.) But perhaps you can look up the info you need yourself.

Since you have a list of the nodes with degree 2, check them.  See what ```G[node]``` is for those nodes.

```python
for node in two:
    print(f"neighbors of node {node} are: ", G[node])
```

It might be worthwhile to pick one such node and investigate that thoroughly -- both in your picture and in NetworkX. The picture clearly shows 3 edges, but NetworkX only records 2. Which one is missing? Why would there be a difference between the two?

Almost certainly it comes down to you making an assumption about what the network looks like that is not what the computer is recording. Maybe that node in the picture is really two nodes? 

Good luck...
