### ISSUE TITLE
Trophic levels (feature suggestion)

### ISSUE THREAD

**Issue by tomalrussell** [networkx/networkx#3736]
Would it be interesting to include an algorithm to calculate trophic levels?

Related notions which could be included are trophic difference and trophic coherence - see wikipedia [1] and [2]. 

This may be a duplicate of #577 from 2012, which was closed due to inactivity.

I've made an initial attempt over at [3], adding a module at `algorithms.centrality.trophic`.

1. https://en.wikipedia.org/wiki/Trophic_coherence
2. Stephen Levine (1980) Several measures of trophic structure applicable to complex food webs. J. theor. Biol. 83, 2, 195-207. https://doi.org/10.1016/0022-5193(80)90288-X
3. https://github.com/tomalrussell/networkx/commit/e715def4abe0a184c0934aa7d6a886b6d5ffe705

**Comment by dschult** [comment]
Yes, we would be interested in this. Your placement in trophic.py looks good. You should use references in the docstrings -- maybe [1] and [2] in your post above.  

Thanks very much!

**Comment by chasmani** [comment]
Hi. I worked with Sam Johnson, who wrote the paper at [1]. I've got some python code for this already, including tests and everything. How can I help?

**Comment by chasmani** [comment]
Hey 

I started adding in some tests and found one that failed. I think we might need to look at the main function again? I can take a look tomorrow I think, or in the next few days anyway. Definitely need to add something to avoid it raising an error if no basal nodes (no nodes with zero in-degree). 

I've also got code to calculate trophic coherence, with tests, so we can add that too. 

I've added a pull request to your code @tomalrussell here https://github.com/tomalrussell/networkx/pull/1


![IMG_20191203_154000](https://user-images.githubusercontent.com/6584368/70067614-6fc40480-15e6-11ea-922f-485157ca91ff.jpg)

**Comment by tomalrussell** [comment]
Thanks @dschult, I'll add those references.

Hey @chasmani thanks for taking a look!

Let's collaborate on the tomalrussell:feature/trophic-level branch and get it into shape for a PR against networkx.

I've merged your tests and pushed a fix to that branch - I'd missed the assumption that for all non-basal nodes, the weights of incoming edges must sum to one.

Is trophic level defined for graphs with no basal nodes? You're right that `np.linalg.inv` throws an error for complete graphs (`numpy.linalg.LinAlgError: Singular matrix`).

**Comment by chasmani** [comment]
Hey @tomalrussell - yes it would be great to collaborate. Thanks for your reply. 

With no basal nodes trophic level isn't defined in at least come cases. For example if you have a cycle of three nodes then there is no solution to the basic trophic level equation - because each node needs a higher trophic level than it's child. That's why the linear equation breaks.

The work I did before was considering graphs without weighted edges. The trophic level calculation involves creating a weighted graph from that, so that like you said the weights of incoming edges sum to one. We're in the process of submitting a paper on it, https://arxiv.org/abs/1909.12603. The Appendix (part A) has a nice derivation of the trophic level calculation.

Like I said I also have code to calculate trophic coherence, as well as the general preferential preying model (introduced in Johnson's paper), so we can add that as well once we have the trophic level function sorted. I'll add in some more tests tomorrow, then we can get the function to pass them all.
