### ISSUE TITLE
Please use major bumps to change public apis

### ISSUE THREAD

**Issue by jonringer** [networkx/networkx#3750]
The graph.node -> graph.nodes change has broken quite a few packages that I maintain. You all are free deprecate as you see fit, but it's unusual for a minor bump to cause breaking changes.

Specifically, this is in regard to https://github.com/networkx/networkx/commit/6b1ce03f485076d39994e8d624bbf6ca82466eb9 and the change of node to nodes, I'm not sure why it wasn't:

```
@property
def node(self):
    logger.warn("The node property is deprecated, please consider using Graph.nodes")
    return self.nodes()
```

I don't think the little `node = nodes` hack isn't working, because node isn't callable anymore:

```
[nix-shell:/home/jon/projects/nixpkgs]$ python
Python 3.7.5 (default, Oct 14 2019, 23:08:55)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
>>> g = networkx.graph.Graph()
>>> dir(g)
['__class__', '__contains__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_adj', '_node', 'add_edge', 'add_edges_from', 'add_node', 'add_nodes_from', 'add_weighted_edges_from', 'adj', 'adjacency', 'adjlist_inner_dict_factory', 'adjlist_outer_dict_factory', 'clear', 'copy', 'degree', 'edge_attr_dict_factory', 'edge_subgraph', 'edges', 'get_edge_data', 'graph', 'graph_attr_dict_factory', 'has_edge', 'has_node', 'is_directed', 'is_multigraph', 'name', 'nbunch_iter', 'neighbors', 'node_attr_dict_factory', 'node_dict_factory', 'nodes', 'number_of_edges', 'number_of_nodes', 'order', 'remove_edge', 'remove_edges_from', 'remove_node', 'remove_nodes_from', 'size', 'subgraph', 'to_directed', 'to_directed_class', 'to_undirected', 'to_undirected_class', 'update']
>>>
```

**Comment by dschult** [comment]
This was changed from v1.x to v2.x with a ```node=nodes``` fix temporarily put in place.
With the removal of support for Python 2.x, we have taken the opportunity to clean up some of the deprecated code, including this removal of the old ```G.node```.  Please update your code to ```G.nodes``` as that is the up-to-date attribute to use and has been since v2.0.  I'm sorry that you would prefer we have named this version v3.0 instead of v2.5. I hope this actually turns out to be a simple search and replace operation for you. Thanks for the idea of creating a property for ```node``` with associated warning. It would have been better to do that for v2.0-v2.5.
