### ISSUE TITLE
MultiGraph: Why does G.edges[key] does not work? Only G.edges[u, v, k] does

### ISSUE THREAD

**Issue by kiryph** [networkx/networkx#3772]
```
type(G)
Out[305]: networkx.classes.multidigraph.MultiDiGraph

list(G.edges)[0:2]
Out[306]: [('1_17_0', '2_16_0', 'e001'), ('1_17_0', '2_15_0', 'e002')]

G.edges['1_17_0', '2_16_0', 'e001']
Out[312]: {'index': 2, 'type': 't', 'transformation': '[[1,0],[0,1]]'}

G.edges['e001']
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-313-46b62708ebb6> in <module>()
----> 1 G.edges['e001']

~/.local/lib/python3.6/site-packages/networkx/classes/reportviews.py in __getitem__(self, e)
   1104 
   1105     def __getitem__(self, e):
-> 1106         u, v, k = e
   1107         return self._adjdict[u][v][k]
   1108 

ValueError: too many values to unpack (expected 3)

nx.__version__
Out[314]: '2.4'
```

Why is it not possible to address an edge in a MultiGraph with the unique key alone? Did I overlook another means to access an edge?

In interactive Jupyter sessions it would be nice when the shorter version would also work.

**Comment by dschult** [comment]
Edge keys are only unique between two edges. In fact the default edge keys are all 0 for the first edge between any pair of nodes. You are thinking of a unique edge key over the whole graph. For that NetworkX uses (u, v, k) as the unique edge key over the whole graph.

**Comment by kiryph** [comment]
Ooh. Ok this is a misunderstanding on my side and how I treated edge keys.

MultiGraphs I know have a unique edge key which I assume lead to my thinking (presumably others may make the same assumption).

Apparently, one can also allow graphs with edge keys only for multi-edges and the 'normal' edges without a key. It is something I just would not do. This looks like I have to check all the time for the type of the edge.

I personally prefer consistency over supporting a more general scenario. However, there might be good reasons I am not aware of.

I assume to have MultiGraphs with unique edge keys would require a new type, something like `EdgeLabelledMultiGraph`. I am obviously not an expert in graph theory and do not know if there would be also reasons from an algorithmic standpoint, not just the convenience in a Jupyter session.

**Comment by dschult** [comment]
Please be careful when using the term "unique edge key". Unique on what scale? Do you see that the term is in itself confusing. Certainly if one MultiGraph has an edge with key 'e001', another MultiGRaph might have an edge with the same key. Would you still call them unique? Instead call them unique within each graph.

Similarly, NetworkX MultiGraphs have unique edge keys within each pair of nodes. So, if there already exists an edge between node 1 and node 2 with key 'e001' then you can't add another edge between 1 and 2 with that same key.

But NetworkX chose to let edge keys be re-used for other pairs of nodes. So edge (1,2,0) can exist along with (2,3,0).

NetworkX does NOT allow a graph to have "edge keys only for multi-edges and the 'normal' edges without a key". Each graph must specify whether it has edge keys (MultiGraph) or not (Graph). The mixed graphs you are talking about have been discussed for NetworkX but we haven't found a good way to implement them yet. 

Also, NetworkX also prefers consistency over a more general scenario. We choose consistency of the return data structure from methods like G.edges(). The return data structure is always 2-tuples. If you want 3-tuples you should use G.edges(keys=True) and this will only work with MultiGraphs.

You can create a subclass of MultiGraph that enforces unique edge keys across the entire multigraph. We have talked about that too. Minor conveniences like referring to an edge by its edge key instead of by a 3-tuple are outweighed by cost of creation/enforcing/checking/storing the unique keys.  Just think of the network-wide edge key as being (u,v,ekey) and it all works smoothly.

**Comment by rossbar** [comment]
It seems like the question was sufficiently answered (thanks @dschult !) so I'm going to close this. Please feel free to reopen if you'd like to pick up the discussion again.
