### ISSUE TITLE
release 2.4 breaks API for nx.Graph

### ISSUE THREAD

**Issue by qudade** [networkx/networkx#3803]
Up to version 2.3 the following was possible

```
import networkx as nx
graph = nx.Graph()
print(graph.node())
```
In version 2.4 this results in

```
>>> graph.node
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Graph' object has no attribute 'node'
```

The reason seems to be that the `node = nodes` aliasing [has been removed](https://github.com/networkx/networkx/commit/6b1ce03f485076d39994e8d624bbf6ca82466eb9#diff-08b36eaddc63c3d59799ce3e16199748L765) (originally announced for 3.x).

**Comment by jarrodmillman** [comment]
This was changed from v1.x to v2.x with a node=nodes fix temporarily put in place.
With the removal of support for Python 2.x, we have taken the opportunity to clean up some of the deprecated code, including this removal of the old G.node. Please update your code to G.nodes as that is the up-to-date attribute to use and has been since v2.0.  I hope this actually turns out to be a simple search and replace operation for you.

**Comment by qudade** [comment]
We'll update the code then - I was just wondering if the incompatibility was intentional. Thanks for the quick response.
