### ISSUE TITLE
High memory usage while reading graphml file?

### ISSUE THREAD

**Issue by deklanw** [networkx/networkx#3828]
I'm reading a large GraphML file with a lot of metadata: 49k nodes and 8.9m edges. The file is 540MB on disk. While reading the file in with `nx.readwrite.read_graphml` Python's memory usage is climbing to about 10-11GB.

Is this normal or is there a bug somewhere here? I'm running Python via WSL on Windows 10.

**Comment by dschult** [comment]
How big is your edge attribute data? Anything that adds memory to each edge it critical with 8.9m edges. During the read process, the function constructs a NetworkX MultiGraph to hold all the information. There is some additional storage to keep track of everything, and then near the end it does copy the MultiGraph to whatever type of graph object is desired. Have you tried it on a graph half as big to see how it scales?  The memory used is very dependent on edge attribute storage space.

**Comment by deklanw** [comment]
My edges had no attributes. It's just ID, source, target.

**Comment by dschult** [comment]
OK... I guess the ID is stored as an attribute.
So that takes however many bytes the length of that string is. Probably not much.
Each edge requires a edgedata dict so that is 240 bytes. The neighbor dicts are 240 bytes when created, but expand if there are more than enough neighbors to cause the dict to allocate more space. So, as a slight overestimate, let's suppose that each edge uses about 500 bytes. The final NetworkX graph will take about 500*10m ~= 5 GB of RAM. And we do copy the graph at the end (in a way that should allow immediate destruction and garbage collection...but it does require the memory to do the copy).

So, the 10-11 GB estimate seems reasonable for this size of graph. We've got [some hacks to keep the memory footprint smaller](https://networkx.github.io/documentation/stable/reference/classes/graph.html?highlight=thingraph), but they aren't built into the GraphML parser.

**Comment by deklanw** [comment]
Edges are like 

```xml
    <edge id="e3" source="n3" target="n2"/>
    <edge id="e4" source="n2" target="n4"/>
    <edge id="e5" source="n3" target="n5"/>
```
Not sure if ID counts as an attribute here.

In any case, graph-tool seems to fit my case better, so I've switched to it. Thanks for your help.
