### ISSUE TITLE
Can we make the graph data structure persistent?

### ISSUE THREAD

**Issue by Sinha-Ujjawal** [networkx/networkx#3877]
Recently I really got into functional programming, was wondering if we can make the graph data-structure functional persistent.

**Comment by dschult** [comment]
Can you explain what you mean by that?

**Comment by kingZthefirst-cypher** [comment]
So networkx provides a DiGraph API for creating Directed Graphs, right. I don't know how it's implemented in the code, but a way we can represent a graph is by using an adjacency list. 

eg-

Below is a digraph, let's call it **ga**

<img src="https://user-images.githubusercontent.com/32126716/77463674-fae23800-6e2b-11ea-9757-a40c5c56e1e5.png" width="200" height="150">

We can represent it as a dictionary of **keys** as nodes and **values** as **set** of adjacent nodes.

```python
ga = {
    'A': {},
    'B': {'C'},
    'C': {'A'},
}
```

Now let's say we want to add a new edge from A to B in the graph **ga**, but we don't want to change **ga**, instead we want to make a copy of it with edge **A->B** in it.

<img src="https://user-images.githubusercontent.com/32126716/77463911-61675600-6e2c-11ea-9029-3cf5c8b6734c.png" width="200" height="150">

One way to do this is to use deep copy to copy **ga** into **gb**, and then add edge **A->B**

```python
import copy

gb = copy.deepcopy(ga)
gb['A'].add('B')

# gb = {
#     'A': {'B'},
#     'B': {'C'},
#     'C': {'A'},
# }
```

Notice that we only had to change the set stored at key 'A', we could have used the sets stored for the remaining keys of **ga** in **gb** (structural / data sharing), but instead we had to make new copies of it.

In a functional setting, any change to a dictionary (associate maps), will create a new copy of it, but still shares a lot of data between them. I was just wondering if we could make the DiGraph functional and how well or worst will ii perform.

Anyway, this is just me wanting to do "pure functional programming" in python (because I feel Haskell is hard). I know for pure functional programming I should probably learn Haskell

**Comment by dschult** [comment]
We tried to implement much of your idea when moving to 2.x.  We called them "views" and they are closely related to "shallow copies". I think you could do what you are thinking about with ```generic_graph_view``` which is used for ```subgraph```. But you could add or remove edges that way.  It creates a View front end that uses the underlying graph for most of the graph information, but checks for changed values before checking the underlying graph.  It would probably take a bit of coding to make it work as you propose. Or at least as I understand what you propose--- that is, you make a copy and add something to the copy. The copy actually just keeps the old graph and doesn't copy it. But it adds a layer of code in front that checks for the changes before looking it up in the old graph.

**Comment by MridulS** [comment]
I'll go ahead and close this issue, there isn't an actionable item here :)
