### ISSUE TITLE
Problem in having different labelling options

### ISSUE THREAD

**Issue by saeid93** [networkx/networkx#3922]
I have a graph that consists of three sets of nodes 1. servers 2. stations 3. users I want to draw them with networks built-in visualization. In the drawing, I want to have the labels for users and stations but not for servers. However, this doesn't work. when I try this:

```
nx.draw_networkx_nodes(network,
                    with_labels=False,
                    nodelist=self.servers_idx,
                    node_size=50, node_shape='s',
                    pos=servers_pos,
                    node_color='r')
nx.draw_networkx_nodes(network, with_labels=True,
                    nodelist=self.stations_idx,
                    node_size=50, node_shape='^',
                    pos=stations_pos,
                    node_color='g')
nx.draw_networkx_nodes(network, with_labels=True,
                    nodelist=self.users_idx,
                    node_size=10, node_shape='o',
                    pos=users_pos,
                    node_color='b')
```

I get the following figure:

![Rn2fF](https://user-images.githubusercontent.com/6298780/79459121-b5f49000-7fea-11ea-8180-58162c8da24d.png)

which as you see shows none of the labels, but I have set the `with_labels` variable value to `True` for stations and users and the expectation is that it will show them. The strange thing is that when I set all the `with_labels` to `True` it will show all the labels. But if I only set one of them to `False` it will not show the other two (like that I have set all of them `False`). Does anyone have any idea what is happening here?

**Comment by rossbar** [comment]
Note that it seems #4033 removed the `with_labels` kwarg entirely, though I'm not sure this was intentional as the removal probably should've been accompanied by a warning. This probably needs a closer look.

Re: the specific issue - one workaround might be to call `nx.draw_networkx_nodes` and `nx.draw_networkx_labels` in two separate steps, e.g.

```python
>>> G = nx.dodecahedral_graph()
>>> pos = nx.spring_layout(G)
>>> nx.draw_networkx_nodes(G, node_size=50, node_shape='^', pos=pos, node_color='g')
>>> nx.draw_networkx_labels(G, pos=pos)
```

It's an extra LOC, but it also affords finer-grained control over the configuration of the labels.

**Comment by dschult** [comment]
Thanks @rossbar... 

The ```with_labels``` keyword argument did nothing within ```draw_networkx_nodes```.  The input was silently ignored without warning or error.  That ```with_labels``` keyword argument exists for ```nx.draw``` and ```nx.draw_networkx```. But if you are getting to the fine-grained detailed functions like ```draw_networkx_nodes``` then you will have to use ```draw_networkx_labels``` to show the labels (as @rossbar points out).

The changes in #4033 make it clear that ```with_labels``` is not a keyword argument of the function by raising an exception when you use an invalid input to the function. So, running your code on the latest version (which will be v2.5) would give an exception telling you that ```with_labels``` is an invalid input parameter.  Hopefully you will no longer have this trouble now that we have fixed this defect. 

I'm going to close this issue because the confusing behavior has been fixed. But please post follow-up questions if this isn't clear.
