### ISSUE TITLE
Possible enhancement: Support for Geopandas GeoDataFrames

### ISSUE THREAD

**Issue by iboates** [networkx/networkx#3932]
I come from a geospatial analysis background and I noticed that there is functionality in networkx to [parse a network from shapefiles](https://github.com/networkx/networkx/blob/9b02800087d6a400ce84f9e44a15eee41c27c4dd/networkx/readwrite/nx_shp.py).

This is certainly very useful, but shapefiles are not the only format for storing geospatial vector data, and in fact they are rather old, being based on technology that is becoming obsolete, and there are [a host of issues with using them](http://switchfromshapefile.org/).

I'm not saying to dump support for them by any means, as they are still very widely proliferated. But there are other libraries that specialize in reading & writing to/from many geospatial formats using GDAL (which is the library responsible for shapefile operations in networkx, and is basically bedrock for all geospatial manipulation libraries).

[Geopandas](https://geopandas.org/) is an extension library for Pandas which adds support for geometry columns and operations by building off of native Pandas types. It also has a very comprehensive input/output system for all the major geospatial file types, and uses shapely to handle geometry, which is also a very robust geometry library for Python.

think that adding support for building networks from GeoPandas GeoDataFrames would be a really good way to unlock interoperability for a very wide range of geospatial data formats by using the GeoDataFrame is a sort of common interface - The [GeoDataFrame.from_file() method](https://geopandas.org/reference.html?highlight=from_file#geopandas.GeoDataFrame.from_file) can open all major geospatial data formats (as defined by fiona, which is another well-used geospatial library for file I/O operations). So if we used the GeoDataFrame as the common interface, you would essentially provide support for all major geospatial formats.

I don't have all the answers here, I just want to start a discussion on this because I think it is an opportunity to add a lot of value to networkx. I have already been using the two (network + geopandas) in unison for some time now and I have found it to already be quite intuitive, even though I have to handle the transformation myself. To get the ball rolling I can share this bit of code which I use to build a networkx graph from a geopandas geodataframe. I know it's probably not optimal, but it is a start:

```
def gdf_to_graph(gdf, geom_col, keep_node_geoms=False, keep_edge_attrs=False) -> nx.Graph:

    # Find all unique start & end points and assign them an id
    gdf["start_node_coords"] = gdf[geom_col].apply(lambda i: (round(i.coords[0][0], 5), round(i.coords[0][1], 5)))
    gdf["end_node_coords"] = gdf[geom_col].apply(lambda i: (round(i.coords[-1][0], 5), round(i.coords[-1][1], 5)))
    node_ids = {}
    i = 0
    for index, row in gdf.iterrows():
        node_1 = row["start_node_coords"]
        node_2 = row["end_node_coords"]
        if node_1 not in node_ids:
            node_ids[node_1] = i
            i += 1
        if node_2 not in node_ids:
            node_ids[node_2] = i
            i += 1

    # Assign the unique id to each
    gdf["source"] = gdf["start_node_coords"].apply(lambda x: node_ids[x])
    gdf["target"] = gdf["end_node_coords"].apply(lambda x: node_ids[x])

    # Make the graph
    if keep_edge_attrs:
        graph = nx.from_pandas_edgelist(gdf, edge_attr=gdf.columns.to_list())
    else:
        graph = nx.from_pandas_edgelist(gdf, edge_attr=[geom_col])

    if keep_node_geoms:
        node_geoms = {node_ids[k]: Point(k) for k in node_ids}
        for n in node_geoms:
            graph.nodes[n].update(geometry=node_geoms[n])

    return graph
```

**Comment by adnanmuttaleb** [comment]
I can work on this feature, is there anything I should take into consideration before I start?

**Comment by jarrodmillman** [comment]
@iboates I don't know anything about geospatial data, so bear with me.

1. How does this relate to #2382?
2. Installing GDAL (https://gdal.org/) is a common problem for NX users.  Is there a solution for helping users with installing GDAL?

**Comment by iboates** [comment]
@jarrodmillman 

1. fiona is an I/O library for geospatial data. The issue which the linked issue directly references seems to be

**Comment by iboates** [comment]
@jarrodmillman Getting close to the boundaries of my knowledge of the Python GIS ecosystem but I will try to make sense of it.

### Question 1

fiona is an I/O library for geospatial data. The issue which the linked issue directly references seems to be due to mixing the Python GDAL bindings (osgeo modules) with shapely. Shapely is a friendlier wrapper to geometric objects and so the Shapely developer is recommending to just use Shapely instead. I would be inclined to agree.

The current NX implementation for reading shapefiles also uses the osgeo modules to open the shapefile and parse out geometric line features and build a topological network out of them. What I am proposing is to open the file as a `GeoDataFame` object offered by `geopandas`. This will create what is effectively just a `pandas.DataFrame` object with a shapely-based geometry column. The topological network can then be built out of that. This is what the code snippet in my first post does, albeit possibly a bit crudely. The reason why I would suggest this is because the `GeoDataFrame` object becomes a sort of Python-based federated interchange format which can be created out of a wide variety of geospatial data formats, shapefiles included.

So, implementing a geopandas-based method for reading geodata files would require re-writing the existing shapefile parsing code to not use `osgeo` anymore, and I think it would actually bypass and possibly even solve the issue that you linked, because `osgeo` would be out of the picture entirely.

### Question 2

Yes, installing GDAL (this includes the osgeo modules) is actually quite notoriously a pain. Since GDAL is itself actually a system binary, it usually gets installed as part of a larger package, which can be complicated if the target system is not configured in a standard way, or if there are limitations related to admin privileges. It could be possible to install it via a wheel file: https://gis.stackexchange.com/a/7617/48798

Another option is to use conda, because conda's gdal package actually installs the system binaries in the virtual environment itself. But I know that conda is controversial so it is probably not an acceptable solution. But this is usually how I do it.

**Comment by iboates** [comment]
I also wanted to say that I will volunteer my time to work on this feature as I think it would be quite useful for my regular day-to-day activities.

**Comment by NicolasCadieux** [comment]
Hi,
This is related to issues 3478.  I would like to work on that.  I also made a script to read shapefiles using geopandas.  We need to fix the 3D shape read problem, fix the parallel edges problem (the are currently rejected by the read shapefiles function.  It would be nice to check for wrong geometries like polygons, or multi-line object that can create problems.  Can I be of any use?

**Comment by jarrodmillman** [comment]
@NicolasCadieux We could definitely use help.  Currently, none of the core developers have any experience working with shapefiles.  We don't even understand the landscape for reading shapefiles in Python or whether they are the main format for spatial data.  Further, we would like to remove the GDAL dependency for networkx.  It is the hardest dependency for us to support.  (As a result, we no longer list it as a dependency in our requirements files.)  We also have no idea to what extent people are using nx_shp.  If they do use it, we don't know if that is a good idea.  Our testing only checks that networkx can read shp files that it creates.  Since we aren't familiar with this format, it is difficult for us to review PRs that "improve" nx_shp.  For instance, we aren't able to determine whether these two PRs are correct:  #4107 and #4205.

Since networkx is a pure Python library that is easy to install and is less specialized than geospatial packages, I think it makes more sense for geospatial libraries to depend on networkx rather than us depending on them.  In fact, some of the geospatial packages already have to/from networkx graph functionality.  As a result, @iboates created this issue: https://github.com/geopandas/geopandas/issues/1592

There seemed to be some interest, but it looks like someone would need to push this effort for it to happen.  I recently made a PR to deprecate nx_shp #4298.  My hope is that we geopandas will add a to/from networkx functionality.  However, it isn't clear to me from reading some of the comments to that issue whether it even makes sense to have a function that converts from shapefiles to NetworkX graphs. For instance, @brendan-ward  asked whether this would be "better handled as a series of examples on how to use GeoPandas + NetworkX, rather than adding functionality directly to GeoPandas."  Given the concerns that people familiar with geospatial data have about supporting this, I am even less certain that we should provide this functionality given we don't understand the format or use cases.

We are also trying to improve our gallery.  It would be great if we could have several examples of using different geospatial packages with NetworkX (e.g., fiona, geopandas, libpysal, momepy, OSMnx, etc.)  My tentative plan was to deprecate nx_shp and try to get some voluteers to provide some examples.  It would also be nice if someone would volunteer to write a paragraph or two providing a brief roadmap to what packages to use to read shapefiles.

Another possibility (that I am less interested in) for potentially keeping nx_shp in networkx would be to:
1. port it to PyShp so we can get rid of the GDAL dependency
2. committing to "owning" the module since someone would need to review future bugfixes.

Would you be able/willing to help out with adding to/from nx.graphs to geopandas?  It isn't clear geopandas would accept such a PR.  Would you be able/willing to create some gallery examples showing how to use geospatial packages with networkx (but not using nx_shp)?  If so, that would be awesome!  We would be more than happy to help you create the gallery examples (assuming you handle the shapefile aspects).  We would also be happy to offer help (to the extent we can) with any PRs to geopandas.

**Comment by NicolasCadieux** [comment]
Hi,
I will read your comments carefully tomorrow.  The bad news is that shapely, and geopandas rely on GDAL.  Would that mess up your plan to get rid of that dependency or would that just pass the trouble to geopandas that already need to take care of that?
Nicolas

**Comment by jarrodmillman** [comment]
I am very happy to hear you are interested in helping us with this!  There are some NX contributors/users (e.g., @iboates) who may also be able/willing to help.  And it seems likely (given the initial response to https://github.com/geopandas/geopandas/issues/1592) that there is some interest in helping out from the larger geospatial community.

The fact that shapely, geopandas, and other libraries depend on GDAL does **not** concern me.  NetworkX wouldn't directly depend on them.  Our gallery of examples would depend on them.  So we would list those dependencies in ``requirements/example.txt``.  Our ``setup.py`` contains the following:
```
install_requires = parse_requirements_file("requirements/default.txt")
extras_require = {
    dep: parse_requirements_file("requirements/" + dep + ".txt")
    for dep in ["developer", "doc", "extra", "test"]
}
```
So users installing networkx wouldn't encounter the dependencies listed in ``requirements/example.txt``.  The examples in the gallery would state that the example requires additional libraries to be installed.  If user's have difficulties installing those packages, we would just direct them to the developers of those packages.  The examples would also help us ensure that when we make changes it doesn't break things for upstream geospatial libraries, since we build the examples with every PR.  Ideally, we would be directing users that have questions about geospatial data and libraries to folks in working in with geospatial data.  And they could direct their users interested in generic network analysis code to us.

This would solve my main two concerns:
1. Since we don't use geospatial libraries (like GDAL), we are not in a good position to help users with install questions.
2. Since we don't use geospatial data, we are not in a good position to review bug reports or PRs regarding ``nx_shp``.

I also think it makes more logical sense to have geospatial libraries depend on networkx, rather than have networkx depend on geospatial libraries.  I suspect the reason that ``nx_shp`` exists is mostly b/c NetworkX existed long before many of the current geospatial libraries for Python were created (not b/c it is the best place for that functionality to exist).

**Comment by NicolasCadieux** [comment]
Ok,
I would like to Skype next week so we can figure things out.  Is there a good time for you?

**Comment by NicolasCadieux** [comment]
Hi,
Anyway we can talk in person about this?  How can I reach you?
Nicolas
