### ISSUE TITLE
The problems about the "similarity.py"

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [networkx/networkx#3941]
Hello ,dear author:

I used your code named “similarity.py” about “how to calculate the GED problem”
([link](https://networkx.github.io/documentation/networkx2.2/_modules/networkx/algorithms/similarity.html#graph_edit_distance )or [link2](https://github.com/networkx/networkx/blob/master/networkx/algorithms/similarity.py) )
I read your code carefully, and have some questions as follows.
# 1. How  how do you store a graph ?
 We know that we often use “adjlist” or “adjmatrix” in the data structure. Every graph in your code use the graph of “networkx” , does it mean that we donnot need to consider the storage of a graph?
# 2. How to define the cost ?
I want to define the cost of opertating on a vertex or an edge like this:
```
path , cost = nx.optimal_edit_paths(graph_nx_1 , graph_nx_2,
                                    node_subst_cost=5,node_ins_cost=1,node_del_cost=1,
                                    edge_subst_cost=4,edge_ins_cost=2,edge_del_cost=3)
```
but it gives some bug which says `"TypeError: 'int' object is not callable".`
I just want to define the cost of every operation on a node or an edge. But the parameter node_subst_cost/node_ins_cost and so on cannot be understood by me. You write the comments during the definition of the function like this :
https://github.com/networkx/networkx/blob/7ae7f0146a33e340acbabe5a11d297e8187cb6d8/networkx/algorithms/similarity.py#L558

# 3.  the more paths, the less similarity between two graphs? 
I print the "path" and "cost" after running the code. I wonder that if I can judge the similarity of two graphs by the number of paths or just the cost ?

I am struggling to  improve the performance of the GED caiculation and want to keep in touch with you. Hope for your reply.  @jwegis @cournape 

Your sincerely, Woog.

**Comment by rafguns** [comment]
Hi, I'm not a networkx maintainer but I'll try to answer your first two questions.

1. This package uses its own graph data structure (`nx.Graph` and derived classes like `nx.DiGraph`). There is documentation on [converting to/from other data structures](https://networkx.github.io/documentation/stable/reference/convert.html).
2. Please check the [documentation of the `optimal_edit_paths` function](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.similarity.optimal_edit_paths.html#networkx.algorithms.similarity.optimal_edit_paths). Arguments `node_subst_cost`, `node_ins_cost` etc. expect functions rather than plain ints.

Sorry, not sure about question 3.

**Comment by tiankonghenlan20113046** [comment]
> Hi, I'm not a networkx maintainer but I'll try to answer your first two questions.
> 
> 1. This package uses its own graph data structure (`nx.Graph` and derived classes like `nx.DiGraph`). There is documentation on [converting to/from other data structures](https://networkx.github.io/documentation/stable/reference/convert.html).
> 2. Please check the [documentation of the `optimal_edit_paths` function](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.similarity.optimal_edit_paths.html#networkx.algorithms.similarity.optimal_edit_paths). Arguments `node_subst_cost`, `node_ins_cost` etc. expect functions rather than plain ints.
> 
> Sorry, not sure about question 3.

Thanks for your reply, I am still reading this code and some paper about GED. Hope keeping contact with you.
