### ISSUE TITLE
What "networkx.algorithms.cuts.boundary_expansion" function exactly mean?

### ISSUE THREAD

**Issue by cherish0** [networkx/networkx#3955]
``` Python
def boundary_expansion(G, S):
    """Returns the boundary expansion of the set `S`.
    The *boundary expansion* is the quotient of the size of the edge
    boundary and the cardinality of *S*. [1]
    Parameters
    ----------
    G : NetworkX graph
    S : sequence
        A sequence of nodes in `G`.
    Returns
    -------
    number
        The boundary expansion of the set `S`.
    See also
    --------
    edge_expansion
    mixing_expansion
    node_expansion
    References
    ----------
    .. [1] Vadhan, Salil P.
           "Pseudorandomness."
           *Foundations and Trends in Theoretical Computer Science*
           7.1–3 (2011): 1–336.
           <https://doi.org/10.1561/0400000010>
    """
    return len(nx.node_boundary(G, S)) / len(S)
```

The document said about "edge boundary" but the source code is about node boundary.

**Comment by dschult** [comment]
This documentation does not seem to match the code -- as you say.
Based on the cited reference, I see no definition of "boundary expansion" as a quantity -- rather it is defined as part of a list of ways in which measures of expansion can be extended. Still, in that definition, it appears that "boundary expansion" refers to nodes rather than edges.

What is your understanding of this term? Can you find a definition published anywhere?  What should this be?

An easy "fix" is to switch the documentation from "edge boundary" to "node boundary". But I think it'd be better to find out whether/how this is actually defined in the literature. And if it isn't then we should say so -- or maybe remove the function...

**Comment by dschult** [comment]
This concept doesn't seem to appear in the literature anywhere else. And even in this place it is stated as an extension that could be done -- not that has been done. I'm going to switch the docstring from edge boundary to node boundary.

**Comment by cherish0** [comment]
Sorry, I totally forgot this issue.

I met this issue when I tried to implement the scoring functions defined in [https://arxiv.org/pdf/1205.6233.pdf](url).
This paper recognizes "Expansion" as the quotient of the edge boundary and the size of set.
I got a wrong answer when i used this function last year.

Maybe an optional parameter "boundary_type" can be added to this function, and let user determine the behavior of this function.
