### ISSUE TITLE
Oddity with networkx.eulerian_path()

### ISSUE THREAD

**Issue by A-GitHub-Wanderer** [networkx/networkx#3976]
This function does not seem to be operating well on a particular example. This function has no restriction on directed or multigraphs, and as far as I know, the graph does not have to be strongly connected because an Eulerian path does not have to have start point and end points equal (as opposed to circuits). Here is an ASCII representation of my network:

```

+-<-+   +-<-+
1   2->-3   4
+->-+   +->-+

```

Inspecting manually, there is an Eulerian path 2->1->2->3->4->3. The output I get from `eulerian_path()` varies oddly depending on the `source` argument.

```
import networkx
print("nx version", networkx.__version__)
# +-<-+   +-<-+
# 1   2->-3   4
# +->-+   +->-+
G = networkx.MultiDiGraph()
G.add_edges_from([
  (1, 2), (2, 1), (2, 3), (3, 4), (4, 3)
])
print("Eulerian path, no source argument", list(networkx.eulerian_path(G)))
print("Eulerian path, source 2", list(networkx.eulerian_path(G, source = 2)))
print("Eulerian path, source 4", list(networkx.eulerian_path(G, source = 4)))
```

Output:

```
nx version 2.4
Eulerian path, no source argument [(2, 1), (1, 2), (2, 3), (3, 4), (4, 3)]
Eulerian path, source 2 [(2, 1), (1, 2)]
Eulerian path, source 4 [(2, 1), (1, 2), (2, 4), (4, 3), (3, 4)]
```

With no source argument, it outputs the expected solution.

With the source argument equal to the source node that was previously found, it does not find a path that covers all arcs.

With a source argument that is an invalid start point for an Eulerian path, it returns a path starting from a different node, contrary to the documentation saying a warning/error will be issued. Edit: moreover, this returned path contains an arc which doesn't exist in the input graph.

**Comment by manasjoshi14** [comment]
I can see several issues in the code and unit tests: 

1) The previous author finds a Euler path/circuit in a reversed directed graph in order to avoid reversing the final Euler path output below:
https://github.com/networkx/networkx/blob/04e1ef2598fa494fc4b0889ef69a71b83ff32493/networkx/algorithms/euler.py#L279-L282 

This works fine if the source is not provided as seen by the first example. In case a source is provided, the source is actually the end of the Euler path in the reversed graph and therefore the code fails in the second example.

2) There are no checks-in "_simplegraph_eulerian_circuit" and "_multigraph_eulerian_circuit" functions whether a Euler path exists at the provided source and therefore the third example fails.

3) Euler path is not properly tested in unit tests :
https://github.com/networkx/networkx/blob/04e1ef2598fa494fc4b0889ef69a71b83ff32493/networkx/algorithms/tests/test_euler.py#L150-L155

@dschult May I take this as a bug fix?

**Comment by dschult** [comment]
I haven't looked into this much yet, but I can verify that the example shown does produce the stated (incorrect) output.  I've put the label "Defect" on this issue. @manasjoshi14 if you can find a/the bug and can fix it that would be great. Does the "source" keyword even make sense with this algorithm? Maybe that needs to be a separate function?
