### ISSUE TITLE
API: Incomplete docstring for authority_matrix and hub_matrix

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4091]
Both `authority_matrix` and `hub_matrix` defined in `algorithms/link_analysis/hits_alg.py` have incomplete docstrings. They are also missing direct unit tests. Perhaps they were not intended to be public API? These functions should either be:
 1. Removed (potentially with deprecation cycle) from the public API or
 2. Documented & tested.

**Comment by dschult** [comment]
These functions haven't been touched (except for style) since put in place in 2008. I suspect they were included as self-documenting pedagogical functions for people learning about authority and hub.  It is true that they are used in one function, but they are called one after the other which duplicates converting G to a numpy matrix, so even that code would be more efficient without these functions.

They can/should probably be turned into docstring examples, (or a gallery example?? if so, should probs be more than just creating the matrices). That means deprecating and removing.  Not just from public API, but from the internals as well.

For a Gallery example, what could we do with the matrices other than compute their spectrum to yield the HITS values?

**Comment by rossbar** [comment]
Thanks for the feedback @dschult that sounds like a good plan. I'll add the documentation label to indicate that there should a at least be a docstring example, and add it to the 2.5 milestone.

**Comment by rossbar** [comment]
I think this can be considered closed by #4617 .
