### ISSUE TITLE
to_pandas_edgelist needs new signature and multigraph handling

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4109]
The ```to_pandas_edgelist``` function signature currently has unused parameters ```dtype``` and ```order```.  This is similar to ```to_numpy_matrix``` so maybe it was copied from there.

We could use ```dtype``` when we create the DataFrame, but ```order``` should not be there as it doesn't apply to pandas DataFrames. 

Furthermore, this function doesn't handle MultiGraphs well. In particular there should be way to specify a column name for the edge key information.  I propose a parameter ```edge_key``` which is similar to the parameter used for ```from_pandas_edgelist```

**Comment by dschult** [comment]
If I'm going to remove the parameter ```order``` from ```nx.to_pandas_edgelist``` do I need to deprecate the old function syntax -- even though it is the last parameter AND it previously did nothing?

Similarly, can I put the new parameter ```edge_key``` before ```dtype``` in the parameter list without deprecating... The current implementation doesn't use ```dtype```.  

The current signature IS in release v2.4.  So it is possible that someone has been using dtype and order without noticing that they don't do anything AND not using the keyword!  But I doubt it... 

Perhaps I can put in place the `/` symbol in this function to enforce keywords.

**Comment by jarrodmillman** [comment]
There seems to be enough change that a deprecation may be warranted.  Also as part of the numpy matrix cleanup (@rossbar), I wonder if we should revisit the API completely for the 3.0 roadmap.  For instance, Aric suggested

> to generalize ``from_numpy_matrix`` to ``from_adjacency_matrix`` and allow either a numpy matrix or a square pandas dataframe

in  https://github.com/networkx/networkx/issues/2029#issuecomment-192766036.  We should start thinking about whether it makes sense to revisit ``networkx/convert_matrix.py `` soon anyway.   For example, #4107 adds ``from_geopandas_edgelist`` and ``from_geopandas_edgelist``.  Maybe we only want ``to_ / from_`` functions for ``adjacency_matrix``, ``edgelist``, and so on.

We should also try to follow our new deprecation policy (if not, we should update it to make sure it reflects our actual policy):
- https://networkx.github.io/documentation/latest/developer/deprecations.html
And we should also add any deprecated code to the list at the bottom of that page (i.e., ``doc/developer/deprecations.rst``)

**Comment by dschult** [comment]
Just to make sure I understand what a "2-release deprecation cycle" is:
We announce in v2.5 that a feature has been deprecated.
In v3.0 (the release after it is announced) that feature is removed.  

(I could also interpret 2-release as meaning the change takes place v3.1...   2 releases later.)

**Comment by jarrodmillman** [comment]
Yes, the "2-release deprecation cycle" would be deprecate in 2.5 , 2.6 and remove in 2.7.  Since we are releasing 3.0, we are going to use a 1-release deprecation cycle for some things.  The policy now says "the 2-release deprecation cycle is not a strict rule."  The policy was copied from scikit-image and it hasn't been included in a release yet.

So we can either just agree that 1) the 3.0 release is special or 2) we could change the policy to a "1-release deprecation cycle" now and change back to a "2-release deprecation cycle" after the 3.0 release.  It may be worth going with option 2 so that it is clearer to users.  Thoughts?

**Comment by rossbar** [comment]
My two cents: treating 3.0 as a "special case" so that deprecations added now expire in only one cycle rather than the traditional two sounds fine to me. If there end up being *a lot* of potentially breaking changes, then perhaps it's worth modifying the policy, but I think people are familiar enough with semantic versioning to already be expecting some API changes anyways.

**Comment by dschult** [comment]
Just so we don't have to remember to go back and update the policy, it might be better to combine them -- we use a 2-release cycle unless the primary number is changing (e.g. from 2.5 to 3.0) in which case a 1-release cycle is used.  I'm fine with whatever works for us. 

This makes even more incentive for us to decide what changes will happen for v3.0 before we release v2.5.

**Comment by jarrodmillman** [comment]
See #4112.

**Comment by dschult** [comment]
Closed by #4384
