### ISSUE TITLE
Repelling nodes based on colors in bigger graph generated from smaller graphs

### ISSUE THREAD

**Issue by amjass12** [networkx/networkx#4146]
Hi all, 

I have generated a graph based on edges in several smaller undirected graphs. The graphs are composed of nodes that are features from aging (so each individual smaller graph is one age). What i would like to see is the transition of edges from one age to another and how communities of features change over time. The bigger graph is generated as follows:

```

g=nx.MultiGraph()
g.add_edges_from(graphAge1.edges(data=True))
g.add_edges_from(graphAge2.edges(data=True))
g.add_edges_from(graphAge3.edges(data=True))

g.add_nodes_from(graphAge1.nodes())
```
etc...

nodes are colored so that any node that is common between all graphs is white and if not it is blue. 
edges are colored such that the edge color represents the age it comes from: A graph composed of edges from three ages produces the following:

<img width="792" alt="Screenshot 2020-08-10 at 12 57 02" src="https://user-images.githubusercontent.com/33659783/89780449-5ece7a00-db09-11ea-8b34-7efe5884dd78.png">

if you look at the the community densely populated by red edges, there are also yellow edges present, however the density of nodes from the red age make it difficult to see! Is there any way that that these nodes can be repelled from one another further so that the yellow and red ages are clearly visible (but without disrupting the community, as these communites tell me which features nodes are connected to at one age and how they change and disband in to certain features are later ages)

Any advice would be much appreciated! Unless there is a better way to construct a big graph from smaller ones and visualise transitions of communities over time?

thanks!

**Comment by rossbar** [comment]
There is a lot to unpack in this issue and I found it difficult to understand. I'm going to close this for now due to inactivity. Please feel free to reopen if the issue persists, but if you do - consider trying to come up with a minimum reproducible example illustrating the problem/feature that you'd like. It would also help to focus on the specific component that your question pertains to (i.e. visualization, constructing graphs, etc.) -- as the scope of a problem grows it becomes much more difficult to understand!
