### ISSUE TITLE
Review public functions in thresholds module.

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4158]
Related to #4157 - There are ~27 functions in the `algorithms.thresholds` module, but only two of them (`is_threshold_graph` and `find_threshold_graph`) are included in `__all__`. Of the non-included functions, some seem like they may be useful while others seem like they may be for internal use only. It would be nice to review this module to include the former in `__all__` and prepend the latter with `_` to further reinforce that they are only for internal use.

Additionally, it seems there may be some functions (e.g. `eigenvectors`) which provide functionality which is implemented elsewhere in networkx. It would be good to consolidate and get rid of any duplicate implementations.

**Comment by dschult** [comment]
That module has a different history than many. It's based on a paper Aric and I wrote about threshold graphs. All those duplicate-sounding functions are there because it is sooo much faster to compute them for threshold graphs than for general graphs.  Restricting yourself to threshold graphs allows very fast computation -- but...   (there's always a "but")

We suspect that not many people use threshold graphs. It is a very restrictive class. Perhaps some sort of decomposition of real networks into nested threshold graphs would be possible, but never been done as far as I know.  Anyway, we didn't want to "pollute" the namespace with these functions that won't get used (and have similar or the same names as other functions). We even had this module out of the documentation completely for a while. But then people discovered it and wondered why we didn't have it hooked in to the docs.

That's part if the trouble with having studied something carefully -- you know its weaknesses.  I'm sure there are other functions we have included in NX that are just as obscure as threshold graphs. But I don't know as much about them.

Anyway, I suspect we either want to keep these in their own namespace, or change the names to make it more clear that they only work for threshold graphs. The two that are public seemed the most useful for someone exploring whether to use these graphs. And the rest are available at ```nx.algorithms.threshold.*``` if needed. But -- really -- we should treat this code like we treat the other code we collect here. In that sense I should recuse myself from the decisions.  But I'll talk your ear off about what the functions do and how they work if you want. :)

**Comment by rossbar** [comment]
Excellent, thanks @dschult for all the background! So it sounds like most functions in the `threshold` module don't belong in the main `networkx` namespace, but may be useful for people who are interested in threshold graphs specifically, so I think the current state of things makes sense. I think it's definitely worthwhile to cleanup the docstrings (#4157), but other than that my vote would be to leave the organization of the module as-is. Individual functions can always be reviewed as new users request that they be exposed :)

I think the explanation just about covers the original issue, so I will close this - please feel free to reopen to continue the discussion!
