### ISSUE TITLE
readwrite.cytoscape_graph(data) removes "source" and "target" fields from edges

### ISSUE THREAD

**Issue by cgrtrifork** [networkx/networkx#4173]
Hi,

I realized the function to get a graph from cytoscape data modifies the data that is received as argument. Is there any reason for that? I couldn't find that in the documentation, and I found it when browsing the code.

Thank you in advance!

**Comment by rossbar** [comment]
> I realized the function to get a graph from cytoscape data modifies the data that is received as argument. Is there any reason for that?

This looks like a defect to me, I don't think the input data dict should be modified. An MRE:

```python
>>> G = nx.path_graph(4)
>>> data_dict = nx.cytoscape_data(G)
>>> data_dict
{'data': [],
 'directed': False,
 'multigraph': False,
 'elements': {'nodes': [{'data': {'id': '0', 'value': 0, 'name': '0'}},
   {'data': {'id': '1', 'value': 1, 'name': '1'}},
   {'data': {'id': '2', 'value': 2, 'name': '2'}},
   {'data': {'id': '3', 'value': 3, 'name': '3'}}],
  'edges': [{'data': {'source': 0, 'target': 1}},
   {'data': {'source': 1, 'target': 2}},
   {'data': {'source': 2, 'target': 3}}]}}
>>> H = nx.cytoscape_graph(data_dict)
>>> data_dict   # 'source' and 'target' keys no longer present for edges
{'data': [],
 'directed': False,
 'multigraph': False,
 'elements': {'nodes': [{'data': {'id': '0', 'value': 0, 'name': '0'}},
   {'data': {'id': '1', 'value': 1, 'name': '1'}},
   {'data': {'id': '2', 'value': 2, 'name': '2'}},
   {'data': {'id': '3', 'value': 3, 'name': '3'}}],
  'edges': [{'data': {}}, {'data': {}}, {'data': {}}]}}
```

> I couldn't find that in the documentation, and I found it when browsing the code.

Unfortunately `cytoscape_graph` is also missing a docstring! Thanks for catching this as well.

**Comment by rossbar** [comment]
FWIW this should be a very straightforward fix that is suitable for new contributors. To do so would require the following:
 1. Add/modify a test in `networkx/readwrite/json_graph/tests/test_cytoscape.py` that will fail with the current behavior but pass with the desired behavior (i.e. the input data is not modified when `cytoscape_graph` is called).
 2. Modify the `cytoscape_graph` function defined in `networkx/readwrite/json_graph/cytoscape.py` so that the input data is not modified by the function

**Comment by cgrtrifork** [comment]
I created a PR addressing this issue: https://github.com/networkx/networkx/pull/4176
