### ISSUE TITLE
edges property and edges() give different results for Multi(Di)Graphs.

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#4179]
``` python
>>> import networkx as nx
>>> G = nx.complete_graph(5, create_using=nx.MultiGraph())
>>> G.add_edge(0, 1)
>>> G.edges
MultiEdgeView([(0, 1, 0), (0, 1, 1), (0, 2, 0), (0, 3, 0), (0, 4, 0), (1, 2, 0), (1, 3, 0), (1, 4, 0), (2, 3, 0), (2, 4, 0), (3, 4, 0)])
>>> G.edges()
MultiEdgeDataView([(0, 1), (0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)])
```

The property one gives out the key name while calling `edges` with the graph object only prints out the nodes. Is this expected behaviour?

**Comment by dschult** [comment]
This was designed this way to avoid backward incompatibility.  But of course now it is an inconsistency.
We should probably do something....

The thinking was as follows: MultiGraphs should have G.edges yield 3-tuples because that is the unique representation of each edge. But we have code that could be much easier to maintain if we return 2-tuples because then the multigraph and graph objects can both work with the same code...  It is useful in this sense to have an option where the same syntax for Graph and MultiGraph yields 2-tuple edges. 

In addition, the v1.x code all used ```G.edges()``` and always got 2-tuples with this syntax. So, we left ```iter(G.edges())``` unchanged in the transition to v2.0. But we implemented G.edges as an object that yields 3-tuples. 

It'd be great to find a consistent useful easy interface...

Actually, consistency is more than you might suspect because ```G.edges``` produces a ```MultiEdgeView``` which yields 3-tuples while ```G.edges()``` returns a ```MultiEdgeDataView``` which yields 2-tuples.  So, if you think of them as different beasts, then no illusion of consistency arises.  But the names are so close to each other that it is easy to start thinking of them as the same thing...

The "How do we handle multiedges?" question rose up very early on...and it will likely continue to be an issue. What' sthe best way to handle G.edges and G.edges()?

**Comment by MridulS** [comment]
Hey @NiklasBeierl!

You could use the `keys` keyword argument to get something similar to `get_out_edges`.

``` python
In [1]: import networkx as nx

In [2]: G = nx.complete_graph(5, create_using=nx.MultiDiGraph())

In [3]: G.add_edge(0, 1)
Out[3]: 1

In [4]: for u, v, node_id in G.out_edges(0, keys=True):
   ...:     print(u, v, node_id)
   ...:
0 1 0
0 1 1
0 2 0
0 3 0
0 4 0
```

But yes we should do a better job of documenting these behaviours of our base classes.

**Comment by MridulS** [comment]
I'll go ahead and close this one as there isn't any specific action item for now.
