### ISSUE TITLE
Review untested functions in utils.misc module

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4224]
There are several functions in `nx.utils.misc` that are not tested. The following gives a rough idea:

```python
>>> import networkx.utils.tests.test_misc as nxtum
>>> set(dir(nx.utils.misc)) - set(dir(nxtum))
   ... see below
```

Some of these functions are used infrequently and/or one-liners that may be candidates for deprecation. In any case, the following list of functions should be reviewed and probably have unit tests added if they are to be kept:
 - [x] `arbitrary_element` #4451
    * Used extensively, esp. in tests. Initial feeling is that it'd be better to document & test this one rather than deprecate
 - [x] `consume` #4449 
 - [x] `default_opener` #4600
 - [x] `empty_generator` #4599 
 - [x] `flatten` #4359
 - [x] `generate_unique_node` #4454
 - [x] `is_iterator`  #4279 
 - [x] `is_list_of_ints`  #4280

**Comment by MridulS** [comment]
this looks like a good candidate for sprints?

**Comment by jarrodmillman** [comment]
Some of the functions in ``nx.utils.misc`` were originally copied from other places.   For example, ``consume`` and ``pairwise`` are recipes from itertools documentation.  It would be worth checking if these recipes have been improved or replaced.  Also, it looks like ``consume`` is just another name for ``deque`` with an option set and is only used once in our codebase.  So we may want to deprecate it as well.

We may want to review other modules in ``nx.utils``.

- For example, now that we depend on NumPy/SciPy, we may want to review ``utils/random_sequence.py``.  I also wonder if any of those distribution are now provided by Python directly.
- I also wonder if ``utils/heaps.py`` can be simplified (Python's ``heapq`` has been improved since this module was added 7 years ago).

**Comment by jebogaert** [comment]
I can work on it, i don't know if this issue has to be assigned or if i should just fork the project and add a pull request when done ? Sorry if it is a dumb question, i'm quite new to open source contribution but i like networkx and i want to help if possible. Thanks in advance for your answer :)

**Comment by rossbar** [comment]
@jebogaert it's not a dumb question :) We typically don't assign issues, so please feel free to contribute to anything that you find interesting!

**Comment by suvayu** [comment]
Tests for `utils.misc.flatten` are in #4359

**Comment by jebogaert** [comment]
I was implementing the MinHeap class in networkx/utils/heaps.py and i saw that the BinaryHeap class has a strange behaviour: 
- It creates (key, counter, value) tuples that it stores in the heap, but it doesn't make any use of it. Is it used anywhere else is the code ?
- It orders the heap using the values rather than the keys. Again, is it intented ?

Here is a screen shot of what is the heap like after calling insert("zero", 0), insert ("one", 1), insert("two", 2) and insert("three", 3). 
![image](https://user-images.githubusercontent.com/38529198/99426354-43db8500-2904-11eb-8d81-8c3a90649b65.png)

I think it should rather be something like : 
![image](https://user-images.githubusercontent.com/38529198/99426211-1ee71200-2904-11eb-8b52-8aa0193e043e.png)

Am i missing something or should i make the changes ?

**Comment by jarrodmillman** [comment]
It looks like MinHeap was just intended as a baseclass for PairingHeap and BinaryHeap.  I don't think it was intended to be used directly.

I am not sure about the BinaryHeap issue you mention.  It looks like PairingHeap and BinaryHeap were implemented b/c heapq didn't have an "efficient implementation of the decrease-key operation:"
https://github.com/networkx/networkx/pull/1094

Before working too much on this, you should look at ``algorithms/connectivity/stoerwagner.py`` and see if we still need our own implementation of ``BinaryHeap``.  You would probably need to write some benchmarking code to see if we are still getting performance improvements using our own implementations over ``heapq`` directly.  I also suspect this is not the easiest place to get started contributing to NetworkX unless you have specific usecases for why you need to modify this code.

Adding tests to untested parts of ``utils`` would likely be a more useful way to start contributing to the codebase.

**Comment by rossbar** [comment]
All of the cases list in the OP have now been addressed one way or another, so closing as resolved.
