### ISSUE TITLE
How to remove float('nan') from a graph?

### ISSUE THREAD

**Issue by zxxml** [networkx/networkx#4247]
It is possible to add `float('nan')` to a graph as a node.
```
import networkx as nx
G = nx.Graph()
G.add_node(float('nan'))
```
However, I donot know how to remove this node from the graph. `G.remove_node(float('nan'))` raise a `NetworkXError` telling me that there is not a node `float('nan')` in the graph. But `G.nodes` shows that the node exists.

**Comment by rossbar** [comment]
Note that this is a quirk of Python dictionaries (on which the graph classes are based). For example, try the following (note: on Python 3.8.5):

```python
>>> d = {float('nan') : 1}   # this is allowed
>>> d[float('nan')]
Traceback (most recent call last)
   ...
KeyError: nan
```

Dicts with nans are a strange beast - for a little context you might find this [SO post](https://stackoverflow.com/questions/6441857/nans-as-key-in-dictionaries) interesting.

IMO it would be an improvement for networkx to break with Python's dict behavior in this instance and raise an error if a user tries to create a `nan` node, since it screws up subsequent lookup/removal. It's also easy to envision how a user might hit this problem while working with numerical data with `nan`s in it (which is pretty common in data analysis).

I'm very curious about other perspectives though - are there use-cases where graphs with `nan` node(s) are useful/meaningful? What would the semantics be?

**Comment by dschult** [comment]
Actually, it's good to avoid any floating point numbers as keys for dicts. 
Round-off makes floating point values really bad for lookup.

The trouble with NaN though is that "equality" doesn't hold for NaN with itself.
Still, it's not good to use any kind of floating point for nodes.  
If you really want them you can convert to integers (after scaling up as large as you want).

**Comment by zxxml** [comment]
> Note that this is a quirk of Python dictionaries (on which the graph classes are based). For example, try the following (note: on Python 3.8.5):
> 
> ```python
> >>> d = {float('nan') : 1}   # this is allowed
> >>> d[float('nan')]
> Traceback (most recent call last)
>    ...
> KeyError: nan
> ```
> 
> Dicts with nans are a strange beast - for a little context you might find this [SO post](https://stackoverflow.com/questions/6441857/nans-as-key-in-dictionaries) interesting.
> 
> IMO it would be an improvement for networkx to break with Python's dict behavior in this instance and raise an error if a user tries to create a `nan` node, since it screws up subsequent lookup/removal. It's also easy to envision how a user might hit this problem while working with numerical data with `nan`s in it (which is pretty common in data analysis).
> 
> I'm very curious about other perspectives though - are there use-cases where graphs with `nan` node(s) are useful/meaningful? What would the semantics be?

In fact, this problem is caused by a [dataset](https://github.com/LCS2-IIITD/CoReRank-WSDM-2019) provided by [Aditya Chetan](https://github.com/justachetan). This dataset use a graph to represent the user-tweet relationship. Node for user or tweet, and edge for tweeting or retweeting. I don't know why there is NaN node in the dataset and just try to delete it.

I know how to remove NaN nodes now: use a loop to find all of them and save the references, then call `remove_nodes_from()` to delete them.

**Comment by rossbar** [comment]
> Actually, it's good to avoid any floating point numbers as keys for dicts.

I'd say this is the key takeaway from this issue.

If more problems like this crop up it may be worth considering a check for `float('nan')` during node creation on the principle of "fail early, noisily, and specifically", but the general advice of using integer nodes is better (and would catch the problem when trying to convert `float('nan')` to `int`).

I will close this as resolved for now, but please don't hesitate to comment/re-open if this gets run into again.
