### ISSUE TITLE
OrderedDiGraphs and successors

### ISSUE THREAD

**Issue by Nolagx** [networkx/networkx#4248]
Do OrderedDiGraphs report the successors of a node in the order that the edges to the successors were added?
For example:

```
g = nx.OrderedDiGraph()
g.add_node(3)
g.add_node(4)
g.add_node(5)
g.add_edge(3, 5)
g.add_edge(3, 4)
successors = list(g.successors(3))
```

In this case, will successors always be [5,4]?

**Comment by dschult** [comment]
Actually, for Python 3.6 or later the behavior of Graph/DiGraph is also ordered because dict's became ordered with that version.

And...   The order of adjacency reporting... g.adj, g.successors, g.predecessors is indeed the order of edge adding.
But the order of g.edges is not always the order of edge adding. The order of g.edges is the order of the adjacencies which includes both the order of the nodes and each node's adjacencies.

```python
g = nx.DiGraph()
g.add_edge(2, 1)   # adds the nodes in order 2, 1
g.add_edge(1, 3)
g.add_edge(2, 4)
g.add_edge(1, 2)
assert list(g.successors(2)) == [1, 4]
assert list(g.edges) == [(2, 1), (2, 4), (1, 3), (1, 2)]
```

**Comment by Nolagx** [comment]
Thanks, good to know!
