### ISSUE TITLE
`cycle_basis` broken

### ISSUE THREAD

**Issue by chadrick-kwag** [networkx/networkx#4256]
I believe the result of `cycle_basis` for a simple 2x2 table grid graph is wrong.

the graph is like this:
9-1-2
|    |   |
8-3-4
|    |   |
7-5-6

```

edges = [
    (1,2),
    (2,4),
    (1,3),
    (3,4),
    (3,5),
    (4,6),
    (5,6),
    (8,3),
    (8,7),
    (5,7),
    (1,9),
    (9,8)
]

# g.add_edge(1,2)
g.add_edges_from(edges)

# nx.drawing.nx_pylab.draw(g)

cb = nx.cycle_basis(g)

print(cb)

# result: [[3, 8, 9, 1], [3, 5, 7, 8], [2, 4, 6, 5, 7, 8, 9, 1], [3, 4, 6, 5]]
```
 instead of [2, 4, 6, 5, 7, 8, 9, 1], [1,2,4,3] should have been the answer, isn't it?

**Comment by dschult** [comment]
I don't understand.... [1,2,3,4] is not a cycle in this network.

**Comment by chadrick-kwag** [comment]
@dschult  oh I meant [1,2,4,3]
perhaps I need to use `minimum_cycle_basis' to get what I want?

**Comment by dschult** [comment]
The result is a perfectly good basis for the cycles.
To obtain [1,2,4,3] just take [2, 4, 6, 5, 7, 8, 9, 1] - [3,4,6,5] - [3,5,7,8] - [3,8,9,1]
The edges 1-2 and 2-4 appear in the 1st term, 4-3 comes from subtracting the second, 3-1 from subtracting the fourth.
Other edges cancel out: 9-1 and 8-9 in 1st minus 4th, 8-3 in 3rd and 4th, 8-7 and 5-7 in 1st and 3rd, 5-3 in 2nd and 3rd, 5-6 and 6-4 in 1st minus 2nd.

Just like coordinate axes are not unique, cycle bases are not unique. This one is perfectly fine.
What don't you like about it? Is there a reason you want [1,2,4,3] instead of the big cycle?

**Comment by rossbar** [comment]
This has been dormant for a while, so I'm going to close this as resolved. If the problem persists, please feel free to reopen.
