### ISSUE TITLE
Error in maximum_spanning_arborescence algorithm

### ISSUE THREAD

**Issue by binh-vu** [networkx/networkx#4271]
I found that the current implementation of the `networkx.algorithms.tree.branchings.maximum_spanning_arborescence` does not return an optimal solution and also not return consistent result.

Networkx version: `2.5`

I tested the algorithm with a graph, that is serialized to two JSON files in [here](https://gist.github.com/binh-vu/8e9775669d6e734a2739b1258263cdb0) and [here](https://gist.github.com/binh-vu/1e3bd1d54fe3d0dd1486b9966bd96fe2). The only different between the two files is the order of nodes/edges.

Code to load the graph:

```python
def load_json(infile: str):
    data = json.loads(open(infile).read())
    g = nx.MultiDiGraph()
    for nid, ndata in data['nodes']:
        g.add_node(nid)

    for i in range(len(data['edges'])):
        data['edges'][i][0] = tuple(data['edges'][i][0])

    for (uid, vid, eid), edata in data['edges']:
        g.add_edge(uid, vid, eid)

    nx.set_node_attributes(g, dict(data['nodes']))
    nx.set_edge_attributes(g, dict(data['edges']))
    return g
```

Code to run maximum_spanning_arborescence
```python
resp = nx.algorithms.tree.branchings.maximum_spanning_arborescence(g, attr='weight',
                                                                       preserve_attrs=True)
count = sum(edata['data']['weight'] for s, t, e, edata in resp.edges(data=True, keys=True))
print(count)
```

The results are 54 and 63 (weight). They should be equal as the two input graphs are identical and the optimal solution is 67. My initial guess is this is due to choose different roots, but the interface of the algorithm doesn't have anyway for me to run with different roots.

**Comment by CyberMobius** [comment]
For what it's worth, I'm working on a new algorithm for maximum spanning arborescence as part of #3825. Progress on it has been pretty slow but hopefully whenever I finish that out it squashes the bug you're having and brings with it a boost in performance. 

I don't know too much about the current algorithm but if anyone really wanted to look into it, my best guess would be to look into how it handles circuits. Since it starts by picking enough edges for an arborescence as well as some extra ones, it ends up creating loops. It then selects which edges from the loops to discard to create a maximum arborescence. I suspect there might be a bug in either how it creates loops or how it discards edges from them (or both). The loops are created by iterating through the nodes in the order that they are added so it would explain why shuffling the order of the nodes changes the output. 

Either way I'll try and get a PR for the new algorithm ASAP.

**Comment by dschult** [comment]
I think the trouble is not the algorithm in this case. The edge data is not fully unpacked in your example. The edge data looks like:

```python
g.edges['1', 'stmt:1-P131']          # =>  {'data': {'weight': 14, 'predicate': 'P131'}}
```
In your graph, each edge has only one attribute called ```data```. The value of that attribute is what would normally be the edge attribute dict. I think this is what you want:
```python
g.edges['1', 'stmt:1-P131']          # => {'weight': 14, 'predicate': 'P131'}
``` 

To make your code load correctly, try changing the adding of the attrubutes:
```python
def load_json(infile):
    data = json.loads(open(infile).read())
    g = nx.MultiDiGraph()
    g.add_nodes_from((n, d['data']) for n, d in data['nodes'])
    g.add_edges_from((u, v, k, d['data']) for (u, v, k), d in data['edges'])
    return g

G=load_json('graph1.json')
arb=nx.maximum_spanning_arborescence(G,'weight')
sum(wt for u,v, wt in arb.edges.data('weight'))       
```
Then I get 67 for the solution.

**Comment by binh-vu** [comment]
Oh, you're right. This is an embarrassing mistake. 

Thank you very much for spending your time investigating this. I appreciate it!
