### ISSUE TITLE
Harmonic centrality computation  - why directed Graph gets reversed?

### ISSUE THREAD

**Issue by KrisNeys** [networkx/networkx#4290]
In the source code of "harmonic_centrality(G, nbunch=None, distance=None)" - there is:
if G.is_directed():
        G = G.reverse()

when computing Harmonic centralities for directed graphs we get a discrepancy with the values produced using the Graph-Tool package, but this difference goes away when G gets reversed again, i.e. we get the original graph. Could it be this is a mistake and G should not get reversed?

Thanks,
Kris

**Comment by dschult** [comment]
What definition do they use? Does Graph-tool cite a paper (or give their definition).

Our doc_string has the formula for harmonic centrality as defined in the paper [Boldi and Vigna 2013](https://arxiv.org/pdf/1308.2140.pdf) cited in our doc_string.
The sum is over nodes v and uses the distance from v to the node of interest u.  By distance, the paper defines d(v, u) as the length of a path from v to u.

We reverse the graph because our shortest_path_length routines are convenient for finding distance from one node x to all others y. So, by reversing the graph we can find d(v, u) for all v by using our shortest_path_length routines.

**Comment by KrisNeys** [comment]
> What definition do they use? Does Graph-tool cite a paper (or give their definition).
> 
> Our doc_string has the formula for harmonic centrality as defined in the paper [Boldi and Vigna 2013](https://arxiv.org/pdf/1308.2140.pdf) cited in our doc_string.
> The sum is over nodes v and uses the distance from v to the node of interest u. By distance, the paper defines d(v, u) as the length of a path from v to u.
> 
> We reverse the graph because our shortest_path_length routines are convenient for finding distance from one node x to all others y. So, by reversing the graph we can find d(v, u) for all v by using our shortest_path_length routines.

thank you - you are right and I was wrong; the graph-tool does not give a clear definition but i tested networkx on a toy graph  where i used BFS and they match. Thanks again for clarifying.
