### ISSUE TITLE
Delete redundant dependencies in the DAG graph

### ISSUE THREAD

**Issue by riskiest** [networkx/networkx#4315]
In the recent module dependency processing, I found that in order to better analyze, it is necessary to deal with the redundant dependencies in the DAG graph. So a simple implementation was made according to the asterix314's reply at https://mathematica.stackexchange.com/questions/33638/remove-redundant-dependencies-from-a-directed-acyclic-graph. the result is exactly the same as Wolfram Mathematica, and the code runs rather fast. I don't know if the community welcomes such code. I will post it below first. I may improve the code and raise a PR and contribute if it is OK and needed.

```python
from scipy.sparse import csr_matrix
import networkx as nx

def reduceDagGraph(DAG):
    '''delete redundant dependencies in the DAG graph'''
    # Algorithm from the link：
    # https://mathematica.stackexchange.com/questions/33638/remove-redundant-dependencies-from-a-directed-acyclic-graph
    A = nx.adjacency_matrix(DAG)
    cnt = 1 # DEBUG
    B = A
    S = csr_matrix(A.shape, dtype=A.dtype)
    while True:
        B = B*A
        B = B.sign()
        S = S+B
        cnt += 1
        p = B.nnz
        print(f"cnt:{cnt}, p:{p}") # DEBUG
        if p==0:
            break
    S = S.sign()
    A_and_S=A.multiply(S)
    A_diff_S = A-A_and_S

    # Generate the result graph based on the adjacency matrix and the name list of the original graph
    new_DG = nx.from_scipy_sparse_matrix(A_diff_S, create_using=nx.DiGraph)
    map = {index:str(name) for index, name in enumerate(DAG.nodes())}
    new_DG = nx.relabel_nodes(new_DG, map, False)
    return new_DG
```

**Comment by dschult** [comment]
This looks like a useful function/algorithm to include in dag.py in NetworkX. It'd be great to have a PR for it.

Some comments/questions:
 - Does it work (return the same values) to use:  `A = nx.to_scipy_sparse_matrix(DAG)`? I think you then need later: `B = B@A` instead of `B = B*A` but otherwise everything goes through and we've saved some RAM and presumably computation times as well.

 - Can you make the while condition: `while p>0` and avoid the `while True:   later break` idiom.
 
 - It seems like a more graph oriented would be possible where you do a breadth first search starting from the roots (in_degree == 0) and any time you discover a new nodes, yield the edge that got there (or add it to the new_DG).  My guess is this would be faster than the linear algebra approach, but maybe not -- and maybe it has been studied before.  Any insights?

Thanks!

**Comment by riskiest** [comment]
I searched for related terms and found that networkx has already been implemented. 
https://networkx.org/documentation/stable//reference/algorithms/generated/networkx.algorithms.dag.transitive_reduction.html

**Comment by AbhayGoyal** [comment]
Hey, maybe I could take this task next?

**Comment by riskiest** [comment]
OK for me, but I don't see the point as Networkx has already done it.

**Comment by dschult** [comment]
Thanks -- I'll close this Issue then. :)
