### ISSUE TITLE
weakly_connected_components: Editing yielded sets during iteration has buggy side effects

### ISSUE THREAD

**Issue by Makman2** [networkx/networkx#4331]
When modifying the yielded component sets during iteration from `weakly_connected_components`, strange things happen:

```python
import networkx as nx
g = nx.MultiDiGraph()

g.add_edge(0, 1)                                                                      
g.add_edge(1, 0)                                                                      
g.add_edge(0, 3)                                                                      
g.add_edge(0, 3)                                                                      

print('Okay:')
print(list(nx.weakly_connected_components(g)))
# Everything alright, gives: [{0, 1, 3}]

print('Still okay:')
for n in nx.weakly_connected_components(g):
    print(n)
    n.remove(0)
# Will print once: {0, 1, 3}

print('NOT okay:')
# Deleting the wrong node during the iteration:
for n in nx.weakly_connected_components(g):
    print(n)
    n.remove(1)
# Will print the set twice:
# {0, 1, 3}
# {0, 1, 3}
```

In case this is actually desired (which I doubt), that should be at least documented that the connected component set is not to be edited.

**Comment by Makman2** [comment]
As to date using the latest release v2.5.
```python
In [2]: nx.__version__                                                                        
Out[2]: '2.5'
```

**Comment by dschult** [comment]
This looks like a bug I believe we ran into elsewhere in the code before. The set that is yielded is added to the `seen` dictionary AFTER yielding. Therefore any changes to it affect whether the algorithm thinks it saw this set previously.   This is definitely a bug.  And should be easily fixed by updating the "seen" dictionary before yielding the set `c`.

While we do this, we need to check the other `weakly_connected` code and I see it in one place in the `strongly_connected` code as well... so we better look through that as well.

**Comment by dschult** [comment]
I think I've got the bug squashed. I added some tests so it doesn't come back.
Thank you for reporting it!!

**Comment by Makman2** [comment]
Cool thank you, that was quick :) I imagined that a reference to the yielded set was kept around and still used inside `weakly_connected_components`.

I guess I will stick now with my simple workaround: copy the set again with `set(x)` inside the loop until the next release happens :)
