### ISSUE TITLE
Clustering coefficient of weighted graph

### ISSUE THREAD

**Issue by qxu1994** [networkx/networkx#4348]
Hi! I'm trying to use networkx.algorithms.cluster.clustering to calculate the clustering coefficient of a weighted network. I noticed that the formula listed in the networkx reference is slightly different from the formula in the paper being cited [1]. Could I ask why?

In the [networkx reference](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.cluster.clustering.html#networkx.algorithms.cluster.clustering), the constant number in the numerator is 1. In the paper[1], that constant number is 2. 

I believe it should be 2, as it should be adapted from the calculation of all possible triangles, namely deg(u)(deg(u-1))/2. 

Thanks!

[1] Intensity and coherence of motifs in weighted complex networks by J. P. Onnela, J. Saramäki, J. Kertész, and K. Kaski, Physical Review E, 71(6), 065103 (2005).

**Comment by dschult** [comment]
That is a confusing part of the docs. I think the confusion is caused by the code where the term `triangles` is used to represent what is actually two times the number of triangles. The code correctly includes the 2, but someone looking at the code might think the 2 is not there. So I suspect the docs incorrectly interpreted the code as not have the factor of 2. 

While we're changing the docs for `clustering`, they don't even show the formula used for a weighted directed clustering case.

**Comment by qxu1994** [comment]
Thanks for the clarification!
