### ISSUE TITLE
read_dot hangs when loading dot graph

### ISSUE THREAD

**Issue by 5hadowblad3** [networkx/networkx#4367]
Hi, there.

Networkx is super cool for graph analysis.

However, recently when I try to analyze a [dot graph](https://drive.google.com/file/d/17YEmdkjoDzlpBXr21RQDU-SS_J6-3eNk/view?usp=sharing), networkx is stuck after more than 24 hours loading this dot with `read_dot` function.

The full code is like this:
~~~~
import networkx.drawing.nx_pydot as pdot
g = pdot.read_dot(dot_file)
~~~~

My python version is 3.7.4 and the version of networkx is 2.5.

I would like to hear your advice on this issue.

Thank you.

**Comment by MridulS** [comment]
The linked dot file is pretty big.
How big is the graph? (nodes and edges)

**Comment by 5hadowblad3** [comment]
I am not exactly sure. The dot graph is around 300 Mb and the node is more than 1000000 I think.

**Comment by dschult** [comment]
That's pretty big.  You should try[ the pygraphviz interface to dot files within NetworkX](https://networkx.org/documentation/stable/reference/drawing.html#graphviz-agraph). But that might take a long time too -- no promises.

**Comment by 5hadowblad3** [comment]
Thank you! I will try it. Is there any recent plan for supporting networkx handling large scale graph?

**Comment by 5hadowblad3** [comment]
I have 4 similar dot graphs like the reported one here, and I accidentally finish one of them.

However, I find the average memory usage of reading this graph is larger than 150 Gb and keep growing until all the memory is used up.

This probably is the reason why the it hangs.

**Comment by dschult** [comment]
It sounds like you have a memory issue. NetworkX stores a dictionary to hold the edge attributes for each edge. This can use a lot of memory if you can a lot of edges or many attributes.  Dot files often have memory intensive edge attributes because it is a format for drawing. You could preprocess the dot files to remove some of the edge attributes. 

You could also try using the [ThinGraph subclass of Graph](https://networkx.org/documentation/stable/reference/classes/graph.html) and you can use integers instead of strings for your nodes. But I think both of those options are not effective when reading from a dot file.

To address your question about support for large graphs in NetworkX: NetworkX is capable of working with graphs with the number of nodes and edges you are talking about (1.5M edges). But once you start storing information on each edge it uses a lot of memory to store those that information. I think the trouble here is that the dot file is creating edge attributes for each edge. Can you get the graphs in a format other than dot?

**Comment by 5hadowblad3** [comment]
Yes. After I delete the information on edges, it can be process after few hours running. But It cannot well satisfy my demand due to the information lost.

I think other file formats cannot help if I want to preserve the information on edges right?

**Comment by dschult** [comment]
If you can use another structure to hold the edge information it might work.
Somehow the information is stored in 300 MB in the file. What makes it expand so much?
Does the file only store default values while the pydot created graph holds those default values on every edge?
Some other reason?

You don't have to store edge attributes on the edges. You can use a separate structure that might be more efficient, for example with default values. It depends what you are trying to do.

**Comment by 5hadowblad3** [comment]
Actually, each node represents a program instruction and each edge represents its control flow information. Since the analyzed program is large, the dot graph generated is also large.

I guess I can separate this information from the dot graph with certain mapping even though combining them together would certainly bring some convenience.

Thanks overall.

**Comment by rossbar** [comment]
I'm going to close this as resolved. If you'd like to follow up or have some new insight on what could be improved here, please don't hesitate to reopen!
