### ISSUE TITLE
Improve nx_pylab testing

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#4389]
Currently our visualization test suite are smoke tests.  We should investigate using ``pytest-mpl``
- https://github.com/matplotlib/pytest-mpl

See #4375.

**Comment by rossbar** [comment]
I ran into an issue while debugging a hang in `test_pylab` due to the recent addition of non-smoke tests (i.e. tests that assert things about axis geometries) in f559558 (#4374):

The default behavior for the `nx_pylab` functions when the `ax` kwarg is `None` (the default value) is to call `plt.gca()`. Note that axis objects created in unit tests persist across function boundaries! 

```python
def test_1():
    fig, ax = plt.subplots()

def test_2():
    ax = plt.gca()   # This is the axis object created in test_1!
```

This crosstalk between tests can lead to unstable/unexpected test behavior, so it's important to recognize. The solution used in #4374 is to call `plt.delaxes` as a "cleanup" step in the unit tests that create axes objects. There's probably a better solution to this, and something to keep in mind as the `nx_pylab` tests are improved.
