### ISSUE TITLE
Anaconda version of pygraphviz is broken

### ISSUE THREAD

**Issue by hayesall** [networkx/networkx#4552]
**Update for conda users: Please make sure pygraphviz from the conda forge channel: `conda -c conda-forge`**

---

### Current Behavior

[`networkx.drawing.nx_agraph.from_agraph`](https://networkx.org/documentation/stable//reference/generated/networkx.drawing.nx_agraph.from_agraph.html) seems to fail with older versions of `pygraphviz`

The example from the documentation:

```python
import networkx as nx
K5 = nx.complete_graph(5)
A = nx.nx_agraph.to_agraph(K5)
G = nx.nx_agraph.from_agraph(A)
```

... currently raises a `StopIteration` `RuntimeError` in `pygraphviz==1.3`, but succeeds with `pygraphviz==1.6`

<details>
<summary>Full Traceback raised with pygraphviz 1.3 installed</summary>

```console
Traceback (most recent call last):
  File "/home/hayesall/miniconda3/envs/spf/lib/python3.7/site-packages/pygraphviz/agraph.py", line 1750, in iteritems
    ah = gv.agnxtattr(self.handle, self.type, ah)
StopIteration: agnxtattr

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "reporod.py", line 4, in <module>
    G = nx.nx_agraph.from_agraph(A)
  File "/home/hayesall/miniconda3/envs/spf/lib/python3.7/site-packages/networkx/drawing/nx_agraph.py", line 82, in from_agraph
    N.graph.update(A.graph_attr)
  File "/home/hayesall/miniconda3/envs/spf/lib/python3.7/site-packages/pygraphviz/agraph.py", line 1740, in keys
    return list(self.__iter__())
  File "/home/hayesall/miniconda3/envs/spf/lib/python3.7/site-packages/pygraphviz/agraph.py", line 1743, in __iter__
    for (k, v) in self.iteritems():
RuntimeError: generator raised StopIteration
```

</details>

### Environment

Python version: `3.7.7`
NetworkX version: `2.5`

pygraphviz: `1.3` -- Fails
pygraphviz: `1.6` -- Succeeds

### Additional context

- I couldn't find a minimum version for `pygraphviz` documented here, but an error message might help this.
- I think `pygraphviz==1.3` is default with Anaconda (`conda install pygraphviz`).

**Comment by jarrodmillman** [comment]
We don't support ``pygrapphviz==1.3`` anymore.  Anaconda stopped maintaining Graphviz and PyGraphviz years ago.  I've repeatedly tried to get them to fix the situation over the last several months.  But I haven't had any success.

You can find the requirements in the requirements files.  For example, you can find the current required version of PyGraphviz for the master branch here:
- https://github.com/networkx/networkx/blob/master/requirements/extra.txt

Here is the requirements file from the 2.5 tagged release:
- https://github.com/networkx/networkx/blob/12f852f6a686ed32f718125c5965586dd6bb82a9/requirements/extras.txt

If you have to use Anaconda for some reason, you may be able to get networkx-2.0 to work with it.  However, networkx-2.0 officially requires pygraphviz 1.3.1 (although it has been so long I can't remember what 1.3.1 fixed compared to 1.3).  So you may need to use NetworkX 1.11 if you need to use Anaconda:  https://pypi.org/project/networkx/1.11/

I know that is old, but Anaconda hasn't updated PyGraphviz since 2015 and the version of Graphviz they support (2.40.1) is broken and there is no release of PyGraphviz that works with that version of Graphviz.  So I would highly recommend against using Anaconda.

Out of curiosity, is there any specific reason why you want to use Anaconda?  Are you on Windows?

**Comment by hayesall** [comment]
I missed the `extra.txt` requirements, thank you for linking that.

The closest I found was this thread on [StackOverflow](https://stackoverflow.com/questions/63583752/runtimeerror-using-networkx-on-example-code). Hopefully future developers will find this issue instead.

> Out of curiosity, is there any specific reason why you want to use Anaconda? Are you on Windows?

A couple reasons:

- Jumping between operating systems to fit slightly different needs (including Windows)
- Frequently on Linux environments without sudo access (`libgraphviz-dev` and `graphviz` aren't always available, so conda is one of the quickest solutions).

**Comment by rossbar** [comment]
A quick update here: the latest pygraphviz should [now be available on the conda-forge channel](https://github.com/pygraphviz/pygraphviz/issues/326#issuecomment-780900158).

**Comment by rossbar** [comment]
The solution here (as of the post date) is for conda users to install `pygraphviz` from the conda-forge channel (`conda -c conda-forge`). We can update this when pygraphviz is fixed on the official Anaconda channel, but I believe that's out of our hands. I'm going to close this now, but if users continue to run into this we can consider pinning the issue or something else to raise visibility.
