### ISSUE TITLE
numeric assortativity coefficient only works for nonnegative numeric attributes

### ISSUE THREAD

**Issue by mdf-github** [networkx/networkx#4776]
### Current Behavior

If the range of numeric attributes ranges from negative to positive (and not all negative), `nx.numeric_mixing_matrix` effectively disregards it since it is generated using `mapping = {x: x for x in range(m + 1)}`.

### Expected Behavior

The negative integers should be included in generating the matrix. Alternatively:
1. just use the Pearson correlation coefficient as given in Peel et al, eq. S4-S5 (Leto Peel, Jean-Charles Delvenne, Renaud Lambiotte, Multiscale mixing patterns in networks, PNAS Apr 2018, 115 (16) 4057-4062; DOI: 10.1073/pnas.1713019115). This has the added benefit that the scalar quantities need not be integers.
2. require that the integers be nonnegative
3. increase the size of the matrix so it includes the negative integers as well.

### Steps to Reproduce

```
G = nx.Graph()
G.add_nodes_from([1,2], a=-1)
G.add_nodes_from([3], a=1)
G.add_nodes_from([4], a=2)
G.add_edges_from([(3,4),(1,2),(1,3)])
# numeric_assortativity_coefficient gives -1.0
print(nx.numeric_assortativity_coefficient(G, 'a'))
```

### Environment

Python version: 3.8
NetworkX version: 2.5

**Comment by dschult** [comment]
I don't think `mapping = {x: x for x in range(m + 1)}` affects or is affected by the attributes of nodes.
This constructs a mapping of nodes to integer indexes in the matrix. In this case it is mapping from the indexes created earlier to the indexes used here -- so it is the identity mapping.

The numeric attributes can range with both positive and negative values.  Also, your example gives coefficient -1, which seems to indicate that it is not ignoring the negative values of attribute `a`. What value would you expect?

Can you clarify your description?

**Comment by mdf-github** [comment]
I actually discovered this error using a larger dataset, comparing the Pearson correlation coefficient (directly from scipy) with the one obtained using `numeric_assortativity_coefficient`. I tried taking the absolute value of the attribute and the discrepancy disappeared.

I think the mapping is the culprit. `numeric_mixing_matrix` takes the dictionary `attribute_mixing_dict`which has _attribute values_ (not node labels) as the keys and the values being another dictionary, with the keys being the neighbor attribute values and the dictionary values being the counts of how many times these attribute values occur in an edge.

Therefore, in `numeric_mixing_matrix`, the value of `m` is the maximum of the attribute values (not the node labels).

I've annotated the snippet below to point out what I think is wrong with the code. I hope that helps.

```
def numeric_mixing_matrix(G, attribute, nodes=None, normalized=True):
    """Returns numeric mixing matrix for attribute.

    The attribute must be an integer.

    Parameters
    ----------
    G : graph
       NetworkX graph object.

    attribute : string
       Node attribute key.  The corresponding attribute must be an integer.

    nodes: list or iterable (optional)
        Build the matrix only with nodes in container. The default is all nodes.

    normalized : bool (default=True)
       Return counts if False or probabilities if True.

    Returns
    -------
    m: numpy array
       Counts, or joint, probability of occurrence of node attribute pairs.
    """
    d = attribute_mixing_dict(G, attribute, nodes)
    s = set(d.keys())  # effectively a set of attribute _values_
    for k, v in d.items():
        s.update(v.keys())
    m = max(s) # the maximum of attribute _values_
    mapping = {x: x for x in range(m + 1)} # begins from zero to m, so if there are negative values, they won't be included
    a = dict_to_numpy_array(d, mapping=mapping)
    if normalized:
        a = a / a.sum()
    return a
```

**Comment by dschult** [comment]
Sorry -- my mistake -- I didn't understand the `mixing _dict` data structure.

So, would a fix be to replace `range(m + 1)` with `range(min(s), max(s)+1)`?

Also, what value would you expect for your example instead of -1?

**Comment by mdf-github** [comment]
Peel et al 2018 published a paper in PNAS about assortativity, and they did include the formula for scalar attributes in the Supplementary Information. Based on this, the expected answer is `r=4/9`.

The advantage of Peel's 2018 formula is that it doesn't require integer values for the attribute values.

Leto Peel, Jean-Charles Delvenne, Renaud Lambiotte, Multiscale mixing patterns in networks, PNAS Apr 2018, 115 (16) 4057-4062; DOI: 10.1073/pnas.1713019115

**Comment by vpozdnyakov** [comment]
@dschult I have taken a closer look at this issue and realized that my changes in PR #4851 do not fix it. Moreover, PR #4851 allows new cases with wrong assortativity coefficient calculation. A cause is in `numeric_ac` in [correlation.py](https://github.com/networkx/networkx/blob/main/networkx/algorithms/assortativity/correlation.py). In lines 
```python
x = np.arange(nx)
y = np.arange(ny)
```
we assume that node attribute values coincides with a mixing matrix indices — 0 is in the first row and first column, 1 is in the second row and second column and so on. As I see now, this method also needs `mapping` variable to correctly calculate assortativity coefficient, because we need to use actual node attribute values, not generated ones. The actual assortativity coefficient in this case is approx. 0.43 and it can be calculated using `numpy` as follows

```python
pairs = np.array(list(nx.node_attribute_xy(G, 'a')))
x, y = pairs[:, 0], pairs[:, 1]
coef = np.corrcoef(x, y)[0, 1]
print(round(coef, 2)) #returns 0.43
```

At first glance, a solution can be to construct `mapping` in `numeric_assortativity_coefficient` and `degree_assortativity_coefficient` and use it in `numeric_ac` as follows

```python
x = np.array(list(mapping.keys()))
y = x.copy()
```

and then it returns a correct coefficient

```python
mapping={-1: 0, 1: 1, 2: 2}
mix_max = nx.numeric_mixing_matrix(G, 'a', mapping=mapping)
coef = numeric_ac(mix_max, mapping)
print(round(coef, 2)) #returns 0.43
```

but it requires (1) to create `mapping` and (2) to sort node attributes values in `mapping` that can be expensive.

Much bigger problem that I realized thanks to this issue is that my changes in PR #4851 make `degree_assortativity_coefficient` and `degree_pearson_correlation_coefficient` return different values in cases where values do not coincide with mixing matrix indices, for example

```python
S1 = nx.star_graph(4)
S2 = nx.star_graph(4)
S = nx.disjoint_union(S1, S2)
S.add_edge(4, 5)
print(nx.degree_assortativity_coefficient(S, weight="weight")) # returns -0.87...
print(nx.degree_pearson_correlation_coefficient(S, weight="weight")) # returns -0.93...
```

Correct one is `degree_pearson_correlation_coefficient`. Now it is obvious that PR #4851 should have contained fixes for this problem. Sorry for my fault. I will try to propose a solution in separate PR. Or maybe it would be better to undo the merge of PR #4851 ?
