### ISSUE TITLE
Deserializing custom default properties from yEd graphML files

### ISSUE THREAD

**Issue by bergmansj** [networkx/networkx#4778]
When importing a yEd created graphml file with custom properties on the 
nodes I found that the default values for boolean properties was always True.

After some browsing through the code of GraphMLReader I found that while
the properties of the nodes themselves are passed through the `decode_data_elements`
method (so that GraphML booleans are parsed correctly), the items in the 
node_default dictionary are not. 

For the defaults, the value of each key is just cast to the appropriate `python_type`
In the case of booleans with value='false' this results in `bool('false') == True`  :(

### Expected Behavior
The default attribute values should also be passed through `decode_data_elements`

### Steps to Reproduce
Make a yed graphml file with some custom node property of value 'boolean' with default 'false'
import the file using GraphMLReader
The resulting default node property has bool value True.

### Environment
Python version:
Python 3.9.4 (default, Apr  6 2021, 11:23:37) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin

NetworkX version:
2.5.1

### Additional context
As posted in google discussion group
[https://groups.google.com/g/networkx-discuss/c/XbFTyx-PKqc/m/pD2_WAdYAQAJ](https://groups.google.com/g/networkx-discuss/c/XbFTyx-PKqc/m/pD2_WAdYAQAJ)

**Comment by dschult** [comment]
We should add code to send the default values through the `decode_data_elements` method -- similar to what we do with the non-default properties of the nodes.

**Comment by bergmansj** [comment]
I made a fork [bergmansj/networkx](https://github.com/bergmansj/networkx) 
to try out some stuff.

Added a test in [networkx/readwrite/tests/test_graphml.py](https://github.com/bergmansj/networkx/commit/ccceceaba206896a03954e8f6085fa716c2cc5c4) and then fixed the issue by adding a small bit of code to [networkx/readwrite/graphml.py](https://github.com/bergmansj/networkx/commit/0577ba83684290c310eb7b07623c7d31cfea6324)

I forgot to make a separate branch for it, sorry for that. I have no experience with pull requests (yet)

**Comment by dschult** [comment]
You can create a Pull Request of this work by clicking on "Open a Pull Request" under the "contributing" label of the home page of your repository. Give that pull request a title similar to this issue and your code will be provided to NetworkX in the form of a Pull Request.  You can continue to make changes and push them to your repository -- they will automatically update the pull request, so be careful only to put changes that relate to this pull request.  (that's why people usually create a separate branch -- so they can do more than one set of changes while the NX folks review the code in the first PR.)

Since you haven't created the PR yet, you can go ahead and make a new branch with what you've got, and create the pull request from that branch -- leaving your "main" branch available.

**Comment by bergmansj** [comment]
Thank you for the extensive explaination. I tried to follow the steps and made a pull request.
