### ISSUE TITLE
in/out_degree interpret strings as collections

### ISSUE THREAD

**Issue by j6k4m8** [networkx/networkx#4781]
When a node does not appear in a graph, calls to `out_degree` or `in_degree` treat a string node parameter as an iterable, yielding a `DegreeView`.

I'm not sure what I would expect to happen, but an IndexError might make sense; treating some strings as node names and some as iterables is confusing behavior.

### Current Behavior

Consider the following example, in which I create two graphs. G2 is the important one here: Notice that it has nodes with multi-character names.

```python
import networkx as nx

G1 = nx.DiGraph()

G1.add_node("A")
G1.add_edge("ABC", "B")


G2 = nx.DiGraph()
G2.add_edge("A", "ABC")
G2.add_edge("ABC", "BCD")
```

When I ask for degree information, SOME node names are treated as nodes; others are treated as iterables of single-character node names. **For example, let's create a dictionary of nodes to their out-degree:**

```python
{
    c: G1.out_degree(c) # searching for degree in G1...
    for c in G2.nodes   # for node-names taken from G2
}
```

```python
{'A': 0, 'ABC': 1, 'BCD': OutDegreeView({'B': 0})}
```

This dictionary very counterintuitively contains nonempty key-val pairs of nodes that don't exist in my graph!

I appreciate that some users may now rely upon this behavior, but I wanted to share it because it returns very counterintuitive results. I wonder if there might be a way to specify that I'm not looking for my node to be interpreted as an iterable:

```python
G1.degree("foo", is_iterable=False) # KeyError
```

(Just a thought!)

### Expected Behavior

I would expect asking for out_degree of a nonexistent node to raise a `IndexError` or `KeyError` because the node isn't in the graph. 

Note that `G2.out_degree(2)` raises a `TypeError` because 2 is not iterable.

### Steps to Reproduce
(See example above)

### Environment

* Python version: 3+
* NetworkX version: 2.4+

**Comment by rossbar** [comment]
> I appreciate that some users may now rely upon this behavior, but I wanted to share it because it returns very counterintuitive results.

I'm not sure anyone should be relying on this behavior, this feels much more like a defect than a feature to me...

Here's another example illustrating the issue:

```python
>>> G = nx.DiGraph()
>>> G.add_node('a')
>>> G.add_node('b')
>>> G.add_node('abc')
>>> list(G.nbunch_iter('abc'))
['abc']
>>> list(G.nbunch_iter('abcd'))
['a', 'b']
```

I'm going to mark this as a defect, but if this behavior is intentional it'd be great if a use-case could be shared (which we could potentially add to the docs) and the label can be updated.

**Comment by dschult** [comment]
The dict you want is best returned using:  `out_degree_dict = dict(G1.out_degree(G2))`

The `nbunch_iter` behavior is one of those long existing NetworkX warts where we decided long ago that the possible confusion was worth the better interface. We should consider improving that wart, of course. But the problem is very unlikely to come up in practice.

The strange "extra node" occurs only when both 1) `G1.out_degree` is being called separately on each node instead of on the desired set of nodes, and 2) G1 has strings of length 1 as nodes while G2 has nodes with multi-character strings that contain the single character used as a node in G1. Both of those conditions must hold while at the same time the user is trying to look up the `G1.out_degree` of nodes from `G2` -- which is pretty wacky in itself. :}

All-in-all it should be unusual that this arises. (I guess you win the prize for being lucky enough to have run into it!) 

One straightforward fix could be to check each iterator and rule out the strings. That disallows strings to be nbunch containers of single character nodes. It also would require checking for a string every time someone uses a container as an nbunch.

Said another way, two plus sides to the current implementation are that we don't have to check for strings every time a container of nodes is used as an nbunch, and strings can be used as containers of single character nodes.

**Comment by j6k4m8** [comment]
> (I guess you win the prize for being lucky enough to have run into it!)

Thank you so much!! 🎉 Let me know where I can send you my delivery address! 🤣

I agree that this is probably best solved in user code in my contrived (two-graph) example. @rossbar's example makes a lot more sense for a "wtf" moment in a conventional use-case, but I completely understand the legacy `nbunch` justification!

**Comment by rossbar** [comment]
> One straightforward fix could be to check each iterator and rule out the strings. That disallows strings to be nbunch containers of single character nodes.

To my mind that isn't necessarily a bad thing, especially since the interpretation of `nbunch` can change based on the nodes in the graph (as noted above). Silent behavior changes based on object state can lead to pernicious bugs. For example, if a user *was* intending to use a string as a collection of single-character nodes, the fact that they could get a different result if a multi-character string was added to the graph as a node feels scary; take the above example but with a different interpretation:

```python
>>> G = nx.Graph()
>>> G.add_nodes_from(['a', 'b', 'c', 'd', 'e'])
>>> my_node_collection = 'abc'  # I intend this string to be interpreted as a container of nodes
>>> list(G.nbunch_iter(my_node_collection))
['a', 'b', 'c']
>>> G.add_node('abc')  # This change to the Graph breaks my expected interpretation of `my_node_collection`
>>> list(G.nbunch_iter(my_node_collection))
['abc']
```

As @dschult points out, this is *very* much a corner case given all the conditions that have to be met to hit it, but clearly one that can be hit. One application that came to mind where something like this could crop up is working with [`Trie`s](https://en.wikipedia.org/wiki/Trie) where working with sets/subsets of strings is common.

I don't have a strong feeling for whether this is a strong enough motivation to change the current behavior, but I think it's worth exploring the tradeoffs if someone is interested!
