### ISSUE TITLE
algorithms.tree.branchings breaks for all minimum_branching() calls

### ISSUE THREAD

**Issue by lkora** [networkx/networkx#4836]
### Current Behavior
Inside of `Edmonds` class, `find_optimum()` method, there is an if statement that checks if the `desired_edge()` method found a valid edge
```
# If weight < 0, then it cannot help in finding a maximum branching.
   if self.style == "branching" and weight <= 0:
      acceptable = False
```
Due to the way the `Edmonds` class was implemented, when calling the `minimum_branching()`, or `minimum_spanning_arborescence()`, all of the weights of the graph are set to their negative values. So the above if statement doesn't pass and add any branches.
So the **return value** of the `minimum_branching()` call is **always a set of nodes, but without any edges**.
![broken](https://user-images.githubusercontent.com/17961880/119535566-6e613b80-bd88-11eb-8fe2-a38d83b64c9d.png)

### Expected Behavior
**The minimum directed edges should be created between the nodes.** 
The conversion to negative weights for minimum `minimum_branching()` and also `minimum_spanning_arborescence()` is pointless and the solution should be rewritten, the current fix that works for my examples is to remove the aforementioned if statement from above, and just leave `acceptable = True`. I have made a pull request with it.

### Steps to Reproduce
Just call either `minimum_branching()`, or `minimum_spanning_arborescence()` for any graph that has positive edge weights.

### Environment
Conda version: 4.10.1
Python version: 3.8.5
NetworkX version: 2.5.1

### Additional information
The existing codebase needs to be rewritten, or at least refactored.

**Comment by mjschwenne** [comment]
Hello!

I have looked at the method in question, and it is indeed bugged. I ran the tests for that file and they all pass... but the tests for the minimum branching case appear to have never been completed!

I can quickly fix and test the problem so that it can be resolved soon.

**Comment by lkora** [comment]
mjschwenne That's what it seems to be the case. I did fix it in the end on my private repo. But I didn't merge it since it's not completely finished.

**Comment by mjschwenne** [comment]
Would you still like me to fix and merge it?

**Comment by lkora** [comment]
Go for it! I am very busy currently, might only start working on it in about a month or so.

**Comment by mjschwenne** [comment]
Sounds good, I should have time over the weekend

**Comment by mjschwenne** [comment]
Ok, I've done some reading from the original Edmond's paper.

The difference between a branching and an arborescence is that the branching is not required to be connected. Thus, a minimum branching from the above graph technically *is* the one that was returned. It has a weight of 0. If there was a negative edge weight then that one would be included in the minimum branching. 

I think `minimum_branching` is effectively a useless function since it will always return the set of negative edges, but I'm not sure what the 'correct' behaviour is since changing it would made it equivalent to `minimum_arborescence`.

I wonder if @dschult would be able to give some guidance.

**Comment by dschult** [comment]
This [wikipedia page describes Edmonds algorithm](https://en.wikipedia.org/wiki/Edmonds%27_algorithm) pretty well.

It looks like `find_optimum` can choose if an edge is "acceptable" and does so only if it is looking for a branching.  As the code is written, a branching does not require each node to be covered by the edges in the branching. That is, it doesn't have to be a spanning branching. In that case, a maximum branching should never choose to add a negatively weighted edge. It would prefer to have no edge at all to make a maximum branching. That is correct logic. But for a minimum branching then, the same logic suggests that you should only consider negatively weighted edges. Because if there are no negatively weighted edges, then having no edges at all is a branching with lower weight. That is how the code currently works.

In this sense then, the `minimum_branching` often does have no edges.  BUT...  this is a very strange way to define a minimum branching.  I can't find that term defined anywhere. But it seems to me that the branching should not be allowed to just choose not to connect to a node.  There ought to be a constraint (like spanning) that requires the problem to add edges where it can.  In this code, that is done by `spanning_arborescence` -- but then the result is thrown away if the final resulting branching is not an arborescence.  That behavior (throwing the branching away) also makes sense and is what the current code does.

I think what @lkora wants is the result of the `minimum_spanning_arborescence` **before** checking to see if it is an arborescence.  That can currently be obtained using:
```python
Ed = nx.tree.branchings.Edmonds(G)
T = Ed.find_optimum("weight", 1, "min", style="arborescence", False)
```

But I'm not sure what to call this.  It is not the minimum weight branching --- that would have no edges in it.
It is not the minimum weight spanning branching --- it doesn't span all the nodes.
It is some sort of **minimum weight, maximal node-coverage branching**.

@lkora does this description make sense to you? Is this is fact what you were expecting from `minimum_branching`?

**Comment by dschult** [comment]
@mjschwenne  Do you want to take a stab at adding a function `minimum_maximal_branching` that mimics the others but this time, runs `find_optimum` using the arborescence node but returns the result without checking if it is an arborescence (the code in the previous comment)?

We should beef up the docstrings to explain the meaning of these subtle yet important distinctions too.  If you'd prefer, I will do it (just let me know), but it might be an easy first-accepted PR.

**Comment by lkora** [comment]
I did want to find the `spanning arborescence of minimum weight` , and the way that the doc explained it was to use `minimum_branching`. But the logic behind `find_optimum` was quite puzzling to me, since I did want to find `minimum_branching`, but the algorithm seemed to work **only** for negative weights, which made no sense to me at the time. 
As @dschult has said:
> It is some sort of minimum weight, maximal node-coverage branching.
That was something that I needed. And the way we were required to implement it was to return the analog of a "Minimum Spanning Tree" but for a directed, weighted graph, or a forest of directed graphs. 
I think that `minimum_maximal_branching` seems to be the most useful method, because it should be a direct analog of "Kruskal's algorithm for MSTs", I could implement this in the existing codebase, I do have the complete algorithm, if you'd want me I could also do a translation of it and make a PR with the step by step solution. Since when I was implementing this, documentation was quite scarce and difficult to find. 

@mjschwenne I'd love to work together on this `Edmonds` class. We could start by probably solving that big unnecessary loop in `find_optimum` method, and documenting the class more.

Please contact/correct me if there are any misunderstandings, since English isn't my mother tongue.

**Comment by mjschwenne** [comment]
I certainly agree that `find_optimum` could use a refactor and would be happy to work with you on that @lkora.

As for the notion of a minimum weight, maximal coverage branching, the main difference between this and a spanning arborescence is that we can return a spanning forest style of graph should there be multiple truly disconnected components in the original graph. Kruskal's algorithm inherently does this and that would be useful functionality for NetworkX in the case of a directed graph we know has multiple components.

It we move that definition any more we get into the gray area of if there is an edge with a high cost, how do we decide that the cost is too high and choice to disallow it? This would be a threshold based approach and even if we let the function caller set the threshold I'm not sure that they would have the information needed to set a good one (hence their interest in calling this function in the first place).

**Comment by dschult** [comment]
Yes, I agree that we should not get into setting thresholds for edge weights being included or not.  Perhaps a minimum branching doesn't even make sense as a concept.  But I think the minimum_maximal_branching makes sense even when it isn't an arborescence. It differs from a spanning arborescence even when the graph is not weakly connected. But I think if the graph is strongly connected it would return the spanning arborescence.

```python
def minimum_maximal_branching(G, attr="weight", default=1, preserve_attrs=False):
    ed = Edmonds(G)
    B = ed.find_optimum(attr, default, kind="min", style="arborescence", preserve_attrs=preserve_attrs)
    return B
```

We have Kruskal's algorithm and there is a function `kruskal_mst_edges` which appears to work with directed and undirected graphs.

**Comment by DavidNemeskey** [comment]
I ran into this problem as well. I am not sure, but I think I agree with @dschult on what I imagined the minimum branching would be. Maybe this logic could be used in `Edmonds` to arrive to it:
1. Set the weight of all branches to `max_edge_weight - weight + min_edge_weight`(the last part so that the edges with the maximum weight are not left out)
2. do `find_optimum` with `max`
3. Re-set the weights

For my use-case (the minimum-weight directed spanning forest) it works and I think this is the logical counterpart to the maximum branching (maximum-weight directed spanning forest).

**Comment by mjschwenne** [comment]
While I did mention this issue in the one about `min_weight_matching`, the implementations are completely separate, so the fix their did nothing to fix the issue here. My point their was that this is the same type of issue more than anything. In the short term, I thing that adapting the same style of edge weight conversion from that issue would help solve this problem as will. In the long term, the `Edmonds` class is very difficult to read and understand even when crossing referencing every step with the original research paper which is what I was doing last summer. In my opinion that whole class should be refactored and rewritten to be more concise and easier to follow but I haven't had the time to throw about it. I can probably take a crack at this in those two step, so first a small PR to fix this and then a larger one to refactor the `Edmonds` class.

**Comment by rossbar** [comment]
Gotcha, I just saw the purple "merged" button and thought I'd check. Thanks for the clarification!

**Comment by lkora** [comment]
> While I did mention this issue in the one about `min_weight_matching`, the implementations are completely separate, so the fix their did nothing to fix the issue here. My point their was that this is the same type of issue more than anything. In the short term, I thing that adapting the same style of edge weight conversion from that issue would help solve this problem as will. In the long term, the `Edmonds` class is very difficult to read and understand even when crossing referencing every step with the original research paper which is what I was doing last summer. In my opinion that whole class should be refactored and rewritten to be more concise and easier to follow but I haven't had the time to throw about it. I can probably take a crack at this in those two step, so first a small PR to fix this and then a larger one to refactor the `Edmonds` class.

Agreed! Original paper is quite difficult to follow. I really wanted to go for it last summer, but I landed a job, and was just preoccupied with work, studies,.. I agree with @mjschwenne whoever wants to get their feet wet with this should first try to refactor the code, as it is written "by the paper", and then rewrite some parts of it. I can see some potential improvements and efficiency gains.
I am happy with the new documentation regarding the `Edmonds` class! 😄
