### ISSUE TITLE
Remove full path from functions in the docs sidebars

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4855]
In the documentation, [the sidebar lists functions within a section](https://networkx.org/documentation/latest/reference/generated/networkx.generators.sudoku.sudoku_graph.html#networkx.generators.sudoku.sudoku_graph) and the names of the functions include the path to the function.  It doesn't fit in the sidebar. 

Can we find a sphinx switch so that the sidebar names include only the function names and not its path?

**Comment by rossbar** [comment]
This was (at least partially) fixed in #5049. It's probably worth revisiting at some point to see if there isn't another way to approach this that doesn't involve overriding the base autosummary template.

I'm going to close this as resolved by #5049 , but that shouldn't stop anyone from looking into this further if interested!
