### ISSUE TITLE
Update random number generators to use numpy.random.Generator  

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4891]
It looks like the latest numpy interface is now `Generator`. So we might need to update our random number generator treatment to handle that.  I believe the old syntax/interface of `RandomState` still works or we would have run into problems. But it'd be good to align ourselves with the latest/greatest.

I think the only place we should have to change is networkx/utils/misc.py  with functions `create_random_state`, `PythonRandomInterface` and `create_py_random_state`.

(Thanks @stefanv for bringing our attention to this.)

**Comment by rossbar** [comment]
Agreed - I think we've had related discussions in the past (maybe in #4452 - though that seems to have mysteriously disappeared!)

One thing to keep in mind is that `Generator` is not generally backward compatible with `RandomState` --- I would advocate for a 2-step adoption process:
 1. Add support for `numpy.random.Generator` in the functions/classes listed above. This can be done now and shouldn't require a ton of re-working (there are just some subtleties to handle: for example `RandomState.randint` has become `Generator.integers` instead)
 2. Make the switch from `numpy.random.mtrand._rand` as the default random instance used in NetworkX when none is specified to `numpy.random.default_rng` (or similar). Since this change is backward incompatible, I think it should be done for version 3.0 then we can draw a lot of attention to the change and announce that results will differ for the same integer `seed` values between networkx 2 and networkx 3. Of course, users can still get access to the old random number generator, but they'll have to pass in an explicit `RandomState` instance.

**Comment by goar5670** [comment]
Hi, can I work on this issue? It's my first time contributing to Networkx so I might need some guidance.

**Comment by rossbar** [comment]
Thanks for your interest in @goar5670 - there's already been quite a bit of progress on this issue: step 1 is implemented and in the latest NetworkX release, and step 2 is being discussed in [NXEP 4](https://networkx.org/documentation/latest/developer/nxeps/nxep-0004.html).

Since this issue is largely addressed I will close it - discussion related to NXEP 4 should happen elsewhere; I'll open a discussion topic for it. Thanks for the ping!
