### ISSUE TITLE
https://networkx.org/documentation/stable/tutorial.html doesn't work

### ISSUE THREAD

**Issue by andriu99** [networkx/networkx#4898]
### Environment

Python version:
NetworkX version:

**Comment by rossbar** [comment]
Hi @andriu99 , it looks like this may have been submitted in error as the issue template appears to be empty. We'll need a bit more information to go on to help figure out if/what your issue is!

I'm going to close this one, but if you want to follow up, please feel free to re-open it with the specific information requested above, at the very least: 1) a description of what specifically isn't working and 2) what versions of networkx you are using.
