### ISSUE TITLE
common_neighbor_centrality throws KeyError in presence of multiple connected components

### ISSUE THREAD

**Issue by fabmazz** [networkx/networkx#4956]
I have just tried to run `networkx.algorithms.link_prediction.common_neighbor_centrality` on a graph, but it throws KeyError in the shortest path dictionary.
I might be wrong, but from the code it seems the computation assumes that there is one connected component, in my case I have 3.

### Current Behavior
Throws KeyError:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-14-d81293677b37> in <module>
----> 1 r_comm = tuple(lp.common_neighbor_centrality(G_cut))

/usr/lib/python3.9/site-packages/networkx/algorithms/link_prediction.py in <genexpr>(.0)
     38     if ebunch is None:
     39         ebunch = nx.non_edges(G)
---> 40     return ((u, v, func(u, v)) for u, v in ebunch)
     41 
     42 

/usr/lib/python3.9/site-packages/networkx/algorithms/link_prediction.py in predict(u, v)
    280     def predict(u, v):
    281         return alpha * len(list(nx.common_neighbors(G, u, v))) + (1 - alpha) * (
--> 282             G.number_of_nodes() / (len(shortest_path[u][v]) - 1)
    283         )
    284 

KeyError: 169
```

### Expected Behavior
Give the scores for the missing edges

### Steps to Reproduce
This snippet is sufficient to trigger the error:
```python
import networkx as nx
import urllib.request as urllib
import io
import zipfile

url = "http://nrvis.com/download/data/socfb/socfb-Haverford76.zip"

sock = urllib.urlopen(url)
s = io.BytesIO(sock.read())
sock.close()

zf = zipfile.ZipFile(s) 
mtx = zf.open('socfb-Haverford76.mtx')

G = nx.Graph()
for l in mtx:
    fields = l.split()
    if len(fields) == 2:
        G.add_edge(int(fields[0]), int(fields[1]))

import random
random.seed(8)

G_cut  = G.copy()


for e in tuple(G_cut.edges):
    if random.random() < 0.05:
        G_cut.remove_edge(*e)

lp = nx.algorithms.link_prediction
r_comm = tuple(lp.common_neighbor_centrality(G_cut))
```

### Environment

Python version: 3.9 (also 3.7)
NetworkX version: 2.5.1

**Comment by rossbar** [comment]
Is there any chance you could boil down the reproducing example, preferably to something that can be built locally rather than requiring downloading data from external sources?

**Comment by fabmazz** [comment]
Sure, here it is:
```python
import networkx as nx

G = nx.generators.erdos_renyi_graph(100,0.03, seed=4)

len(tuple(nx.connected_components(G)))

lp = nx.algorithms.link_prediction
r_comm = tuple(lp.common_neighbor_centrality(G))
```

throws:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-30026dd2ddee> in <module>
      6 
      7 lp = nx.algorithms.link_prediction
----> 8 r_comm = tuple(lp.common_neighbor_centrality(G))

~/app/miniconda3/envs/myenv/lib/python3.8/site-packages/networkx/algorithms/link_prediction.py in <genexpr>(.0)
     38     if ebunch is None:
     39         ebunch = nx.non_edges(G)
---> 40     return ((u, v, func(u, v)) for u, v in ebunch)
     41 
     42 

~/app/miniconda3/envs/myenv/lib/python3.8/site-packages/networkx/algorithms/link_prediction.py in predict(u, v)
    280     def predict(u, v):
    281         return alpha * len(list(nx.common_neighbors(G, u, v))) + (1 - alpha) * (
--> 282             G.number_of_nodes() / (len(shortest_path[u][v]) - 1)
    283         )
    284 

KeyError: 12
```

**Comment by rossbar** [comment]
I think your original diagnosis is correct; an even more minimal reproducer highlights the core of the problem:

```python
>>> G = nx.Graph([(0, 1)])
>>> G.add_node(2)
>>> list(nx.common_neighbor_centrality(G))
Traceback (most recent call last)
   ...
KeyError: 2
```

This error path is hit via `link_prediction._apply_prediction` with `ebunch=None` (the default), which uses `nx.non_edges(G)` to create the `ebunch` that the prediction is applied over. As mentioned in the OP, this causes problems when there are multiple components. Using the above example, node 2 is not connected, so there is no path to it, resulting in the KeyError:

```python
>>> sp_dict = nx.shortest_path(G)
>>> print(sp_dict)
{0: {0: [0], 1: [0, 1]}, 1: {1: [1], 0: [1, 0]}, 2: {2: [2]}}
>>> list(nx.non_edges(G))
[(0, 2), (1, 2)]
>>> # No path from 0 or 1 to 2
>>> sp_dict[0][2]
Traceback (most recent call last)
   ...
KeyError: 2
```

I'm not sure what the CCPA is supposed to do in the case of multiple connected components, but some ideas come to mind:
 1) Raise an exception on `not nx.is_connected(G)`
 2) Compute the CCPA for each component and return a sequence of scores or a mapping of components -> CCPA value.

I think option 1 makes the most sense but am interested to hear what others think; especially if anyone is familiar with the Ahmad et. al. paper.

**Comment by dschult** [comment]
The function `common_neighbor_centrality` is calling `nx.shortest_path` when all it uses is the length of that path.  It should call `nx.shortest_path_length`.  That will cause the same problem with disconnected graphs, but it will be easier to fix. The two options given by @rossbar above should be augmented by a third option to have the length be infinity.

I think this makes the most sense in this case because an infinite length means that term of the formula becomes 0 so there is no contribution to the probability from being "close" to the other node.  I prefer it to option 1 (raise an exception) because presumably we want to be able to predict link formation between the components.  Option 2 (computing for each component separately) is a good approach for algorithms that focus on connections. But this question of link prediction focuses on **missing edges**, not connections. So treating each component as their own separate graph is not as compelling to me.  

I've looked through the Ahmad paper, and it doesn't talk directly about the case of disconnected graphs, but they do talk about having a distance metric between nodes. This is what made me think of using a metric that includes infinity as a possible distance. (not even sure it that violates the definition of metric, but my intuition is that we want a very large distance in this case --> zero contribution toward the probability of an edge forming.

Thoughts?
