### ISSUE TITLE
Can't retrieve all edges for pair of nodes in Multi(Di)Graph

### ISSUE THREAD

**Issue by logan-dunbar** [networkx/networkx#4962]
According to the docs, I should be able to subscript into Multi(Di)Graph by pair of nodes and retrieve all the edges:

> Hence, **G.edges[u, v]['color']** provides the value of the color attribute for edge (u, v) while for (u, v, c) in G.edges(data='color', default='red'): iterates through all the edges yielding the color attribute. [Docs](https://networkx.org/documentation/stable/reference/classes/generated/networkx.MultiGraph.edges.html)

Either the docs are incorrect (I suspect a copy-paste from non-Multi Graph/DiGraph), or this does not work as expected.

### Current Behavior

```python
G = nx.MultiGraph()  # or MultiDiGraph
nx.add_path(G, [0, 1, 2])
key = G.add_edge(1, 2, weight=5)
G.edges[1, 2]
# G.edges[1, 2, 0] or G.edges[1, 2, 1] works
```

> ValueError: not enough values to unpack (expected 3, got 2)

### Expected Behavior

I would expect to be able to retrieve all the (multi-)edges for a pair of nodes by subscripting into the edges of the MultiGraph:
```python
G.edges[1, 2]
```

> MultiEdgeView([(1, 2, 0), (1, 2, 1)])

### Environment

Python version: 3.8
NetworkX version: 2.6.1

**Comment by rossbar** [comment]
> I should be able to subscript into Multi(Di)Graph by pair of nodes and retrieve all the edges

The docs aren't particularly clear here, though I don't think they support the interpretation that indexing edges by node numbers will return all edges between the two nodes --- rather, indexing EdgeView (and subclasses) is intended to access specific edges (or their attributes). In the case of MultiGraphs, each edge includes a key hence the above error. I agree that the documentation could be improved here to make this more clear.

**Comment by logan-dunbar** [comment]
Ye, I wanted a quick way to get a list of a specific attribute value for each of the edges. I ended up doing this, is there a better way?

```
G = nx.MultiGraph()
G.add_edge(1, 2, weight=3)
G.add_edge(1, 2, weight=5)
list(map(itemgetter('weight'), G[1][2].values()))
```
> Out[10]: [3, 5]

I was missing that `G[1][2]` provides an `AtlasView` of all the edges with attributes.

**Comment by rossbar** [comment]
> a quick way to get a list of a specific attribute value for each of the edges. I ended up doing this, is there a better way?

It depends on what you want specifically. For example, what you've done above will grab the `"weight"` attribute for every edge between two nodes (only relevant for multigraphs). Your solution is perfectly fine, though I would probably use list comprehension instead of the `list(map(` pattern:

```python
>>> e12_wts = [e['weight'] for e in G[1][2].values()]
```

If instead you wanted the attribute for *all* edges (instead of all edges between two specific nodes) then you'd iterate over the edge view (with data), something like:

```python
>>> G.add_edge(0,1, weight=7)  # Add a new edge for illustration
>>> edge_wts = [d["weight"] for _, _, d in G.edges(data=True)]
```

**Comment by logan-dunbar** [comment]
Still dusting off my python hat, list comprehension is much more legible xD thanks for the help!

**Comment by dschult** [comment]
The DataView can also specify which data attribute (instead of `data=True`):
```python
>>> G.add_edge(0,1, weight=7)  # Add a new edge for illustration
>>> edge_wts = [wt for _, _, wt in G.edges(data="weight")]
```
You can specify a `default` value for edges that don't have that attribute (the default edge weight default is `None`).  For `MultiGraph` You can also request that the edge keys be returned -- then you get a 4-tuple.
```python
>>> edge_wts = [wt for _, _, wt in G.edges(data="weight", default=1)]
```

But the bottom line is that the docs for Multi(Di)Graph need to be updated...   :}
