### ISSUE TITLE
read_edgelist not reading all lines of write_edgelist file

### ISSUE THREAD

**Issue by arav-agarwal2** [networkx/networkx#4989]
For a graph analysis I am doing, I am using nx.write_edgelist(G,path=path) to write to the following file.

[A2_early_0.04.15.txt](https://github.com/networkx/networkx/files/6893893/A2_early_0.04.15.txt)

However, reading this data through nx.readwrite.edgelist.read_edgelist(filename, create_using=nx.DiGraph()) 
causes a problem, as not all data is read. 

### Current Behavior

Reads in 617 edges of the above adjacency list

### Expected Behavior

Expect to read all 780 edges

### Steps to Reproduce

G = nx.readwrite.edgelist.read_edgelist(filename, create_using=nx.DiGraph()) 
print(G.number_of_edges)

### Environment

Python version: 3.8.5
NetworkX version: 2.5.1

**Comment by boothby** [comment]
Hi @arav-agarwal2, it looks like your file contains quite a few lines with `#` characters.  By default, those are treated as comments in `read_edgelist`.  This can be fixed by setting the `comments` parameter to a string that doesn't occur in the file, or to be a little sneaky,`'\n'`:

```
G = nx.readwrite.edgelist.read_edgelist(filename, create_using=nx.DiGraph(), comments='\n')
```

**Comment by rossbar** [comment]
Excellent catch @boothby - this is indeed what is happening with this particular data file.

On a related note, maybe `comments` should be made an optional kwarg with the ability to pass in `comments=None` to indicate that there is no comment character, rather than making the user get creative with their comment character selection. Thoughts?
