### ISSUE TITLE
KeyError in greedy_modularity_communities() when dQ approaches zero

### ISSUE THREAD

**Issue by tristanic** [networkx/networkx#4992]
### Current Behavior

Calling `algorithms.community.greedy_modularity_communities()` on a weighted graph sometimes fails with a `KeyError`, e.g.:

```---> 15     clusters = community.greedy_modularity_communities(g, weight='weight', resolution=graph_resolution)
     16     residue_clusters = []
     17     for i, c in enumerate(clusters):

~/.local/share/ChimeraX/1.3/site-packages/networkx/algorithms/community/modularity_max.py in greedy_modularity_communities(G, weight, resolution)
    209                     else:
    210                         # Only update per-row heap
--> 211                         dq_heap[row].remove(d_old)
    212 
    213         del dq_dict[i]

~/.local/share/ChimeraX/1.3/site-packages/networkx/utils/mapped_queue.py in remove(self, elt)
    112         # Find and remove element
    113         try:
--> 114             pos = self.d[elt]
    115             del self.d[elt]
    116         except KeyError:

KeyError: (-7.32467090554133e-06, 1010, 1016)
```

In each case the failure happens when the first value is very close to zero. Could perhaps be avoided by rounding to some reasonable number of significant figures?

### Steps to Reproduce

Using the JSON file from https://alphafold.ebi.ac.uk/files/AF-P06213-F1-predicted_aligned_error_v1.json:

```
def cluster_into_domains(pae_matrix, distance_cutoff=5, graph_resolution=1):
    import networkx as nx
    import numpy
    g = nx.Graph()
    size = pae_matrix.shape[0]
    g.add_nodes_from(range(size))
    for i in range(size):
        for j in range(i, size):
            pae = pae_matrix[i,j]
            if pae < distance_cutoff:
                g.add_edge(i, j, weight=1/pae)

    from networkx.algorithms import community

    return community.greedy_modularity_communities(g, weight='weight', resolution=graph_resolution)

import json, numpy
with open(filename, 'rt') as f:
    data = json.load(f)[0]
r1, r2, d = data['residue1'],data['residue2'],data['distance']
size = max(r1)
pae = numpy.empty((size,size))
pae.ravel()[:] = d

cluster_into_domains(pae, graph_resolution=3)
```

### Environment

Python version: 3.9
NetworkX version: 2.6.2

**Comment by dschult** [comment]
Floating point numbers are not good choices for problems where equality is checked or required.
Our standard advice is to change the weights to integers (by multiplying by e.g. 1e6 and rounding?)
I'm not sure if it will work in your case, but it's worth a try:

```python
pae.ravel()[:] = round(d * 1e6)
```
and then further scaling of `distance_cutoff` and `weight=1e6/pae`.

It's hard to avoid the trouble with equating floating point values. You could also create your own subclass of float by over-writing __eq__ and __lt__ to provide some tolerance for equals as well as less than and greater than. But that's pretty extreme.

**Comment by tristanic** [comment]
Converting to ints should actually work fine in this case (the PAE values have only a single decimal place, and at the worst only go up to 30 or so).
________________________________

**Comment by tristanic** [comment]
Creating a weight matrix as:

`    weights = (1/pae_matrix*10000).astype(numpy.int)`

and using that in place of `1/pae` works fine. Thanks for the very fast feedback!

**Comment by tristanic** [comment]
Turns out I spoke too soon. Converting the weights to integers improved the stability, but doesn't fix the problem. The type of the offending element in that tuple doesn't appear to be dictated by the type of the weights - I just got the same `KeyError` from a different case.

**Comment by tristanic** [comment]
Here's where the problem arises: https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/algorithms/community/modularity_max.py#L67

```
    m = sum([d.get("weight", 1) for u, v, d in G.edges(data=True)])
    q0 = 1.0 / (2.0 * m)
```
`q0` is then used to calculate `dq`, and `-dq` becomes the offending element in the key tuple:

https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/algorithms/community/modularity_max.py#L93-L104

```
    dq_dict = {
        i: {
            j: 2 * q0 * G.get_edge_data(i, j).get(weight, 1.0)
            - 2 * resolution * k[i] * k[j] * q0 * q0
            for j in [node_for_label[u] for u in G.neighbors(label_for_node[i])]
            if j != i
        }
        for i in range(N)
    }
    dq_heap = [
        MappedQueue([(-dq, i, j) for j, dq in dq_dict[i].items()]) for i in range(N)
    ]
```

One possible way to work around this with minimal fuss would be to store `dq` as a `Fraction` with a (suitably large) limit on the size of the denominator:

```
from fractions import Fraction
dq = Fraction(dq).limit_denominator(100000000)
```
`Fraction`s are hashable, and the rounding involved in creating the `Fraction` instance does away with this `KeyError`... but when I tried it out it made the method significantly slower. Simply rounding `dq` to 6 significant figures wherever it's calculated (as per the attached diff) seems the simplest working approach that doesn't entail a substantial change in the logic.
[modularity_max.py.diff.txt](https://github.com/networkx/networkx/files/6913093/modularity_max.py.diff.txt)

**Comment by tristanic** [comment]
That version works successfully for a previously-crashing test case, for all values of `resolution` ranging from 0.1 to 5.0 in increments of 0.1.

**Comment by rossbar** [comment]
Thanks for the followup - it does indeed seem like the computed values in `dq_dict` will be floats regardless of whether `weight` is floating point due to `q0`.

Rather than share a download link to a diff, it would be easier to open a PR (feel free to create it as "draft" if you're intent is mostly for illustration/feedback).

**Comment by tristanic** [comment]
Done.

**Comment by elplatt** [comment]
Hi all! After looking over this, #5000 and #5065, here's what I see:

* The rounding is occurring when dq is converted to -dq, and the key error occurs when -(-dq) != dq.
* The problem is that some of the MappedQueues use dq as a key and some use -dq.
* It looks like @dschult's test case works in the latest code as of @ThanasisMattas's commit 3a44d3ec7593358778a2336a5ec2faf5afe49da9, although I think the rounding problem still potentially exists in that code.

I know that @dschult and @tristanic have already been collaborating on fixing the bug by separating the MappedQueue element priority from the element itself. However, I'd like to see if I can write a fix that preserves the performance a little better, as performance is one of the main reasons this community detection algorithm is used. It may involve adding a "reverse_priority" flag or something similar to MappedQueue. I'll post a pull request sometime in the next few days.

**Comment by dschult** [comment]
Given that floating point errors are really tricky to try to debug, I don't think `dq` should be involved in a dict key lookup.  The heapq documentation about how to make heaps with the ability to update the priority say that the dict should map the element to its position. I think we should do the same.

Given that we have a number of Issues about this function and in fact this very issue, I would like to make a 2.6.3 release so they are fixed.  Let's work on performance for the 2.7 release.

It would be worth trying the heapdict package to compare performance too.  It would require a dependency but how much speed difference is there?  BTW, what is a good test for the speed?  erdos-renyi graph with 500 nodes and p=0.5?

**Comment by rossbar** [comment]
I agree with @dschult - I think correcting the behavior is the major priority. This has been affecting a lot of users so getting a fix out asap would be beneficial IMO.

**Comment by elplatt** [comment]
While this issue has been resolved a long time, I've always been curious about the cause of the original bug. I finally got around to looking into it. Here's what I found, just in case it ends up being helpful for future dev or debugging.

There were actually two distinct bugs. Both in the [following code](https://github.com/cvanelteren/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/algorithms/community/modularity_max.py#L93-L101):

    dq_dict = {
        i: {
            j: 2 * q0 * G.get_edge_data(i, j).get(weight, 1.0)
            - 2 * resolution * k[i] * k[j] * q0 * q0
            for j in [node_for_label[u] for u in G.neighbors(label_for_node[i])]
            if j != i
        }
        for i in range(N)
    }

Bug 1 was in the call to `get_edge_data()`. The arguments are indexes rather than node labels, which was causing some of the `KeyError` exceptions.

Bug 2 was indeed a floating point error. Because floating point multiplication is not associative, the term `resolution * k[i] * [j]` was not always symmetric in i and j. This sometimes resulted in a `KeyError` later on. If the i-j merge was the best merge available to community i and also the best merge available to community j, both `(-dq, i, j)` and `(-dq, j, i)` would appear in the queue `H`. When one reached the front of the queue, the other had to be removed with [this code](https://github.com/cvanelteren/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/algorithms/community/modularity_max.py#L122-L130):

        # If this element was also at the root of row j, we need to remove the
        # duplicate entry from H
        if dq_heap[j].h[0] == (-dq, j, i):
            H.remove((-dq, j, i))
            # Remove best merge from row j heap
            dq_heap[j].remove((-dq, j, i))
            # Push new row max onto H
            if len(dq_heap[j]) > 0:
                H.push(dq_heap[j].h[0])

The problem was in the call to `dq_heap[j].remove()`, because the `dq` value was sometimes slightly different due to the associativity problem mentioned above. This was causing the rest of the `KeyError` exceptions.

The fix sidestepped these issues by changing the way `MappedQueue` works. The change eliminating indexes and instead using node labels was a good call and I probably should have done that in the first place. As for the symmetric elements `(-dq, i, j)` and `(-dq, j, i)` not being equal, I think if I wrote it again I'd enforce equality by making them identical, instead using `(-dq, frozenset([i, j]))`. A little more complex, but it would have prevented the need to remove duplicates and made it impossible to violate the symmetry assumption.
