### ISSUE TITLE
Feature request: 'to_pandas_adjacency' option on 'nodelist' behaviour

### ISSUE THREAD

**Issue by MikeB2019x** [networkx/networkx#5009]
When using the 'to_pandas_adjacency' conversion method, if a node listed in the 'nodelist' parameter is not present in the graph being converted, an error is thrown.

![image](https://user-images.githubusercontent.com/49003263/128536065-6171b0d8-86c2-471d-81a1-aef1d8ea6760.png)

This change was introduced to the latest release.  The prior behaviour (v 2.5.1) allowed a nodelist that had nodes that were not in the graph.  For example:  if a graph had only 4 of say 16 nodes in the 'nodelist', the resulting adjacency matrix would still be 16x16.  The use-case for that behaviour is if you are comparing a series of graphs that are constructed from a subset of a set of common nodes.

It is possible to get the desired behaviour by processing after the fact in pandas, but would it be possible to make the behaviour selectable so that the user could choose either behaviour?

**Comment by dschult** [comment]
I think you can simply add the 16 nodes to all the graphs.  They won't have any edges, but the nodes will be there and will appear in pandas if I understand correctly.

**Comment by MikeB2019x** [comment]
True but that alters the graph definition and anyone using the graph will have to be aware that the extra nodes are not meant to have edges.  As well, if the superset of nodes changes, then all the graphs will need to be updated (in my case 760+ and growing).  The change proposed would simply alter a conversion utility.

**Comment by rossbar** [comment]
I'm not sure what's the best way to go about this. On the one hand I understand the convenience argument of allowing `nodelist` to have nodes that are not in `G`, but one major downside of this is that it would result in silently-incorrect results when a user *accidentally* adds a node to the nodelist that is not intended to be there.

I think @dschult 's suggestion is a good one, especially since this guarantees that the various data structures are kept in sync.

**Comment by MikeB2019x** [comment]
I don't view it as a convenience but as a use-case and one that is the bulk of my work (graphs, graph evolution, graph time-series in business/finance). My guess is that the original intent of the `nodelist` argument in the method was precisely the use-case I presented in the OP. 

In the to_pandas_adjacency method as described [here](https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.to_pandas_adjacency.html) what would be the point of being allowed to supply a `nodelist` if it always had to be identical to the graph's nodelist?  The default behaviour in the _absence_ of a supplied `nodelist` is that the method uses the nodes in the graph definition.  However, currently `nodelist` can _only_ have a value of the nodes in the graph definition therefore it is redundant b/c it is the same a providing no list.

I think the intent of the original addition of the `nodelist` argument is to permit a superset (or subset I suppose) of nodes for the adjacency matrix.  The user was protected from accidentally adding a node b/c the argument was optional and the default behaviour only used the graph's nodes.  The change removed a useful functionality and made the `nodelist` argument redundant.

No code change is required per se just reverse the change that led to the current behaviour.

**Comment by rossbar** [comment]
This change was made in #4216, precisely to prevent the case where an accidental inclusion of a non-node in `nodelist` would result in a resulting adjacency structure with the wrong shape.

> My guess is that the original intent of the nodelist argument in the method was precisely the use-case I presented in the OP.

The docstring makes it seem like the intent of `nodelist` is to control the ordering, i.e. the mapping from node to row/column number.

> In the to_pandas_adjacency method as described [here](https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.to_pandas_adjacency.html) what would be the point of being allowed to supply a nodelist if it always had to be identical to the graph's nodelist?

The two obvious use-cases are 1) to control the row/column ordering (as mentioned above) or 2) get the adjacency of a subset of nodes

> However, currently nodelist can only have a value of the nodes in the graph definition therefore it is redundant b/c it is the same a providing no list.

This is not correct, subsets of nodes are valid. Also the ordering is still important.

> The user was protected from accidentally adding a node b/c the argument was optional

This change was made precisely to prevent this problem - see the discussion in #4216

I'm personally -1 on the proposed change (i.e. reverting #4216) because I think the downside of silently getting the wrong adjacency from accidentally including nodes in `nodelist` that are not in `G` can lead to difficult-to-chase-down bugs. I also agree with the reasoning in #4216 that the "fix" to reclaim the old behavior is relatively straightforward. Even in the case where you have many graphs and a node-superset that changes, adding isolated nodes to the underlying graphs should be relatively quick and unlikely to be a bottleneck in any analysis:

```python
for g in my_graph_collection:
    g.add_nodes_from(my_node_superset)
```

**Comment by MikeB2019x** [comment]
The addition of nodes as in your snippet is what I've been doing since the change was implemented.  Currently at 12,000  graphs a run (and should be increasing by an order of magnitude by year end) it's noticeable.  I've read the discussion on the change and respectfully disagree with the reasons for that change, being able to include nodes not in the graph should at least be an option and I think the user was reasonably protected from error as it was.  All that said, I've made my case and appreciate that it was discussed.  I think this is a great product and appreciate the time and effort people put in on it.
