### ISSUE TITLE
`geometric_edges` should be accessible

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#5025]
The function `geometric_edges` in `generators.geometric` is not callable.   However, I have found a case where someone wants to use it (more specifically is asking for a function that does it).  https://stackoverflow.com/q/68815295/2966723 

I thought I'd just build an example for the person, but I can't figure out how to call it, presumably because it isn't in `__all__`, but I'm not an expert on this.

### Current Behavior
I get an error that the function doesn't exist.

### Expected Behavior
I'd like the function to run.

### Steps to Reproduce

    import networkx as nx
    import random 
    pos = {n: (random.random(), random.random()) for n in range(100)}
    G= nx.Graph()
    G.add_nodes_from(pos)
    radius = 0.1 #connect nodes of distance <0.1
    G.add_edges_from(nx.generators.geometric.geometric_edges(G, radius,2))
    > AttributeError: module 'networkx.generators.geometric' has no attribute 'geometric_edges'

### Environment

Python version: 3.7(?)
NetworkX version: 2.4

**Comment by dschult** [comment]
The function is available in NetworkX 2.6.2.  I haven't tracked down which version it became available.
The calling name is just as you expected:  `nx.generators.geometric.geometric_edges`

But I think it makes sense to publish this function to the public interface so that `nx.geometric_edges` would work.
