### ISSUE TITLE
Using networkx in Azure Databrick results in extremely slow writing to blob storage

### ISSUE THREAD

**Issue by phil-burrows** [networkx/networkx#5070]
I have developed a routing process for research on transportation network disruption events. The script runs well apart from writing the results df to Azure blob storage (as csv) extremely slowly. It's a small results file (3.8mb) of a pyspark dataframe takes over 3 hours to write. It would seem to me that the bug is somehow coming from having used nx functions on the df. The same file can be read, written and reread from blob storage very quickly in a notebook where nx is installed, but wasn't used on the df. Other applications in our department that use databricks (without networkx functions) have not experienced this slowdown issue. 

Is there any way implementing this package could result in extremely slow file writing? Has anyone else here deployed networkx tools in Azure Databricks/Azure storage explorer?

**Comment by dschult** [comment]
It is extremely unlikely that NetworkX affects the time needed to write files to disk -- or internet storage.
The reason is that we don't actually do the writing... other parts of python do. We call them.
If you are writing something as a csv file, networkx is not writing the csv file.

I would suggest trying writing it to a local disk to make sure that is fast -- and then writing a different dataframe (not NX related) of similar size to blob storage and see whether that is slow.
