### ISSUE TITLE
Refactor _AntiGraph to `nx.classes`?

### ISSUE THREAD

**Issue by stefanv** [networkx/networkx#5128]
`_AntiGraph` is defined in `kcomponents.py` and used in `k_components`. Is this the right place for that class to live?  The same exact class definition also appears [in the examples](https://github.com/networkx/networkx/blob/main/examples/subclass/plot_antigraph.py#L23).

**Comment by rossbar** [comment]
Good point - I'm not sure what the best approach is here. On the one hand, having duplicated code is obviously not ideal. OTOH, the `AntiGraph` in the examples is intended to illustrate how to properly subclass one of NetworkX's graph classes, whereas in `kcomponents.py` that same implementation is used internally (and, fortunately, privately) in the `kcomponents` code.

Due to the differing goals, I'd be less concerned about things like the implementations diverging, as the "how-to-subclass" example can still be useful even if the implementation is different than the `_AntiGraph` that is actually used in the library.

I don't have any concrete ideas or strong opinions about what to do here... anyone else?

**Comment by dschult** [comment]
I think having duplicate code as a private function and as an example is OK.
The codes can diverge over time -- but it probably is a good thing to let them diverge if needed to serve their different goals.
