### ISSUE TITLE
lowest_common_ancestor for multigraph

### ISSUE THREAD

**Issue by tkmamidi** [networkx/networkx#5209]
Hello,
I am working with a multigraph and would like to find the lowest common ancestor for nodes. It looks like there's no implementation for multigraph. Can you please help me with this?

**Comment by dschult** [comment]
Hmmm...  How would that differ for multigraph and graph?
Can't you just use the same function?

**Comment by tkmamidi** [comment]
This is what I get
![image](https://user-images.githubusercontent.com/41593805/144683566-76877580-78d5-4b7f-abb6-88b1d2117f82.png)

Also, the source code says that it is not implemented for multigraph
https://networkx.org/documentation/stable/_modules/networkx/algorithms/lowest_common_ancestors.html#lowest_common_ancestor

**Comment by dschult** [comment]
Hmmm...  You are right -- the code explicitly checks for multigraphs and rules them out.
We should probably look at that more closely. I can't think of a reason why that should be done.

A workaround is to convert the graph to a `nx.DiGraph` for the `lowest_common_ancestor` calculation:
```python
nx.lowest_common_ancestor(nx.DiGraph(final), "HP:0003388", "HP:0011968")
```

**Comment by tkmamidi** [comment]
That works for now :) 
Thanks for the help!
I really appreciate it!

**Comment by parikshit14** [comment]
@dschult can we apply the same solution internally as well for finding multigraph's `lowest_common_ancestor`, if so then I can create a PR for that.

**Comment by dschult** [comment]
I think of this method (converting the MultiDiGraph to a DiGraph so it produces a lowest_common_denominator) as a workaround. I'd rather figure out why the algorithm doesn't work for a `MultiDiGraph` and fix it.  It seems like it should.

**Comment by baheckman** [comment]
Is the `@not_implemented_for("multigraph")` needed for any of the LCA algorithms? According to the docs, these functions should work on any non-null DAG, which can include a MultiDiGraph I think.

A previous change refactored the decorator from `@not_implemented_for("multigraph", "undirected")` to the current setting [here](https://github.com/networkx/networkx/pull/2603). However, I think this should only need the `@not_implemented_for("undirected")` decorator. This would also throw an exception for s Multigraph, but allow MultiDiGraph to work as expected. 

If that's the case, I'm happy to file a PR for this one. If not then apologies for the noise here!

**Comment by dschult** [comment]
Can you figure out whether this code for LCA algorithms works for multigraphs?  Maybe take out the "not_implemented_for" line for multigraph and try it on a few carefully constructed MultiDiGraphs. If there are inconsistent results we could start with a test that shows the problem -- that might make it possible to adapt the code to work for MultiDiGraph. If there are no inconsistent results then it might be possible to remove the "multigraph" restriction.  But it is very simple to covert the MultiDiGraph to a DiGraph. So it might be sufficient to add that to the doc_string and maybe include an example of doing that.

There are definitely places in the code where `degree` is used and other places with `dfs_preorder` used. The degree could easily be a problem for MultiDiGraphs.  For example, the in-degree > 1 check would probably change if we had a MultiDiGraph instead of a DiGraph.
