### ISSUE TITLE
Write_graphml doesn't work on contracted graphs

### ISSUE THREAD

**Issue by taylorn3** [networkx/networkx#5292]
I cannot write a graph that has been contracted to a graphml file.

### Current Behavior
I receive the following error:
```
~/.local/lib/python3.9/site-packages/networkx/readwrite/graphml.py in write_graphml_lxml(G, path, encoding, prettyprint, infer_numeric_types, named_key_ids, edge_id_from_attribute)
    169         )
    170 
--> 171     writer = GraphMLWriterLxml(
    172         path,
    173         graph=G,

~/.local/lib/python3.9/site-packages/networkx/readwrite/graphml.py in __init__(self, path, graph, encoding, prettyprint, infer_numeric_types, named_key_ids, edge_id_from_attribute)
    727 
    728         if graph is not None:
--> 729             self.add_graph_element(graph)
    730 
    731     def add_graph_element(self, G):

~/.local/lib/python3.9/site-packages/networkx/readwrite/graphml.py in add_graph_element(self, G)
    768         for node, d in G.nodes(data=True):
    769             for k, v in d.items():
--> 770                 T = self.xml_type[self.attr_type(k, "node", v)]
    771                 self.get_key(str(k), T, "node", node_default.get(k))
    772         # Edges and data

KeyError: <class 'dict'>
```

### Expected Behavior
The graph should be exported to test.graphml

### Steps to Reproduce
```
import networkx as nx
G=nx.Graph()
G.add_edge("A","B")
G=nx.contracted_edge(G,["A","B"])
nx.write_graphml(G,"test.graphml")
```

### Environment

Python version: 3.9.5
NetworkX version: 2.6.3

### Additional context
It appears the issue is that NetworkX writes contractions as attributes of the node, but then the writer doesn't know how to handle dict attributes.

**Comment by rossbar** [comment]
Good question. Does the GraphML standard support containers as node attributes? If so then I'd say this is a bug, but even if not I think a more informative exception message could be raised.

**Comment by dschult** [comment]
Here's a fix.  The idea is that you need to remove the node attribute that has a value which is a dict. That's a limitation of the GraphML format. If you need these attributes, you can try a different graph format.

```python 
import networkx as nx
G=nx.Graph()
G.add_edge("A","B")
G=nx.contracted_edge(G,["A","B"])
for node, datadict in G.nodes.data():   # these two lines do the node attribute removal
    del datadict["contraction"]
nx.write_graphml(G,"test.graphml")
```

**Comment by taylorn3** [comment]
I understood the issue, and I could have solved it myself, if I saw it as not an issue with the package but with my own code.  Does NetworkX need to keep a record of the contractions that have been made?  Is that record used elsewhere?

**Comment by MridulS** [comment]
I don't think it's used anywhere inside networkx (the need for keeping a track of the contraction) but it's definitely something that people use (I remember using it for a project).
This is also an issue with supporting a bunch of different formats (this would be perfectly fine to be exported as a JSON blob for example).

I agree with @rossbar this should raise a better exception rather than the cryptic error, we should error out more gracefully.
That will also take care of the cases where folks added containers as edge attributes and ended up getting these cryptic errors.
Thanks for raising this @taylorn3!

**Comment by taylorn3** [comment]
Is the XML writer standard and unchangeable? Instead of throwing errors, would it be easier to (after line 769, for example) ask that k and v be of a certain type that the writer can handle, and ignore them otherwise?  Or would that just be too annoying to maintain?

**Comment by rossbar** [comment]
> Is the XML writer standard and unchangeable? Alternatively, instead of throwing errors, would it be easier to (after line 769, for example) ask that k and v be of a certain type that the writer can handle, and ignore them otherwise? Or would that just be too annoying to maintain?

IMO since there is a defined standard for this format I think it's best to adhere to it. Implementing features beyond the standard has a lot of potential downsides. For example, if NetworkX implements features that are not in the current version of the GraphML standard, but then GraphML is updated at some future date in a way that differs from NetworkX's implementation, then we have the sticky scenario of NetworkX's GraphML implementation being "wrong", but potentially having users that depend on the "wrong" behavior.

So if this feature is really desired, I would advocate for proposing it to whomever maintains the GraphML standard. In the meantime fortunately there are other graph format options that support attr dicts.

**Comment by rossbar** [comment]
Looking back at the issues history, it seems this has come up quite frequently. See also: #5058 #485 #3663 #5071.

Note that more informative error messages have already been added in #5058, so I will close this.
