### ISSUE TITLE
`to_numpy_recarray` throws `KeyError: weight`

### ISSUE THREAD

**Issue by juansebastianl** [networkx/networkx#5309]
Hello! I am running into trouble with `networkx` version 2.6.3 running an extremely simple script: 

     import networkx as nx
     c_50 = nx.complete_graph(50)
     nx.to_numpy_recarray(c_50)

Which throws a `KeyError: weight` in `convert_matrix.py`.

**Comment by rossbar** [comment]
`to_numpy_recarray` expects to be passed a structured dtype with named fields, which are used to determine which attributes to use in constructing the adjacency matrix. If you don't supply a dtype, then it's assumed that `"weight"` is the attribute of interest (though this fact is not adequately documented). This explains the exception you're seeing.

In your particular case it's not clear why you'd want a recarray instead of a `ndarray` given that your graph does not have edge attributes. You should probably be using `nx.to_numpy_array(c_50)` instead. If (for whatever reason) you *really* wanted a `recarray` (even though there are no named fields to access in the case above) you could do `nx.to_numpy_array(c_50).view(np.recarray)`.

**Comment by juansebastianl** [comment]
That is useful to know! I was writing a function which relied on the `recarray` output and the unweighted graph was a case I wanted to handle. In the general case I guess `nx.to_numpy_array` makes the most sense.
