### ISSUE TITLE
Error in running requirements/test.txt

### ISSUE THREAD

**Issue by JatinSharma** [networkx/networkx#5355]
While installing networkx, I was following the instructions on the contributor guide. 

### Current Behavior

The following code: 
`conda install -c conda-forge --file requirements/default.txt --file requirements/test.txt --file requirements/developer.txt`
results in error: 
`InvalidVersionSpec: Invalid version '0.14;platform_python_implementation!='PyPy'andpython_version<='3.10'': invalid character(s)
`
### Environment

Python version:3.8.8
NetworkX version:

**Comment by rossbar** [comment]
Requirements files are specifications for `pip` - AFAIK conda does not fully support reading from requirements files.

**Comment by JatinSharma** [comment]
When I removed the said line, it worked. Also in developer.txt file, the ~ operator was not recognized. Can I take up this issue to work seamlessly for conda?

**Comment by rossbar** [comment]
These lines are important for correctly specifying all the constraints, so I'm -1 on modifying requriements files to make them work with `conda`. In principle we could add an `environments.yml`, but IME that's a bit of a pain from a maintenance standpoint.

For conda users, my recommendation would be to use `conda` for environment management, then `pip` to install everything in the environment.

**Comment by JatinSharma** [comment]
Ok. Thank you.

**Comment by dschult** [comment]
Maybe we should rewrite our docs then to suggest the hybrid approach instead of having an example line of code that doesn't actually work.  I typically just go in and change the requirements file locally so it works for `conda`.  Does `pip` do things like install GraphViz when you install pygraphviz? Maybe pip is smarter now than when I last looked at it closely. :}

Anyway, we should fix the docs to provide a line of code that works for conda -- or to remove the description of how to make it work with conda.  I guess one option is to have requirements files for pip and other requirements files for conda.  I'm not sure we can make a single requirements file work for both.

**Comment by rossbar** [comment]
> Does pip do things like install GraphViz when you install pygraphviz?

No it doesn't; pip doesn't handle non-Python dependencies whereas `conda` handles installation of more packages. In order to install e.g. `pygraphviz` (or any library that has a non-Python dependency) with pip, users will have to have that package installed separately on their system.

> I guess one option is to have requirements files for pip and other requirements files for conda.

The way `conda` handles environment specification is with [environment files](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually). Many projects maintain both `requirements.txt` and `environments.yml` files, but this has it's own drawbacks, namely:
 - it's easy for them to get out of sync
 - The dependency resolvers for `pip` and `conda/mamba` are different, so it's possible that any environment specification that works with `pip` won't work with `conda` and vice-versa.

I'm ambivalent about adding and `environment.yml` file - on the one hand it probably helps windows users who want to set up a full development environment; OTOH it's another thing to maintain and AFAIK there are no good solutions for automatically keeping conda/pip requirements in sync. Adding "official" support for `conda` also opens up the whole can-of-worms regarding which "channel" packages are retrieved from, which has proved problematic for packages NX cares about, most especially [pygraphviz](https://pygraphviz.github.io/documentation/stable/install.html)
