### ISSUE TITLE
Filter* views input checks for NODE_OK look for .nodes attributes (?)

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#5374]
While working on https://github.com/networkx/networkx/issues/4433 I started looking into the code of `Filter*` views and I was wondering why do we have the bit about checking for the `.nodes` attributes in filtered nodes input (`NODE_OK`). 

https://github.com/networkx/networkx/blob/8feb4a645c93598bb187bf1707beb673fa27915e/networkx/classes/coreviews.py#L275-L278

Was this to make something like this work? @dschult 
```
>>> G = nx.Graph(...)
>>> H = nx.Graph(...)
>>> nx.subgraph_view(G, H)
A subgraph of G with nodes from H?
```
From what I know, nowhere in our current documentation do we claim that users can use anything except a `filter_node` callable to get the underlying `FilterAtlas` view.
 
For now if I remove the bits of code (https://github.com/networkx/networkx/pull/5373) none of our tests are complaining.

**Comment by dschult** [comment]
The blame indicates that this was added to try to speed up the subgraph views.  #3017
Most of the time we are using induced subgraphs. And most of the time there are far fewer nodes in the subgraph than in the graph. So we can speed up the process by iterating over the nodes of the filter and checking if they are in the graph, rather than iterating over the graph and checking if the nodes are in the filter.

So, I'm not surprised that no tests complained when you remove that code. It is supposed to speed thing up.
Perhaps a better comment would make that clear.

**Comment by dschult** [comment]
Perhaps this wasn't as clear as I intended. The testing for a `nodes` attribute is not to check if a NetworkX Graph `H` is used to specify the nodes in the subgraph. Any `show_nodes` filter has an attribute `nodes`. So, e.g. 
```python
SG = G.subgraph([2, 3])
assert SG._NODE_OK.nodes == [2, 3]
```
It's only the `show_nodes` filter, as far as I can tell, that benefits from this, but that is a common filter to use.
