### ISSUE TITLE
Weird results in average_neighbor_degree for directed graph

### ISSUE THREAD

**Issue by psrubing** [networkx/networkx#5383]
Hi,
I was looking at average_neighbor_degree method with directed graphs and I've got results that don't match with my intuition and my hand calculation. 

My graph:
![digraph](https://user-images.githubusercontent.com/37271385/157540141-125f7746-9258-45ea-b215-7f1c4433732b.png)

I've run average_neighbor_degree with every possible combination with params source and target which implies basic attributes for directed graph. Here's my code and results:

```
G = nx.DiGraph([(0, 3), (1, 3), (2, 4), (3, 5), (3, 6), (4, 6), (6, 5), (4, 3)])

print(f'in-in: {nx.average_neighbor_degree(G, source="in", target= "in")}')
print(f'in-out: {nx.average_neighbor_degree(G, source="in", target= "out")}')
print(f'out-in: {nx.average_neighbor_degree(G, source="out", target= "in")}')
print(f'out-out: {nx.average_neighbor_degree(G, source="out", target= "out")}')

in-in: {0: 3.0, 3: 1.3333333333333333, 1: 3.0, 2: 1.0, 4: 5.0, 5: 0.0, 6: 1.0}
in-out: {0: 2.0, 3: 0.3333333333333333, 1: 2.0, 2: 2.0, 4: 3.0, 5: 0.0, 6: 0.0}
out-in: {0: 3.0, 3: 2.0, 1: 3.0, 2: 1.0, 4: 2.5, 5: 0.0, 6: 2.0}
out-out: {0: 2.0, 3: 0.5, 1: 2.0, 2: 2.0, 4: 1.5, 5: 0.0, 6: 0.0}
```

Looking at this graph I don't understand how this is calculated and from where those results come from. It maybe a bug or it's something I don't understand how this alogrithm works. Either way could somone explain it to me please?

Best regards

### Environment

Python version: 3.8.8
NetworkX version: 2.5

**Comment by dschult** [comment]
Can you upgrade NetworkX?  This function was updated last summer and you've got a version older than that.  

My results show:
```
   >>>  G = nx.DiGraph([(0, 3), (1, 3), (2, 4), (3, 5), (3, 6), (4, 6), (6, 5), (4, 3)])
   ...: print(f'in-in: {nx.average_neighbor_degree(G, source="in", target= "in")}')
   ...: print(f'in-out: {nx.average_neighbor_degree(G, source="in", target= "out")}')
   ...: print(f'out-in: {nx.average_neighbor_degree(G, source="out", target= "in")}')
   ...: print(f'out-out: {nx.average_neighbor_degree(G, source="out", target= "out")}')
   ...: 
in-in: {0: 0.0, 3: 1.3333333333333333, 1: 0.0, 2: 0.0, 4: 5.0, 5: 0.0, 6: 1.0}
in-out: {0: 0.0, 3: 0.3333333333333333, 1: 0.0, 2: 0.0, 4: 3.0, 5: 0.0, 6: 0.0}
out-in: {0: 3.0, 3: 2.0, 1: 3.0, 2: 1.0, 4: 2.5, 5: 0.0, 6: 2.0}
out-out: {0: 2.0, 3: 0.5, 1: 2.0, 2: 2.0, 4: 1.5, 5: 0.0, 6: 0.0}
```

**Comment by psrubing** [comment]
Okey, I've upgraded NetworkX to version 2.7.1 and now I have the same results as you, but still I can't understand the math behind calculating those values. Let's take for example node number 3. It's has 5 neighbors (0, 1, 4, 6, 5 where 0,1,4 are in neighbors and 5,6 are out neighbors). Let's suppose I want to calculate source=in and target in version. Shouldn't it be (in_degree_0 + in_degree_1 _ in_degree_4)/3 = (0+0+1)/3 = 0.333. The method returns 1.333. Could you provide more details how is it calculated?

**Comment by rossbar** [comment]
The `average_neighbor_degree` calculation is described in the [docstring of the function](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.assortativity.average_neighbor_degree.html)

Alternatively you can take a look at the implementation itself to get a better sense of how it's computed. This is very easy to do with e.g. IPython, where the `??` will show the function implementation. However, since we're on GH:

https://github.com/networkx/networkx/blob/0ce72858168a8ece6b55f695677f4be80f144aff/networkx/algorithms/assortativity/neighbor_degree.py#L124-L138

So, does the confusion arise because what is being computed is different than your expectation, or perhaps there's a problem with the implementation? We'll need to answer this question before we can determine how best to improve things (better docs, fix a defect, etc.)

**Comment by dschult** [comment]
It looks like the question is: "What is a neighborhood?"  You are thinking (reasonably in my view) that when `source_degree` is "in", that the neighbors should be the incoming neighbors. That is any nodes which connect to the source node. But in fact, that is not what is done in the code. And it seems to be mixed up from what I'd expect.

In the code, the sum is always over the neighbors on the outgoing edges from the source node.  But the size of the neighborhood is computed based on the keyword `source_degree` as "in" or "out". So that when "in" is indicated, we sum over outgoing neighbors but divide by the number of incoming neighbors. 

In your example and considering node 3, it is currently computing (in_degree_5 + in_degree_6) / 3 = (2+2)/3 = 1.333.  This is certainly one way to extend the formula to the directed case, but it seems wonky.

Does the reference talk about directed graphs and how to handle them.  Or is there another reference that does?

**Comment by psrubing** [comment]
@rossbar Thanks for your answer! Regarding to how this method calculates due to @dschult explanation now I understand and know where those results come from, but to be honest it still doesn't match my intuition on how should it be calculated (like @dschult said, "the sum is always over the neighbors on the outgoing edges from the source node. But the size of the neighborhood is computed based on the keyword source_degree as "in" or "out". - why it's always summed up over the outgoing edges? It's little bit confusing and it should be better explained in docs, because there are only few words about parameters 'in' and 'out' in source and target nodes and there is none information how it's connected to neighborhood "size" and how the sum is calculated.

@dschult  Thank you very much for your explanation, now I get it! But nevertheless it's still little bit confusing how it was implemented and from what you said I have reasonable point of view on how those parameters about source node should impact calculation. Because of what you said (you agree that it seems to mixed up) may I ask if you will be changing this method in near future?

**Comment by dschult** [comment]
Yes -- let's leave this issue open so that we will address the documentation at the least and (hopefully) improve the method so it is actually taking an average of degrees instead of summing over one neighborhod and dividing by the size of another neighborhood.

I'd love to have a paper that talks about "nearest neighbor average degree" (or "average neighbor degree") in the context of directed graphs.
