### ISSUE TITLE
Networkx generates an unusual graph (figure keeps on changing and labels are scattered)

### ISSUE THREAD

**Issue by vappiah** [networkx/networkx#5421]
### Current Behavior
When I generate a weighted graph  labels are not placed properly. Also the figure keeps on changing anytime I run the codes.
Here are three figures that were generated using the same codes.
![Figure_1](https://user-images.githubusercontent.com/14283733/160019015-5026f06c-a738-4c3a-828d-223b904397d1.png)
![Figure_2](https://user-images.githubusercontent.com/14283733/160019022-60ac2839-6b5f-4865-8ab8-a074d1415de3.png)
![Figure_3](https://user-images.githubusercontent.com/14283733/160019023-e62c03a2-1beb-427f-ba3d-f7e26af7643c.png)

### Reproducer

```python
import matplotlib.pyplot as plt
import numpy as np
import networkx as nx

nodes=['1', '2', '3', '4', '5']

P=nx.Graph()
P.add_nodes_from(nodes)

weighted_edges=[('1', '2' ,0.11),('1', '3', 3.1),('1','5',2.25),('4','5',0.25),('2','5',0.2),('2','4',0.22),('2','3',0.2)]

P.add_weighted_edges_from(weighted_edges)
#get edges, positions and weights

pos=nx.spring_layout(P)
labels=nx.get_edge_attributes(P,'weight')
nx.draw(P, with_labels = True)
#get edge labels
edge_labels=dict([((u,v,),d['weight']) for u,v,d in P.edges(data=True)])
#add edge labels

plot=nx.draw_networkx_edge_labels(P,pos,edge_labels=edge_labels,font_weight='normal')

plt.show()
```

### Environment
Python version: 3.8.10
NetworkX version: 2.6.3

**Comment by rossbar** [comment]
Thanks @vappiah - I went ahead and just embedded the reproducing code directly in the issue, as it's much more straightforward to see what's going on.

There are two things in this example that jump out to me:
 1. You are not using the `pos` with `draw` - this is why the edge labels are in different positions than the edges
 2. You are not using a seed when computing the layout, which is why the results are different each time you plot

Re: `1.` - `nx.draw` computes the layout under the hood when `pos=None`. You can fix this issue by: `nx.draw(P, pos=pos, with_labels=True)`.
If you want to guarantee that the positions will be the same every single time, you should provide a `seed` to the layout algorithm, e.g. `pos = nx.spring_layout(P, seed=123456789)`

**Comment by MridulS** [comment]
Changing the code with @rossbar suggestions should get you the same results every time. 

Editing the code at these 2 places gives me consistent results locally when I run it multiple times :)

``` python
import matplotlib.pyplot as plt
import numpy as np

import networkx as nx

nodes = ["1", "2", "3", "4", "5"]

P = nx.Graph()
P.add_nodes_from(nodes)

weighted_edges = [
    ("1", "2", 0.11),
    ("1", "3", 3.1),
    ("1", "5", 2.25),
    ("4", "5", 0.25),
    ("2", "5", 0.2),
    ("2", "4", 0.22),
    ("2", "3", 0.2),
]

P.add_weighted_edges_from(weighted_edges)
# get edges, positions and weights

pos = nx.spring_layout(P, seed=1)  # Add the seed here

labels = nx.get_edge_attributes(P, "weight")

nx.draw(P, pos=pos, with_labels=True)  # add the position argument

# get edge labels
edge_labels = dict(
    [
        (
            (u, v),
            d["weight"],
        )
        for u, v, d in P.edges(data=True)
    ]
)
# add edge labels

nx.draw_networkx_edge_labels(P, pos, edge_labels=edge_labels, font_weight="normal") # no need to create the variable plot

plt.show()
```

Feel free to reopen this issue if you have any other queries :)

**Comment by vappiah** [comment]
Thanks @rossbar  and @MridulS .
The codes  you suggested worked successfully and gave consistent output.
