### ISSUE TITLE
Wrong output in `hamiltonian_path()`

### ISSUE THREAD

**Issue by NikitaSharma1** [networkx/networkx#5551]
According to documentation, the `hamiltonian_path()` function is applicable only for tournament graphs, but, it is not checking whether the graph is a tournament or not. Moreover, it gives the wrong output even if the graph doesn't have a hamiltonian path. 

Current Output
```py
>>> from networkx.algorithms import tournament
>>> G = nx.DiGraph([(1, 2), (2, 3), (0, 1), (4, 3)])
>>> tournament.is_tournament(G)
False
>>> tournament.hamiltonian_path(G)
[1, 2, 3, 0, 4]
```
The code should check for the tournament graph first and return "G is not a tournament graph" instead of the wrong output.

**Comment by NikitaSharma1** [comment]
Another suggestion,
Every tournament graph has a hamiltonian path but the hamiltonian path can exist even if the graph is not a tournament or directed graph. So, maybe this function can be used for all undirected and directed graphs as well.

**Comment by MridulS** [comment]
> So, maybe this function can be used for all undirected and directed graphs as well.

Finding the hamiltonian path is a hard problem and it's not trivial to generalize the hamiltonian function for a tournament graph to work with any general graph :)

But we should definitely catch the "G is not a tournament graph" error as users shouldn't really use a function from a sub-package namespace on general graph in networkx.

**Comment by dschult** [comment]
The tournament module is quite clear in the documentation that rather than check `is_tournament` for each function, it is the responsibility of the user to provide a tournament graph as input. So, my impression is that we don't want to make each function test for a tournament graph before it runs its code. Perhaps that warning language needs to be spread to all the function doc_strings as well. I haven't looked at how long it takes to run `is_tournament` recently either.  But I don't think there has been any confusion with the current setup.

This is part of the reason why we have a separate namespace for these functions. So this may relate to #5542 
although that Issue also talks about bringing only the `is_tournament` function into the main namespace.
With a separate namespace, it is much less likely that people will mistakenly run these functions on a non-tournament graph.

**Comment by rossbar** [comment]
I've reviewed the documentation for the functions in the `tournament` module and it looks to me like they are in good shape re: notifying the user that the input should be a tournament graph. This is admittedly a subjective assessment, so if there are ideas for concrete documentation improvements, please submit a PR!

I'm going to go ahead and close this as resolved, but again - improvements to `tournament` documentation is always welcome.

**Comment by plammens** [comment]
> Finding the hamiltonian path is a hard problem and it's not trivial to generalize the hamiltonian function for a tournament graph to work with any general graph :)

I would add that even though the implementation might not be efficient, a basic function for finding hamiltonian paths in general (for small graphs) is clearly needed in a reference graph package such as `networkx`.

**Comment by plammens** [comment]
> We are happy to include a submission along those lines if it is well tested and documented. This [wikipedia article](https://en.wikipedia.org/wiki/Hamiltonian_path_problem#:~:text=An%20early%20exact%20algorithm%20for,in%20the%20path%2C%20and%20undecided.) hints at some algorithms to try.

The most basic option that occurs to me is something like this:

```python
def hamiltonian_paths(graph: nx.Graph):
    for source in graph.nodes:
        yield from _hamiltonian_paths(graph, source)


def _hamiltonian_paths(graph: nx.Graph, source):
    total_nodes = len(graph.nodes)

    def dfs(node, path: tuple):
        if len(path) == total_nodes:
            yield path

        for neighbour in graph[node].keys() - path:
            yield from dfs(neighbour, path=path + (neighbour,))

    yield from dfs(source, path=(source,))
```

Perhaps rewriting the recursion with a stack for efficiency. 

Or even just filtering the results from `nx.all_simple_paths` to avoid re-implementing a DFS.

But I assume you're looking for a more sophisticated algorithm than this, like those mentioned in the Wikipedia article?
