### ISSUE TITLE
Properly handle edge cases for greedy_modularity_communities

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#5562]
Currently we don't do a good job of catching edge cases like empty graph, no edges, 3 nodes 1 edge:
``` python
>>> greedy_modularity_communities(G) # empty graph
....
....
ValueError: cutoff must be between 1 and 0. Got 1.

>>> greedy_modularity_communities(G) # 3 nodes 1 edge
.....
.....
StopIteration:

>>>  greedy_modularity_communities(G) # no edges
....
....
ZeroDivisionError: division by zero
```

We should catch them and error out more gracefully.

**Comment by stanyas** [comment]
Hi Mridul,

I would like to work on the issue, plus its visualization. Is this the desired behavior? 

Instead of ValueError, printing 'This is an empty graph.' 
Instead of StopIteration, printing 'Only one edge.' 
Instead of ZeroDivisionError, print 'no edges.'

Thanks.

**Comment by dschult** [comment]
I think the middle error was fixed in #5550 recently.  So that’s helpful. ;}

The other two cases could maybe raise a NetworkXPointlessConcept exception explaining that there are no edges upon which to build communities.  
But I’d prefer that we return an object that makes sense for the request rather than raise an exception.  That way when people apply this function to a large collection of graphs, and one happens to e.g. have no edges, it doesn’t break the process with an exception.  I know they can just use try/except. But it’s probably better for them to just get an empty list back…   Thoughts?

The first and 3rd case can be handled as one case by testing for `G.size() == 0` in which case my suggestion is to return `[{n} for n in G]`. That would be an empty list for the null graph, and each node in its own community for the no edges case. I think these make sense…???    We’ll need tests too, of course.

**Comment by rossbar** [comment]
>  But I’d prefer that we return an object that makes sense for the request rather than raise an exception. That way when people apply this function to a large collection of graphs, and one happens to e.g. have no edges, it doesn’t break the process with an exception. I know they can just use try/except. But it’s probably better for them to just get an empty list back… Thoughts?

I agree that this behavior is preferable from a usability standpoint :+1: 

> The first and 3rd case can be handled as one case by testing for G.size() == 0 in which case my suggestion is to return [{n} for n in G]. That would be an empty list for the null graph, and each node in its own community for the no edges case. I think these make sense…???

I like this idea, assuming it makes sense in the context of what constitutes a "community" - I defer to the experts! @z3y50n does this sound reasonable to you?

**Comment by j-hap** [comment]
The `ZeroDivisionError` also happens (of course) when inputting a graph without edges into `networkx.algorithms.community.quality.modularity`.

**Comment by khushishikhu** [comment]
Hi @MridulS I would like to take up this issue. I have setup the local development environment

**Comment by MridulS** [comment]
Please feel free to send a PR @khushishikhu

**Comment by khushishikhu** [comment]
@MridulS how do you test the outcome? I ran the command `PYTHONPATH=. pytest networkx` but i can't figure out the specific results tests_modularity_max.py file.

**Comment by khushishikhu** [comment]
I tried to understand the code and researched.
came up with the following output by acknowledging @dschult comment.
![Screenshot 2023-10-07 115114](https://github.com/networkx/networkx/assets/65439761/8cc627c0-1f43-4380-9ba0-0d0968d4b40b)
@MridulS please have a look
I tried to cover first and third edge case

**Comment by MridulS** [comment]
@khushishikhu please open a pull request, it's much easier to review and comment on a pull request vs a screenshot :)

**Comment by khushishikhu** [comment]
@MridulS I have raised a PR . Please check it out and give me your recommended suggestions

**Comment by Ytemiloluwa** [comment]
Hello @MridulS I will like to work on this as well. Can I ?
