### ISSUE TITLE
Ordering of layers in multipartite_layout changed in v2.7. Add a way to control the order?

### ISSUE THREAD

**Issue by lthumbe** [networkx/networkx#5691]
I am trying to run a script to plot graphs, but they're coming out wrong. I've tracked down the issue to incorrect positions obtained from the multipartite_layout command, which is either ignoring or misordering the node layer information.

### Current Behavior
The positions output by multipartite_layout don't order the layers correctly.

### Expected Behavior
The positions output by multipartite_layout should order the layers by value.

### Steps to Reproduce
Here is a snippet of what I currently get for the position of nodes in a small graph:
import networkx as nx

```
G = nx.DiGraph()
G.add_node('a',layer=2)
G.add_node('b',layer=3)
G.add_node('c',layer=1)
G.add_node('d',layer=2)
G.add_node('e',layer=4)
nx.multipartite_layout(G,align='horizontal',subset_key='layer')

{'d': array([-0.27777778, -0.66666667]),
 'a': array([ 0.27777778, -0.66666667]),
 'b': array([ 0.        , -0.11111111]),
 'c': array([0.        , 0.44444444]),
 'e': array([0., 1.])}
```
What I expect to get out (and can still see if I use an online compiler) is
```
{'d': array([-0.3125, -0.25  ]),
 'a': array([ 0.3125, -0.25  ]),
 'b': array([0.   , 0.375]),
 'c': array([ 0.   , -0.875]),
 'e': array([0., 1.])}
```

### Environment
Python version: 3.9.12
NetworkX version: 2.7.1

### Additional context
On an older computer when I had this issue I was able to resolve it by uninstalling and reinstalling Anaconda. This time I'm working from a new computer with a fresh install and uninstalling/reinstalling doesn't work.

**Comment by dschult** [comment]
In PR #5153 we allowed non-numeric layer values. But that change also impacts the order of the layers in the multipartite layout. The order of the layers is no longer determined by the layer's numeric value.  Notice that we never intended the layer's value to be required to be a number nor to reflect the position/order of the layers. But I can see why it would be surprising to suddenly have that change.

At the moment, the order of the layers is determined by the order that the nodes are reported by `G.nodes`.  That is, the layers are ordered based on the first time in `G.nodes` that a node has that layer value.  So, with your example, the nodes are ordered alphabetically, so the layer for 'a' is the first layer even though it's layer is `2`. Layer `1` is not positioned until node `c` is processed.  

Technically this is not a bug because we never guaranteed the order of the layers, but our implementation did provide an order and we changed that order. So we broke backward compatibility and should provide a way to indicate the order of the layers.

I'm going to change the title of this issue to reflect a request for the ability to choose the order of the layers in a multipartitie layout.  A solution will need a way to allow the user to indicate the order of the layers while still allowing non-numeric layer values.  Suggestions?

**Comment by rossbar** [comment]
> This would handle the case when the layer identifiers are unsortable, but it will also work for ordering the layers according to a sort of the layer identifier when all layer identifiers are sortable. It does not allow the layer identifier to provide the numerical value for the position of that layer. Is that important to allow? That is how it used to work, so maybe good to have it available...

I think this is the way to go. Even though the ordering was never guaranteed, it's clear that users are relying on it (see also #5515 ) and it's perfectly reasonable to expect numeric layers to be sorted. I prefer the solution proposed above to e.g. adding a new keyword argument.
