### ISSUE TITLE
draw_networkx_edges ignores connectionstyle parameter

### ISSUE THREAD

**Issue by jackhenderson101** [networkx/networkx#5694]
If you call `draw_networkx_edges` with an undirected graph with no self loops, the `connectionstyle` parameter is ignored unless `arrows=True`.
This is not clear from the documentation. Either the documentation could be changed to clarify this, or the code could be changed to use the FancyArrowPatch when the connectionstyle parameter is included.

**Comment by dschult** [comment]
Would changing the name of `arrows` to `fancy_edges` alleviate this confusion?
When `fancy_edges` is False, the arrowstyle and connectionstyle are ignored.
Directed graphs default to `fancy_edges=True`, Undirected graphs default to `fancy_edges=False`.
Hmmmm.... maybe its the same problem.  But what do you think? Would that be less confusing?

**Comment by Qudirah** [comment]
@dschult can I work on this?

**Comment by dschult** [comment]
I think it would be fine to work on this -- but you should realize that the final API decisions haven't been made. It might be helpful to see what could work though.

It looks like `arrows` is only used to help set a variable called `use_lineCollection`.  Maybe that should be the name of the input variable instead of `arrows` or `fancy_edges`. Whatever we call it, it should have 3 possible inputs: None, True and False. None means we determine a default from `G.is_directed()` and based on whether connectionstyle or arrowstyle are set. True or False mean we use those values (but should check whether connectionstyle and arrowstyle make sense in these cases and raise a warning (or exception?) in those cases.

Changing the code is not too hard, but making those decisions might be. :)

**Comment by dschult** [comment]
Closed due to being fixed in #6098
