### ISSUE TITLE
graph.copy() retains the original graph attribute dictionary if graph_attr_dict_factory is defined

### ISSUE THREAD

**Issue by peterhs73** [networkx/networkx#5703]
### Current Behavior

The copy created using`graph.copy` shares the same graph attribute dictionary as the original, when graph_attr_dict_factory is defined (similar to the example [antigraph](https://github.com/networkx/networkx/blob/main/examples/subclass/plot_antigraph.py)).

### Expected Behavior

Expect `H.graph` is a shallow copy of  `G.graph`.

### Steps to Reproduce

```python

class AntiGraph(Graph):

    graph_attr_dict = {"weight": 1}

    def single_graph_attr_dict(self):
        return self.graph_attr_dict

    graph_attr_dict_factory = single_graph_attr_dict

>>> G = AntiGraph()
>>> G.add_node(1)
>>> H = G.copy()
>>> H.graph is G.graph
True
```

### Environment

Python version: python 3.8.13
NetworkX version: 2.8.3

### Additional context

The [copy method](https://github.com/networkx/networkx/blob/main/networkx/classes/graph.py):

```python
class Graph:
    ...
    def copy(self, as_view=False):
        if as_view is True:
            return nx.graphviews.generic_graph_view(self)
        G = self.__class__()
        G.graph.update(self.graph)
        G.add_nodes_from((n, d.copy()) for n, d in self._node.items())
        G.add_edges_from(
            (u, v, datadict.copy())
            for u, nbrs in self._adj.items()
            for v, datadict in nbrs.items()
        )
        return G
``` 
The defined class attribute `graph_attr_dict = {"weight": 1}` in `AntiGraph` is mutable and shared across all instances. When the copy G is created, the newly defined `G.graph` is `self.graph`, rather than creating a shallow copy of the graph attribute.

I am not sure if this is intentional, but I think the examples and documentation are not clear that this is the expected behavior.

**Comment by dschult** [comment]
If I understand correctly, your example creates a class where every instance shares the same graph attribute dict.
In that case, when you make a copy of that graph, it will still be an instance of that class, and thus it will share the same graph attribute dict.  Are you asking that the copy method create a Graph object instance of your subclass?

**Comment by peterhs73** [comment]
I guess I am asking if this is the intended behavior, or maybe have a note in the documentation? Without looking at the internal code, the documentation and the examples suggest that a copy of the graph attribute dictionary is created.

subclass:
> graph_attr_dict_factoryfunction, (default: dict)
Factory function to be used to create the graph attribute dict which holds attribute values keyed by attribute name. It should require no arguments and return a dict-like object.

graph.copy:
> The copy method by default returns an independent shallow copy of the graph and attributes. That is, if an attribute is a container, that container is shared by the original an the copy. Use Python’s [copy.deepcopy](https://docs.python.org/3/library/copy.html#copy.deepcopy) for new containers.

[subclass example](https://networkx.org/documentation/stable/auto_examples/subclass/plot_antigraph.html)

I think fixing this on the user side can be done. For example, make`single_graph_attr_dict` return a copy of the graph dictionary. 

```python
class AntiGraph(Graph):

    graph_attr_dict = {"weight": 1}

    def single_graph_attr_dict(self):
        return self.graph_attr_dict.copy()

    graph_attr_dict_factory = single_graph_attr_dict
```

**Comment by rossbar** [comment]
> I guess I am asking if this is the intended behavior, or maybe have a note in the documentation? Without looking at the internal code, the documentation and the examples suggest that a copy of the graph attribute dictionary is created.

The `graph_attr_dict_factory` is a *factory function* that returns a dict-like. In the particular case of the `AntiGraph` example, the factory simply returns an existing *class attribute* (i.e. `graph_attr_dict`), so yes, in this case the example is specifically designed so that the graph_attr_dict common to all AntiGraph instances. In principle this is a useful pattern as it allows the subclass designer tighter control over the memory footprint of the subclasses. The best example of why you might want to do this is the `ThinGraph` example in the [section of the Graph docstring on subclassing](https://github.com/networkx/networkx/blob/14c294b372efe1423dc2666457c98fc428ca0d02/networkx/classes/graph.py#L241-L260).

Your update to the example would indeed get you closer to the behavior you were expecting (though with some probably unintended side effects if you ever added a mutable object to the dict due to the shallow copy!) but a more idiomatic way to achieve the desired behavior would be to use the factory function pattern, which might look something like:

```python
class AntiGraph(nx.Graph):
    graph_attr_dict_factory = lambda self: dict([("weight", 1)])

# Test that this behaves as expected
>>> G1 = AntiGraph()
>>> G1.graph["weight"]
1
>>> G2 = G1.copy()
>>> G2.graph is G1.graph  # different instances produced by factory
False
>>> G2.graph["weight"] = 3
>>> G1.graph["weight"]
1
```

**Comment by peterhs73** [comment]
> In principle this is a useful pattern as it allows the subclass designer tighter control over the memory footprint of the subclasses.

I agree. If this is the intended behavior, I would prefer an example of how the graph attribute should be used or the behavior is noted in `graph.copy` docstring. I am going to close this issue since this depends on the interpretations. Thank you.

**Comment by dschult** [comment]
Another possibly useful pattern for how this would be used is, e.g. if you wanted a defaultdict instead of a dict for your subclass. Maybe you want your subclass to assign a default attribute value of "not assigned" for any attributes that are not assigned.  Then you could create the new class like this:

```python
import collections
class DefaultGraphAttrClass(nx.Graph):
    graph_attr_dict_factory = lambda self: collections.defaultdict(lambda :"not assigned")

G = DefaultGraphAttrClass([(0,1)])
G.graph["date"]="today"
H = G.copy()
assert H.graph is not G.graph
assert H.graph == G.graph
```
