### ISSUE TITLE
Converting from DOT graph file to NetworkX graph adds unexpected '\\n' node

### ISSUE THREAD

**Issue by KrishivVora** [networkx/networkx#5803]
Converting from a DOT graph file to a NetworkX graph using the function G = nx.Graph(nx.nx_pydot.read_dot(path)) (as mentioned on https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pydot.read_dot.html) adds an unexpected and inexplicable '\\n' node to the NetworkX graph that is not present in the Graphviz DOT graph.

### Current Behavior
NetworkX graph has an extra '\\\n' node that shouldn't be there.

### Expected Behavior
NetworkX graph has exactly the same nodes as the DOT graph file indicates.

### Steps to Reproduce
Create a simple DOT graph file and convert it to NetworkX using G = nx.Graph(nx.nx_pydot.read_dot(path)), then show nodes using nx.nodes(G).

### Environment
Python version: 3.9.12
NetworkX version: 2.7.1

**Comment by MridulS** [comment]
Thanks for the report @KrishivVora, please go through https://github.com/networkx/networkx/issues/5686. This is an issue if you mix `pydot` and `networkx` read write functions. A `pydot` write to disk adds the extra `\n`.

A workaround could also be to use `nx.nx_agraph` (pygraphviz) instead of `nx.nx_pydot` (pydot). I'll close the issue for now, but please feel free to put in more details if you think there are any other issues :)
