### ISSUE TITLE
Improve testing for directed_edge_swap

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5814]
There is an opportunity to improve the testing of the `directed_swap_function`.

There is a concrete suggestions [here](https://github.com/networkx/networkx/pull/5663#discussion_r906225024) for improving `test_directed_edge_swap` by validating that the input and output edges are indeed different. Upon reflection, I think this check could even be improved further by verifying that the number of swaps is correct... I think the difference in the edge sets should be 2*`nswap` - that might be one way to check.

It'd also be good to add more test cases of non-path graphs where there are only a limited number of edge swaps possible, and verify that the algorithm can recover all of them. See [the discussion](https://github.com/networkx/networkx/pull/5663#pullrequestreview-1018715617) for further details.

**Comment by Dishie2498** [comment]
Hello
I would like to take up this issue. I will open a pull request soon.

I have made the function `test_directed_edge_swap()`  assert that the edges of the original DiGraph and the one after swapping edges are not all the same, in addition to checking the in and out degree of the graph.

Also, in order to remove the limitation of test on path graph only, I have made changes which would generate a random directed graph (which would not be a path graph) and run the tests on it.

**Comment by dschult** [comment]
Testing a random graph isn't all that helpful. It would be better to test a graph with a specific configuration that you are concerned will be handled correctly by the function. Random graphs give a different result every time you run them, so it is very hard to track down what the cause of the error is. You can specify a "seed" to make it the same result every time, but that is no longer random. It is just some arbitrary graph that you usually don't know much about. 

So, if you want to expand beyond a `path_graph`, I would suggest choosing a specific graph that has a different topology and working with that.  One option would be a complete graph with only one directed edge for each edge pair.
```python
G = nx.DiGraph(nx.complete_graph(N).edges)
``` 
You should think about better graphs to test edge swaps. I just made this one up as something that looks very different from a path -- not because of some feature about edge swaps. 

Thanks for taking this on! :}
