### ISSUE TITLE
Amount of nodes and edges have mistakes when reading adjlist file

### ISSUE THREAD

**Issue by forestbat** [networkx/networkx#5911]
I wrote this code：
`nx.write_adjlist(network_graph, 'network_graph.adjlist')`
And debug info is like this：

> DiGraph with 269 nodes and 244 edges (Correct amount）

However when I read the same adjlist file like this：
`network_graph = nx.read_adjlist('network_graph.adjlist')`
debug info told me：

> Graph with 429 nodes and 723 edges（Wrong amount）

And I can't find useful information from the wrong graph，so why it will happen and how I can solve it？
This is my adjlist file：https://paste.ubuntu.com/p/QFBNqshqsj/

**Comment by rossbar** [comment]
The problem is that your nodes (which appear to be 2-tuple coordinates) contain whitespaces, which [is treated as the delimiter character by default for the `read_` and `write_` adjlist functions](https://networkx.org/documentation/latest/reference/readwrite/generated/networkx.readwrite.adjlist.read_adjlist.html).

You should be able to fix this for your case by choosing a delimiter character doesn't appear in your nodes, e.g. `"|"`.

**Comment by rossbar** [comment]
AFAICT this behavior isn't mentioned in the documentation anywhere, so the documentation seems like it could be improved here!

**Comment by forestbat** [comment]
@rossbar Thank for your reply，and amount of nodes and edges are correct.
However I have another problem：networkx will parse data like (124.18640986496392, 43.72390986496422) in adjlist file to '(124.18640986496392, 43.72390986496422)'，is a string instead of tuple.
I use this setting：
`network_graph = nx.read_adjlist('network_graph.adjlist', delimiter='|', nodetype=(float, float))`
And the console told me：

> TypeError: Failed to convert node ((124.6171154674783, 44.175448800812)) to type (<class 'float'>, <class 'float'>)

How to solve this problem？The document isn't so detailed.

**Comment by rossbar** [comment]
The read/write adjlist functions are very simple and don't really have a mechanism for generic node serialization (i.e. converting complicated node types to/from string formats). You might want to take a look at the [parse_adjlist](https://github.com/networkx/networkx/blob/5c0b11afb4c0882a070d522ef3fa41482ba935d3/networkx/readwrite/adjlist.py#L140-L209) for further details.

At face value, it seems the text-based read/write adjlist functions are too simplistic for what you're trying to accomplish. I would recommend either:
 1. Changing the problem statement a bit. For example, using tuples of floats as nodes is not a good idea *in general* as floating point values can be tricky in the context of e.g. comparison. You could instead relabel the nodes so that the nodes themselves are integers and 2-tuple coordinate data are stored on the nodes as attributes. You could then use one of the existing graph formats that supports node attributes to round-trip your data more reliably.
 2. implement custom parsing for your data; for example, you could convert the data from file back into Python 2-tuples with something like `conv = lambda t: tuple([float(v) for v in str(t).strip("()").split(",")])`. Of course, you'd then have to handle the construction from adjacency in a different way...

**Comment by forestbat** [comment]
@rossbar Thank you for very much！I solved my problem，however I will keep this issue open util they change document or close this issue.

**Comment by brocla** [comment]
How about adding this text to the notes for `write_adjlist`?

> If spaces are embedded in the names of nodes, the parser in `read_adjlist` will be confused becasue _space_ is the default delimiter. The parser will not know if a _space_ belongs in the node name or is just a delimiter. To avoid this problem, specify an alternate delimiter when spaces are valid in node names.

A similar note should be added to `generate_adjlist`.  It has the same issue.

**Comment by rossbar** [comment]
> How about adding this text to the notes for write_adjlist?

Thanks @brocla , your suggestion would do the trick IMO. Another option would be to add an example of round-tripping to the `Examples` section of the docstring, though that may be more work. I think either approach would be fine!

**Comment by Qudirah** [comment]
@rossbar Can I work on what you have suggested?

**Comment by rossbar** [comment]
> Can I work on what you have suggested?

Absolutely, please do!

**Comment by Qudirah** [comment]
> > Can I work on what you have suggested?
> 
> Absolutely, please do!

Just to be clear I go to the doc/readwrite/adjlist.rst and indicate a note under read_adjlist and generate_adjlist. Please correct me if I am wrong
