### ISSUE TITLE
deterministic pos

### ISSUE THREAD

**Issue by davejakenic** [networkx/networkx#5920]
The following code shall --whenever called with identical data ```V,E```-- create the exact same image.

The documentation does not permit a clue on whether or where any randomness might be involved.
I am aware that the optional argument "pos" may be created by an nx.layout function such as the kamada_kawai_layout.
Notice however, that all this misses what the question is.

```
G=networkx.DiGraph()
G.add_nodes_from(V)
G.add_edges_from(E)
networkx.draw_networkx(G,nodelist=[i for i in range(len(V))],labels=V)
matplotlib.pyplot.show()
```

**Comment by rossbar** [comment]
In general this will *not* result in deterministic node positions because the default behavior is to use `spring_layout`, which is not deterministic. This behavior is [noted in the documentation](https://networkx.org/documentation/latest/reference/generated/networkx.drawing.nx_pylab.draw_networkx.html?highlight=draw_networkx#networkx.drawing.nx_pylab.draw_networkx) (specifically, in the description of the `pos` parameter).

For some simple cases (e.g. a small path graph) spring layout *may* result in a visually similar layout when called multiple times in a row, this is not guaranteed however.

As you've noted, if you need determinism, you should compute the layout specifically with the `seed` argument.

**Comment by MridulS** [comment]
I'll go ahead and close this, if there is a way we can make the documentation better please let us know :)
