### ISSUE TITLE
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'

### ISSUE THREAD

**Issue by forestbat** [networkx/networkx#5996]
I want to print picture of my digraph: `nx.draw_networkx(upstream_graph, node_size=10)`

However it crashed like this: https://pastebin.ubuntu.com/p/yt5pCpKkVX/

My version of networkx is 2.8.6, and version of matplotlib is 3.6.0. I think this is not my problem,so please fix or help me resolve this problem.

**Comment by dschult** [comment]
Can you plot (in the same workflow) a simple matplotlib figure that isn't networkx?
That would indicate whether the problem is matplotlib or not.  I suspect your difficulties are with matplotlib rather than networkx.try something like: `matplotlib.pyplot.plot([1, 2, 3], [4, 5, 4])` inside the same environment that you are using to try to draw the graph. You might need `import matplotlib.pyplot` if those imports aren't somewhere else. And to see the plot you might need `matplotlib.pyplot.show()`.

**Comment by forestbat** [comment]
Yes，it's matplotlib's problem. I'm sorry to disturb you.
