### ISSUE TITLE
Bug: `is_minimal_d_separator` may return True even for a non d-separating set

### ISSUE THREAD

**Issue by ilya-causalens** [networkx/networkx#6216]
When experimenting with `networkx` 3.0.rc1, specifically with the d-separation algorithms, I noticed a bug where a set would be non d-separating, however would still return `True` for `is_minimal_d_separator`. Interestingly, it returns `False` for `d_separated`.

### Current Behavior
```
import networkx
from networkx.algorithms.d_separation import is_minimal_d_separator, d_separated

if __name__ == '__main__':
    g = networkx.DiGraph()

    g.add_edges_from([('A', 'B'), ('A', 'E'), ('B', 'C'), ('B', 'D'), ('D', 'C'), ('D', 'F'), ('E', 'D'), ('E', 'F')])

    assert not d_separated(g, {'C'}, {'F'}, {'D'})

    # the set is not d-separated, but returns True for minimally separated.
    assert is_minimal_d_separator(g, 'C', 'F', {'D'}) # < this should fail
    assert is_minimal_d_separator(g, 'C', 'F', {}) # < this should fail
```

### Expected Behavior
```
import networkx
from networkx.algorithms.d_separation import is_minimal_d_separator, d_separated

if __name__ == '__main__':
    g = networkx.DiGraph()

    g.add_edges_from([('A', 'B'), ('A', 'E'), ('B', 'C'), ('B', 'D'), ('D', 'C'), ('D', 'F'), ('E', 'D'), ('E', 'F')])

    assert not d_separated(g, {'C'}, {'F'}, {'D'})
    assert not  is_minimal_d_separator(g, 'C', 'F', {'D'}) # < this should pass
    assert not is_minimal_d_separator(g, 'C', 'F', {}) # < this should pass
```

### Steps to Reproduce

```
import networkx
from networkx.algorithms.d_separation import is_minimal_d_separator, d_separated

if __name__ == '__main__':
    g = networkx.DiGraph()

    g.add_edges_from([('A', 'B'), ('A', 'E'), ('B', 'C'), ('B', 'D'), ('D', 'C'), ('D', 'F'), ('E', 'D'), ('E', 'F')])

    assert not d_separated(g, {'C'}, {'F'}, {'D'})

    # the set is not d-separated, but returns True for minimally separated.
    assert is_minimal_d_separator(g, 'C', 'F', {'D'})
    assert is_minimal_d_separator(g, 'C', 'F', {})
```

### Environment

Python version: 3.8.12
NetworkX version: 3.0rc1

**Comment by rossbar** [comment]
I can confirm that this issue is present on `main`. Here's my reproducer (with visualization):

```python
>>> G = nx.DiGraph(
...     [
...         ("A", "B"),
...         ("A", "E"),
...         ("B", "C"),
...         ("B", "D"),
...         ("D", "C"),
...         ("D", "F"),
...         ("E", "D"),
...         ("E", "F"),
...     ]
... )
# Draw graph reflecting DAG structure
>>> for i, gen in enumerate(nx.topological_generations(G)):
...     for n in gen:
...         G.nodes[n]["layer"] = i
>>> pos = nx.multipartite_layout(G, subset_key="layer")
>>> nx.draw(G, pos, with_labels=True)
```
![dsep](https://user-images.githubusercontent.com/1268991/201769426-ff1a098a-ef1b-495e-8184-6c1892ac8e00.png)

It's clear that node "F" is unreachable from "C" regardless of "D", so {"D"} should is not a d-separating set:

```python
>>> nx.d_separated(G, {"C"}, {"F"}, {"D"})  # as expected
False
```

Perhaps `nx.is_minimal_d_separator` assumes that `z` is a valid d-separating set? If so, then this is likely fixed by adding a check that enforces this assumption. Otherwise there's likely a deeper bug in the `nx.is_minimal_d_separator` implementation.

**Comment by dschult** [comment]
@adam2392 Can you verify if the assumption is that input set `z` is a valid separating set?

**Comment by ilya-causalens** [comment]
@adam2392  Ah, that makes sense. I am not sure if the flag is required since it's quite easy to also do the `d_separated` check yourself. But the doc string should just clearly state that it is not checked. Of course, this is just my opinion and up to you/admins here.

Thanks for your answer and indeed for adding this capability to `networkx`!

**Comment by adam2392** [comment]
@ilya-causalens if you're up for the PR, I can help review. Otw I can possibly do it this weekend.

**Comment by ilya-causalens** [comment]
@adam2392 Sounds good. I will get on that. Also likely this weekend. Will add you as a reviewer :)

**Comment by tamandeeps** [comment]
Hi everyone. 
Is there anyone working on this issue, or I can start working on this issue? Btw I am new here and would love to be part of this community.

**Comment by adam2392** [comment]
@tamandeeps I think @ilya-causalens already started a PR? If not, and they want, you can start one and address the comments raised here?

**Comment by ilya-causalens** [comment]
@tamandeeps - feel free to start a PR. I was planning on it but never got around to starting it.

**Comment by tamandeeps** [comment]
sure, I will get on it.

**Comment by adam2392** [comment]
Hi @tamandeeps was there any progress on this?

**Comment by tamandeeps** [comment]
Yes, I made a PR for the same. 
Apologies for the delay. I was thinking of various approaches to fix this issue and understanding how it is working. I basically checked for d-separation.

**Comment by rossbar** [comment]
> I agree that strong statements in the doc_string are preferred over an extra keyword argument.

This would be my preference too. In this case though I don't think updating the docstring is enough. Given the function name I think it's reasonable for users to expect that the function would check that `z` is both valid and minimal. IMO the best approach is to explicitly check that the input is indeed a valid d-separating set. Even though this makes things more computationally expensive, it's the most straightforward way to get clear, correct results without complicating the API. In the long run, it'd be great to refactor the function so that it is capable of checking that a given input is both a *valid* and *minimal* d-separating set all in one go to avoid the duplication.
