### ISSUE TITLE
traveling_salesman_problem fails when including edges with weight 0

### ISSUE THREAD

**Issue by WouterMieras** [networkx/networkx#6389]
The result of solving the traveling salesman problem should be a route that visits each node exactly once. When including edges of weight 0 it seems that applying the various TSP algorithms in networkx can give a route that visits some nodes more than once. Using edges with weight 0 is a valid use-case: for example to model routes with a fixed start node and end node or when it is not desired or necessary to return to the start node at the end of the route.

### Current Behavior
When adding edges with weight 0 to a Graph `nx.approximation.traveling_salesman_problem()` (and other TSP algorithms in networkx!) can give a route in which nodes are visited more than once.

### Expected Behavior
Appying  `nx.approximation.traveling_salesman_problem()` on any Graph should output a route in which each node is visited exactly once. 

### Steps to Reproduce

```
import networkx as nx

graph = nx.Graph()

# simple graph with 3 nodes
graph.add_edge(1,2,weight=1.0)
graph.add_edge(2,3,weight=1.0)
graph.add_edge(1,3,weight=1.0)

# add dummy node 4 which has distance 0 to all other nodes
graph.add_edge(4,1,weight=0.0)
graph.add_edge(4,2,weight=0.0)
graph.add_edge(4,3,weight=0.0)

# result:  [1, 4, 3, 4, 2, 4, 1]
# this is unexpected, node 4 should be visited only once.
result = nx.approximation.traveling_salesman_problem(graph, nodes=[1,2,3,4], cycle=True)
```
### Environment

Python version: 3.10.4
NetworkX version: 2.8.8 (also tested with 3.0)

### Additional context
As a workaround I've used the `python_tsp` library which deals with 0-edges correctly

**Comment by dschult** [comment]
The traveling salesman problem **on a network** cannot be guaranteed to only visit each node once.  Consider the path on 3 nodes (0, 1, 2). The route starting at node 0 would be (0, 1, 2, 1, 0).  One way to guarantee that each node is only visited once is to use a complete graph. But that's not really the TSP on a network.  That's the full TSP. And I don't think that's what you are talking about. 

If you have edges with weight 0 and that makes it cheaper to go through a node twice (because the route is better), then I think you **should** expect to have a node repeated on the tour.  Consider the cycle on node (0,1,2) with weight zero on edges (1, 2) and (2, 0).  Then the best route is (0, 2, 1, 2, 0) and not (0, 1, 2, 0).  So that is another case where you don't expect each node to appear once.

**Comment by WouterMieras** [comment]
> The traveling salesman problem **on a network** cannot be guaranteed to only visit each node once. Consider the path on 3 nodes (0, 1, 2). The route starting at node 0 would be (0, 1, 2, 1, 0). One way to guarantee that each node is only visited once is to use a complete graph. But that's not really the TSP on a network. That's the full TSP. And I don't think that's what you are talking about.
> 
> If you have edges with weight 0 and that makes it cheaper to go through a node twice (because the route is better), then I think you **should** expect to have a node repeated on the tour. Consider the cycle on node (0,1,2) with weight zero on edges (1, 2) and (2, 0). Then the best route is (0, 2, 1, 2, 0) and not (0, 1, 2, 0). So that is another case where you don't expect each node to appear once.

Thank you for your quick reply! I **am** considering the full TSP in a complete graph where I need to find the most efficient route that visits all nodes exactly once. Considering your answer, it seems that the networkx implementation (or at least the default algorithm, cristofides) deals with a variant of the problem in which I cannot model my specific use-case.

**Comment by mjschwenne** [comment]
Two points to add to the conversation:

1. Christofides algorithm (which is the default choice for an undirected graph) is an approximation algorithm for the *metric* TSP. This means that the edge between two nodes must be at least as short as any other path between those nodes in the graph. Since passing through the fourth node in your example can find paths between all nodes with a total length of zero, the original graph is not metric and directly using Christofides is not the right choice.

2. The `traveling_salesman_problem` function will replace edge weights with the shortest distance between those two nodes so that the direct link between the nodes is always the shortest path, even if the input graph is complete (if the input is not complete, this process will also complete it). This will implicitly also ensure that the graph is metric. After it has been passed through the method which it was given, it will recover the path in the original graph by undoing the shortcutting, so if the edge between nodes is not the shortest for all pairs of vertices it is possible to get repeated nodes in the output solution.

So for your example, the `traveling_salesman_problem` function converted the graph to only have zero edge weights and passed it to `christofides` which probably reports a valid TSP tour for a complete and metric input. Perhaps it was `[1, 3, 2, 4, 1]`, but there are several other valid outputs which are possible. On the way out, the original paths are recovered and the `1 -> 3` edge traversed by the algorithm with weight zero after the shortcutting becomes `1 -> 4 -> 3` which we see in the output.

**Comment by Qudirah** [comment]
@dschult what do you think? this should be closed?
