### ISSUE TITLE
weight default argument inconsistencies on community detection algorithms

### ISSUE THREAD

**Issue by JAugusto97** [networkx/networkx#6425]
Hey,

I was running multiple community detection algorithms, and since I started with louvain and noticed the weight parameter defaulted to "weight", I didn't bother setting up this parameter on other algorithms, but after a while I noticed they have different default values for this argument. They are:

defaults to weight=None:
* greedy_modularity_communities
* naive_greedy_modularity_communities
* lukes_partitioning
* asyn_lpa_communities

defaults to weight="weight":
* louvain_communities
* louvain_partitions
* kernighan_lin_bisection
* modularity

Should they all default to None, to "weight" or is this intentional?

I can follow up with a PR if its suitable.
Thanks!

**Comment by dschult** [comment]
The default values are chosen intentionally -- though I can believe that some are based on historical defaults rather than some sort of "ideal" way to choose the weight argument. I haven't looked specifically at these functions to see the histories. But if a method can use edge weight but often or famously doesn't, then the default `weight=None` makes sense with detection of "None" meaning make every edge have weight 1. If the function always or by design uses an edge weight, then `weight="weight"` is a good default. And  then occasionally, a function may have been implemented without edge weights, and then the edge weight keyword argument in implemented later. For backward compatibility, it makes sense to leave the weight parameter defaulting to all edges having weight 1 (that is, `weight=None`).  

From a user perspective, if you are running your graph through many different functions, I would recommend that you not use default values for `weight`.  It makes your code more clear and avoids any confusion between functions.
