### ISSUE TITLE
Minimal d-separator function does not handle cases where no d-separating set exists

### ISSUE THREAD

**Issue by jaron-lee** [networkx/networkx#6430]
The minimal d-separator function does not return a special value when no valid d-separating set exists.

### Current Behavior

Currently the code returns:
```
>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_edge("A", "B")
>>> nx.minimal_d_separator(G, "A", "B")
set()
```
but this implies that A is marginally independent of B in G, which is false.

Compare with 
```
>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_edge("A", "B")
>>> G.add_edge("C", "B")
>>> nx.minimal_d_separator(G, "A", "C")
set()
```

and this empty set correctly implies that A is marginally independent of C.

### Expected Behavior
The function should return None, raise an error, or otherwise indicate that there is no valid d-separating set for A and B in the above graph, in order to distinguish from cases where the empty set is indeed a valid d-separating set.

### Steps to Reproduce
See above.

### Environment

Python version: 3.10.9
NetworkX version: 3.0

### Additional context

Related to discussions in #6247

**Comment by adam2392** [comment]
@dschult I can also handle this by adding a return `None` in this edge-case, unless @jaron-lee wants to take the PR?

**Comment by jaron-lee** [comment]
That seems relatively straightforward, I'm happy to take a stab over the weekend

**Comment by dschult** [comment]
I agree that returning `None` should indicate that there is no minimal separator. And returning an empty set means that the empty set is a d_separator.  

This changes (corrects) the current behavior, so a note should be added to the API changes section of `doc/release/release_dev.rst`.  I don't think it should need a deprecation, since it is correcting a faulty previous behavior. But I'd like @rossbar to verify that I'm not missing something.
