### ISSUE TITLE
Website Footer needs to align at center

### ISSUE THREAD

**Issue by SoumyadeepOSD** [networkx/networkx#6436]
## You can see it in picture

![image](https://user-images.githubusercontent.com/115442240/219105396-749ca027-785d-412c-aaf3-28605bb75ad2.png)

**Comment by rossbar** [comment]
I believe the footer is aligned with the header element, and any offset likely has to do with the logo placement rather than page layout.

Either way, the docs use the [pydata-sphinx-theme](https://github.com/pydata/pydata-sphinx-theme) which is where these things are set. I'd suggest checking out the documentation there to see if there's anything to be done about this - I don't think we'd want to add project-specific custom templating.

**Comment by Qudirah** [comment]
@rossbar this issue should be closed?

**Comment by SoumyadeepOSD** [comment]
@rossbar  I'm not getting figure out the solution regarding this issue. If you want to contribute you can do so.
