### ISSUE TITLE
Purpose of `create_using` for generators that don't support other graph types

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#6452]
This is just something I noticed while looking at the `dorogovtsev_goltsev_mendes` graph generator. The function has a `create_using` arg, but doesn't actually support any of the other non-Graph builtin graph classes:

https://github.com/networkx/networkx/blob/0b0a5fc5c512c2cbacd374860e47742e48a8dcfe/networkx/generators/classic.py#L410-L414

At first glance, this seems like a strange pattern: why provide the option to provide a `create_using` arg if it just results in an exception for the built-in, non-"simple" graph types? After thinking about this a bit though, the most likely motivating use-case is for user-defined subclasses of `nx.Graph`, e.g. `ThinGraph` (see the `nx.Graph` docstring section on subclassing).

I just wanted to raise this as a discussion point as the pattern may apply to other generators. Is this something that graph generators should support generally? This also ties into the wider discussion in NXEP3.

**Comment by mohamedrezk122** [comment]
You have raised a good point. I went through the code, and yes implementing these exceptions is for custom-build graphs which user can pass through create_using argument as a graph constructor. This behavior is also present in some other graph generator functions which might not support all sort of graph classes ( like digraph, multigrpah,  or generally non-simple graph ).

**Comment by dschult** [comment]
Yes -- the reason `create_using` is a keyword even though the function only works with undirected graph that aren't multigraph is so that a user could build the graph using their custom graph subclass.  I am almost certain there are other graph generator functions that could use this reasoning and don't -- i.e. they don't have a `create_using` keyword input. 

The ideas from NXEP 3 might make this no longer relevant (use the edges_and_nodes version of the builder and pass that to your subclass), but for now `create_using` is the best way to plug your graph subclass into the graph generators tools.

I also notice that this function is old enough not to use `not_implement_for` to restrict which graph type is allowed. :)

**Comment by rossbar** [comment]
My question was sufficiently answered so I'm going to close this. As noted this behavior is potentially relevant other generators which may benefit from adopting a similar pattern, but IMO there's no need to keep a tracking issue about it - I'd vote to "fix" things on a case-by-case basis as they come up!
