### ISSUE TITLE
Unexpected behaviour of .edges

### ISSUE THREAD

**Issue by Hanspagh** [networkx/networkx#6509]
When using a string to look up edges the string gets interpreted as an array which results in the edges call returning edges with the id of any of the chars of the string. If the string is surrounded by a list it works as expected. This behavior was a little surprising to me, but if it is expected feel free to ignore this.

### Current Behavior
``` python
import networkx as nx
g = nx.DiGraph()
g.add_edge("b", "c")
g.edges("ab")
OutEdgeDataView([('b', 'c')])
g.edges(["ab"])
OutEdgeDataView([])
```

### Expected Behavior

``` python
import networkx as nx
g = nx.DiGraph()
g.add_edge("b", "c")
g.edges("ab")
OutEdgeDataView([])
```

### Environment
Python version: 3.9.13
NetworkX version: '3.0.0'

**Comment by navyagarwal** [comment]
@Hanspagh Hey, you can check out a related discussion over [here](https://github.com/networkx/networkx/issues/4781)!

@dschult I think we should include some clarifying examples in the [documentation here](https://networkx.org/documentation/stable/reference/glossary.html#term-nbunch) for the time being, irrespective of whether we plan to change the current behavior or not, so that there are no surprises for users!

**Comment by Hanspagh** [comment]
Thanks for the link, not sure how I missed that discussion.

**Comment by dschult** [comment]
Yes -- a string is a container. And containers can be nodes, or pairs of nodes (edges), or even paths in some contexts.

And yes @navyagarwal including some clarifying examples in the documentation would be good! :)

**Comment by navyagarwal** [comment]
> And yes @navyagarwal including some clarifying examples in the documentation would be good! :)

I'll get to it!
