### ISSUE TITLE
Memory issue with read_graph6

### ISSUE THREAD

**Issue by alabarre** [networkx/networkx#6510]
I'm having memory issues when loading some moderately large graphs stored in the graph6 format (they were produced by `networkx` by the way, and neither generating them nor writing them to file using `write_graph6` raised any issue).
 
### Current Behavior

When loading the file using `read_graph6`, all memory is quickly used up and the system will become unresponsive if I fail to kill `python`.

### Expected Behavior

The file should be read and loaded into an `nx.Graph` object without any issue.

### Steps to Reproduce

Decompress [the attached file](https://github.com/networkx/networkx/files/10989656/problematic-instance-for-read_graph6.g6.zip) (warning: decompressed file size is about 130M), open `top` in another terminal to "see" the problem, and then simply try to initialise the graph:

    >>> import networkx as nx
    >>> graph = nx.read_graph6("problematic-instance-for-read_graph6.g6")
    # be ready to kill the interpreter

### Environment

Python version: 3.9.2
NetworkX version: 2.5
OS: Debian 11.6

### Additional context

The graph contains "only" 40.320 nodes and 564.480 edges, and `nauty-showg` has no problem displaying its contents in under a second. Smaller graphs of the same family yield no issue, but they're an order of magnitude smaller (the largest similar graph that poses no problem has 5.040 nodes and 52.920 edges).

If you have `nauty-showg`, you can load the graph without any issue as follows:

    >>> import subprocess
    >>> import networkx as nx
    >>> G = nx.Graph()
    >>> output = subprocess.check_output(("nauty-showg", "-l0", "problematic-instance-for-read_graph6.g6"))
    >>> for row in output.decode().split('\n')[2:]:
    ...    line = row.strip()[:-1].split()
    ...    G.add_edges_from((int(line[0]), int(x)) for x in line[2:])

**Comment by rossbar** [comment]
Downloading unknown zip files from the internet is generally not a good idea :upside_down_face: , so here's a reproducer to generate a graph with the given number of nodes and roughly the same number of edges:

```python
>>> import networkx as nx
>>> nnodes, nedges = 4320, 564480
>>> p = 2 * nedges / (nnodes**2 - nnodes)
>>> G = nx.erdos_renyi_graph(nnodes, p, seed=0xdeadc0de)  # seed for reproducibility
>>> print(G)
Graph with 40320 nodes and 564980 edges
```

You can then use this graph to test round-tripping with read/write graph6:

```python
>>> nx.write_graph6(G, "/tmp/example.g6")
>>> H = nx.read_graph6("/tmp/example.g6")  # failure here
```

Having looked at the `read_graph6` code, the problem lies here:

https://github.com/networkx/networkx/blob/1034b689cadfc8a854745043783ba53a73cbdf36/networkx/readwrite/graph6.py#L124

The first term in the `zip` constructs a list with `nnodes**2 / 2` terms essentially corresponding to the upper-triangle of the adjacency matrix. Each term is a tuple representing the edge, so a quick back-of-the-envelope calculation gives the expected number of GB required to instantiate this list:

```python
# Use sys.getsizeof as a minimum estimate for the size of a 2-tuple of integers
>>> (nnodes**2 / 2) * sys.getsizeof((0, 1)) / 1e9
45.5196672
```

Fortunately - we can eliminate this memory footprint by using a generator instead - see #6519.

I think there are many other opportunities to improve the graph6 code, but #6519 should at least fix the memory issue reported here. Thanks for reporting @alabarre !

**Comment by alabarre** [comment]
Thanks for the fix, we're lucky the solution was that simple.
