### ISSUE TITLE
Similar functions in shortest_paths produce different types of output

### ISSUE THREAD

**Issue by navyagarwal** [networkx/networkx#6527]
The single_source_shortest_path_length method returns a dictionary while the single_target_shortest_path_length returns a generator.  This was first discussed [here](https://github.com/networkx/networkx/discussions/5511).

I further looked into the output types of all related functions in shortest_paths and I believe it would make sense to change the output type of all length-related methods to dictionary for the sake of consistency.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/82928853/226372801-5a4edf02-4dbe-4294-bcfc-93b9ab8ed74a.png">

Fixing this would only require minor code edits and I presume some changes in the test files as well, it'd be great if I can get someone else's opinion on this as well!

**Comment by dschult** [comment]
I vaguely recall a discussion of this long long ago where we decided that the `all_pairs_...` versions should return an iterator that could easily be made into a dict. That was because the dicts that are created can be huge, especially when returning the paths. And for memory many people would want to process them one at a time rather than store a large data structure holding all that at once.

My quick peek suggests that the `all_pairs_shortest_path` returns an iterator no matter what the docs say (hmmm... seems the docs are wrong.

I am disappointed that the `single_source_shortest_path_length` returns a dict. That should be an iterator as well. If someone needs a dict they can easily make it one by wrapping it in a `dict` call. But maybe I should look at the "blame history" to figure out why it is the way it is. 

I think the `shortest_path` and `shortest_path_length` are meant to return the full structure -- because those are for ease of use. And sometimes they are returning a single path and other times a whole collection of paths. So the return value can be int or list of dict if I understand correctly.

I would think that all the rest could/should return iterators that can be made into dicts easily.  But I better do a "blame" search before this gets merged... :)   There is also backward-compatibility to take into account, but this PR is more about what it should be -- we can worry about backward compatibility later. :)

**Comment by navyagarwal** [comment]
`all_pairs_shortest_path` does return an iterator, I will correct the return type in the docs in PR #6528 

As for the other methods, considering the memory savings  and how easily the iterator can be wrapped in a dictionary when needed, wouldn't it be best if we could return an iterator for all methods instead of a dictionary? Because even for methods like `single_source_...` or `single_target_...` whose output is smaller than `all_pairs_...`, the output can still be significantly large if the graph is big enough.

> I think the shortest_path and shortest_path_length are meant to return different things depending on the inputs. Those are for ease of use. And sometimes they are returning a single path and other times a whole collection of paths. So the return value can be int or list or iterator if I understand correctly.

Yes, when source and target are both specified, returning an int/list makes sense. When either one or both are not specified, then an iterator/dictionary needs to be returned.

**Comment by dschult** [comment]
Upon reading this thread again today, I notice that making the `single_source_...` functions return iterators might make it more difficult to create the `all_pairs_...` outputs because each inner function would need to get wrapped in a `dict`. Otherwise we'd have an iterator of `(node, iterator)` pairs. So should the `all_pairs...` functions `yield (n, dict(iterator))` or `yield (n, iterator)`?  

It is certainly most important for the `all_pairs...` to iterate -- the output is quadratic in number of nodes otherwise. The choice for `single_...` is more subtle than I realized in my comments above. It still might be good to have them iterate. But can we make it easy?

And certainly the `single_source...` and `single_target...` functions should do the same thing.

**Comment by navyagarwal** [comment]
I think `all_pairs_...` should yield `(n, dict(iterator))` instead of `(n, iterator)`.

Once we have modified `single_source_shortest_path` to return iterators, wouldn't we just have to modify the return statement of `all_pairs_shortest_path` as follows - `yield (n, dict(single_source_shortest_path(G, n, cutoff=cutoff)))` ?

I was also wondering if we could do a performance analysis sort of something, to compare how the three methods - 

1. `all_pairs_shortest_...`
2. `single_source_shortest_...`
3. `single_target_shortest_...`

would be affected if the `single_...` methods return a dictionary vis-a-vis yield an iterator. This would allow us to make a more mathematically-validated decision.

**Comment by dschult** [comment]
Yes -- you are correct that we can have `all_pairs...` return (n, dict(iterator))`  I think that is the way to go if we turn `single_...` into returning an iterator.

And: Yes, a performance analysis would be helpful. Before we worry about whether it should be an iterator or a dict, we should know the impact of each option. But we probably don't need to do a memory-size performance test -- we can figure out the size of a dict with would be.  As for CPU time, I suspect that the time difference is a small percentage of the time for computing `single_...` with a large graph (assuming the memory doesn't get full -- because then it will slow down considerably).

I'm guessing that long ago we figured out that the dict returned by `single_..._length` uses O(n) memory for n nodes. That's not too bad. So that could be a dict. The `all_pairs_...length` uses O(n^2) memory. So that could return an iterator.  But then `single_..._path` uses O(n^2) in general, but smaller amounts in many cases.  It's not clear whether, from a memory perspective, we should make a dict for paths or not.  But the `all_pairs_..._path` functions use O(n^3) memory, so I think we should definitely return an iterator.  (This is all assuming that CPU time diff is negligible.) 

And of course we need to keep backward compatibility in mind too.  We don't want to switch what we return and make a bunch of people have to change their code just so they keep up with the latest version. There should be some payoff before we make a change.  I would argue that making `single_target...` match the return type of `single_source...` is a desirable API choice that should be done.  We would want to "deprecate" the current behavior for a while before actuating the change (at least I think that's how this is supposed to be done).   :)

So...   what change do we need to make to have a consistent API? And are there any outputs that really should be switched?

**Comment by navyagarwal** [comment]
> We don't want to switch what we return and make a bunch of people have to change their code just so they keep up with the latest version.

Ah, I did not think about this at all.

And yes, changing the return type of `single_target_...` to dictionary seems much better now.

We just need to switch the output of `single_target_shortest_path_length` to dictionary. Then the return types of all `single_source_` and `single_target_` methods would be consistent.

As for `all_pairs_...`, the methods return iterators and are already consistent.

What about `shortest_path_length` method when neither source nor target is specified? It currently yields an iterator, very similar to `all_pairs_...`, and considering the same reasoning as for `all_pairs_...`, maybe it should stay the same.

**Comment by dschult** [comment]
I think the `shortest_path_length` output should match the underlying code used. So, if the inputs to `shortest_path_length` indicate a source and target, we return a number. If a source, but no target, or a target but no source, we return whatever `single_...` returns. and if neither source nor target is provided, we return an iterator like `all_pairs...`.  I think this is what you suggested also.  And I think it is what the function currently does (and `shortest_path` should be similar.)

It looks like the only change, other than the doc fixes in #6528 that we need is to switch the output of `single_target_...` to match the output of `single_source...`. I just did a quick dive-in to see how the inconsistency occurred and when `single_source...` got changed from returning an iterator to a dict, we just didn't change `single_target...`.  It was an oversight (and it was mine :)

So, I think it could be considered as an API bug or at least an API wart that needs to be fixed.  I scanned through the `weighted.py` versions of these functions and they seem to be consistent with our decisions here. I didn't check every function with its doc_string though.

So, let's make a PR to switch the return value of `single_target...` to a dict instead of an iterator. This corrects an oversight in #2612 .  I'm not sure if it will require a deprecation due to backward incompatibility, because it fixes an API error. But I'll put that on the topic list for our next discussion of such questions.

**Comment by navyagarwal** [comment]
> if neither source nor target is provided, we return an iterator like `all_pairs...`. I think this is what you suggested also. And I think it is what the function currently does (and `shortest_path` should be similar.)

While `shortest_path_length` correctly returns an iterator for this case, `shortest_path` returns a dictionary instead of an iterator. This needs to be corrected.

> we need to switch the output of `single_target_...` to match the output of `single_source...`

I'll raise a PR for this.

> I scanned through the `weighted.py` versions of these functions and they seem to be consistent with our decisions here. I didn't check every function with its doc_string though.

I combed through all the functions of weighted.py and found 3 inconsistencies.

1. `all_pairs_dijkstra_path` -> returns iterator but docstring says dictionary
2. `all_pairs_bellman_ford_path` -> returns iterator but docstring says dictionary
3. `single_source_bellman_ford_path_length` -> returns dictionary but docstring says iterator

The output of these functions are actually consistent with our discussion over here, only the docstrings need some fixing.

**Comment by dschult** [comment]
If you mean changing `single_target_shortest_path_length` and `shortest_path` for the case of `source` and `target` being `None`, then this makes sense to me. I will create a PR to add deprecation notices for these changes. We will need to wait until v3.3 to release these changes.  But go ahead and get the PR ready so it will be easy to merge at that time.

**Comment by dschult** [comment]
And can you make the changes in the doc_strings be in a different PR, so we can get that one merged soon. :}
