### ISSUE TITLE
is_chordal crashes on empty graphs

### ISSUE THREAD

**Issue by alabarre** [networkx/networkx#6562]
### Current Behavior

Running `nx.is_chordal` on an empty graph raises `StopIteration`.

### Expected Behavior

The function should simply return `True`, since the definition simply requires that all cycles of length >= 4 contain a chord. Paths or trees are chordal since they have no cycles, and the function does not crash on these, nor on edgeless graphs.

### Steps to Reproduce

Just create an empty graph and run the function:

```python
>>> import networkx as nx
>>> graph = nx.Graph()
>>> nx.is_chordal(graph)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/networkx/algorithms/chordal.py", line 89, in is_chordal
    if len(_find_chordality_breaker(G)) == 0:
  File "/usr/lib/python3/dist-packages/networkx/algorithms/chordal.py", line 320, in _find_chordality_breaker
    s = arbitrary_element(G)
  File "/usr/lib/python3/dist-packages/networkx/utils/misc.py", line 233, in arbitrary_element
    return next(iter(iterable))
StopIteration
```
### Environment

Python version: 3.9.2
NetworkX version: 2.5

**Comment by navyagarwal** [comment]
When `is_chordal` is called, this statement is executed - 

```python
return len(_find_chordality_breaker(G)) == 0
```
Since no source `s` has been specified in `_find_chordality_breaker`, the following statements execute which further raises `StopIteration` because there are no nodes in G.

```python
if s is None:
        s = arbitrary_element(G)
```

I believe a specific condition needs to be added to `is_chordal` that returns True when `len(G.nodes) == 0`,  in fact this condition can be extended to `len(G.nodes) <= 3` because such a graph will always be chordal.

**Comment by PurviChaurasia** [comment]
Yes I think `len(G.nodes) <= 3` will be the correct condition to implement here as a graph with only one or two vertices is trivially chordal because it contains no cycle. A graph with three vertices can have at most three edges, and every cycle of length four or more would require at least four edges, so no such cycle can exist in a graph with three vertices.

**Comment by alabarre** [comment]
@PurviChaurasia your contributions indicate that you're more familiar with the code base than I am, so I'll gladly let you make the change. The suggested addition seems to be the only required change indeed.

Thanks!

**Comment by PurviChaurasia** [comment]
Thanks a lot :)

**Comment by PurviChaurasia** [comment]
I'll bit more context for the change in the docstring as well and add relevant tests.

**Comment by navyagarwal** [comment]
> I'll add bit more context for the change in the docstring as well and add relevant tests.

@PurviChaurasia Hey, I'm already working on it, was just adding test cases when I saw the comments 😅

**Comment by PurviChaurasia** [comment]
There is actually a wrong test case in `test_chordal.py` in line 63. It is mentioned:
`assert nx.is_chordal(nx.complete_graph(3))`
I think we'll have to comment that out as well.

**Comment by PurviChaurasia** [comment]
@navyagarwal if it's fine by you could we be co-authors on this PR? I was actually just about to submit the mine when I saw your message :)

**Comment by PurviChaurasia** [comment]
Yep meant that only!

**Comment by PurviChaurasia** [comment]
> > There is actually a wrong test case in `test_chordal.py` in line 63. It is mentioned: `assert nx.is_chordal(nx.complete_graph(3))` I think we'll have to comment that out as well.
> 
> No, but why? The test case looks alright to me

did you try running the test case after making the changes?

**Comment by PurviChaurasia** [comment]
Wait you're right, there was issue from my end.
