### ISSUE TITLE
cycle_basis algorithm is non-deterministic

### ISSUE THREAD

**Issue by EfremBraun** [networkx/networkx#6653]
As discussed on https://groups.google.com/g/networkx-discuss/c/bBMbsfInwAs?pli=1, the cycle_basis algorithm is non-deterministic.

**Comment by dschult** [comment]
Wow -- that discussion is from a loonngg time ago...  And it's actually not about determinism of the cycle_basis so much as why the algorithm wasn't choosing the optimal basis (as measured by shortest cycles).

Your issue is about preserving the order of the nodes so that the results don't depend on the set implementation ordering. Sets in python provide an arbitrary order that can differ based on their history. They are random, but the order can change in ways we can't easily control. So it's a reasonable goal to move away from sets if you want the same cycle_basis for the same inputs.

**Comment by EfremBraun** [comment]
It sure is old. But I just spent a day of work debugging before I was able to pinpoint the issue I was having down to it :)

And yes, for a given set of inputs, I was getting a different cycle_basis result when I was running the function multiple times. #6654 fixes that.

**Comment by EfremBraun** [comment]
> Wow -- that discussion is from a loonngg time ago... And it's actually not about determinism of the cycle_basis so much as why the algorithm wasn't choosing the optimal basis (as measured by shortest cycles).

Oh, it's the latter emails threads in that thread that discuss the indeterminism issue.

**Comment by rossbar** [comment]
I believe this was fixed by #6654 - please reopen if I'm mistaken!
