### ISSUE TITLE
all_simple_paths returns empty generator when the source is one of the possible targets

### ISSUE THREAD

**Issue by plammens** [networkx/networkx#6690]
### Current Behavior

Due to this conditional:

https://github.com/networkx/networkx/blob/5f2f88f6afc385892d91c20676d7dc6aa80d52bb/networkx/algorithms/simple_paths.py#L253-L254

whenever the `source` node appears as one of the possible targets, `all_simple_paths` always generates an empty list of paths.

For example:

```python
import networkx as nx

graph = nx.Graph([(1, 2), (1, 3)])
```
```python
>>> list(nx.all_simple_paths(graph, source=1, target={1, 2, 3}))
[]
```

### Expected Behavior

Apologies if I have misunderstood what the function is meant to do. Here's what I understand.

The function generates a list of simple paths from the given source to (any of the) given target(s). The docstring says:
> Pass an iterable of nodes as target to generate all paths ending in **any** of several nodes

So the fact that the source node is in the set of target nodes does not necessarily exclude _all_ paths, there could be some other target that works. For instance, in the example above the function missed out on two perfectly reasonable paths: `[1, 2]` and `[1, 3]`. As far as I understand they both satisfy the description above: they're simple paths from the source (1) to any of the targets (1, 2, 3).

So why does it return an empty generator? It should return the same as `list(nx.all_simple_paths(graph, source=1, target={2, 3}))`, that is, `[[1, 2], [1, 3]]`.

I understand that any path from source to itself wouldn't be simple, but again this doesn't automatically exclude paths to any of the other specified targets.

### Steps to Reproduce

```python
import networkx as nx

graph = nx.Graph([(1, 2), (1, 3)])
list(nx.all_simple_paths(graph, source=1, target={1, 2, 3}))
```

### Environment

Python version: 3.11
NetworkX version: 5f2f88f6afc385892d91c20676d7dc6aa80d52bb (3.1)

**Comment by dschult** [comment]
It looks like handling multiple targets was introduced in #3138 and at that time the if-structure was changed from
```python
if source == target:
    return []
```
to 
```python
if source in target:
    return []
```
The current post's corner case was not discussed at the time.  The previous behavior is different because with only one target, when that target equals the source, you don't get a simple path. It is a cycle. But with multiple targets, we now have the case in the OP -- what about paths to the other targets?

A workaround is to call the helper function directly:
```python
list(nx.algorithms.simple_paths._all_simple_paths_graph(G, source=1, targets={1, 2, 3}, cutoff=10))
```
or to call with `target=set(target) - {source}`.

But I think the fix is pretty easy. We can let the code do it's thing with the full set of targets.  But we could retain the spirit of the original code (avoiding extra computation in a corner case) by making the check:
```python
targets.discard(source)
if not targets:
    return _empty_generator()
```

Does this make sense?

**Comment by plammens** [comment]
> We can let the code do it's thing with the full set of targets. 

That was my first thought too.

> But we could retain the spirit of the original code (avoiding extra computation in a corner case) by making the check:
> 
> ```python
> targets.discard(source)
> if not targets:
>     return _empty_generator()
> ```
> 
> Does this make sense?

Seems like the best fix. I can't do it right now, but if in a while nobody has submitted a PR I'll do it.

**Comment by plammens** [comment]
Actually, isn't the trivial path `[source]` always a simple path from `source` to `source`? It seems kind of arbitrary to exclude this case too.

**Comment by dschult** [comment]
Indeed -- at least based on a definition that a path is a sequence of nodes.  But I guess that also means that a list of no nodes `[]` is also a path.  Isn't the empty sequence a sequence?  These corner cases are rarely described in a satisfying manner in textbooks/references.

But `[source]` is not a path if we go by [the definition e.g. wikipedia](https://en.wikipedia.org/wiki/Path_(graph_theory)), that `In graph theory, a path in a graph is a finite or infinite sequence of edges which joins a sequence of vertices.`

So, I think we should decide based on whether users will be more troubled by having to remove the single node paths (and zero length paths) when they don't want them vs by having to add the single node paths when they do want them.

Backward compatibility suggests we should not report these paths with less than 2 nodes in this PR.  But I am open to discussion about whether we should have another PR that deprecates the current behavior and adds single node (or less than 2 node) paths in a future version.  I'm -0.5 on adding them because I believe more users will want to remove them than users who will need to add them.

In the meantime, we should add a sentence or note to the doc_string that this function does not yield paths with less than 2 nodes, so those should be manually added by the user if desired.

**Comment by plammens** [comment]
I agree with your reasoning overall.

I would say that in all settings where you need to "do X for every Y in an arbitrary object Z", in this case "do X for every simple path in an arbitrary graph", it helps to be as general as possible with your definition of Y (simple path). Like including the empty set when computing the subsets of a set, or in this case returning the trivial path.

For example, a simple routine to find Hamiltonian paths could just use `all_simple_paths` with every possible source and specifying the entire set of vertices as possible targets, and then filter to only return paths that include all vertices. If the trivial path is excluded, this would not work for graphs of size one, and the routine would have to handle it manually.

In general I think that the more general the method is, the less corner cases the user will have to deal with manually themselves. So I am in favour of adding this change in the future.

By the way, I think a mathematician would say that the Wikipedia definition does definitely include the path `[source]`: it is a sequence (of length 1) of vertices that are joined together. In a similar spirit as 0! = 1 or that the number of permutations of the empty set is 1, that kind of thing. Of course, as you say, this reasoning also implies the empty sequence is a path. Maybe we could draw the line at non-empty paths, specifying this in the documentation?

**Comment by plammens** [comment]
By the way, `shortest_simple_paths` does currently include the singleton path, so consistency is another reason to  make the change to `all_simple_paths`:
```python
>>> G = nx.cycle_graph(5)
>>> list(nx.shortest_simple_paths(G, 0, 0))
[[0]]
```

**Comment by dschult** [comment]
You are sooo right...  And the `is_simple_path` also recognizes a single node path. So in our simple_path functions we have:
- `list(nx.shortest_simple_paths(G, 0, 0))` returns [[0]]
- `nx.is_simple_path(G, [0])` returns True
- `list(nx.all_simple_paths(G, 0, 0))` returns []
- `list(nx.all_simple_edge_paths(G, 0, 0))` returns []
- `nx.simple_cycles(G)` yields single node paths when a self-loop exists.  

So, the evidence for yielding single node paths is much stronger than I realized.

@MartinPJorge do you have an opinion about returning single node paths?

I think I am now +0.5 on reporting single node simple paths.

If we do change the `all_simple_paths` and `all_simple_edge_paths` to yield the single node paths, I think we would need to deprecate the current skipping of those edges. Does anyone think we should fix this without deprecation (e.g. because the current behavior is wrong)?

Also, looking briefly at the current code, this might require that we change how the `cutoff < 1` check is done. And maybe we could get rid of `empty_generator` now and make the functions be generators which use `yield from ...` instead of `return ...`.

**Comment by plammens** [comment]
>  Does anyone think we should fix this without deprecation (e.g. because the current behavior is wrong)?

Given the above discussion and the fact that other simple path functions include singletons, I would say this is a bug that needs to be fixed. But, on a pragmatical side, who knows if someone somewhere is relying on this behaviour...

**Comment by rossbar** [comment]
> If we do change the all_simple_paths and all_simple_edge_paths to yield the single node paths, I think we would need to deprecate the current skipping of those edges. Does anyone think we should fix this without deprecation (e.g. because the current behavior is wrong)?

Without having any real sense of how disruptive this would be in user code, my general feeling is that deprecating/warning would be overkill. IIUC, there is already an inconsistency in behavior between various functions, so user code would be getting different answers depending on which functions were used. Within this context, modifying behavior to improve consistency between functions feels more like a fix than an unexpected change!

**Comment by rossbar** [comment]
Two more cents from me: I think the best way to discuss/build consensus on this would be to have a PR that adds tests for the desired behavior across all relevant functions.

**Comment by boothby** [comment]
The debate over path length is as old as time itself -- is it the number of nodes or the number of edges?  Is a path a sequence of edges, or a sequence of nodes with edges between them?  Throughout our library, we have used the latter.   I think that it's important to remain consistent on this, and that strongly implies that we should treat `[0]` as a sequence of nodes starting at `0` and ending at `0` where all consecutive pairs of nodes are joined by an edge -- a path.

**Comment by boothby** [comment]
More supporting evidence: `len(nx.path_graph(1))` is `1`.

**Comment by dschult** [comment]
Great -- I think we have consensus on changing #6694 
1. report the single node paths (and show this in doc_string examples)
2. add a test that these functions report single node paths.
3. If you want (otherwise we will do it in another PR) add tests to the other functions mentioned above to ensure that they treat single node paths as paths. Those tests may already exist. But if they don't it'd be good to add them. 

@plammens Can you do 1) and 2) and let me know if you want us to do 3)?
Thanks!!

**Comment by dschult** [comment]
More evidence:
```python
G = nx.empty_graph(0)  # or any graph with 0 as a node
nx.has_path(G, 0)
```
outputs   `True`

**Comment by plammens** [comment]
> @plammens Can you do 1) and 2) and let me know if you want us to do 3)? Thanks!!

I'm now working on 1) and 2), I think I can also do 3) but I'll let you now if not.

**Comment by plammens** [comment]
By the way, it seems that for some reason this bug was explicitly tested for in multiple tests, for example:
https://github.com/networkx/networkx/blob/2d9fa51b2baddbfebbf971f366778331309a19d7/networkx/algorithms/tests/test_simple_paths.py#L213-L214

So at some point in time this was considered an intentional feature instead of a bug.

**Comment by plammens** [comment]
I'm now working on 3), adding tests to other functions.

> * `list(nx.all_simple_edge_paths(G, 0, 0))` returns []

Given the discussion above, if we consider `[0]` a simple path in the format of a list of nodes, then the equivalent format as a list of edges should be `[]`. Therefore this should return `[[]]`, correct?

**Comment by dschult** [comment]
> So at some point in time this was considered an intentional feature instead of a bug.

Yes, until this thread -- and sometimes during this thread -- it was considered as an intentional feature instead of a bug. We are definitely walking back what we had decided before in this case.

> if we consider [0] a simple path in the format of a list of nodes, then the equivalent format as a list of edges should be []. Therefore this should return [[]], correct?

I'm not sure what the right definition of an edge-path for the path `[0]` is.  If there are no edges, it is an edge path??  That is, is `[]` a path? If it is, then you're right that this line of code should return `[[]]`.  I can also see an argument for `[]` with a note in the doc_string that empty paths are not returned. Is there any source for a definition of an edge-path that indicates this is correct?

**Comment by plammens** [comment]
> I'm not sure what the right definition of an edge-path for the path `[0]` is. If there are no edges, it is an edge path?? That is, is `[]` a path? If it is, then you're right that this line of code should return `[[]]`. I can also see an argument for `[]` with a note in the doc_string that empty paths are not returned. Is there any source for a definition of an edge-path that indicates this is correct?

I was arguing more in terms of internal consistency within networkx. If the path that starts and ends at the same vertex `0` without tracing any edge is accepted as a simple path (as we have now established), then both the node-list representation `[0]` and the edge-list representation `[]` ought to be accepted, since after all they are not two different things, rather they're just two different _representations_ of the same thing. I would find it inconsistent if `nx.all_simple_paths` and `nx.all_simple_edge_paths` return some different (amount of) results, because I see them as just two different 'flavours' of the same thing.

In the same way that we consider that a graph with a single node as having a Hamiltionian path, I would also say it has an Eulerian path, i.e. the empty path.

In any case, none of the definitions I've seen explicitly require a path to be non-empty. For example, in [Wikipedia], they define a walk as a sequence of edges which joins a sequence of vertices, and it doesn't say that there must be more than one vertex, or equivalently that the sequence of edges must be non-empty. [ProofWiki](https://proofwiki.org/wiki/Definition:Walk_(Graph_Theory)) (which cites more standard sources to which I don't have access) defines walks as an alternating sequence of vertices and edges starting and ending with a vertex; the sequence consisting of a single node satisfies this definition and doesn't contain any edges. A path is then defined as a walk with no repeated edges or vertices.

Any other opinions on this?

**Comment by MartinPJorge** [comment]
I am ok with the node singleton result for `nx.all_simple_paths`. In the sense that there exists a way to arrive from 0 to 0, i.e. `[0]`.

However, the graph
```python3
G = nx.Graph()
G.add_node(0)
```
has no edge, and `nx.all_simple_edge_paths` should return `[]` for there is not any edge path.

If we return `[[]]`,  `len(nx.all_simple_edge_paths(G))` will yield `1` although there is no edge path.

---------
P.D.: sorry for the late reply @dschult and @plammens. And thanks a lot for the great effort! :D

**Comment by plammens** [comment]
> However, the graph
> 
> ```python
> G = nx.Graph()
> G.add_node(0)
> ```
> 
> has no edge, and `nx.all_simple_edge_paths` should return `[]` for there is not any edge path.
> 
> If we return `[[]]`, `len(nx.all_simple_edge_paths(G))` will yield `1` although there is no edge path.

I'm not convinced by this argument. I agree there is no edge, but I disagree that this implies that there is no edge path: the empty path without any edge from 0 to 0 is still a path. In the same way that we define the number of permutations of an empty set as 1: even though there are no objects to arrange, there is one way to arrange zero objects, because there is no choice, and 1 is the "combinatorial identity".

I'd also like to point out a (possibly) important nuance: in the empty graph with no nodes or no edges, then I would agree that there is no path, but not because there is no edge, but instead because there is no node from which to start or at which to end a path. (In fact, we wouldn't even be able to call ```nx.all_simple_edge_paths``` because we need to specify a source and a target.) And since there is no path, there is neither a node path nor an edge path.

In any case, I still think the strongest argument is that of consistency: I don't think it makes sense to accept the node list representation but exclude the edge list representation of a trivial path, or viceversa, because they're both representations of the same thing. 
As you say,
> there exists a way to arrive from 0 to 0

and that way can be represented as a sequence of nodes, `[0]`, or as a sequence of edges, `[]` (or in fact as an alternating sequence of nodes and edges, `[0]`). So I'd say: either we exclude both or we include both.

**Comment by plammens** [comment]
> Then, what about adding a note in the `nx.all_simple_edge_paths` docs?

Definitely! I forgot about updating the documentation, thanks for pointing that out. I added a note in https://github.com/networkx/networkx/pull/6694/commits/90dd5f97eb225430edfc59d4fb4286d0b1d5fa2c, let me know what you think.

**Comment by MartinPJorge** [comment]
> Definitely! I forgot about updating the documentation, thanks for pointing that out. I added a note in [90dd5f9](https://github.com/networkx/networkx/commit/90dd5f97eb225430edfc59d4fb4286d0b1d5fa2c), let me know what you think.

Looks perfect to me! Thank you. :)
