### ISSUE TITLE
all_simple_paths missing some simple paths

### ISSUE THREAD

**Issue by kenneth-lee-ch** [networkx/networkx#6709]
I ran the following code with the latest version of `networkx`. I find one of the functions `all_simple_paths` does not print out all simple paths. The following example illustrates my point.

### Current Behavior
When I run the following code
```
import networkx as nx

g = nx.MultiDiGraph()
g.add_edge(0,1)
g.add_edge(1,2)
g.add_edge(3, 0)
g.add_edge(3, 2)
paths = nx.all_simple_paths(g, 0, 2)
print(list(paths))
```
It gives me `[[0, 1, 2]]`

### Expected Behavior
I think it should output `[[0, 1, 2], [0, 3, 2]]`

### Steps to Reproduce
```
import networkx as nx

g = nx.MultiDiGraph()
g.add_edge(0,1)
g.add_edge(1,2)
g.add_edge(3, 0)
g.add_edge(3, 2)
paths = nx.all_simple_paths(g, 0, 2)
print(list(paths))
```

### Environment

Python version: 3.10.0
NetworkX version: networkx-3.1

**Comment by MridulS** [comment]
In the given example it's a multi directed graph. There is no way of going from 0 to 3. Adding an edge from 3 to 0 doesn't mean you can go from 0 to 3 in a directed graph.

**Comment by kenneth-lee-ch** [comment]
@MridulS  I don't follow. By definition, a path in a directed graph is a sequence of edges having the property that the ending vertex of each edge in the sequence is the same as the starting vertex of the next edge in the sequence. A simple path only means there is no repeated vertex in the sequence. What do you mean there is no way?

**Comment by MridulS** [comment]
> A simple path only means there is no repeated vertex in the sequence. 

Yes, but you can't take the path from 0 to 3 right?

<img width="642" alt="Screenshot 2023-05-24 at 11 36 34 PM" src="https://github.com/networkx/networkx/assets/5363860/43672f31-bde5-4732-9830-e00e6d0b3d57">

There is no way I can go from 0 to 3.

Now if you change your graph and add an edge `g.add_edge(0, 3)` then yes you would have a path from 0 ->3 -> 2.

Does this make sense or am I missing something? :)

**Comment by kenneth-lee-ch** [comment]
As far as I understand, that's not how a simple path is defined. What you pointed out is called a directed path from 0 to 2 e.g. `0->1->2`. A path from 0 to 2 can be a sequence of 0, 1, 2, 3, 0, 1, 2. But this is not a simple path because of the repeated vertices in the sequence.  A simple path from 0 to 2 can be 0, 1, 2 and also 0, 3, 2

**Comment by kenneth-lee-ch** [comment]
Here is a reference about simple paths: https://www.baeldung.com/cs/simple-paths-between-two-vertices

**Comment by MridulS** [comment]
Even the definition there doesn't really say anything about directionality in simple paths.

"For each two consecutive vertices (v_i, v_{i+1}), where (1 \leq i < k), there is an edge e = (v_i, v_{i+1}) that belongs to the set of edges E"

The edge (3, 0) doesn't belong in the edge set.

Is there a specific reference that explicitly state that this example should include 0->3->2 ?

**Comment by MridulS** [comment]
https://algs4.cs.princeton.edu/42digraph/ does state one definition of directed simple path. I can't really find anything on "simple path" for a directed graph, there is literature on directed simple path.

If you really want to ignore the directionality, you can just convert this graph to a MultiGraph and then run `all_simple_paths`.

**Comment by kenneth-lee-ch** [comment]
Sorry, I deleted the reference because I think it is actually missing one of the simple paths in the example it used.  To your question, that's exactly my point. `nx.all_simple_paths` currently outputs all **simple directed paths**, but not all **simple paths**.  We are not dealing mixed graphs here, but a DAG. Directionality doesn't matter for the edge set, so you cannot say the edge between 0 and 3 is not part of the edge set.

**Comment by kenneth-lee-ch** [comment]
The definition here about simple path can be applied to undirected graphs or directed graphs: https://www.baeldung.com/cs/simple-paths-between-two-vertices

**Comment by MridulS** [comment]
> nx.all_simple_paths currently outputs all simple directed paths, but not all simple paths.

Yes, and in my head there is no thing as simple path but for directed graph. It should just be **simple directed paths**, unless there is a specific resource in literature that defines simple path in a directed graph ignoring directionality.

Even in this definition https://www.baeldung.com/cs/simple-paths-between-two-vertices, the edge (0, 3) is **not** in the edge set (so it doesn't satisfy the third condition). For a directed edge the edge set is an ordered pair. `(3, 0) != (0, 3)`

**Comment by kenneth-lee-ch** [comment]
You can read here: https://en.wikipedia.org/wiki/Path_(graph_theory)#simple_path

**Comment by kenneth-lee-ch** [comment]
All I am saying is that the path doesn't have to be a directed path in order to be simple. Clearly, 0<-3->2 is a path from 0 to 2 and all vertices of this sequence are distinct. Therefore, it is a simple path.

**Comment by MridulS** [comment]
> You can read here: https://en.wikipedia.org/wiki/Path_(graph_theory)#simple_path

Yeah, and according to this there is no such thing as simple path for directed graph?

**Comment by kenneth-lee-ch** [comment]
I don't know how you get the idea that `according to this there is no such thing as simple path for directed graph`. Nowhere in the reference says there is no such thing. 

Anyways, I have already made my point. I am not here to argue. If you refuse to increase the clarity of the package, that is totally up to you. A simple path is not defined only for directed graphs. It is a general idea in graph theory. As long as you have a path that doesn't have repeated vertices, it is a **simple path**

**Comment by MridulS** [comment]
I'll wait for someone else to have a look at this too :)

Thanks for opening the issue!

**Comment by dschult** [comment]
A simple path is a list of nodes where each pair in the list corresponds to an edge. If the graph is an undirected graph then adding the edges (0, 3) allows a path that includes edges (0, 3) or (3, 0).  If the graph is a directed graph then the edge (0, 3) allows a path the node order (0, 3), but not (3, 0).  That is what it means for "an edge to be in the graph". In a directed graph, we pay attention to the direction when considering edges. In an undirected graph, we don't.  A DAG is a directed acyclic graph, so the paths never return to the same node (no cycles exist in the graph). 

A simple path is a path without repeated nodes. A simple path in a directed graph pays attention to the direction of the edges, while in an undirected graph the path doesn't not have to follow the direction of the edges.

> By definition, a path in a directed graph is a sequence of edges having the property that the ending vertex of each edge in the sequence is the same as the starting vertex of the next edge in the sequence. A simple path only means there is no repeated vertex in the sequence. What do you mean there is no way?

The term "ending vertex of each edge" and "starting vertex of each edge" shows how the directionality plays a role. For a directed graph the path [0, 3, 2] must have edges (0, 3) and (3, 2). Your graph doesn't have an edge with starting vertex 0 and ending vertex 3.   That's why [0, 3, 2] is not reported by the function `all_simple_paths`. 

> is 0<-3->2 a path from 0 to 2?
> If so, is it simple?

No, (0, 3, 2) is not a path from 0 to 2. Look at the definition (the wikipedia page has it). For (0, 3, 2) to be a path, the edges (0, 3) and (3,2) must exist in the graph, and they don't exist in this directed graph.  I the edge (0, 3) did exist in the graph, then the path **is simple** because (as the wikipedia page says) if the nodes in the path are distinct then the path is a simple path. (0, 1, 2) is a simple path in your graph. (0, 3, 2) is not a simple path because it is not a path in the graph.

Hope this helps clear it up.

**Comment by dschult** [comment]
The Graph Theory literature is quite established and clear about this -- and the Wikipedia page agrees with that literature -- as does our library. The edges for a path in an undirected graph are an unordered set of 2 nodes. While the edges in a directed graph are ordered pairs of nodes. A directed path is just a path in a directed graph.

The causal DAG literature is notable in its sloppy handling of graphs as being both directed and undirected. The term causal path refers to a path in the directed graph under consideration. While non-causal path considers the edges as undirected and finds a path in the obviously related undirected graph. Some people refer to the graphs in the causal literature as Mixed Edge Graphs, but that is really a different definition of a Graph where the edge set can contain both directed edges and non-directed edges.

Our function naming convention is not (usually) a set of commands like "find this". We try to describe what is being returned in as concise a way as possible and no more concise. The function `all_simple_paths` finds undirected paths if the graph is undirected and directed paths if the graph is directed. Adding the adjective "directed" would be incorrect. The function finds undirected paths when the edges are undirected. The output depends on your input. 

To expect an undirected path when providing a directed graph suggests that the literature you are working from is not being careful in their communication. And there is nothing wrong with that -- but you need to realize that when you reach out beyond that literature to the rest of the world.

**Comment by kenneth-lee-ch** [comment]
> the causal DAG literature is notable in its sloppy handling of graphs as being both directed and undirected.

I don't know how you can end up saying this. Just because there exists literature that goes against what you said doesn't mean they are sloppy. 

> the Wikipedia page agrees with that literature -- as does our library

I literally just quoted from Wikipedia and you can tell me the opposite...interesting.

> Adding the adjective "directed" would be incorrect

It won't be as you can have both `find_all_simple_undirected_path` and `find_all_simple_directed_path`. It's just a matter of design. 

> To expect an undirected path when providing a directed graph suggests that the literature you are working from is not being careful in their communication. And there is nothing wrong with that -- but you need to realize that when you reach out beyond that literature to the rest of the world.

It's interesting that you first say it is not being careful and then say there is nothing wrong with that. So, you are suggesting that there is nothing wrong with not being careful. First, you have no way to prove you are more **careful** than those who wrote that literature. Just because there exists literature that goes against what you define is called **not careful**?

I am going to quote directly from a graduate-level graph theory textbook (Graduate Texts in Mathematics by J.A Bondy and U.S.R. Murty) for you since you said 

> The Graph Theory literature is quite established and clear about this -- and the Wikipedia page agrees with that literature -- as does our library.


![Screenshot 2023-05-26 at 3 05 12 AM](https://github.com/networkx/networkx/assets/24616330/182d72ed-9162-49a4-8043-e747570c1fb8)

![Screenshot 2023-05-26 at 3 04 14 AM](https://github.com/networkx/networkx/assets/24616330/4a120786-ac6a-4233-906a-f27771d3251d)

Note that a **path** may not necessarily be **directed**.  Now you can say that perhaps this textbook is being sloppy or not careful.

**Comment by rossbar** [comment]
I'm going to close this - the original question has been sufficiently addressed and there are no action items. Thanks all for taking the time to discuss in such depth.

**Comment by dschult** [comment]
The quoted textbook is considering an undirected graph.  How do we know that?  Because it says that edges are "two-element subsets of V".  Those are undirected edges. Directed edges are ordered pairs of nodes.  Similarly for the wikipedia page. The undirected description uses {v1, v2} notation to denote sets, while the directed description uses (v1, v2) to denote the ordered pairs.  I think it is useful to look again at the wikipedia page. We both seem to suggest that it backs our claims -- and it very well might back both of our claims. :}  Perhaps we are agreeing in the end. But be careful -- the subtlety of using {} vs () makes a difference. That's the sense in which I use the word careful. In the causal inference literature, authors often switch between treating edges as ordered and treating them as sets. And that's the sense in which I mean that there is nothing wrong with not that approach -- sometimes ignoring the difference between two types of objects can lead to new ideas and new advances. It's best, of course, to be flexible and be able to think about edges as being the same and also turn around and think of edges as being different if they are directed vs not directed. In NetworkX we use Graph and MultiGraph when the edges are undirected and DiGraph and MultiDiGraph when the edges are directed. And most of the functions work with either -- applying the appropriate methods and returning the appropriate results depending on what type of graph is considered.

**Comment by kenneth-lee-ch** [comment]
It seems you are not satisfied based on the fact that you want to keep on going even if your colleague has already closed this thread. To this end, I take another screenshot of the same book under the chapter about directed graphs. The authors specifically give the difference between a **directed path** and a **path**. They define a directed path as an orientation of a path, what does that mean? That means paths in directed graphs are different than directed paths in directed graphs. 

<img width="1085" alt="Screenshot 2023-05-26 at 11 35 26 AM" src="https://github.com/networkx/networkx/assets/24616330/2938fb5d-fd55-4723-bbe9-7806a5936d97">

From the perspective of increasing the usability of the library, it's very interesting to see that you keep on juggling between the idea of being careful as a reason why you don't think there is a problem in your library and the idea of nothing being wrong when there is a community of people not agreeing with you the definitions of paths.

All I see is that you refuse to increase the clarity of the library even if there is evidence to suggest that could cause confusion and want to restrict its use. That's totally fine to me since it's your library and this thread of discussion has already shown me the quality of the library.
