### ISSUE TITLE
A typo in documentation

### ISSUE THREAD

**Issue by skyerguo** [networkx/networkx#6735]
### Environment

Python version:
NetworkX version:

### Additional context

In the page "https://networkx.org/documentation/networkx-2.1/reference/algorithms/generated/networkx.algorithms.structuralholes.effective_size.html?highlight=effective_size#networkx.algorithms.structuralholes.effective_size", it tells a name called "efficency"
.
However, in Bert theory, it is "efficiency". It is a typo, I recommend you to fix it.

**Comment by MridulS** [comment]
Thanks for opening this issue!

This has been fixed in https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.structuralholes.effective_size.html#networkx.algorithms.structuralholes.effective_size

networkx 2.1 is a pretty old version and I don't think it's worth going and fixing these typos (I'm sure there are a lot more) in all the old published documentation :)

**Comment by skyerguo** [comment]
Thanks， I will use the newest documentation. Thanks~
