### ISSUE TITLE
Docstring of `johnson` algorithm handling of weight incorrect

### ISSUE THREAD

**Issue by eriknw** [networkx/networkx#6749]
### Current Behavior

The documentation says:
```
If no such edge attribute exists, the weight of the edge is assumed to be one.
```
### Expected Behavior

The behavior to match the docstring or the docstring to match the behavior.

### Steps to Reproduce

```python
In [1]: import networkx as nx

In [2]: G = nx.Graph()

In [3]: G.add_edge(0, 1, weight=2)

In [4]: G.add_edge(0, 2)

In [5]: nx.johnson(G)
---------------------------------------------------------------------------
NetworkXError                             Traceback (most recent call last)
Cell In[5], line 1
----> 1 nx.johnson(G)

File ~/miniconda3/envs/gb8/lib/python3.11/site-packages/networkx/algorithms/shortest_paths/weighted.py:2469, in johnson(G, weight)
   2402 r"""Uses Johnson's Algorithm to compute shortest paths.
   2403
   2404 Johnson's Algorithm finds a shortest path between each pair of
   (...)
   2466
   2467 """
   2468 if not nx.is_weighted(G, weight=weight):
-> 2469     raise nx.NetworkXError("Graph is not weighted.")
   2471 dist = {v: 0 for v in G}
   2472 pred = {v: [] for v in G}

NetworkXError: Graph is not weighted.
```

### Environment

Python version: 3.11
NetworkX version: 3.1

### Additional context

It uses `nx.is_weighted`, which requires that _all_ edges have the attribute to be considered weighted.

**Comment by navyagarwal** [comment]
The parameters part of the docstring may have been copied from the rest of the functions (Dijkstra and Bellman-ford) in the file. These methods assume the weight of the edge to be 1 when not specified.

It makes sense to have similar behavior for the Johnson method as well. We'll only need to remove the `nx.is_weighted` condition and modify/remove the test cases for unweighted and single-node graphs.

No other changes will be required since the Johnson method uses `_bellman_ford` and `_dijkstra` methods that already handle the unweighted edges.

If this approach seems alright, I'll create a PR.

**Comment by dschult** [comment]
Yes -- that looks like a correct description of what has happened with the documentation of this function. And I agree that it seems straightforward to make it handle edges without an edge attribute.

It'd be nice to include tests of input graphs without edge attributes for some edges and show the function working and maybe even check that results match a case with weight specified as 1... ???
