### ISSUE TITLE
NetworkX fails with NumPy 2.0dev - NEP 51

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#6846]
The `main` branch currently [fails](https://github.com/networkx/networkx/actions/runs/5845735581/job/15850137542) with the numpy 2.0 nightly release as numpy has changed the (printing) behavior of scalars [NEP 51](https://numpy.org/neps/nep-0051-scalar-representation.html). Our doctests will fail as it's expecting an exact string match (?).

**Comment by dschult** [comment]
This looks like another one of those changes that mess up our doc_strings. When numpy changed their output format we had to handle those differently.  I don't recall if we only tested doc_strings with specific numpy versions, but I think it was something like that. And we changed all the doc_strings format in one big commit I think.

So, we should talk about how best to handle it.  My initial thought is that we drop the `--doctest-modules` on much of the testing matrix -- At first that can be for whenever numpy >= 2.0. But then we'll need to switch it at some point from dropping it for newest numpy to dropping it for the older numpy -- and we make that CI change when we make the doc_string change. 

I guess the idea is that the results of doc_string tests/examples are rarely dependent on version of numpy. So as long as we're testing it on one version of numpy, it is likely working on the others and we test the others using the test modules.

**Comment by rossbar** [comment]
> So, we should talk about how best to handle it

My initial thought was to investigate how many of the tests we could reformat so that the output didn't contain scalar repr's. From a quick glance it seems there may be a few that can be modified, but I don't think that will work in every case. Therefore investigating alternatives is worthwhile.

I think @dschult 's proposal is the most workable, even if it requires a bit of manual config/pinning in CI. Another option might be to use `np.printoptions` to set printing to "legacy" mode for the scalars, at least for the purposes of testing. I *think* this is doable, but we'll have to look into it more (if it is possible, it should probably be added to the NEP!)

The silver lining of these failures is that the new scalar repr identifies some places in the codebase where numpy scalars are returned implicitly. Kinda neat IMO :)
