### ISSUE TITLE
The adjacency matrix generated for a directed graph might be incorrect.

### ISSUE THREAD

**Issue by iebeid** [networkx/networkx#7021]
### Description

I was trying to create a directed graph with preset edges. After I created the graph, I tried to generate an adjacency matrix from the created directed graph. The generated adjacency just follows the order the edges provided. One of the entries of the adjacency generated using nx.adjacency_matrix() had a misplaced edge value.

### Current Behavior

When generating an adjacency matrix for a directed graph there seems to be a misplaced 1 especially for the last edge in the list of edges predefined.

### Expected Behavior

Correct adjacency matrix should be generated.

### Steps to Reproduce

GD1 = nx.DiGraph()
GD1.add_edges_from(
    [('A', 'B'), ('A', 'C'), ('D', 'B'), ('E', 'C'), ('E', 'F'),
     ('B', 'H'), ('B', 'G'), ('B', 'F'), ('C', 'G')])
GD1A = np.array(nx.adjacency_matrix(GD1).todense())
print(GD1)
print(GD1A)

Please work out the adjacency matrix on paper first and compare outputs.

### Environment

Python version: 3.9.1 (Anaconda)
NetworkX version: 3.1, Scipy 1.11.3

### Additional context

![error-networkx](https://github.com/networkx/networkx/assets/8671747/3ce837d2-8fa8-4746-9fa4-6b6f7053f335)

**Comment by dschult** [comment]
This is almost certainly due to the fact that you expect the rows and columns to be ordered in alphabetical order when they aren’t ordered that way. Since you did not supply the `nodelist` keyword argument, the order of the nodes in the rows is the same as the order of nodes reported by G.nodes.  That order may not be alphabetical.  In this case ‘H’ is added to the graph before ‘G’ so the order hasH before G. The resulting matrix is in fact correct with that ordering.

**Comment by iebeid** [comment]
Oh I see. Thanks for the clarification.
