### ISSUE TITLE
3.2 backends: maxflow backend kwargs vs flow_func kwargs

### ISSUE THREAD

**Issue by rhelmot** [networkx/networkx#7044]
There is an abstraction collision between the system for providing kwargs to a backend vs the system for providing kwargs to the provided flow_func. I have not tested this, but I suspect that this means that you can't both explicitly specify a backend with kwargs _and_ provide kwargs to the flow func. A potential solution could include passing flow_func kwargs not as actual kwargs, but as an explicit dictionary.

For context, I am preparing type stubs for networkx for typeshed, and this popped out as an issue while trying to describe the public interfaces.

**Comment by eriknw** [comment]
Yeah, this is indeed an abstraction collision, and providing kwargs to e.g. the flow func is chosen over providing backend kwargs. I'm impressed you spotted this!

This is apparent when looking at the generated signature (one branch adds `**backend_kwargs`, the other doesn't):
https://github.com/networkx/networkx/blob/1c5272054f71f9484347f7e4246ae3d5da367f7b/networkx/utils/backends.py#L370-L401

> A potential solution could include passing flow_func kwargs not as actual kwargs, but as an explicit dictionary.

Yeah, here are potential solutions that I see:
- Pass kwargs to flow_func as a dict argument (as you proposed).
- Pass a dict for the backend kwargs as e.g. `backend_kwargs={...}`, thereby making `backend_kwargs` another reserved argument.
- Don't support kwargs for flow_func and direct users to curry argument (such as with `functools.partial`) instead
- Provide a convenient way to get a function from a backend, such as `nx.pagerank.funcs["graphblas"]` or whatever

**Comment by dschult** [comment]
It looks like we could allow both backend and flow functions to use the values in the kwargs so long as they don't collide. Is this correct? So the backends just need to choose keyword names for their flow solvers that don't match the ones used by the 3 networkx flow solvers.  But maybe I am missing something.

**Comment by dschult** [comment]
After some discussion and further thought, here's an idea that seems promising: 
Use `functools.partial` on the solver functions instead of allowing kwargs to be passed in dynamically. We would need to make it easy for users to figure out how to do this. Perhaps an example or two in the relevant function doc_strings. 

I think this issue is somewhat separate in that it is more about getting the stubs to work correctly. So we could open a separate issue with the `functools.partial` idea. We could also let this issue be the marker for that work. 

As far as getting the type stubs working, I think they should indicate what the current configuration is. Yes -- it is possible to have a collision. Authors of backends implementing flow functions should be aware of these potential problems and name parameters to avoid the collision. The type stubs should be able to indicate this somehow even if there is a potential collision.  Other thoughts?

**Comment by eriknw** [comment]
I think type stubs today should only have `**kwargs` for these functions and not `**backend_kwargs` (which also matches the generated signatures). If networkx changes, then naturally type stubs should also change to match.

**Comment by dschult** [comment]
It sounds like we have addressed the OP question: how to make type stubs for the flow func interface? With the answer that it should have `**kwargs` for these functions and not `**backend_kwargs`. 

So, I'm going to close the issue, and we'll continue the surrounding conversations elsewhere. We can reopen if there is more to cover.
