### ISSUE TITLE
3.2.1 release

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#7067]
Closes #7064

I think we have about 5 actual bug fixes merged since the release. 
One affects being able to import networkx on some configurations.
If we're thinking of a patch release, which PRs should be included?

Here's my take. But others should push back and Jarrod should give the final word.
We have merged 16 PRs since the release:  
Only one should **not** be included in a patch release (the one dropping python 3.9).
All the rest can be included. OR we could just add the 5 that fix broken things.

Fix broken stuff:
#7034 - syntax error upon import
#7041 - is should be ==
#6825 - fix new from_numpy feature of no edge attr
#7042- add find_extendability to the docs (broken link)
#7030- release numbers stopped working with glob. go back to manual list

Safe to backport but not anything broken:
#7043  - favicon
#7048  - avoid docs warnings
#7053 - remove code from 6925 that is after `return` statement (not usable)
#7056 - doc typo
#7057 - don't allow negative sizes in complete_multipartitite_graph 
#7018 - harmless doc improvement
#7055 - fix small graph name attribute
#7062 - better error handling that shouldn't ever happen except to us.
#6999 - add tadpole
#7029 - update release process

Don't backport:
#7028 - drop support for Python v3.9

```

**Comment by MridulS** [comment]
+1 on including everything but the 3.9 support drop.

**Comment by jarrodmillman** [comment]
@dschult @MridulS Here is the 3.2 release branch:
https://github.com/networkx/networkx/tree/v3.2

I am waiting for the tests to pass. Everything applied cleanly except:
https://github.com/networkx/networkx/commit/c9f893476ba9905a98e6c03c9d33a3826a474416
Because we dropped support for 3.9 in #7028, we remove
```
    if sys.version_info < (3, 10):
        backends = (
            ep for ep in entry_points()["networkx.backends"] if ep.name == "nx-loopback"
        )
    else:
        backends = entry_points(name="nx-loopback", group="networkx.backends")
```
and replaced it with
```
backends = entry_points(name="nx-loopback", group="networkx.backends")
```

So I had to put  back the code.

**Comment by MridulS** [comment]
The tests have passed, I guess we can tag the last commit on https://github.com/networkx/networkx/tree/v3.2 as `networkx-3.2.1` and pypi publish action should take care of it right?

**Comment by dschult** [comment]
This looks good-- tests pass. and your solution seems like a good one.
:)
Thanks!!

**Comment by jarrodmillman** [comment]
Sorry, I was out. I just got back and will take care of the release now. It isn't just a tag. The process is documented here:
https://github.com/networkx/networkx/blob/main/doc/developer/release.rst

Tag the release is one of the steps, but there are others listed. And since this is a special case release I may need to update the release process notes.
