### ISSUE TITLE
Intermittent test failures for test_directed_edge_swap

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#7236]
It looks like CI is occasionally tripping up on the tests added in #6426 due to going over the maximum number of attempted swaps. It should be investigated whether these tests can incorporate a seed to remove this variability (and double check that `double_edge_swap` is performing well!)

**Comment by rossbar** [comment]
It turns out the [failing test case](https://github.com/networkx/networkx/actions/runs/7567366601/job/20606378190) already [includes a seed](https://github.com/networkx/networkx/blob/7fc4fa51875d9e326416f998c51f208442d55dad/networkx/algorithms/tests/test_swap.py#L18) - further investigation required!

**Comment by dschult** [comment]
The randomness is coming from the graph creation rather than the tested function.
The `random_tree` creator works fine for seed integers 0 -> 14, but
`G=random_tree(10, create_using=nx.DiGraph, seed=15)`
produces the error shown in the failing tests. 

I believe the `random_tree` and `binomial_tree` graph creation will need seed values too. A fix is on the way.
