### ISSUE TITLE
Inconsistency in return type of `all_node_cuts`

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#7285]
I noticed this while reviewing docstrings in #7258.

From the documentation, it seems `all_node_cuts` is intended to return node sets. This is indeed the behavior for some graphs, e.g.

```python
>>> G = nx.path_graph(5)
>>> list(nx.all_node_cuts(G))
[{1}, {2}, {3}]
```

However, for other input graphs, the returned values are sets of 2-tuples (which to me look suspiciously like edges). One example of this behavior is actually available in the docstring itself:

```python
>>> G = nx.grid_2d_graph(5, 5)
>>> list(nx.all_node_cuts(G))
[{(3, 0), (4, 1)}, {(0, 3), (1, 4)}, {(3, 4), (4, 3)}, {(0, 1), (1, 0)}]
```

The sets in this last output don't appear to me to be interpretable as node cut-sets. Perhaps there's a missing edge-unpacking step somewhere in the algorithm?

**Comment by dschult** [comment]
This example uses `nx.grid_2d_graph` which creates nodes that are 2-tuples of ints (positions in the 2d grid). So interpreting each 2-tuple of ints as a node, this suggests that the node cuts are (sets of) pairs of nodes. That could be true since this is a lattice structure -- that is, I think removing individual nodes won't create a cut. But removing pairs of nodes next to each corner or the grid would cut off the corner node.  The corners would likely be the smallest cuts possible. Any other part of the grid/lattice would need more nodes cut. So this result makes sense to me.  At least they are interpretable as node cut-sets.

Does this make sense?

**Comment by rossbar** [comment]
> Does this make sense?

It does indeed - thanks @dschult ! You are definitely right - I was just thrown by the fact that the nodes "looked" like edges, but indeed they are nodes as expected for this case. Issue resolved!
