### ISSUE TITLE
`numpy>=2`: Inconsistent `nx.subgraph` node types (`int`, `np.int64`)

### ISSUE THREAD

**Issue by nelsonaloysio** [networkx/networkx#7575]
Creating a subgraph with `nx.{edge_,}subgraph` returns nodes with inconsistent types, either `int` or `np.int64`.

Results seem to vary depending on (1) the node types given to the function; and (2) the order/size of the graph object.

### Current Behavior

Creating subgraphs yield nodes with different dtypes depending on the original graph's order and the filtered nodes types.

### Expected Behavior

Subgraphs should return node types as defined in the graph object, independent of (1) and (2) IMHO.

#### Input:

```python
import networkx as nx
import numpy as np

graphs = [
      nx.dense_gnm_random_graph(3, 3),
      nx.dense_gnm_random_graph(5, 10),
      nx.karate_club_graph(),
]

nodes_int = [0, 1]
nodes_npy = [np.int64(0), np.int64(1)]
nodes_mix = [0, np.int64(1)]

for G in graphs:
    print(f"{G}\n"
          f"G_subgraph_int: {G.subgraph(nodes_int).nodes()}\n"
          f"G_subgraph_npy: {G.subgraph(nodes_npy).nodes()}\n"
          f"G_subgraph_mix: {G.subgraph(nodes_mix).nodes()}\n")
```

#### Output:

```none
Graph with 3 nodes and 3 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [0, 1]
G_subgraph_mix: [0, 1]

Graph with 5 nodes and 10 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [np.int64(0), np.int64(1)]
G_subgraph_mix: [0, np.int64(1)]

Graph named "Zachary's Karate Club" with 34 nodes and 78 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [np.int64(0), np.int64(1)]
G_subgraph_mix: [0, np.int64(1)]
```

### Environment

Python version: `3.12.4`
NetworkX version: `3.3`
NumPy version: `2.0.1`

### Additional context

(!) Please note that **this bug has been observed only on `numpy>= 2.0`.** Previous versions seem unaffected.

When running the same code on `numpy==1.26.4`, with the same networkx version, returned output is as expected:

```
Graph with 3 nodes and 3 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [0, 1]
G_subgraph_mix: [0, 1]

Graph with 5 nodes and 10 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [0, 1]
G_subgraph_mix: [0, 1]

Graph named "Zachary's Karate Club" with 34 nodes and 78 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [0, 1]
G_subgraph_mix: [0, 1]
```

**Comment by nelsonaloysio** [comment]
See additional context above - when running the same code on Python 3.11, returned output is as expected:

```
Graph with 3 nodes and 3 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [0, 1]
G_subgraph_mix: [0, 1]

Graph with 5 nodes and 6 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [0, 1]
G_subgraph_mix: [0, 1]

Graph named "Zachary's Karate Club" with 34 nodes and 78 edges
G_subgraph_int: [0, 1]
G_subgraph_npy: [0, 1]
G_subgraph_mix: [0, 1]
```

Ultimately I am unsure if this report belongs here or not, but I am more inclined to believe that yes.

**Comment by dschult** [comment]
The problem with mixing numpy scalars and python ints is that they are equal when the value is equal. So Python dicts treat them as the same key in the dict. The examples you show seem to be related to the printing changes for numpy 2.0 rather than the python version used. By that I mean in numpy 2.0 printing a scalar shows the text e.g. `np.int32(0)` whereas in previous versions of numpy it shows `0`. So with the old version they **look** the same, but the type of the answer is actually different. With numpy 2.0 they now appear different when they have a different type. 

When mixing numpy and python numbers you can take two approaches (as I understand it). You can treat the numpy scalars as the same as python numbers -- in which case you should ignore what the string values show as being different. The values are the same (they are equal) and the hashes are the same so dicts treat them as the same. Printing them treats them  as different. The other approach is to be very careful to convert all of one type to the other type when you interacxt with the graph. For example, make them all python numbers on the graph object, and only create subgraphs using python numbers.

There are other subtle differences between numpy scalars and python numbers -- like numpy scalars have finite size, so overflow and underflow can occur if you do arithmetic with them. That allows them to be efficiently stored in fixed stride arrays/buffers which is good. But `np.int32(2**31) * 4` gives a strange result.  This kind of difference between python numbers and numpy numbers has alwayds been there. But now they appear different when printed. That can cause confusion. But hopefully when we all get used to thinking of them as different objects even though they hash and equate as the same there will be less confusion.

I personally usually choose to use python numbers in my networkx graphs and convert the output of numpy arrays to python numbers when non-numpy manipulations are involved.  i.e.  while I used to write `A[3, 4] * 4`, with numpy 2.0 I will write `int(A[3, 4]) * 4`.  If others know a better approach please let me know.

**Comment by nelsonaloysio** [comment]
Indeed, `numpy>=2` is the culprit for the apparent difference. I have updated the issue description accordingly. Thanks!

To avoid this issue, I have submitted a PR (#7576) to return nodes with the same type as defined in the graph object.

**Comment by rossbar** [comment]
FWIW, there is no real behavior change - the above `G_subgraph_npy` example has *always* returned subgraphs with numpy integer scalars as nodes - it's just that prior to numpy 2.0, the distinction between numpy and Python scalars was not made explicit to users (due to type information not being included in numpy scalar reprs). You'd have to explicitly probe the types in order to see this. Here's a functionally equivalent example with numpy 1.26:

```python
>>> import numpy as np
>>> np.__version__
1.26.0
>>> G = nx.karate_club_graph()
>>> G_subgraph_npy = G.subgraph(np.array([0, 1]))
>>> G_subgraph_npy.nodes  # These *look* the same as Python scalars
NodeView((0, 1))
>>> [type(n) for n in G_subgraph_npy.nodes]  # but are in fact numpy scalars
[numpy.int64, numpy.int64]
```

All that's to say - nothing has fundamentally changed: NetworkX continues to handle numerical scalars (whether from Python, NumPy, Pytorch, etc.) the way that it always has. The only difference is what information is displayed to the user.

**Comment by nelsonaloysio** [comment]
After reading your comments (thank you!), I completely agree now that this is not an issue. More like a feature. :-)

For a lack of a better approach, I am taking the liberty to close this ticket and the corresponding PR ([link for ref.](https://github.com/networkx/networkx/pull/7576#issuecomment-2289603641)).
