### ISSUE TITLE
Floyd warshall and single source shortest paths give different results

### ISSUE THREAD

**Issue by Fre0Grella** [networkx/networkx#7607]
I was trying to reproduce the closeness centrality algorithm using floyd warshall but i encounter this problem using les miserables graph

### Current Behavior and Expected Behavior
after running floyd warshall and a loop for all node of single source shortest paths the result were different when they are supposed to be identical

### Steps to Reproduce
```python
LM = nx.les_miserables_graph()
nodes = LM.nodes()
path_length = nx.single_source_shortest_path_length
D = {}
for n in nodes:
    sp = path_length(LM, n)
    D[n] = sp
C = nx.floyd_warshall(LM)
C == D 
``` 
Return False

Python version: Python 3.12.5
NetworkX version: current

### Additional context
I checked some values manually and floyd get paths of value up to 13,
when single_source_shortest_path_length get the same paths to around 4 
Let me know if i'm wrong thanks for the support

**Comment by dschult** [comment]
The path lengths are different because `single_source_shortest_path_length` doesn't take the weights into account while `floyd_warshall` uses the 'weight' attribute of the edges.  You could specify the weight attribute for shortest path using something like:

```python
nx.shortest_path_length(LM, 'Brujon', weight='weight')
```
and the results agree with the results of `floyd_warshall(LM)['Brujon']`
