### ISSUE TITLE
Multi{Di}Graph incorrectly parses `incoming_graph_data` attributes from {Di}Graph objects.

### ISSUE THREAD

**Issue by Cerebus** [networkx/networkx#7696]
### Current Behavior
```
>>> import networkx as nx
>>> nx.__version__
'3.4.2'
>>> g = nx.diamond_graph()
>>> g[1][2]
{}
>>> h = nx.DiGraph(g)
>>> h[1][2]
{}
>>> h = nx.MultiGraph(g)
>>> h[1][2]
AtlasView({0: {}})
>>> h = nx.MultiDiGraph(g)
>>> h[1][2]
AtlasView({0: {}})
>>> h = nx.DiGraph(g)
>>> h[1][2]
{}
>>> i = nx.MultiDiGraph(h)
>>> i[1][2]
AtlasView({0: {}})
>>> i = nx.MultiGraph(h)
>>> i[1][2]
AtlasView({0: {}})
```

### Expected Behavior
Attributes should be `dict` not `AtlasView`.

### Steps to Reproduce
See above.

### Environment
Python version: 3.12.4
NetworkX version: 3.4.2

**Comment by rossbar** [comment]
This is the expected behavior --- in MultiGraphs, the edges are stored according to a `key` attribute; in other words, there is another layer of dict-nesting in order to support the ability to store edge attributes for multiple edges between two nodes. Therefore, *individual* edge attribute access in multigraphs looks something like `G[node_1][node_2][edge_key]`.

This is baked into the structure of the MultiGraph, even when there is only a single edge between two nodes (the default key is `0`) - so to get to the edge-attribute-layer of MultiGraph, you have to provide the edge key as well:

```python
>>> h = nx.MultiGraph(g)
>>> h[1][2]
AtlasView({0: {}})
>>> h[1][2][0]  # where 0 is the edge key
{}
```
