### ISSUE TITLE
graph_clique_number missing in 3.4.2 from clique.py file

### ISSUE THREAD

**Issue by dbiton** [networkx/networkx#7733]
graph_clique_number shows up in clique.pyi, but can not be imported since the code seems to be missing from clique.py, node_clique_number seems to be there.
An IDE would recognize:

from networkx.algorithms.clique import graph_clique_number

but actually running the code throws an:

ImportError: cannot import name 'graph_clique_number' from 'networkx.algorithms.clique' (...\Python312\Lib\site-packages\networkx\algorithms\clique.py). Did you mean: 'node_clique_number'?

Python 3.12.5, Windows, pip 24.3.1

**Comment by dschult** [comment]
You should probably address this report to the source of your clique.pyi file.

**Comment by dbiton** [comment]
So is graph_clique_number not implemented in networkx? Was it removed?

**Comment by dschult** [comment]
Yes, the function was deprecated in #6186 and then removed two releases later (3.2) in #6941.  As a replacement, the doc_strings were enhanced to include  the one-liner code that computes the answer. There were three such functions eventually removed. The graph_clique_number is/was computed using
```python
max(len(c) for c in nx.find_cliques(G))
```
The doc_string descriptions of how to compute this quantity is in [the `find_cliques` function docs](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.clique.find_cliques.html).  

But the problem seems to be that the type stubs are not correct -- not that you want to find the clique number.

**Comment by rossbar** [comment]
> graph_clique_number shows up in clique.pyi, but can not be imported since the code seems to be missing from clique.py, node_clique_number seems to be there.

Networkx does not provide type stubs (.pyi files) so this issue has arisen because wherever you are acquiring type stubs from is out-of-sync with NetworkX itself. Consider reporting the typing issue to the provider of the .pyi files.
